// src/yoyocmstemplate-vue/src/app/demo/x-address-linkage/x-address-linkage.vue
<template>
    <a-spin :spinning="spinning">
        <!-- 鼠标进入触发加载 -->
        <a-cascader
            :options="provinces"
            :load-data="loadData"
            expand-trigger="hover"
            :placeholder="placeHolder" />
        <!-- 点击触发加载 -->
        <p class="cascader-margin"></p>
        <a-cascader
            :options="provinces"
            :load-data="loadData"
            :placeholder="mouseclickplaceHolder" />
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { AddressLinkageServiceProxy } from "@/shared/service-proxies";

export default {
    name: "x-address-linkage",
    mixins: [AppComponentBase],
    props: {
        placeHolder: {
            type: String
        },
        mouseclickplaceHolder: {
            type: String
        }
    },
    components: {},
    data() {
        return {
            spinning: false,
            _addressLinkageServiceProxy: "",
            // 省
            provinces: [],
            // 市
            citys: [],
            // 区
            areas: [],
            // 街道
            streets: []
        };
    },
    created() {
        this._addressLinkageServiceProxy = new AddressLinkageServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._addressLinkageServiceProxy
                .getAll()
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    res.provinces.forEach(element => {
                        this.provinces.push({
                            value: element.code,
                            label: element.name,
                            isLeaf: false,
                            index: 0
                        });
                    });
                    res.citys.forEach(element => {
                        this.citys.push({
                            value: element.code,
                            label: element.name,
                            provinceCode: element.provinceCode,
                            isLeaf: false,
                            index: 1
                        });
                    });
                    res.areas.forEach(element => {
                        this.areas.push({
                            value: element.code,
                            label: element.name,
                            provinceCode: element.provinceCode,
                            cityCode: element.cityCode,
                            isLeaf: false,
                            index: 2
                        });
                    });
                    res.streets.forEach(element => {
                        this.streets.push({
                            value: element.code,
                            label: element.name,
                            provinceCode: element.provinceCode,
                            cityCode: element.cityCode,
                            areaCode: element.areaCode,
                            isLeaf: true,
                            index: 3
                        });
                    });
                    console.log(this.provinces);
                });
        },
        /**
         * 动态加载数据
         */
        loadData(selectedOptions) {
            console.log(selectedOptions);
            const targetOption = selectedOptions[selectedOptions.length - 1];
            console.log(targetOption);
            targetOption.loading = true;
            setTimeout(() => {
                targetOption.loading = false;
                if (targetOption.index === 0) {
                    let selectCitys = this.citys.filter(
                        x => x.provinceCode === targetOption.value
                    );
                    targetOption.children = selectCitys;
                } else if (targetOption.index === 1) {
                    let selectAreas = this.areas.filter(
                        x => x.cityCode === targetOption.value
                    );
                    targetOption.children = selectAreas;
                } else {
                    let selectStreet = this.streets.filter(
                        x => x.areaCode == targetOption.value
                    );
                    targetOption.children = selectStreet;
                }
                this.provinces = [...this.provinces];
            }, 500);
        }
    }
};
</script>

<style scoped lang="less">
.cascader-margin {
    margin-top: 10px;
}
</style>

// src/yoyocmstemplate-angular/src/app/demo-management/components/x-address-linkage/x-address-linkage.component.ts
import { Component, OnInit, Injector, Input, Output, EventEmitter } from '@angular/core';
import { AppComponentBase } from '@shared/component-base';
import { AddressLinkageServiceProxy, AddressEnum } from '@shared/service-proxies/service-proxies';

// 省
const provinces = [];
// 市
const cities = [];
// 县
const areas = [];
// 镇、乡
const street = [];

@Component({
  selector: 'x-address-linkage',
  templateUrl: './x-address-linkage.component.html',
  styles: []
})
/**
 * 省市县镇组件
 */
export class XAddressLinkageComponent extends AppComponentBase implements OnInit {

  constructor(
    injector: Injector,
    private _addressLinkageServiceProxy: AddressLinkageServiceProxy,
  ) {
    super(injector);
  }

  @Input() name: string;

  @Input()
  placeHolder = '所在地区';  // 文本框展示的内容

  @Input()
  xDisabled = false;   // 禁用

  @Input()
  isClickOnLoad = false; // ture 点击加载 ；false：鼠标移动加载

  @Output()
  selectCodeChange = new EventEmitter<string[] | number[]>();  // 选择后回调事件

  @Output()
  selectNameChange = new EventEmitter<string[]>(); // 选中的文本

  values: any[] | null = null;

  ngOnInit(): void {
    this.getData();
  }


  /**
   * 获取所有数据
   */
  getData() {
    this._addressLinkageServiceProxy.getAll()
      .subscribe(item => {
        item.provinces.forEach(element => {
          provinces.push({ value: element.code, label: element.name });
        });
        item.citys.forEach(element => {
          cities.push({ value: element.code, label: element.name, provinceCode: element.provinceCode });
        });
        item.areas.forEach(element => {
          areas.push({ value: element.code, label: element.name, provinceCode: element.provinceCode, cityCode: element.cityCode });
        });
        item.streets.forEach(element => {
          street.push({ value: element.code, label: element.name, provinceCode: element.provinceCode, cityCode: element.cityCode, areaCode: element.areaCode, isLeaf: true });
        });
      });

    // this._addressLinkageServiceProxy.get(AddressEnum._0, "")
    //   .subscribe(item => {
    //     item.forEach(element => {
    //       provinces.push({ value: element.code, label: element.name });
    //     });
    //   })
    // this._addressLinkageServiceProxy.getAllCity()
    //   .subscribe(item => {
    //     item.forEach(element => {
    //       cities.push({ value: element.code, label: element.name, provinceCode: element.provinceCode });
    //     });
    //   })
    // this._addressLinkageServiceProxy.getAllArea()
    //   .subscribe(item => {
    //     item.forEach(element => {
    //       areas.push({ value: element.code, label: element.name, provinceCode: element.provinceCode, cityCode: element.cityCode });
    //     });
    //   })
    // this._addressLinkageServiceProxy.getAllStreet()
    //   .subscribe(item => {
    //     item.forEach(element => {
    //       street.push({ value: element.code, label: element.name, provinceCode: element.provinceCode, cityCode: element.cityCode, areaCode: element.areaCode, isLeaf: true });
    //     });
    //   })
  }

  onChanges(values: any): void {
    this.selectCodeChange.emit(this.values);
  }

  onSelectionChange(selectedOptions: any[]): void {
    let ret: string[] = [];
    ret = selectedOptions.map(o => o.label);
    this.selectNameChange.emit(ret);
  }


  /** load data async execute by `nzLoadData` method */
  loadData(node: any, index: number): PromiseLike<any> {
    return new Promise(resolve => {
      setTimeout(() => {
        if (index < 0) {
          node.children = provinces;
        } else if (index === 0) {
          const selectCitys = cities.filter(x => x.provinceCode === node.value);
          node.children = selectCitys;
        } else if (index === 1) {
          const selectAreas = areas.filter(x => x.cityCode === node.value);
          node.children = selectAreas;
        } else {
          const selectStreet = street.filter(x => x.areaCode == node.value);
          node.children = selectStreet;
        }
        resolve();
      }, 500);
    });
  }
}

<!-- 点击触发加载 -->
<nz-cascader nzChangeOnSelect 
    *ngIf="isClickOnLoad"
    name="{{name}}" 
    [(ngModel)]="values" 
    [nzLoadData]="loadData" 
    (ngModelChange)="onChanges($event)"
    [nzPlaceHolder]="placeHolder"
    [disabled]="xDisabled"
    (nzSelectionChange)="onSelectionChange($event)"
    > 
</nz-cascader>

<!-- 鼠标进入触发加载 -->
<nz-cascader nzChangeOnSelect 
    *ngIf="!isClickOnLoad"
    name="{{name}}" 
    [(ngModel)]="values" 
    [nzLoadData]="loadData" 
    (ngModelChange)="onChanges($event)"
    [nzTriggerAction]="'hover'"
    [nzExpandTrigger]="'hover'"
    [nzPlaceHolder]="placeHolder"
    [disabled]="xDisabled"
    (nzSelectionChange)="onSelectionChange($event)"
    > 
</nz-cascader>
