// src/yoyocmstemplate-angular/src/app/admin/shared/edition-feature-tree/edition-feature-tree.component.ts
import { Component, Injector } from '@angular/core';
import { FlatFeatureDto, NameValueDto, FeatureInputTypeDto } from '@shared/service-proxies/service-proxies';
import * as _ from 'lodash';
import { NzTreeNode } from 'ng-zorro-antd/tree';
import { ArrayService } from '@delon/util';
import { AppComponentBase } from '@shared/component-base';
import { TreeDataHelperService, ArrayToTreeConverterService } from '@shared/utils';
import { FeatureTreeEditModel } from './types';

@Component({
  selector: 'edition-feature-tree',
  templateUrl: './edition-feature-tree.component.html',
  styleUrls: ['./edition-feature-tree.component.less'],
})
export class EditionFeatureTreeComponent extends AppComponentBase {
  /**
   * 功能源数据
   */
  _featureSourceData: FeatureTreeEditModel;

  /**
   * 树数据
   */
  treeData: NzTreeNode[] = [];

  /**
   * 编辑用的数据
   */
  set editData(val: FeatureTreeEditModel) {
    this._featureSourceData = val;
    this.processsTreeData();
  }

  constructor(private arrayService: ArrayService, injector: Injector) {
    super(injector);
  }

  /**
   * 将数据转换成树
   */
  processsTreeData() {
    this.treeData = this.arrayService.arrToTreeNode(this._featureSourceData.features, {
      idMapName: 'name',
      parentIdMapName: 'parentName',
      titleMapName: 'displayName',
    });

    this.arrayService.visitTree(this.treeData, item => {
      item.isLeaf = true;
      this.fullTreeData(item, item.origin.name);
    });
  }

  /**
   * 填充数据到节点
   * @param node
   * @param featureName
   */
  fullTreeData(node: NzTreeNode, featureName: string) {
    const feature = this._featureSourceData.featureValues.find(item => item.name === featureName);
    // 默认值
    if (!feature) {
      const defaultValue = this.convertValue(node.origin.inputType, node.origin.defaultValue);
      if (typeof defaultValue === 'boolean') {
        node.isChecked = defaultValue;
        node.origin.value = node.isChecked;
      } else {
        node.origin.value = defaultValue;
      }
      return;
    }

    const featureValue = this.convertValue(node.origin.inputType, feature.value);
    if (typeof featureValue === 'boolean') {
      node.isChecked = featureValue;
      node.origin.value = node.isChecked;
    } else {
      node.origin.value = featureValue;
    }
  }

  /**
   * 根据功能绑定控件类型做转换值
   * @param inputType
   * @param value
   */
  convertValue(inputType: FeatureInputTypeDto, value: any): any {
    if (inputType.name === 'CHECKBOX') {
      return value === 'true';
    }

    return value;
  }

  /**
   * 所有的功能和值
   */
  getGrantedFeatures(): NameValueDto[] {
    if (!this.treeData) {
      return [];
    }

    const features: NameValueDto[] = [];
    this.arrayService.visitTree(this.treeData, item => {
      const feature = new NameValueDto();
      feature.name = item.origin.name;
      feature.value = item.origin.value;
      features.push(feature);
    });

    return features;
  }

  /**
   * 遍历树校验数据
   */
  areAllValuesValid(): boolean {
    let result = true;

    this.arrayService.visitTree(this.treeData, item => {
      if (!this.isFeatureValueValid(item.origin, item.origin.value)) {
        result = false;
      }
    });

    return result;
  }

  /**
   * 是否为子节点
   * @param node
   */
  isLeaf(node: NzTreeNode): boolean {
    return node.children && Array.isArray(node.children) && node.children.length > 0;
  }

  /**
   * 是否展开
   * @param node
   * @param value
   */
  setNodeIsExpanded(node: NzTreeNode, value: boolean) {
    node.isExpanded = value;
  }

  /**
   * 功能的数据校验
   * @param feature 功能
   * @param value 值
   */
  isFeatureValueValid(feature: FlatFeatureDto, value: any): boolean {
    if (!feature || !feature.inputType || !feature.inputType.validator) {
      return true;
    }

    const validator = feature.inputType.validator as any;
    if (validator.name === 'STRING') {
      if (value === undefined || value === null) {
        return validator.allowNull;
      }

      if (typeof value !== 'string') {
        return false;
      }

      if (validator.minLength > 0 && value.length < validator.minLength) {
        return false;
      }

      if (validator.maxLength > 0 && value.length > validator.maxLength) {
        return false;
      }

      if (validator.regularExpression) {
        return new RegExp(validator.regularExpression).test(value);
      }
    } else if (validator.name === 'NUMERIC') {
      const numValue = parseInt(value);

      if (isNaN(numValue)) {
        return false;
      }

      const minValue = validator.minValue;
      if (minValue > numValue) {
        return false;
      }

      const maxValue = validator.maxValue;
      if (maxValue > 0 && numValue > maxValue) {
        return false;
      }
    }

    return true;
  }
}

<nz-tree [nzData]="treeData" [nzCheckStrictly]="true" [nzMultiple]="true">
  <ng-template #nzTreeTemplate let-node>
    <!-- {{outData(node)}} -->
    <!-- 这里是前面的展示符号 -->
    <!-- 展开 -->
    <span class="ant-tree-switcher ant-tree-switcher_open" *ngIf="isLeaf(node)&&node.isExpanded"
      (click)="setNodeIsExpanded(node,false)">
      <!-- <i class="anticon ant-tree-switcher-icon  anticon-caret-down"></i> -->
      <i class="iconfont ant-tree-switcher-icon icon-caret-down"></i>
    </span>
    <!-- 收起 -->
    <span class="ant-tree-switcher ant-tree-switcher_close" *ngIf="isLeaf(node)&&!node.isExpanded"
      (click)="setNodeIsExpanded(node,true)">
      <!-- <i class="anticon ant-tree-switcher-icon anticon-caret-down"></i> -->
      <i class="iconfont ant-tree-switcher-icon icon-caret-down"></i>
    </span>
    <!-- 占位 -->
    <span class="ant-tree-switcher ant-tree-switcher_close" *ngIf="!isLeaf(node)"> </span>

    <!-- 下面的才是对数据的操作 -->


    <!-- 特性名称 -->
    <span style="margin-right: 5px;">{{node.title}}</span>

    <!-- 如果是输入框 -->
    <div class="ant-tree-checkbox" *ngIf="node?.origin?.inputType.name === 'SINGLE_LINE_STRING'">
      <input nz-input [(ngModel)]="node.origin.value" [attr.name]="node?.origin?.name">
    </div>

    <!-- 如果是checkbox -->
    <span class="ant-tree-checkbox" *ngIf="node?.origin?.inputType.name==='CHECKBOX'">
      <label nz-checkbox [attr.name]="node?.origin?.name" [(ngModel)]="node.origin.value"></label>
    </span>

    <!-- 如果是下拉框 -->
    <select class="ant-tree-checkbox" [attr.name]="node?.origin?.name"
      *ngIf="node?.origin?.inputType.name === 'COMBOBOX'" [(ngModel)]="node.origin.value">
      <option *ngFor="let item of node?.origin?.itemSource.items" [value]="item.value">
        {{item.displayName}}
      </option>
    </select>

  </ng-template>
</nz-tree>

// src/yoyocmstemplate-vue/src/app/admin/shared/edition-feature-tree/edition-feature-tree.vue
<template>
    <a-tree :checkStrictly="true" :multiple="false" :treeData="treeData">

        <template slot="nzTreeTemplate" slot-scope="node">
            <!-- 特性名称 -->
            <span style="margin-right: 5px;">{{node.title}}</span>

            <!-- 如果是输入框 -->
            <div class="ant-tree-checkbox" v-if="node.origin.inputType.name === 'SINGLE_LINE_STRING'">
                <a-input :defaultValue="node.origin.value"
                         :key="node.origin.name"
                         :name="node.origin.name"
                         @change="inputChange($event,node)"></a-input>
            </div>

            <!-- 如果是checkbox -->
            <span class="ant-tree-checkbox" v-if="node.origin.inputType.name==='CHECKBOX'">
                <a-checkbox :defaultChecked="node.origin.value"
                            :key="node.origin.name"
                            :name="node.origin.name"
                            @change="checkboxChange($event,node)">
                </a-checkbox>
            </span>

            <!-- 如果是下拉框,此功能有待校验 -->
            <select :key="node.origin.name"
                    :name="node.origin.name"
                    @change="node.origin.value=$event"
                    class="ant-tree-checkbox"
                    v-if="node.origin.inputType.name === 'COMBOBOX'"
                    v-model="node.origin.value">
                <option :key="index"
                        :value="item.value"
                        v-for="(item, key, index) in node.origin.itemSource.items">
                    {{item.displayName}}
                </option>
            </select>

        </template>

    </a-tree>
</template>

<script>
    import {AppComponentBase} from "@/shared/component-base";
    import {arrayService} from '@/shared/utils';
    import {NameValueDto} from '@/shared/service-proxies';

    export default {
        name: "edition-feature-tree",
        mixins: [AppComponentBase],
        props: ['editData'],
        data() {
            return {
                treeDataVal: [],
                featureSourceData: this.editData,
            }
        },
        mounted() {
            if (this.featureSourceData) {
                this.processsTreeData();
            }
        },
        computed: {
            treeData: {
                get() {
                    return this.treeDataVal;
                },
                set(val) {
                    this.treeDataVal = val;
                }
            }
        },
        watch: {
            editData(val) {
                this.featureSourceData = val;
                this.processsTreeData();
            }
        },
        methods: {
            processsTreeData() {
                let treeData = arrayService.arrToTreeNode(
                    this.featureSourceData.features,
                    {
                        idMapName: 'name',
                        parentIdMapName: 'parentName',
                        titleMapName: 'displayName',
                    });

                arrayService.visitTree(treeData, (item) => {
                    // 绑定模板
                    item.scopedSlots = {title: 'nzTreeTemplate'};

                    item.selectable = false;
                    item.class = "nzTreeTemplate";
                    this.fullTreeData(item, item.origin.name);
                });

                this.treeData = treeData;
            },
            fullTreeData(node, featureName) {
                let feature = this.featureSourceData.featureValues.find(item => item.name === featureName);
                // 默认值
                if (!feature) {
                    let defaultValue = this.convertValue(node.origin.inputType, node.origin.defaultValue);
                    if (typeof defaultValue === "boolean") {
                        node.isChecked = defaultValue;
                        node.origin.value = node.isChecked;
                    } else {
                        node.origin.value = defaultValue;
                    }
                    return;
                }

                let featureValue = this.convertValue(node.origin.inputType, feature.value);
                if (typeof featureValue === "boolean") {
                    node.isChecked = featureValue;
                    node.origin.value = node.isChecked;
                } else {
                    node.origin.value = featureValue;
                }

            },
            convertValue(inputType, value) {
                if (inputType.name === "CHECKBOX") {
                    return value === "true";
                }

                return value;
            },
            getGrantedFeatures() {
                if (!this.treeData) {
                    return [];
                }

                let features = [];
                arrayService.visitTree(this.treeData, (item) => {
                    let feature = new NameValueDto();
                    feature.name = item.origin.name;
                    feature.value = item.origin.value;
                    features.push(feature);
                });

                return features;
            },
            areAllValuesValid() {
                let result = true;

                arrayService.visitTree(this.treeData, item => {
                    if (!this.isFeatureValueValid(item.origin, item.origin.value)) {
                        result = false;
                    }
                });

                return result;
            },
            isLeaf(node) {
                return node.children && Array.isArray(node.children) && node.children.length > 0;
            },
            setNodeIsExpanded(node, value) {
                node.isExpanded = value;
            },
            isFeatureValueValid(feature, value) {
                if (!feature || !feature.inputType || !feature.inputType.validator) {
                    return true;
                }

                const validator = feature.inputType.validator;
                if (validator.name === 'STRING') {
                    if (value === undefined || value === null) {
                        return validator.allowNull;
                    }

                    if (typeof value !== 'string') {
                        return false;
                    }

                    if (validator.minLength > 0 && value.length < validator.minLength) {
                        return false;
                    }

                    if (validator.maxLength > 0 && value.length > validator.maxLength) {
                        return false;
                    }

                    if (validator.regularExpression) {
                        return (new RegExp(validator.regularExpression)).test(value);
                    }
                } else if (validator.name === 'NUMERIC') {
                    const numValue = parseInt(value);

                    if (isNaN(numValue)) {
                        return false;
                    }

                    const minValue = validator.minValue;
                    if (minValue > numValue) {
                        return false;
                    }

                    const maxValue = validator.maxValue;
                    if (maxValue > 0 && numValue > maxValue) {
                        return false;
                    }
                }

                return true;
            },
            inputChange(e, node) {
                node.origin.value = e.srcElement.value;
            },
            checkboxChange(e, node) {
                node.origin.value = e.target.checked;
            },

        }
    }
</script>

<style scoped lang="less">
    @import "./edition-feature-tree.less";

    .nzTreeTemplate {
        .ant-tree-node-content-wrapper {
            &:hover {
                background-color: red !important;
            }

        }
    }
</style>
