// src/yoyocmstemplate-angular/src/layout/components/header-notifications/header-notifications.component.ts
import { Component, Injector, NgZone, OnInit } from '@angular/core';
import { AppComponentBase } from '@shared/component-base';
import { IFormattedUserNotification, UserNotificationHelper } from '@shared/helpers/UserNotificationHelper';
import { NotificationServiceProxy } from '@shared/service-proxies/service-proxies';
import { AppConsts } from '../../../abpPro/AppConsts';
import { finalize } from 'rxjs/operators';
import { HeaderNotificationSettingsComponent } from '../header-notification-settings/header-notification-settings.component';

@Component({
  selector: 'header-notifications',
  templateUrl: './header-notifications.component.html',
  styles: [],
})
export class HeaderNotificationsComponent extends AppComponentBase implements OnInit {

  notifications: IFormattedUserNotification[] = [];
  unreadNotificationCount = 0;
  loading: boolean;

  constructor(
    injector: Injector,
    private _notificationService: NotificationServiceProxy,
    private _userNotificationHelper: UserNotificationHelper,
    public _zone: NgZone,
  ) {
    super(injector);
  }

  ngOnInit(): void {
    this.loadNotifications();
    this.registerToEvents();
  }

  loadNotifications(): void {
    this.loading = true;
    // this._notificationService.getPagedUserNotifications(undefined, AppConsts.notificationCount, 0)
    //   .pipe(finalize(() => {
    //     this.loading = false;
    //   }))
    //   .subscribe(result => {
    //     this.unreadNotificationCount = result.unreadCount;
    //     this.notifications = [];
    //     result.items.forEach((item) => {
    //       this.notifications.push(this._userNotificationHelper.format(item as any));
    //     });
    //   });
  }

  registerToEvents() {

    abp.event.on('abp.notifications.received', userNotification => {
      this._zone.run(() => {
        this._userNotificationHelper.show(userNotification);
        this.loadNotifications();
      });
    });

    abp.event.on('app.notifications.refresh', () => {
      this._zone.run(() => {
        this.loadNotifications();
      });
    });


    abp.event.on('app.notifications.read', userNotificationId => {
      this._zone.run(() => {
        for (let i = 0; i < this.notifications.length; i++) {
          if (this.notifications[i].userNotificationId === userNotificationId) {
            this.notifications[i].state = 'READ';
          }
        }
        this.unreadNotificationCount -= 1;
      });
    });

  }

  setAllNotificationsAsRead(): void {
    this._userNotificationHelper.setAllAsRead();
  }

  chantNotificationSettings(): void {
    this.modalHelper.create(HeaderNotificationSettingsComponent)
      .subscribe((res) => {

      });
  }

  setNotificationAsRead(userNotification: IFormattedUserNotification): void {
    this._userNotificationHelper.setAsRead(userNotification.userNotificationId);
  }

  gotoUrl(url): void {
    if (url) {
      location.href = url;
    }
  }
}

<ng-template #extra>
    <a
            [hidden]="notifications && notifications.length === 0"
            (click)="setAllNotificationsAsRead()"
            style="margin-right: 10px;"
    >
        <i class="iconfont icon-check" style="font-size: 20px;"></i>
        {{ l('SetAllAsRead') }}
    </a>
    <a class="mr-sm" (click)="loadNotifications()">
        <i class="iconfont icon-reload" style="font-size: 20px;"></i>
        {{ l('Refresh') }}
    </a>
    <a (click)="chantNotificationSettings()">
        <i class="iconfont icon-setting" style="font-size: 20px;"></i>
        {{ l('Settings') }}
    </a>
</ng-template>

<div class="alain-pro__nav-item" nz-dropdown nzPlacement="bottomRight" [nzDropdownMenu]="dropdownMenu">
    <nz-badge [nzCount]="unreadNotificationCount">
        <i class="iconfont icon-bell"></i>
    </nz-badge>
</div>

<nz-dropdown-menu #dropdownMenu="nzDropdownMenu">
    <div nz-menu class="wd-lg">
        <nz-spin [nzSpinning]="loading">
            <nz-card
                    [nzTitle]="l('NewNotifications')"
                    [nzLoading]="loading"
                    nzBordered="false"
                    class="ant-card__body-nopadding"
                    [nzExtra]="extra"
                    style="min-width:450px;"
            >
                <!-- 通知列表 -->
                <div
                        nz-row
                        [nzType]="'flex'"
                        [nzJustify]="'center'"
                        [nzAlign]="'middle'"
                        class="py-sm bg-grey-lighter-h point"
                        *ngFor="let item of notifications"
                        (click)="gotoUrl(item.url)"
                >
                    <div nz-col [nzSpan]="20">
                        <p class="mb0">
                            <ellipsis lines="1">
                <span nz-tooltip [nzTooltipTitle]="item.text">
                  <nz-badge [hidden]="item.icon === 'fatal'" [nzStatus]="item.icon"></nz-badge>
                  <nz-badge
                          [hidden]="item.icon !== 'fatal'"
                          nzStatus="default"
                          [nzStyle]="{ 'background-color': 'black' }"
                  >
                  </nz-badge>
                    {{ item.text }}
                </span>
                            </ellipsis>
                        </p>
                        <p>
                            {{ item.time | momentFromNow }}
                            <a [hidden]="item.state !== 'UNREAD'" (click)="setNotificationAsRead(item)">{{ l('SetAsRead') }}</a>
                        </p>
                    </div>
                </div>

                <!-- 没有数据 -->
                <div nz-row *ngIf="!notifications || notifications.length === 0">
                    <div nz-col [nzSpan]="24" class="pt-md border-top-1 text-center text-grey point">
                        {{ l('ThereIsNoNotification') }}
                    </div>
                </div>

                <!-- 查看所有通知 -->
                <div nz-row *ngIf="notifications && notifications.length !== 0">
                    <div nz-col [nzSpan]="24" class="pt-md border-top-1 text-center text-grey point">
                        <a [routerLink]="['/app/notifications']">{{ l('SeeAllNotifications') }}</a>
                    </div>
                </div>
            </nz-card>
        </nz-spin>
    </div>
</nz-dropdown-menu>

// src/yoyocmstemplate-vue/src/layout/default/header/components/header-notifications/header-notifications.vue
<template>

    <a-dropdown class="alain-pro__nav-item" placement="bottomRight">
        <template slot="overlay">
            <a-spin :spinning="loading">
                <a-card :title="l('NewNotifications')" :bordered="false"
                        class="ant-card__body-nopadding"
                        style="min-width:450px;">
                    <template slot="extra">
                        <a v-show="notifications&&notifications.length===0" @click="setAllNotificationsAsRead()"
                           style="margin-right: 10px;">
                            <a-icon type="check"></a-icon>
                            {{l("SetAllAsRead")}}
                        </a>
                        <a class="mr-sm" @click="loadNotifications()">
                            <a-icon type="reload"></a-icon>
                            {{l("Refresh")}}
                        </a>
                        <a @click="chantNotificationSettings()">
                            <a-icon type="setting"></a-icon>
                            {{l("Settings")}}
                        </a>
                    </template>

                    <a-row v-for="(item,key,index) in notifications"
                           :key="index"
                           type="flex"
                           justify="center"
                           align="middle"
                           class="py-sm bg-grey-lighter-h point"

                           @click="gotoUrl(item.url)">

                        <a-col :span="20">
                            <a-tooltip>
                                <template slot="title">
                                    {{item.text}}
                                </template>

                                <a-badge v-show="item.icon!=='fatal'" :status="item.icon"></a-badge>
                                <a-badge v-show="item.icon==='fatal'" status="default"
                                         :style="{'background-color':'black'}">
                                </a-badge>
                                {{item.text}}
                            </a-tooltip>

                            <p>
                                {{item.time | momentFromNow}}
                                <a v-show="item.state==='UNREAD'"
                                   @click="setNotificationAsRead(item)">
                                    {{l('SetAsRead')}}
                                </a>
                            </p>

                        </a-col>
                    </a-row>

                    <!-- 没有数据 -->
                    <a-row v-if="!notifications||notifications.length===0">
                        <a-col :span="24" class="pt-md border-top-1 text-center text-grey point">
                            {{l("ThereIsNoNotification")}}
                        </a-col>
                    </a-row>

                    <!-- 查看所有通知 -->
                    <a-row v-if="notifications&&notifications.length!==0">
                        <a-col :span="24" class="pt-md border-top-1 text-center text-grey point">
                            <router-link to="/app/notifications">{{l('SeeAllNotifications')}}</router-link>

                        </a-col>
                    </a-row>

                </a-card>
            </a-spin>
        </template>

        <a-badge :count="unreadNotificationCount">
            <a-icon type="bell" class="alain-pro__nav-item-icon"></a-icon>
        </a-badge>
    </a-dropdown>

    <!--    -->
    <!--    <a-popover trigger="hover" placement="bottomRight">-->
    <!--        <template slot="title">-->

    <!--        </template>-->
    <!--        <template slot="content">-->

    <!--            <a-spin :spinning="loading">-->
    <!--                <a-card :title="l('NewNotifications')" :bordered="false"-->
    <!--                        class="ant-card__body-nopadding"-->
    <!--                        style="min-width:450px;">-->
    <!--                    <template slot="extra">-->
    <!--                        <a v-show="notifications&&notifications.length===0" @click="setAllNotificationsAsRead()"-->
    <!--                           style="margin-right: 10px;">-->
    <!--                            <a-icon type="check"></a-icon>-->
    <!--                            {{l("SetAllAsRead")}}-->
    <!--                        </a>-->
    <!--                        <a class="mr-sm" @click="loadNotifications()">-->
    <!--                            <a-icon type="reload"></a-icon>-->
    <!--                            {{l("Refresh")}}-->
    <!--                        </a>-->
    <!--                        <a @click="chantNotificationSettings()">-->
    <!--                            <a-icon type="setting"></a-icon>-->
    <!--                            {{l("Settings")}}-->
    <!--                        </a>-->
    <!--                    </template>-->

    <!--                    <a-row v-for="(item,key,index) in notifications"-->
    <!--                           :key="index"-->
    <!--                           type="flex"-->
    <!--                           justify="center"-->
    <!--                           align="middle"-->
    <!--                           class="py-sm bg-grey-lighter-h point"-->

    <!--                           @click="gotoUrl(item.url)">-->

    <!--                        <a-col :span="20">-->
    <!--                            <a-tooltip>-->
    <!--                                <template slot="title">-->
    <!--                                    {{item.text}}-->
    <!--                                </template>-->

    <!--                                <a-badge v-show="item.icon!=='fatal'" :status="item.icon"></a-badge>-->
    <!--                                <a-badge v-show="item.icon==='fatal'" status="default"-->
    <!--                                         :style="{'background-color':'black'}">-->
    <!--                                </a-badge>-->
    <!--                                {{item.text}}-->
    <!--                            </a-tooltip>-->

    <!--                            <p>-->
    <!--                                {{item.time | momentFromNow}}-->
    <!--                                <a v-show="item.state==='UNREAD'"-->
    <!--                                   @click="setNotificationAsRead(item)">-->
    <!--                                    {{l('SetAsRead')}}-->
    <!--                                </a>-->
    <!--                            </p>-->

    <!--                        </a-col>-->
    <!--                    </a-row>-->

    <!--                    &lt;!&ndash; 没有数据 &ndash;&gt;-->
    <!--                    <a-row v-if="!notifications||notifications.length===0">-->
    <!--                        <a-col :span="24" class="pt-md border-top-1 text-center text-grey point">-->
    <!--                            {{l("ThereIsNoNotification")}}-->
    <!--                        </a-col>-->
    <!--                    </a-row>-->

    <!--                    &lt;!&ndash; 查看所有通知 &ndash;&gt;-->
    <!--                    <a-row v-if="notifications&&notifications.length!==0">-->
    <!--                        <a-col :span="24" class="pt-md border-top-1 text-center text-grey point">-->
    <!--                            <router-link to="/app/notifications">{{l('SeeAllNotifications')}}</router-link>-->

    <!--                        </a-col>-->
    <!--                    </a-row>-->

    <!--                </a-card>-->
    <!--            </a-spin>-->


    <!--        </template>-->
    <!--        <a-badge :count="unreadNotificationCount">-->
    <!--            <a-icon type="bell" class="alain-pro__nav-item-icon"></a-icon>-->
    <!--        </a-badge>-->
    <!--    </a-popover>-->

</template>

<script>

    import {AppComponentBase} from '@/shared/component-base';
    import {NotificationServiceProxy} from "@/shared/service-proxies";
    import {UserNotificationHelper,ModalHelper} from "@/shared/helpers";
    import {abpService} from "@/shared/abp";
    import {NotificationSettings} from '../notification-settings';
    import {Modal} from 'ant-design-vue';

    export default {
        name: "header-notifications",
        mixins: [AppComponentBase],
        data() {
            return {
                unreadNotificationCountVal: 0,
                notificationService: null,
                notificationsVal: null
            }
        },
        created() {
            this.notificationService = new NotificationServiceProxy(this.$apiUrl, this.$api);
            this.loadNotifications();
            this.registerToEvents();
        },
        computed: {
            unreadNotificationCount: {
                get() {
                    return this.unreadNotificationCountVal;
                },
                set(val) {
                    this.unreadNotificationCountVal = val;
                }
            },
            notifications: {
                get() {
                    return this.notificationsVal;
                },
                set(val) {
                    this.notificationsVal = val;
                }
            },
        },
        methods: {
            loadNotifications() {
                this.loading = true;
                this.notificationService.getPagedUserNotifications(undefined, this.$notificationCount, 0)
                    .finally(() => {
                        this.loading = false;
                    })
                    .then(result => {
                        this.unreadNotificationCount = result.unreadCount;
                        this.notifications = [];
                        result.items.forEach((item) => {
                            this.notifications.push(UserNotificationHelper.format(item)
                            )
                            ;
                        });
                    });
            },
            registerToEvents() {
                abpService.abp.event.on('abp.notifications.received', userNotification => {
                    UserNotificationHelper.show(userNotification);
                    this.loadNotifications();
                });

                abpService.abp.event.on('app.notifications.refresh', () => {
                    this.loadNotifications();
                });


                abpService.abp.event.on('app.notifications.read', userNotificationId => {
                    for (let i = 0; i < this.notifications.length; i++) {
                        if (this.notifications[i].userNotificationId === userNotificationId) {
                            this.notifications[i].state = 'READ';
                        }
                    }
                    this.unreadNotificationCount -= 1;
                });
            },
            setAllNotificationsAsRead() {
                UserNotificationHelper.setAllAsRead();
            },
            chantNotificationSettings() {
                ModalHelper.create(NotificationSettings,null,{width:'900px'})
                    .subscribe((res) => {

                    });
            },
            setNotificationAsRead(userNotification) {
                UserNotificationHelper.setAsRead(userNotification.userNotificationId);
            },
            gotoUrl(url) {
                if (url) {
                    window.location.href = url;
                }
            }
        }
    }
</script>

<style scoped>

</style>
