// src/yoyocmstemplate-angular/src/app/admin/tenants/create-tenant/create-tenant.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import {
  CreateTenantInput,
  TenantServiceProxy,
  SubscribableEditionComboboxItemDto,
} from '@shared/service-proxies/service-proxies';
import { Validators, AbstractControl, FormControl } from '@angular/forms';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';

@Component({
  selector: 'app-create-tenant',
  templateUrl: './create-tenant.component.html',
  styles: [],
})
export class CreateTenantComponent extends ModalComponentBase
  implements OnInit {

  confirmPassword = '';
  useDefaultPassword = true;
  useHostDatabase = true;
  editionId: any = null;
  isUnlimited = false; // 是否无限期订阅
  model: CreateTenantInput = new CreateTenantInput();
  edition: SubscribableEditionComboboxItemDto;

  constructor(injector: Injector, private tenantService: TenantServiceProxy) {
    super(injector);
  }

  ngOnInit() {
    this.model.init({ isActive: true });
  }


  save(): void {
    this.saving = true;
    // 版本
    this.model.editionId = this.edition ? parseInt(this.edition.value, ) : null;
    // 如果没有选择版本或勾选了无限期使用，订阅时间设置为null
    this.model.subscriptionEndUtc = (!this.model.editionId || this.isUnlimited) ? null : this.model.subscriptionEndUtc;

    console.log(this.model);
    this.tenantService
      .create(this.model)
      .finally(() => {
        this.saving = false;
      })
      .subscribe(() => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success();
      });
  }

  selectedEditionChange(edtion: SubscribableEditionComboboxItemDto) {
    this.edition = edtion;
    this.model.isInTrialPeriod = false;
  }
}

<div class="modal-header">
    <div class="modal-title">{{l('CreateNewTenant')}}</div>
</div>

<nz-spin [nzSpinning]="saving">
    <form nz-form #validateForm="ngForm" (ngSubmit)="save()" nzLayout="vertical">

        <!-- 租户名称(租户代码) -->
        <nz-form-item>
            <nz-form-label nzFor="tenancyName" nzRequired>{{l('TenancyName')}}</nz-form-label>
            <nz-form-control nzHasFeedback>
                <input nz-input name="tenancyName" #tenancyName="ngModel" [(ngModel)]="model.tenancyName"
                       [placeholder]="l('TenancyName')" required>
                <nz-form-control nzExtra *ngIf="tenancyName.control.dirty&&tenancyName.control.errors">
                    <ng-container
                            *ngIf="tenancyName.control.hasError('required')">{{l('ThisFieldIsRequired')}}</ng-container>
                </nz-form-control>
            </nz-form-control>
        </nz-form-item>

        <!-- 名称 -->
        <nz-form-item>
            <nz-form-label nzFor="Name" nzRequired>{{l('DisplayTenancyName')}}</nz-form-label>
            <nz-form-control nzHasFeedback>
                <input nz-input name="name" #name="ngModel" [(ngModel)]="model.name" [placeholder]="l('Name')" required>
                <nz-form-control nzExtra *ngIf="name.control.dirty&&name.control.errors">
                    <ng-container *ngIf="name.control.hasError('required')">{{l('ThisFieldIsRequired')}}</ng-container>
                </nz-form-control>
            </nz-form-control>
        </nz-form-item>

        <!-- 租户管理员使用默认密码 -->
        <nz-form-control>
            <label nz-checkbox name="useHostDatabase" #useHostDatabaseInput="ngModel"
                   [(ngModel)]="useHostDatabase">{{l("UseHostDatabase")}}</label>
        </nz-form-control>

        <!-- 自定义数据库链接字符串 -->
        <nz-form-item *ngIf="!useHostDatabase">
            <nz-form-label nzFor="connectionString" nzRequired>{{l('DatabaseConnectionString')}}</nz-form-label>
            <nz-form-control nzHasFeedback>
                <input nz-input name="connectionString" #connectionString="ngModel" [(ngModel)]="model.connectionString"
                       [placeholder]="l('DatabaseConnectionString')+l('Optional')">
            </nz-form-control>
        </nz-form-item>

        <!-- 租户管理员邮箱 -->
        <nz-form-item>
            <nz-form-label nzFor="adminEmailAddress" nzRequired>{{l('AdminEmailAddress')}}</nz-form-label>
            <nz-form-control nzHasFeedback>
                <input nz-input type="email" name="adminEmailAddress" #adminEmailAddress="ngModel"
                       [(ngModel)]="model.adminEmailAddress" [placeholder]="l('EmailAddress')" required email>
                <nz-form-control nzExtra *ngIf="adminEmailAddress.control.dirty&&adminEmailAddress.control.errors">
                    <ng-container *ngIf="adminEmailAddress.control.hasError('email')">{{l('NotEmail')}}</ng-container>
                    <ng-container *ngIf="adminEmailAddress.control.hasError('required')">{{l('ThisFieldIsRequired')}}
                    </ng-container>
                </nz-form-control>
            </nz-form-control>
        </nz-form-item>

        <!-- 租户管理员使用默认密码 -->
        <nz-form-control>

            <nz-form-control>
                <label nz-checkbox name="useDefaultPassword" #useDefaultPasswordInput="ngModel"
                       [(ngModel)]="useDefaultPassword">{{l("UseDefaultPassword", "123qwe")}}</label>
            </nz-form-control>

        </nz-form-control>

        <!-- 租户管理员密码 -->
        <nz-form-item *ngIf="!useDefaultPassword">
            <nz-form-label nzFor="password" nzRequired>{{l('Password')}}</nz-form-label>
            <nz-form-control nzHasFeedback>
                <input nz-input name="password" #passwordInput="ngModel"
                       [(ngModel)]="model.adminPassword"
                       [placeholder]="l('Password')"
                       type="password"
                       required
                       minlength="6" maxlength="32">
                <nz-form-control nzExtra *ngIf="passwordInput.control.dirty&&passwordInput.control.errors">
                    <ng-container *ngIf="passwordInput.control.hasError('minlength')">{{l('minlength')}}</ng-container>
                    <ng-container *ngIf="passwordInput.control.hasError('maxlength')">{{l('maxlength')}}</ng-container>
                    <ng-container
                            *ngIf="passwordInput.control.hasError('required')">{{l('ThisFieldIsRequired')}}</ng-container>
                </nz-form-control>
            </nz-form-control>
        </nz-form-item>

        <!-- 租户管理员确认密码 -->
        <nz-form-item *ngIf="!useDefaultPassword">
            <nz-form-label nzFor="password" nzRequired>{{l('ConfirmPassword')}}</nz-form-label>
            <nz-form-control nzHasFeedback>
                <input nz-input name="confirmPassword" #confirmPasswordInput='ngModel' [(ngModel)]="confirmPassword"
                       [placeholder]="l('ConfirmPassword')"
                       type="password"
                       [validateEqual]="model.adminPassword"
                       required>
                <nz-form-control nzExtra
                                 *ngIf="confirmPasswordInput.control.dirty&&confirmPasswordInput.control.errors">
                    <ng-container *ngIf="confirmPasswordInput.control.hasError('required')">{{l('ThisFieldIsRequired')}}
                    </ng-container>
                    <ng-container
                            *ngIf="confirmPasswordInput.control.hasError('validateEqual')">{{l('PasswordInconsistent')}}
                    </ng-container>
                </nz-form-control>
            </nz-form-control>
        </nz-form-item>

        <!-- 版本 -->
        <nz-form-item>
            <nz-form-label>{{l('Edition')}}</nz-form-label>
            <nz-form-control nzHasFeedback>
                <edition-combo [(selectedEdition)]="edition" (selectedEditionChange)="selectedEditionChange($event)"
                               [placeholder]="l('PleaseSelect')"></edition-combo>
            </nz-form-control>
        </nz-form-item>

        <!-- 无限时间订阅 -->
        <nz-form-control *ngIf="model.editionId">
            <label nz-checkbox name="isUnlimited" #isUnlimitedInput="ngModel"
                   [(ngModel)]="isUnlimited">{{l("IsUnlimited")}}</label>
        </nz-form-control>

        <!-- 结束时间 -->
        <nz-form-item *ngIf="model.editionId&&!isUnlimited">
            <nz-form-label nzFor="edition" nzRequired>{{l('SubscriptionEndDateUtc')}}</nz-form-label>
            <nz-form-control nzHasFeedback nzRequired>
                <nz-date-picker name="subscriptionEndUtc" #subscriptionEndUtcInput="ngModel"
                                [(ngModel)]="model.subscriptionEndUtc" required></nz-date-picker>
                <nz-form-control nzExtra
                                 *ngIf="subscriptionEndUtcInput.control.dirty&&subscriptionEndUtcInput.control.errors">
                    <ng-container
                            *ngIf="subscriptionEndUtcInput.control.hasError('required')">{{l('ThisFieldIsRequired')}}
                    </ng-container>
                </nz-form-control>
            </nz-form-control>
        </nz-form-item>

        <!-- 是否试用 -->
        <nz-form-control>
            <label nz-checkbox name="isInTrialPeriod" #isInTrialPeriodInput="ngModel"
                   [(ngModel)]="model.isInTrialPeriod"
                   [nzDisabled]="edition&&edition.isFree">{{l("IsInTrialPeriod")}}</label>
        </nz-form-control>

        <!-- 下次登陆需要修改密码 -->
        <nz-form-control>
            <label nz-checkbox name="shouldChangePasswordOnNextLogin" #shouldChangePasswordOnNextLoginInput="ngModel"
                   [(ngModel)]="model.shouldChangePasswordOnNextLogin">{{l("ShouldChangePasswordOnNextLogin")}}</label>
        </nz-form-control>

        <!-- 发送激活邮件 -->
        <nz-form-control>
            <label nz-checkbox name="sendActivationEmail" #sendActivationEmailInput="ngModel"
                   [(ngModel)]="model.sendActivationEmail">{{l("SendActivationEmail")}}</label>
        </nz-form-control>

        <!-- 激活 -->
        <nz-form-control>
            <label nz-checkbox name="isActive" #isActiveInput="ngModel"
                   [(ngModel)]="model.isActive">{{l("IsActive")}}</label>
        </nz-form-control>


        <!-- 功能按钮 -->
        <div class="modal-footer">
            <button nz-button type="button" [disabled]="saving" (click)="close()">
                {{l("Cancel")}}
            </button>
            <button nz-button [nzType]="'primary'" type="submit" [disabled]="!validateForm.valid||saving">
                {{l("Save")}}
            </button>
        </div>


    </form>
</nz-spin>

// src/yoyocmstemplate-vue/src/app/admin/tenants/create-tenant/create-tenant.vue
<template>
  <a-spin :spinning="spinning">
    <div class="modal-header">
      <div class="modal-title">{{l('CreateNewTenant')}}</div>
    </div>
    <a-form :form="form" @submit="handleSubmit">
      <!-- 租户名称 -->
      <a-form-item :label="l('TenancyName')">
        <a-input
          :placeholder="l('TenancyName')"
          v-decorator="[
                        'tenancyName',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]"
        />
      </a-form-item>

      <!-- 租户显示名称 -->
      <a-form-item :label="l('DisplayTenancyName')">
        <a-input
          :placeholder="l('Name')"
          v-decorator="[
                        'name',
                        {
                            rules: [
                                {
                                    required: true,
                                message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]"
        />
      </a-form-item>

      <!-- UseHostDatabase -->
      <a-checkbox
        @change="UseHostDatabaseChange"
        :checked="UseHostDatabasechecked"
      >{{l("UseHostDatabase")}}</a-checkbox>
      <a-form-item :label="l('DatabaseConnectionString')" v-if="!UseHostDatabasechecked">
        <a-input
          :placeholder="l('DatabaseConnectionString')+l('Optional')"
          v-decorator="[
                        'connectionString',
                        {
                            rules: [
                                {
                                    required: true,
                                message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]"
        />
      </a-form-item>

      <!-- 管理员邮箱 -->
      <a-form-item :label="l('AdminEmailAddress')">
        <a-input
          :placeholder="l('EmailAddress')"
          v-decorator="[
                        'adminEmailAddress',
                        {
                            rules: [
                                {
                                    type: 'email',
                                    message: l('NotEmail'),
                                },
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                },
                            ],
                        },
                        ]"
        />
      </a-form-item>

      <!-- 密码 -->
      <a-checkbox
        @change="passwordChange"
        :checked="passwordchecked"
      >{{l("UseDefaultPassword","123qwe")}}</a-checkbox>
      <a-form-item :label="l('Password')" v-if="!passwordchecked" has-feedback>
        <a-input
          :placeholder="l('Password')"
          type="password"
          v-decorator="[
                        'adminPassword',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                },
                                {
                                    max: 32,
                                    message: l('maxlength'),
                                },
                                {
                                    min: 6,
                                    message: l('minlength'),
                                },
                                {
                                    validator: validateToNextPassword,
                                },
                            ],
                        },
                        ]"
        />
      </a-form-item>
      <a-form-item :label="l('ConfirmPassword')" v-if="!passwordchecked" has-feedback>
        <a-input
          :placeholder="l('ConfirmPassword')"
          type="password"
          v-decorator="[
                        'confirmPassword',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                },
                                {
                                    validator: validateEqual,
                                },
                            ],
                        },
                        ]"
        />
      </a-form-item>

      <!-- 版本 -->
      <a-form-item :label="l('Edition')" has-feedback>
        <edition-combo
          :placeholder="l('PleaseSelect')"
          :selectedEdition="selectedEdition"
          @selectedEditionChange="selectedEditionChange($event)"
        ></edition-combo>
      </a-form-item>

      <!-- IsUnlimited -->
      <a-checkbox
        @change="checkedChange('IsUnlimitedchecked', $event)"
        v-if="isShowIsUnlimited"
        :checked="IsUnlimitedchecked"
      >{{l("IsUnlimited")}}</a-checkbox>
      <a-form-item
        :label="l('SubscriptionEndDateUtc')"
        v-if="!IsUnlimitedchecked && isShowIsUnlimited"
      >
        <a-date-picker
          @change="subscriptionEndDateUtconChange"
          placeholder="请选择日期"
          v-decorator="[
                        'subscriptionEndUtc',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]"
        />
      </a-form-item>
      <br />

      <!-- 是否试用 -->
      <a-checkbox
        @change="checkedChange('isInTrialPeriod', $event)"
        :disabled="IsInTrialPerioddisabled"
        :checked="isInTrialPeriod"
      >{{l("IsInTrialPeriod")}}</a-checkbox>
      <br />

      <!-- 下次登录需要修改密码 -->
      <a-checkbox
        @change="checkedChange('shouldChangePasswordOnNextLogin', $event)"
        :checked="shouldChangePasswordOnNextLogin"
      >{{l("ShouldChangePasswordOnNextLogin")}}</a-checkbox>
      <br />

      <!-- 发送激活邮件 -->
      <a-checkbox
        @change="checkedChange('sendActivationEmail', $event)"
        :checked="sendActivationEmail"
      >{{l("SendActivationEmail")}}</a-checkbox>
      <br />

      <!-- 是否激活 -->
      <a-checkbox @change="checkedChange('isActive', $event)" :checked="isActive">{{l("IsActive")}}</a-checkbox>

      <a-form-item class="btn--container">
        <a-button type="button" @click="close()">{{ l("Cancel") }}</a-button>
        <a-button type="primary" html-type="submit">{{ l('Save') }}</a-button>
      </a-form-item>
    </a-form>
  </a-spin>
</template>

<script>
import { ModalComponentBase } from "@/shared/component-base";
import EditionCombo from "../../shared/edition-combo/edition-combo.vue";
import {
  TenantServiceProxy,
  TenantListDto,
  SubscribableEditionComboboxItemDto,
  EntityDtoOfInt64,
  NameValueDto,
  CommonLookupServiceProxy,
  CommonLookupFindUsersInput
} from "@/shared/service-proxies";

export default {
  name: "create-tenant-component",
  mixins: [ModalComponentBase],
  components: {
    EditionCombo
  },
  data() {
    return {
      confirmDirty: false,
      autoCompleteResult: [],
      UseHostDatabasechecked: true,
      passwordchecked: true,
      // 版本
      selectedEdition: {
        value: 0
      },
      // 是否在试用期
      isInTrialPeriod: false,
      IsInTrialPerioddisabled: false,
      // 下次登录需要修改密码
      shouldChangePasswordOnNextLogin: false,
      // 发送激活邮件
      sendActivationEmail: false,
      // 是否激活
      isActive: true,
      IsUnlimitedchecked: false,
      // IsUnlimited
      isShowIsUnlimited: false,
      // 版本号
      editionId: 0,
      spinning: false
    };
  },
  beforeCreate() {
    this.form = this.$form.createForm(this, { name: "register" });
  },
  created() {
    this.fullData(); // 模态框必须,填充数据到data字段
  },
  methods: {
    /**
     * UseHostDatabaseChange
     */
    UseHostDatabaseChange(e) {
      this.UseHostDatabasechecked = eval(`${e.target.checked}`.toLowerCase());
    },
    /**
     * password
     */
    passwordChange(e) {
      this.passwordchecked = eval(`${e.target.checked}`.toLowerCase());
    },
    /**
     * 验证密码
     */
    validateToNextPassword(rule, value, callback) {
      const form = this.form;
      if (value && this.confirmDirty) {
        form.validateFields(["confirm"], { force: true });
      }
      callback();
    },
    validateEqual(rule, value, callback) {
      const form = this.form;
      if (value && value !== form.getFieldValue("adminPassword")) {
        callback(this.l("PasswordInconsistent"));
      } else {
        callback();
      }
    },
    /**
     * 版本选择
     */
    selectedEditionChange(e) {
      if (e && e.value) {
        this.IsInTrialPerioddisabled = true;
        this.isShowIsUnlimited = true;
        this.editionId = parseInt(e.value);
      } else {
        this.IsInTrialPerioddisabled = false;
        this.isShowIsUnlimited = false;
        this.editionId = null;
      }
    },
    /**
     * 是否试用
     * 下次登录需要修改密码
     * 发送激活邮
     * 是否激活
     */
    checkedChange(type, e) {
      this[`${type}`] = eval(`${e.target.checked}`.toLowerCase());
    },
    /**
     * 订阅结束日期
     */
    subscriptionEndDateUtconChange(date, dateString) {
      console.log(date, dateString);
    },
    /**
     * 提交表单
     */
    handleSubmit(e) {
      e.preventDefault();
      this.form.validateFieldsAndScroll((err, values) => {
        if (!err) {
          let otherobj = {
            shouldChangePasswordOnNextLogin: this
              .shouldChangePasswordOnNextLogin,
            sendActivationEmail: this.sendActivationEmail,
            isInTrialPeriod: this.isInTrialPeriod,
            isActive: this.isActive,
            editionId: this.editionId
          };
          values = Object.assign(values, otherobj);
          values.subscriptionEndUtc =
            !this.editionId || this.IsUnlimitedchecked
              ? null
              : values.subscriptionEndUtc;
          this.spinning = true;
          this._tenantService = new TenantServiceProxy(this.$apiUrl, this.$api);
          this._tenantService
            .create(values)
            .finally(() => {
              this.spinning = false;
            })
            .then(res => {
              // this.notify.success(this.l('SavedSuccessfully'));
              this.$notification["success"]({
                message: this.l("SavedSuccessfully")
              });
              this.success();
            })
            .catch(err => {
              console.log(err);
            });
        }
      });
    }
  }
};
</script>

<style lang="less" scoped>
/deep/.btn--container .ant-form-item-children {
  display: block;
  margin: 10px auto;
  text-align: center;
}
</style>
