// src/yoyocmstemplate-angular/src/app/admin/users/users.component.ts
import { Component, OnInit, Injector, ViewChild } from '@angular/core';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import {
  UserListDto,
  UserServiceProxy,
  EntityDtoOfInt64,
  PagedResultDtoOfUserListDto,
} from '@shared/service-proxies/service-proxies';
import { CreateOrEditUserComponent } from '@app/admin/users/create-or-edit-user/create-or-edit-user.component';
import { EditUserPermissionsComponent } from '@app/admin/users/edit-user-permissions/edit-user-permissions.component';
import { ActivatedRoute } from '@angular/router';
import { finalize } from 'rxjs/operators';

// import _ = require('../@types/lodash');
import * as _ from 'lodash';
import { AppConsts } from 'abpPro/AppConsts';
import { ImpersonationService } from '@shared/auth';
import { getBaseHref } from '../../../root.module';
import { FileDownloadService } from '@shared/utils';
import { TokenService } from 'abp-ng2-module';
import { UploadFile } from 'ng-zorro-antd/upload';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styles: [],
})
export class UsersComponent extends PagedListingComponentBase<UserListDto> implements OnInit {
  /**
   * 从Excel导入用户后台处理地址
   */
  importFromExcelUrl: string = AppConsts.remoteServiceBaseUrl + '/UserImport/ImportFromExcel';

  importFromExcelTemplateUrl: string =
    AppConsts.remoteServiceBaseUrl + '/yoyosoft/SampleFiles/ImportUsersSampleFile.xlsx';

  uploadHeaders: any;

  // 模糊搜索
  filterText = '';
  advancedFiltersVisible = false; // 是否显示高级过滤
  /**
   * 选中的权限过滤
   */
  selectedPermission: string[] = [];

  /**
   * 是否激活过滤
   */
  isActive: boolean = undefined;
  /**
   * 是否已验证邮箱过滤
   */
  isEmailConfirmed: boolean = undefined;
  /**
   * 选中的角色Ids过滤
   */
  role: number[] = undefined;

  /**
   * 是否显示解锁按钮
   */
  get enabledUnlock(): boolean {
    return (
      this.isGranted('Pages.Administration.Users.Edit') &&
      this.setting.getBoolean('Abp.Zero.UserManagement.UserLockOut.IsEnabled')
    );
  }

  constructor(
    injector: Injector,
    private _userService: UserServiceProxy,
    private _activatedRoute: ActivatedRoute,
    public _impersonationService: ImpersonationService,
    private _fileDownloadService: FileDownloadService,
    private _tokenService: TokenService,
  ) {
    super(injector);
    this.filterText = this._activatedRoute.snapshot.queryParams.filterText || '';
    // 设置头部信息
    this.uploadHeaders = {
      Authorization: 'Bearer ' + this._tokenService.getToken(),
    };
    console.log(
      this.isGrantedAny(
        'Pages.Administration.Users.Impersonation',
        'Pages.Administration.Users.ChangePermissions',
        'Pages.Administration.Users.Unlock',
      ),
    );
  }

  // 搜索
  onSearch(): void {
    this.refresh();
  }

  /**
   * 激活过滤
   * @param event 值
   */
  isActiveFilter(event: any): void {
    if (event === null || event === 'All') {
      this.isActive = undefined;
    } else {
      this.isActive = event;
    }
    this.refreshGoFirstPage();
  }

  /**
   * 邮件确认过滤
   * @param event 值
   */
  isEmailConfirmedFilter(event: any): void {
    if (event === null || event === 'All') {
      this.isEmailConfirmed = undefined;
    } else {
      this.isEmailConfirmed = event;
    }
    this.refreshGoFirstPage();
  }

  /**
   * 根据角色列表进行数据展示
   * @param roles 角色列表信息
   */
  getRolesAsString(roles): string {
    let roleNames = '';
    for (let j = 0; j < roles.length; j++) {
      if (roleNames.length) {
        roleNames = roleNames + ', ';
      }
      roleNames = roleNames + roles[j].roleName;
    }
    return roleNames;
  }

  /**
   * 添加或者编辑实体信息模态框
   * @param id 需要修改实体信息的ID
   */
  createOrEdit(id?: number): void {
    this.modalHelper.static(CreateOrEditUserComponent, { id: id }).subscribe(res => {
      if (res) {
        this.refresh();
      }
    });
  }

  editUserPermissions(user: UserListDto): void {
    this.modalHelper
      .open(EditUserPermissionsComponent, {
        userId: user.id,
        userName: user.userName,
      })
      .subscribe(result => {
      });
  }

  unlockUser(user: UserListDto): void {
    const data = new EntityDtoOfInt64();
    data.id = user.id;
    this._userService
      .unlock(data)
      .finally(() => {
      })
      .subscribe(() => {
        this.refresh();
        this.notify.success(this.l('SuccessfullyUnlock'));
      });
  }

  /**
   * 强制刷新
   */
  forceRefresh() {
    this.filterText = '';
    this.isEmailConfirmed = undefined;
    this.isActive = undefined;
    this.selectedPermission = undefined;
    this.role = undefined;
    this.refreshGoFirstPage();
  }

  /**
   * 获取远端数据
   * @param request
   * @param pageNumber
   * @param finishedCallback
   */
  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    this._userService
      .getPaged(
        this.selectedPermission,
        this.role,
        this.isEmailConfirmed,
        this.isActive,
        undefined,
        this.filterText,
        request.sorting,
        request.maxResultCount,
        request.skipCount,
      )
      .pipe(
        finalize(() => {
          finishedCallback();
        }),
      )
      .subscribe((result: PagedResultDtoOfUserListDto) => {
        this.dataList = result.items;
        this.showPaging(result);
      });
  }

  /**
   * 批量删除
   */
  batchDelete(): void {
    const selectCount = this.selectedDataItems.length;
    if (selectCount <= 0) {
      abp.message.warn(this.l('PleaseSelectAtLeastOneItem'));
      // this.miniMessage.warning(this.l('PleaseSelectAtLeastOneItem'));
      return;
    }
    this.message.confirm(this.l('ConfirmDeleteXItemsWarningMessage', selectCount), undefined, res => {
      if (res) {
        const ids = _.map(this.selectedDataItems, 'id');
        this._userService.batchDelete(ids).subscribe(() => {
          this.refreshGoFirstPage();
          this.notify.success(this.l('SuccessfullyDeleted'));
        });
      }
    });
  }

  /**
   * 下载user的模板
   */
  ImportUsersSampleFile(): void {
    this._fileDownloadService.downloadTemplateFile('ImportUsersSampleFile.xlsx');
  }

  exportToExcel(): void {
    this._userService.getUsersToExcel().subscribe(result => {
      console.log(result);
      this._fileDownloadService.downloadTempFile(result);
    });
    // 调用后端的到处方法
  }

  /**
   * 删除功能
   * @param entity 实体信息：User
   */
  delete(entity: UserListDto): void {
    if (entity.userName === AppConsts.userManagement.defaultAdminUserName) {
      abp.message.warn(this.l('XUserCannotBeDeleted', AppConsts.userManagement.defaultAdminUserName));
      return;
    }

    this._userService.delete(entity.id).subscribe(() => {
      this.refreshGoFirstPage();
      this.notify.success(this.l('SuccessfullyDeleted'));
    });
  }

  isAdmin(item: UserListDto): boolean {
    return item.userName === AppConsts.userManagement.defaultAdminUserName;
  }

  refreshCheckStatus(entityList: any[]): void {
    entityList.forEach(item => {
      if (item.userName === AppConsts.userManagement.defaultAdminUserName) {
        item.checked = false;
      }
    });

    // 是否全部选中
    const allChecked = entityList.every(value => value.checked === true);
    // 是否全部未选中
    const allUnChecked = entityList.every(value => !value.checked);
    // 是否全选
    this.allChecked = allChecked;
    // 全选框样式控制
    this.checkboxIndeterminate = !allChecked && !allUnChecked;
    // 已选中数据
    this.selectedDataItems = entityList.filter(value => value.checked);
  }

  /**
   * 选择Excel上传事件
   * @param info 反馈信息
   */
  uploadPictureChange(info: any) {
    if (info.type === 'success') {
      this.refreshGoFirstPage();
    }
  }
}

<page-header [title]="l('Users')"></page-header>

<!-- 表格部分 -->

<nz-card [nzBordered]="false">
  <div class="mb-md">
    <!-- 模糊搜索框 -->
    <nz-row nzGutter="8">
      <nz-col nzSm="24">
        <nz-form-item>
          <nz-form-control>
            <nz-input-group nzSearch [nzAddOnAfter]="suffixSearchButton">
              <input type="text" nz-input [(ngModel)]="filterText" name="filterText" (keyup.enter)="refresh()"
                [placeholder]="l('SearchWithThreeDot')" />
              <ng-template #suffixSearchButton>
                <button nz-button nzType="primary" nzSearch (click)="onSearch()">
                  <!-- <i class="iconfont icon-search"></i> -->
                  <i class="iconfont icon-search"></i>
                </button>
              </ng-template>
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
      </nz-col>
    </nz-row>

    <!-- 高级过滤 -->

    <nz-row nzGutter="8" *ngIf="advancedFiltersVisible">
      <nz-col nzSm="12">
        <app-permission-combox [multiple]="true" [dropDownStyle]="{ 'max-height': '500px' }"
          [(selectedPermission)]="selectedPermission" (selectedPermissionChange)="refreshGoFirstPage()">
        </app-permission-combox>
      </nz-col>
      <nz-col nzSm="12">
        <app-role-combox [(selectedRole)]="role" (selectedRoleChange)="refreshGoFirstPage()"></app-role-combox>
      </nz-col>
    </nz-row>
  </div>

  <!-- 操作常规按钮部分 -->

  <nz-row nzGutter="8">
    <nz-col nzMd="20" nzSm="12" class="btn-gutter">
      <button nz-button [nzType]="'primary'" *ngIf="isGranted('Pages.Administration.Users.Create')"
        (click)="createOrEdit()">
        <i class="iconfont icon-plus"></i>

        <span>
          {{ l('CreateNewUser') }}
        </span>
      </button>
      <button nz-button [nzType]="'danger'" *ngIf="isGranted('Pages.Administration.Users.Delete')"
        (click)="batchDelete()">
        <i class="iconfont icon-delete"></i>

        <span>
          {{ l('BatchDelete') }}
        </span>
      </button>

      <button nz-button nzType="default" *ngIf="isGranted('Pages.Administration.Users.ExportToExcel')"
        (click)="exportToExcel()">
        <i class="iconfont icon-file-excel"></i>
        <!-- <i class="iconfont icon-file-excel"></i> -->
        <span>
          {{ l('ExportToExcel') }}
        </span>
      </button>

      <button nz-button *ngIf="isGranted('Pages.Administration.Users.Impersonation')" nzType="default"
        (click)="ImportUsersSampleFile()" file-name="ImportUsersSampleFile">
        <i class="iconfont icon-file-excel"></i>
        <!-- <i class="iconfont icon-file-excel"></i> -->
        <span>
          {{ l('ImportToExcelTemplate') }}
        </span>
      </button>

      <nz-upload nzAction="{{ importFromExcelUrl }}" [nzHeaders]="uploadHeaders"
        (nzChange)="uploadPictureChange($event)" nzWithCredentials="false" nzAccept="xls/*">
        <button nz-button nzType="default" *ngIf="isGranted('Pages.Administration.Users.Impersonation')">
          <!-- <i class="iconfont icon-file-excel" nzType="upload"></i> -->
          <i class="iconfont icon-file-excel"></i>
          <span>
            {{ l('ImportFromExcel') }}
          </span>
        </button>
      </nz-upload>
    </nz-col>
    <nz-col nzMd="4" nzSm="12" class="text-right">
      <a (click)="advancedFiltersVisible = !advancedFiltersVisible">
        {{ advancedFiltersVisible ? l('HideAdvancedFilters') : l('ShowAdvancedFilters') }}
        <!-- <i class="anticon" [class.anticon-down]="!advancedFiltersVisible"
          [class.anticon-up]="advancedFiltersVisible"></i> -->

        <i class="iconfont" [class.icon-down]="!advancedFiltersVisible" [class.icon-up]="advancedFiltersVisible"></i>
      </a>
    </nz-col>
  </nz-row>
  <!-- 数据部分 -->
  <!-- 复选框提示的内容数据部分 -->
  <table-checkbox-panel [selectLength]="selectedDataItems.length" (onClear)="restCheckStatus(dataList)"
    (onRefresh)="refreshGoFirstPage()"></table-checkbox-panel>
  <!-- 表格内容 -->

  <nz-table #ajaxTable [nzData]="dataList" [nzTotal]="totalItems" [(nzPageIndex)]="pageNumber" [(nzPageSize)]="pageSize"
    [nzLoading]="isTableLoading" (nzPageIndexChange)="pageNumberChange()" (nzPageSizeChange)="refresh()"
    [nzShowSizeChanger]="true" [nzShowQuickJumper]="true" [nzNoResult]="noDataTemplate"
    [nzShowTotal]="showTotalTemplate" [nzFrontPagination]="false">
    <!-- 暂无数据 -->
    <ng-template #noDataTemplate>
      <no-data></no-data>
    </ng-template>
    <!-- 分页信息显示 当前 1 页/共 3 页，共 5 条/显示 1-2 条 -->
    <ng-template #showTotalTemplate let-total let-range="range">
      {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
    </ng-template>
    <!-- 表头 -->
    <thead (nzSortChange)="gridSort($event)">
      <tr>
        <th nzShowCheckbox [(nzChecked)]="allChecked" [nzDisabled]="allCheckboxDisabled"
          [nzIndeterminate]="checkboxIndeterminate" (nzCheckedChange)="checkAll($event)"></th>

        <th nzShowSort nzSortKey="userName">
          <span>{{ l('UserName') }}</span>
        </th>
        <th>
          <span>{{ l('Roles') }}</span>
        </th>

        <th nzShowSort nzSortKey="emailAddress">
          <span>{{ l('EmailAddress') }}</span>
        </th>
        <th nzShowSort nzSortKey="isEmailConfirmed" nzShowFilter [nzFilterMultiple]="false"
          [nzFilters]="booleanFilterList" (nzFilterChange)="isEmailConfirmedFilter($event)" class="text-center">
          <span>{{ l('EmailConfirm') }}</span>
        </th>
        <th nzShowSort nzSortKey="isActive" nzShowFilter [nzFilterMultiple]="false" [nzFilters]="booleanFilterList"
          (nzFilterChange)="isActiveFilter($event)" class="text-center">
          <span>{{ l('Active') }}</span>
        </th>
        <th nzShowSort nzSortKey="lastLoginTime" class="text-center">
          <span>{{ l('LastLoginTime') }}</span>
        </th>
        <th nzShowSort nzSortKey="creationTime" class="text-center">
          <span>{{ l('CreationTime') }}</span>
        </th>
        <th nzWidth="230px" class="text-center">
          <span>{{ l('Actions') }}</span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let item of ajaxTable.data">
        <td nzShowCheckbox [(nzChecked)]="item.checked" [nzDisabled]="isAdmin(item)"
          (nzCheckedChange)="refreshCheckStatus(dataList)"></td>
        <td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.userName">
              {{ item.userName }}
            </span>
          </ellipsis>
        </td>
        <td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="getRolesAsString(item.roles)">
              <nz-tag *ngFor="let role of item.roles">
                {{ role.roleName }}
              </nz-tag>
            </span>
          </ellipsis>
        </td>
        <td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.emailAddress">
              {{ item.emailAddress }}
            </span>
          </ellipsis>
        </td>
        <td class="text-center" [innerHTML]="item.isEmailConfirmed | yn"></td>
        <td class="text-center" [innerHTML]="item.isActive | yn"></td>
        <td class="text-center">
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.lastLoginTime ? (item.lastLoginTime | _moment) : '—'">
              {{ item.lastLoginTime ? (item.lastLoginTime | _moment) : '—' }}
            </span>
          </ellipsis>
        </td>
        <td class="text-center">
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.creationTime | _moment">
              {{ item.creationTime | _moment }}
            </span>
          </ellipsis>
        </td>
        <td>
          <!-- 编辑 -->
          <ng-container *ngIf="isGranted('Pages.Administration.Users.Edit')">
            <a (click)="createOrEdit(item.id)">
              <i class="iconfont icon-edit mr-sm"></i>
              <span>{{ l('Edit') }}</span>
            </a>
            <nz-divider nzType="vertical"></nz-divider>
          </ng-container>
          <!-- 删除 -->
          <ng-container *ngIf="isGranted('Pages.Administration.Users.Delete') && !isAdmin(item)">
            <a nz-popconfirm [nzPopconfirmTitle]="l('ConfirmDeleteWarningMessage')" (nzOnConfirm)="delete(item)"
              [nzOkText]="l('Ok')" [nzCancelText]="l('Cancel')">
              <i class="iconfont icon-delete mr-sm"></i>
              <span>{{ l('Delete') }}</span>
            </a>
          </ng-container>
          <!-- 更多 -->
          <ng-container *ngIf="
                isGrantedAny(
                  'Pages.Administration.Users.Impersonation',
                  'Pages.Administration.Users.ChangePermissions',
                  'Pages.Administration.Users.Unlock'
                )
              ">
            <nz-divider nzType="vertical"></nz-divider>
            <a nz-dropdown [nzDropdownMenu]="menu">
              {{ l('Actions') }}
              <i class="iconfont icon-down"></i>
              <!-- <i nz-icon nzType="down"></i> -->
            </a>
            <nz-dropdown-menu #menu="nzDropdownMenu">
              <a nz-dropdown>
                <i class="iconfont icon-down"></i>
                <!-- <i class="iconfont icon-down"></i> -->
                <span>{{ l('More') }}</span>
              </a>
              <ul nz-menu>
                <li nz-menu-item>
                  <a *ngIf="isGranted('Pages.Administration.Users.Impersonation') && item.id !== appSession.userId"
                    (click)="_impersonationService.impersonate(item.id, appSession.tenantId)">{{ l('LoginAsThisUser') }}</a>
                </li>
                <li nz-menu-item *ngIf="isGranted('Pages.Administration.Users.Edit')"
                  (click)="editUserPermissions(item)">
                  <a>
                    <i class="iconfont icon-safety mr-sm"></i>
                    <!-- <i class="iconfont icon-safety mr-sm"></i> -->
                    <span>{{ l('Permissions') }}</span>
                  </a>
                </li>
                <li nz-menu-item *ngIf="enabledUnlock" (click)="unlockUser(item)">
                  <a>
                    <i class="iconfont icon-unlock mr-sm"></i>
                    <!-- <i class="iconfont icon-unlock mr-sm"></i> -->
                    <span>{{ l('Unlock') }}</span>
                  </a>
                </li>
              </ul>
            </nz-dropdown-menu>
          </ng-container>
        </td>
      </tr>
    </tbody>
  </nz-table>

</nz-card>

// src/yoyocmstemplate-vue/src/app/admin/users/users.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('Users')"></page-header>
        <a-card :bordered="false">
            <a-form :layout="'vertical'" @submit.prevent="getData">
                <a-row :gutter="8">
                    <!-- 搜索 -->
                    <a-col :sm="24">
                        <a-form-item>
                            <a-input-search
                                name="filterText"
                                :placeholder="l('SearchWithThreeDot')"
                                @search="getData"
                                enterButton
                                v-model="filterText"
                                v-decorator="['filterText']" />
                        </a-form-item>
                    </a-col>
                    <!-- 权限过滤 -->
                    <a-col :sm="12" v-if="advancedFiltersVisible">
                        <a-form-item>
                            <permission-combox
                                :multiple="true"
                                :dropDownStyle="{ 'max-height': '500px' }"
                                :selectedPermission="selectedPermission"
                                @selectedPermissionChange="refreshGoFirstPage">
                            </permission-combox>
                        </a-form-item>
                    </a-col>
                    <!-- 角色过滤 -->
                    <a-col :sm="12" v-if="advancedFiltersVisible">
                        <a-form-item>
                            <role-combox :selectedRole="role" @selectedRoleChange="selectedRoleChange"></role-combox>
                        </a-form-item>
                    </a-col>
                </a-row>
            </a-form>
            <!-- 操作部分 -->
            <a-row :gutter="8">
                <a-col :md="20" :sm="12">
                    <!-- 添加用户 -->
                    <a-button
                        :type="'primary'"
                        v-if="isGranted('Pages.Administration.Users.Create')"
                        @click="createOrEdit()">
                        <a-icon type="plus" />
                        <span>{{l("CreateNewUser")}}</span>
                    </a-button>
                    <!-- 批量删除 -->
                    <a-button :type="'danger'" v-if="isGranted('Pages.Administration.Users.Delete')" @click="batchDelete">
                        <a-icon type="delete" />
                        <span>{{l("BatchDelete")}}</span>
                    </a-button>
                    <!-- 导出excel -->
                    <a-button v-if="isGranted('Pages.Administration.Users.ExportToExcel')" @click="exportToExcel">
                        <a-icon type="file-excel" />
                        <span>{{l("ExportToExcel")}}</span>
                    </a-button>
                    <!-- 下载excel -->
                    <a-button v-if="isGranted('Pages.Administration.Users.Impersonation')" @click="ImportUsersSampleFile">
                        <a-icon type="file-excel" />
                        <span>{{l("ImportToExcelTemplate")}}</span>
                    </a-button>
                    <!-- 导入excel -->
                    <!-- <a-button v-if="isGranted('Pages.Administration.Users.Impersonation')">
                        <a-icon type="file-excel" />
                        <span>{{l("ImportFromExcel")}}</span>
                    </a-button> -->
                    <a-upload
                        :action="importFromExcelUrl"
                        :multiple="false"
                        :fileList="fileList"
                        accept="xls/*"
                        :headers="uploadHeaders"
                        @change="uploadChange">
                        <a-button style="margin-left:10px" v-if="isGranted('Pages.Administration.Users.Impersonation')">
                            <a-icon type="file-excel" />
                            <span>{{l("ImportFromExcel")}}</span>
                        </a-button>
                    </a-upload>
                </a-col>
                <!-- 显示暴击过滤 -->
                <a-col :md="4" :sm="12" class="text-right">
                    <a @click="advancedFiltersVisible=!advancedFiltersVisible">
                        {{advancedFiltersVisible ? l('HideAdvancedFilters') : l('ShowAdvancedFilters')}}
                        <a-icon :type="advancedFiltersVisible ? 'up' : 'down'" />
                    </a>
                </a-col>
            </a-row>

            <!-- 数据部分 -->
            <div class="my-md">
                <a-alert :type="'info'" :showIcon="true">
                    <template slot="message">
                        <span v-html="l('GridSelectedXItemsTips',selectedRowKeys.length)"></span>
                        <a @click="restCheckStatus()" class="ml-md">{{l('ClearEmpty')}}</a>
                        <a-divider type="vertical"></a-divider>
                        <a @click="getData()">{{l('Refresh')}}</a>
                    </template>
                </a-alert>
            </div>

            <a-row>
                <a-table
                    class="list-table"
                    @change="getData"
                    :pagination="false"
                    :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange, getCheckboxProps:getCheckboxProps}"
                    :columns="columns"
                    :rowKey="tableDatas => tableDatas.id"
                    :dataSource="tableData">
                    <!-- 角色 -->
                    <p class="roles" slot="roles" slot-scope="text, record">
                        <a-tag v-for="item in record.roles" :key="item.roleId">{{ item.roleName }}</a-tag>
                    </p>
                    <!-- 是否邮箱验证 -->
                    <a class="isEmailConfirmed" slot="isEmailConfirmed" slot-scope="record">
                        <a-icon v-if="record" type="check" />
                        <a-icon v-if="!record" type="close" />
                    </a>
                    <!-- 是否激活-->
                    <a class="isActive" slot="isActive" slot-scope="record">
                        <a-icon v-if="record" type="check" />
                        <a-icon v-if="!record" type="close" />
                    </a>
                    <!-- 上次登录时间 -->
                    <a class="lastLoginTime" slot="lastLoginTime" slot-scope="record">
                        <p v-if="record">{{ record }}</p>
                        <p v-if="!record">---</p>
                    </a>
                    <span slot="actions" slot-scope="text, record">
                        <!-- 修改 -->
                        <a class="table-edit" @click="createOrEdit(record.id)" v-if="isGranted('Pages.Administration.Users.Edit')">
                            <a-icon type="edit" />{{ l('Edit') }}</a>
                        <!-- 删除 -->
                        <a-popconfirm placement="top" v-if="!isAdmin(record) && isGranted('Pages.Administration.Users.Delete')" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="deleteItem(record)">
                            <template slot="title">
                                {{ l('ConfirmDeleteWarningMessage') }}
                            </template>
                            <a class="table-delete">
                                <a-icon type="delete" />{{ l('Delete') }}</a>
                        </a-popconfirm>
                        <!-- 更多 -->
                        <a-dropdown v-if="!isGrantedAny(
                                'Pages.Administration.Users.Impersonation',
                                'Pages.Administration.Users.ChangePermissions',
                                'Pages.Administration.Users.Unlock'
                                )">
                            <a class="ant-dropdown-link" @click="e => e.preventDefault()">
                                {{ l('Actions') }}
                                <a-icon type="down" />
                            </a>
                            <a-menu slot="overlay">
                                <a-menu-item
                                    v-if="isGranted('Pages.Administration.Users.Impersonation') && record.id !== _appSessionService.userId"
                                    @click="tenantImpersonateLogin(record)">
                                    <a href="javascript:;">
                                        <a-icon type="login" />
                                        <span>{{ l('LoginAsThisUser') }}</span>
                                    </a>
                                </a-menu-item>
                                <a-menu-item
                                    v-if="isGranted('Pages.Administration.Users.Edit')"
                                    @click="editUserPermissions(record)">
                                    <a href="javascript:;">
                                        <a-icon type="codepen" />
                                        <span>{{ l('Permissions') }}</span>
                                    </a>
                                </a-menu-item>
                                <a-menu-item v-if="enabledUnlock" @click="unlockTenantAdminUser(record)">
                                    <a href="javascript:;">
                                        <a-icon type="unlock" />
                                        <span>{{ l('Unlock') }}</span>
                                    </a>
                                </a-menu-item>
                            </a-menu>
                        </a-dropdown>
                    </span>
                </a-table>
                <a-pagination
                    class="pagination"
                    size="middle"
                    :total="totalItems"
                    showSizeChanger
                    showQuickJumper
                    :showTotal="showTotalFun"
                    @change="onChange"
                    @showSizeChange="showSizeChange" />
            </a-row>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import PermissionCombox from "../shared/permission-combox/permission-combox.vue";
import { ModalHelper } from "@/shared/helpers";
import { UserServiceProxy } from "@/shared/service-proxies";
import RoleCombox from "../shared/role-combox/role-combox";
import CreateOrEditUserCompent from "./create-or-edit-user/create-or-edit-user";
import EditUserPermissionsCompent from "./edit-user-permissions/edit-user-permissions";
import moment from "moment";
import { AppConsts } from "@/abpPro/AppConsts";
import { appSessionService } from "@/shared/abp";
import { fileDownloadService } from "@/shared/utils";
import { impersonationService } from "@/shared/auth/index";

export default {
    mixins: [AppComponentBase],
    name: "tenants",
    components: {
        PermissionCombox,
        CreateOrEditUserCompent,
        RoleCombox,
        EditUserPermissionsCompent
    },
    data() {
        return {
            // 是否显示高级过滤
            advancedFiltersVisible: false,
            _userServiceProxy: null,
            // 选中的权限过滤
            selectedPermission: [],
            // 表格
            columns: [
                {
                    title: this.l("UserName"),
                    dataIndex: "userName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "userName" }
                },
                {
                    title: this.l("Roles"),
                    dataIndex: "roles",
                    align: "center",
                    scopedSlots: { customRender: "roles" }
                },
                {
                    title: this.l("EmailAddress"),
                    dataIndex: "emailAddress",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "emailAddress" }
                },
                // 邮箱验证
                {
                    title: this.l("EmailConfirm"),
                    dataIndex: "isEmailConfirmed",
                    sorter: true,
                    align: "center",
                    filters: [
                        { text: this.l("All"), value: "" },
                        { text: this.l("Yes"), value: "true" },
                        { text: this.l("No"), value: "false" }
                    ],
                    filterMultiple: false,
                    onFilter: (value, record) =>
                        String(record.isEmailConfirmed).indexOf(value) === 0,
                    scopedSlots: { customRender: "isEmailConfirmed" }
                },
                // 是否激活
                {
                    title: this.l("Active"),
                    dataIndex: "isActive",
                    sorter: true,
                    align: "center",
                    filters: [
                        { text: this.l("All"), value: "" },
                        { text: this.l("Yes"), value: "true" },
                        { text: this.l("No"), value: "false" }
                    ],
                    filterMultiple: false,
                    onFilter: (value, record) =>
                        String(record.isActive).indexOf(value) === 0,
                    scopedSlots: { customRender: "isActive" }
                },
                {
                    title: this.l("LastLoginTime"),
                    dataIndex: "lastLoginTime",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "lastLoginTime" }
                },
                {
                    title: this.l("CreationTime"),
                    dataIndex: "creationTimeStr",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "creationTimeStr" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "actions",
                    align: "center",
                    scopedSlots: { customRender: "actions" }
                }
            ],
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { sorting: "", maxResultCount: 10, skipCount: 0 },
            // 选择多少项
            selectedRowKeys: [],
            selectedRows: [],
            // 请求参数
            filterText: undefined,
            tableData: [],
            // loading
            spinning: false,
            // 选中的角色Ids过滤
            role: [],
            /**
             * 是否已验证邮箱过滤
             */
            isEmailConfirmed: undefined,
            /**
             * 是否激活过滤
             */
            isActive: undefined,
            _appSessionService: "",
            _fileDownloadService: "",
            // 上传excel
            fileList: [],
            importFromExcelUrl:
                AppConsts.remoteServiceBaseUrl + "/UserImport/ImportFromExcel",
            uploadHeaders: {}
        };
    },
    created() {
        this._userServiceProxy = new UserServiceProxy(this.$apiUrl, this.$api);
        this._fileDownloadService = fileDownloadService;
        this.getData();
        this._appSessionService = appSessionService;
        console.log(this._appSessionService);
        Object.assign(this.uploadHeaders, {
            Authorization: "Bearer " + abp.auth.getToken()
        });
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._userServiceProxy
                .getPaged(
                    this.selectedPermission,
                    this.role,
                    this.isEmailConfirmed,
                    this.isActive,
                    undefined,
                    this.filterText,
                    this.request.sorting,
                    this.request.maxResultCount,
                    this.request.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.tableData = res.items;
                    this.tableData.map(item => {
                        item.creationTimeStr = item.creationTime
                            ? moment(item.creationTime).format(
                                  "YYYY-MM-DD HH:mm:ss"
                              )
                            : "-";
                    });
                    this.totalItems = res.totalCount;
                    this.totalPages = Math.ceil(
                        res.totalCount / this.request.maxResultCount
                    );
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                });
        },
        /**
         * table默认配置 （是否禁用）
         */
        getCheckboxProps: record => ({
            props: {
                disabled: record.id === appSessionService.userId
            }
        }),
        /**
         * 添加用户  修改用户
         */
        createOrEdit(id) {
            ModalHelper.create(
                CreateOrEditUserCompent,
                { id: id },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 批量删除
         */
        batchDelete(e) {
            const selectCount = this.selectedRowKeys.length;
            if (selectCount <= 0) {
                abp.message.warn(this.l("PleaseSelectAtLeastOneItem"));
                return;
            }
            this.message.confirm(
                this.l("ConfirmDeleteXItemsWarningMessage", selectCount),
                res => {
                    if (res) {
                        const ids = _.map(this.selectedRowKeys);
                        this.spinning = true;
                        this._userServiceProxy
                            .batchDelete(ids)
                            .finally(() => {
                                this.spinning = false;
                            })
                            .then(() => {
                                this.selectedRowKeys = [];
                                this.refreshGoFirstPage(
                                    this.selectedPermission
                                );
                                this.$notification["success"]({
                                    message: this.l("SuccessfullyDeleted")
                                });
                            });
                    }
                }
            );
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * 单个删除
         */
        deleteItem(item) {
            if (item.isStatic) {
                abp.message.warn(
                    this.l(
                        "XUserCannotBeDeleted",
                        AppConsts.userManagement.defaultAdminUserName
                    )
                );
                return;
            }
            this.spinning = true;
            this._userServiceProxy
                .delete(item.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(() => {
                    this.refreshGoFirstPage(this.selectedPermission);
                    this.$notification["success"]({
                        message: this.l("SuccessfullyDeleted")
                    });
                });
        },
        /**
         * 清空选择
         */
        restCheckStatus() {
            this.selectedRowKeys = [];
        },
        /**
         * table选择事件
         */
        onSelectChange(selectedRowKeys, selectedRows) {
            this.selectedRowKeys = selectedRowKeys;
            this.selectedRows = selectedRows;
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        },
        /**
         * 选择完权限过滤
         */
        refreshGoFirstPage(data) {
            this.selectedPermission = data;
            this.request = { maxResultCount: 10, skipCount: 0 };
            this.getData();
        },
        /**
         * 角色过滤选择
         */
        selectedRoleChange(data) {
            this.role = data;
            this.getData();
        },
        /**
         * 是否是管理员
         */
        isAdmin(item) {
            return (
                item.userName === AppConsts.userManagement.defaultAdminUserName
            );
        },
        /**
         * 是否显示解锁按钮
         */
        enabledUnlock() {
            return (
                this.isGranted("Pages.Administration.Users.Edit") &&
                this.setting.getBoolean(
                    "Abp.Zero.UserManagement.UserLockOut.IsEnabled"
                )
            );
        },
        /**
         * 导出为excel
         */
        exportToExcel() {
            this._userServiceProxy.getUsersToExcel().then(result => {
                this._fileDownloadService.downloadTempFile(result);
            });
        },
        /**
         * 下载excel模版
         */
        ImportUsersSampleFile() {
            this._fileDownloadService.downloadTemplateFile(
                "ImportUsersSampleFile.xlsx"
            );
        },
        /**
         *
         */
        uploadChange(info) {
            let fileList = [...info.fileList];
            fileList = fileList.slice(-2);
            fileList = fileList.map(file => {
                if (file.response) {
                    file.url = file.response.url;
                }
                return file;
            });
            this.fileList = fileList;
            if (info.file.status === "done") {
                this.refreshGoFirstPage();
            }
        },
        /**
         * 使用此账户登录
         */
        tenantImpersonateLogin(item) {
            impersonationService.impersonate(
                item.id,
                this._appSessionService.tenantId
            );
        },
        /**
         * 权限
         */
        editUserPermissions(item) {
            ModalHelper.create(
                EditUserPermissionsCompent,
                { id: item.id, userName: item.userName },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                console.log(res);
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 解锁
         */
        unlockTenantAdminUser(item) {
            this.spinning = true;
            this._userServiceProxy
                .unlock({
                    id: item.id
                })
                .finally(() => {
                    this.spinning = false;
                })
                .then(() => {
                    this.getData();
                    this.notify.success(this.l("SuccessfullyUnlock"));
                });
        }
    }
};
</script>

<style scoped lang="less">
@import "./users.less";
</style>
