// src/yoyocmstemplate-vue/src/app/admin/shared/role-combox/role-combox.vue
<template>
    <a-select
        mode="multiple"
        :dropdownStyle="dropDownStyle"
        :placeholder="l('FilterByRole')"
        :defaultValue="selectedRoleVal"
        @change="selectedChange($event)"
        allowClear
        style="width: 100%;">
        <a-select-option :key="index" :value="role.id" v-for="(role,key,index) of roles">
            {{role.displayName}}
        </a-select-option>

    </a-select>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { RoleServiceProxy } from "@/shared/service-proxies";

export default {
    name: "role-combox",
    mixins: [AppComponentBase],
    props: ["dropDownStyle", "selectMode", "selectedRole"],
    data() {
        return {
            roleService: null,
            roles: [],
            selectedRoleVal: this.selectedRole
        };
    },
    created() {
        this.roleService = new RoleServiceProxy(this.$apiUrl, this.$api);
    },
    mounted() {
        this.roleService.getAll(undefined).then(result => {
            this.roles = result.items;
        });
    },
    methods: {
        selectedChange(selectKey) {
            this.$emit("selectedRoleChange", selectKey);
        }
    },
    watch: {}
};
</script>

<style scoped>
</style>

// src/yoyocmstemplate-angular/src/app/admin/shared/role-combox/role-combox.component.ts
import {
  Component,
  OnInit,
  Injector,
  Input,
  Output,
  EventEmitter,
} from '@angular/core';
import {
  RoleServiceProxy,
  RoleListDto,
} from '@shared/service-proxies/service-proxies';
import { AppComponentBase } from '@shared/component-base/app-component-base';

@Component({
  selector: 'app-role-combox',
  templateUrl: './role-combox.component.html',
})
export class RoleComboxComponent extends AppComponentBase implements OnInit {
  /**
   * 角色数据
   */
  roles: RoleListDto[] = [];
  /**
   * 下拉框样式
   */
  @Input()
  dropDownStyle: any = null;

  /**
   * 选择模式，默认`multiple`
   */
  @Input()
  selectMode: 'multiple' | 'tags' | 'default' = 'multiple';
  /**
   * 已选项Value
   */
  @Input()
  selectedRole: any = undefined;
  /**
   * 选中回发父页面事件
   */
  @Output()
  selectedRoleChange: EventEmitter<any> = new EventEmitter<any>();

  constructor(private _roleService: RoleServiceProxy, injector: Injector) {
    super(injector);
  }

  ngOnInit(): void {
    this._roleService.getAll(undefined).subscribe(result => {
      this.roles = result.items;
    });
  }

  /**
   * 选择事件
   * @param selectKey 选择Value
   */
  selectedChange(selectKey: any) {
    this.selectedRoleChange.emit(selectKey);
  }
}

<nz-select  style="width: 100%;"  nzAllowClear [nzMode]="selectMode" [nzPlaceHolder]="l('FilterByRole')" [nzDropdownStyle]="dropDownStyle" [(ngModel)]="selectedRole"
  (ngModelChange)="selectedChange($event)">
  <nz-option *ngFor="let role of roles" [nzLabel]="role.displayName" [nzValue]="role.id"></nz-option>
</nz-select>
