// src/yoyocmstemplate-vue/src/account/tenant-change/tenant-change.vue
<template>
    <div v-if="isMultiTenancyEnabled" class="card tenant-change-component">
        <div class="body text-center">
            <span>
                {{l("CurrentTenant")}}:
                <span v-if="tenancyName" :title="name">
                    <strong>{{tenancyName}}</strong>
                </span>
                <span v-if="!tenancyName">{{l("NotSelected")}}</span>
                (
                    <a href="javascript:;" @click="showChangeModal()">{{l("Change")}}</a>)
            </span>
        </div>
    </div>
</template>

<script>
    import {AppComponentBase} from "@/shared/component-base";
    import {appSessionService, abpService} from "@/shared/abp";
    import TenantChangeModal from "./tenant-change-modal";
    import {ModalHelper} from '@/shared/helpers';

    export default {
        name: "tenant-change",
        mixins: [AppComponentBase],
        components: {},
        data() {
            return {
                show: false
            };
        },
        computed: {
            tenancyName: vm => {
                if (!appSessionService.tenant) {
                    return undefined;
                }
                return appSessionService.tenant.tenancyName;
            },
            name: vm => {
                return appSessionService.tenant.name;
            },
            isMultiTenancyEnabled: vm => {
                return abpService.abp.multiTenancy.isEnabled;
            }
        },
        methods: {
            showChangeModal() {
                ModalHelper.create(TenantChangeModal, {
                    tenancyName: this.tenancyName
                }).subscribe((res) => {

                });
            }
        }
    };
</script>

<style lang="less" scoped>
    @import "./tenant-change.less";
</style>

// src/yoyocmstemplate-angular/src/account/tenant/tenant-change.component.ts
import { Component, OnInit, Injector, ViewChild } from '@angular/core';
import { AccountServiceProxy } from '@shared/service-proxies/service-proxies';
import { AppComponentBase } from '@shared/component-base/app-component-base';
import { TenantChangeModalComponent } from './tenant-change-modal.component';

@Component({
  selector: 'tenant-change',
  templateUrl: './tenant-change.component.html',
})
export class TenantChangeComponent extends AppComponentBase implements OnInit {
  tenancyName: string;
  name: string;

  constructor(injector: Injector) {
    super(injector);
  }

  ngOnInit() {
    if (this.appSession.tenant) {
      this.tenancyName = this.appSession.tenant.tenancyName;
      this.name = this.appSession.tenant.name;
    }
  }

  get isMultiTenancyEnabled(): boolean {
    return abp.multiTenancy.isEnabled;
  }

  showChangeModal(): void {
    this.modalHelper
      .open(
        TenantChangeModalComponent,
        { tenancyName: this.tenancyName },
        'md',
        {
          nzMask: true,
        },
      )
      .subscribe(() => { });
  }
}

<div *ngIf="isMultiTenancyEnabled" class="card tenant-change-component">
  <div class=" body text-center">
    <span>
      {{l("CurrentTenant")}}:
      <span *ngIf="tenancyName" title="{{name}}">
        <strong>{{tenancyName}}</strong>
      </span>
      <span *ngIf="!tenancyName">{{l("NotSelected")}}</span>
      (
      <a href="javascript:void();" (click)="showChangeModal()">{{l("Change")}}</a>)
    </span>
  </div>
</div>
