// src/yoyocmstemplate-vue/src/account/tenant-change/tenant-change-modal.vue
<template>
    <div>
        <div class="modal-header">
            <div class="ant-modal-title">
                {{l('ChangeTenant')}}
            </div>
        </div>

        <div>
            <a-form :form="form" @submit="save()">
                <a-form-item :label="l('TenancyName')" :label-col="{ span: 5 }" :wrapper-col="{ span: 19 }">
                    <a-input v-decorator="['tenancyName']"/>
                    <span class="text-sm text-grey">{{l("LeaveEmptyToSwitchToHost")}}</span>
                </a-form-item>
            </a-form>
        </div>

        <div class="modal-footer">
            <a-button @click="close()">
                <i class="anticon anticon-close-circle-o"></i>
                {{l("Cancel")}}
            </a-button>
            <a-button @click="save()" type="primary">
                <i class="anticon anticon-save"></i>
                {{l("Save")}}
            </a-button>
        </div>

    </div>
</template>

<script>
    import {ModalComponentBase} from "@/shared/component-base";
    import {AccountServiceProxy, IsTenantAvailableInput} from "@/shared/service-proxies";
    import {AppTenantAvailabilityState} from "@/abpPro/AppEnums";
    import {abpService} from "@/shared/abp";
    import {Modal} from "ant-design-vue";

    export default {
        name: "tenant-change-modal",
        mixins: [ModalComponentBase],
        data() {
            return {
                isSaving: false,
                form: this.$form.createForm(this, {name: "coordinated"}),
                accountService: undefined,
                tenancyName: undefined
            };
        },
        computed: {
            saving: {
                set(val) {
                    this.isSaving = val;
                },
                get() {
                    return this.isSaving;
                }
            }
        },
        created() {
            this.fullData(); // 模态框必须,填充数据到data字段
            this.accountService = new AccountServiceProxy(this.$apiUrl, this.$api);
        },
        mounted() {
        },
        watch: {
            tenancyName(val) {
                if (val) {
                    this.form.setFieldsValue({tenancyName: val});
                }
            }
        },
        methods: {
            save() {
                this.saving = true;

                let newTenancyName = this.form.getFieldValue("tenancyName");

                if (newTenancyName === this.tenancyName) {
                    this.close();
                    return;
                }
                if (!newTenancyName || newTenancyName === "") {
                    abpService.abp.multiTenancy.setTenantIdCookie(undefined);
                    this.close();
                    location.reload();
                    return;
                }
                const input = new IsTenantAvailableInput();
                input.tenancyName = newTenancyName;
                this.accountService
                    .isTenantAvailable(input)
                    .finally(() => {
                        this.saving = false;
                    })
                    .then(
                        result => {
                            switch (result.state) {
                                case AppTenantAvailabilityState.Available:
                                    abpService.abp.multiTenancy.setTenantIdCookie(result.tenantId);
                                    this.success();
                                    window.location.reload();
                                    return;
                                case AppTenantAvailabilityState.InActive:
                                    Modal.warning({
                                        message: this.l("TenantIsNotActive", input.tenancyName)
                                    });
                                    // this.message.warn(
                                    //   this.l("TenantIsNotActive", this.tenancyName)
                                    // );
                                    break;
                                case AppTenantAvailabilityState.NotFound: // NotFound
                                    Modal.warning({
                                        content: this.l(
                                            "ThereIsNoTenantDefinedWithName{0}",
                                            input.tenancyName
                                        )
                                    });
                                    // this.message.warn(
                                    //   this.l("ThereIsNoTenantDefinedWithName{0}", this.tenancyName)
                                    // );
                                    break;
                            }
                        },
                        error => {
                            console.error(error);
                        }
                    );
            }
        }
    };
</script>

<style lang="less" scoped>
</style>

// src/yoyocmstemplate-angular/src/account/tenant/tenant-change-modal.component.ts
import { Component, OnInit, Injector, Input } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { AccountServiceProxy } from '@shared/service-proxies/service-proxies';
import { IsTenantAvailableInput } from '@shared/service-proxies/service-proxies';
import { AppTenantAvailabilityState } from 'abpPro/AppEnums';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import { AppComponentBase } from '@shared/component-base/app-component-base';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-tenant-change-modal',
  templateUrl: './tenant-change-modal.component.html',
})
export class TenantChangeModalComponent extends ModalComponentBase implements OnInit {
  @Input()
  tenancyName = '';
  beforeTenancyName = '';
  saving = false;

  constructor(injector: Injector, private _accountService: AccountServiceProxy) {
    super(injector);
  }

  ngOnInit(): void {
    this.beforeTenancyName = this.tenancyName;
  }

  save(): void {
    this.saving = true;
    if (this.tenancyName === this.beforeTenancyName) {
      this.close();
      return;
    }
    if (!this.tenancyName || this.tenancyName === '') {
      abp.multiTenancy.setTenantIdCookie(undefined);
      this.close();
      location.reload();
      return;
    }

    const input = new IsTenantAvailableInput();
    input.tenancyName = this.tenancyName;

    this._accountService
      .isTenantAvailable(input)
      .pipe(finalize(() => (this.saving = false)))
      .subscribe(
        result => {
          switch (result.state as any) {
            case AppTenantAvailabilityState.Available:
            case 'Available':
              abp.multiTenancy.setTenantIdCookie(result.tenantId);
              this.success();
              location.reload();
              return;
            case AppTenantAvailabilityState.InActive:
            case 'InActive':
              this.message.warn(this.l('TenantIsNotActive', this.tenancyName));
              break;
            case AppTenantAvailabilityState.NotFound: // NotFound
            case 'NotFound':
              this.message.warn(this.l('ThereIsNoTenantDefinedWithName{0}', this.tenancyName));
              break;
          }
        },
        error => {
          console.error(error);
        },
      );
  }
}

<form nz-form #changeTenantForm="ngForm" (ngSubmit)="save()">
  <div class="modal-header">
    <div class="modal-title">
      <!-- <i class="iconfont icon-home"></i> -->
      <i class="iconfont icon-home"></i>
      {{ l('ChangeTenant') }}
    </div>
  </div>

  <fieldset>
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="4" nzFor="TenancyName">
        {{ l('TenancyName') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="20">
        <nz-input-group [nzPrefix]="nzPrefixIconHome">
          <input nz-input name="TenancyName" [(ngModel)]="tenancyName" type="text" [placeholder]="l('TenancyName')" />
        </nz-input-group>
        <span class="text-sm text-grey">{{ l('LeaveEmptyToSwitchToHost') }}</span>

        <ng-template #nzPrefixIconHome
          ><span class="iconfont icon-home" style="color: rgba(0, 0, 0, 0.25);"></span>
        </ng-template>
      </nz-form-control>
    </nz-form-item>
  </fieldset>

  <div class="modal-footer">
    <button nz-button [nzType]="'default'" type="button" (click)="close()" [disabled]="saving">
      <!-- <i class="iconfont icon-close-circle-o"></i> -->
      <i class="iconfont icon-close-circle "></i>
      {{ l('Cancel') }}
    </button>
    <button
      nz-button
      [nzType]="'primary'"
      type="submit"
      [disabled]="!changeTenantForm.form.valid"
      [disabled]="saving"
      [nzLoading]="saving"
    >
      <!-- <i class="iconfont icon-save"></i> -->
      <i class="iconfont icon-save"></i>
      {{ l('Save') }}
    </button>
  </div>
</form>
