// src/yoyocmstemplate-angular/src/app/admin/language-texts/edit-language-text/edit-language-text.component.ts
import { Component, OnInit, Injector, Input } from '@angular/core';
import { UpdateLanguageTextInput, LanguageServiceProxy } from '@shared/service-proxies/service-proxies';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-edit-language-text',
  templateUrl: './edit-language-text.component.html',
  styles: [],
})
export class EditLanguageTextComponent extends ModalComponentBase implements OnInit {
  @Input()
  data: UpdateLanguageTextInput;
  @Input()
  baseText: string;
  @Input()
  baseLanguage: abp.localization.ILanguageInfo;
  @Input()
  targetLanguage: abp.localization.ILanguageInfo;
  baseLanguageName: string;
  targetLanguageName: string;

  saving = false;

  constructor(injector: Injector, private languageService: LanguageServiceProxy) {
    super(injector);
  }

  ngOnInit(): void {
    const self = this;
    self.baseLanguage = self.findLanguage(self.baseLanguageName);
    self.targetLanguage = self.findLanguage(self.targetLanguageName);
  }

  save(): void {
    if (this.data.value && this.data.value !== '') {
      this.saving = true;
      this.languageService
        .updateLanguageText(this.data)
        .pipe(finalize(() => (this.saving = false)))
        .subscribe(() => {
          this.notify.success(this.l('SavedSuccessfully'));
          this.success();
        });
    } else {
      this.message.warn('值不能为空');
    }
  }

  private findLanguage(name: string): abp.localization.ILanguageInfo {
    return abp.localization.languages.find((item, index, array) => item.name === name);
  }
}

<div class="modal-header">
  <div class="modal-title">
    <i class="iconfont icon-form mr-sm"></i>
    <span>{{ l('EditText') }}</span>
  </div>
</div>
<div>
  <div>
    <p>{{ l('Key') }}</p>
    <p>
      <strong>{{ data.key }}</strong>
    </p>
  </div>
  <br />
  <div>
    <p>
      <!-- <i class="anticon {{baseLanguage.icon}}"></i> -->
      <i class="iconfont {{ baseLanguage.icon }}"></i>
      &nbsp;&nbsp;{{ baseLanguage.displayName }}
    </p>
    <div>
      <input nz-input [(ngModel)]="baseText" [disabled]="true" />
    </div>
  </div>
  <br />
  <div>
    <p>
      <!-- <i class="anticon {{targetLanguage.icon}}"></i> -->
      <i class="iconfont {{ targetLanguage.icon }}"></i>
      &nbsp;&nbsp;{{ targetLanguage.displayName }}
    </p>
    <div>
      <textarea nz-input [(ngModel)]="data.value" [nzAutosize]="{ minRows: 3 }"></textarea>
    </div>
  </div>
</div>

<!-- 功能按钮 -->

<div class="modal-footer">
  <button nz-button type="button" [disabled]="saving" (click)="close()">
    {{ l('Cancel') }}
  </button>
  <button nz-button [nzType]="'primary'" type="button" (click)="save()">
    <!-- <button nz-button [nzType]="'primary'" type="button"  (click)="save()" [disabled]="!validateForm.valid"> -->
    {{ l('Save') }}
  </button>
</div>

// src/yoyocmstemplate-vue/src/app/admin/language-texts/edit-language-text/edit-language-text.vue
<template>
    <a-spin :spinning="spinning">
        <div class="modal-header">
            <div class="modal-title">{{l('EditText')}}</div>
        </div>
        <a-form :form="form" @submit="save()" autocomplete="off">
            <!-- 键值 -->
            <a-form-item
                :label="l('Key')">
                <p>{{editItem.key }}</p>
            </a-form-item>
            <!-- 简体中文 -->
            <a-form-item
                :label="editItem.baseLanguageNameText">
                <p>{{ editItem.baseValue }}</p>
            </a-form-item>
            <!-- 启用 -->
            <a-form-item
                :label="editItem.targetLanguageNameText">
                <a-textarea
                    v-decorator="['value', {}]"
                    :placeholder="editItem.targetLanguageNameText"
                    :auto-size="{ minRows: 3, maxRows: 5 }" />
            </a-form-item>
        </a-form>

        <div class="modal-footer">
            <a-button :disabled="saving" @click="close()" type="button">
                {{l("Cancel")}}
            </a-button>
            <a-button :loading="saving" :type="'primary'" @click="save()">
                <i class="acticon acticon-save"></i>
                <span>{{l("Save")}}</span>
            </a-button>
        </div>
    </a-spin>
</template>
<script>
import { ModalComponentBase } from "@/shared/component-base";
import { LanguageServiceProxy } from "@/shared/service-proxies";

export default {
    name: "edit-language-text",
    mixins: [ModalComponentBase],
    components: {},
    data() {
        return {
            form: this.$form.createForm(this),
            languageServiceProxy: "",
            spinning: false
        };
    },
    created() {
        this.fullData(); // 模态框必须,填充数据到data字段
        this._languageServiceProxy = new LanguageServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.$nextTick(() => {
            this.form.setFieldsValue({
                value: this.editItem.targetValue
            });
        });
        console.log(this.editItem);
    },
    methods: {
        /**
         * 提交
         */
        save() {
            this.form.validateFields((err, values) => {
                if (!err) {
                    console.log(this.editItem);
                    let parmas = {
                        key: this.editItem.key,
                        languageName: this.editItem.targetLanguageName,
                        sourceName: this.editItem.sourceName,
                        value: values.value
                    };
                    this.spinning = true;
                    this._languageServiceProxy
                        .updateLanguageText(parmas)
                        .finally(() => {
                            this.spinning = false;
                        })
                        .then(res => {
                            this.notify.success(this.l("SavedSuccessfully"));
                            this.success(true);
                            console.log(res);
                        });
                }
            });
        }
    }
};
</script>
