// src/yoyocmstemplate-vue/src/app/demo/demoui.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('DemoManagement')"></page-header>
        <a-card :bordered="false" :title="l('AddressSelection')">
            <x-address-linkage :placeHolder="l('MouseMovementLoading')" :mouseclickplaceHolder="l('MouseClickLoading')"></x-address-linkage>
        </a-card>
        <a-card :bordered="false" :title="l('DateAndTime')">
            <a-date-picker placeholder="请选择日期" />
            <br>
            <br>
            <a-month-picker placeholder="请选择日期" />
            <br>
            <br>
            <a-date-picker mode="year" placeholder="请选择日期" />
            <br>
            <br>
            <a-range-picker :placeholder="['开始日期','结束日期']" />
            <br>
            <br>
            <a-week-picker placeholder="请选择日期" />
        </a-card>
        <a-card :bordered="false" :title="l('DateAndTime')">
            <a-date-picker mode="year" placeholder="请选择日期" />
            <br>
            <br>
            <a-week-picker placeholder="请选择日期" />
            <br>
            <br>
            <a-range-picker :placeholder="['开始日期','结束日期']" />
            <br>
            <br>
            <a-month-picker placeholder="请选择日期" />
            <br>
            <br>
            <a-date-picker placeholder="请选择日期" />
            <br>
            <br>
            <a-time-picker :default-open-value="moment('00:00:00', 'HH:mm:ss')" placeholder="请选择时间" />
        </a-card>
        <a-card :bordered="false" title="支付Demo">
            <a-button type="primary" @click="onClickPay">
                赏口饭
            </a-button>
        </a-card>
        <a-card :bordered="false" :title="l('DemoMarkDown')">
            <mavon-editor
                v-model="content"
                ref="md"
                @change="Markdownchange"
                style="min-height: 300px" />
            <br>
            <a-button type="primary">{{ l('Save') }}</a-button>
            <a-button @click="resetMarkdown($event)">
                {{ l('Reset') }}
            </a-button>
        </a-card>
        <a-card :bordered="false" :title="l('ExportToExcel')">
            <a-button @click="exportToExcel">
                <a-icon type="file-excel" />{{ l('ExportToExcel') }}</a-button>
            <br><br>
            <a-table :columns="columns" :data-source="tabledata">
                <span slot="rolesStr" slot-scope="text, record">
                    <a-tag v-for="item in record.roles" :key="item.roleId">{{ item.roleName }}</a-tag>
                </span>
            </a-table>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import XAddressLinkage from "./x-address-linkage/x-address-linkage";
import {
    PurchaseServiceProxy,
    UserServiceProxy
} from "@/shared/service-proxies";
import { fileDownloadService } from "@/shared/utils";
// 导入组件 及 组件样式
import { mavonEditor } from "mavon-editor";
import "mavon-editor/dist/css/index.css";
import moment from "moment";

export default {
    name: "demoui",
    mixins: [AppComponentBase],
    components: {
        XAddressLinkage,
        mavonEditor
    },
    data() {
        return {
            spinning: false,
            _purchaseServiceProxy: "",
            _userServiceProxy: "",
            _fileDownloadService: "",
            content: "", // 输入的markdown
            html: "", // 及时转的html
            skipCount: 0,
            tabledata: [],
            columns: [
                {
                    title: this.l("UserName"),
                    dataIndex: "userName",
                    key: "userName"
                },
                {
                    title: this.l("Roles"),
                    dataIndex: "rolesStr",
                    key: "rolesStr",
                    align: "center",
                    scopedSlots: { customRender: "rolesStr" }
                },
                {
                    title: this.l("CreationTime"),
                    dataIndex: "creationTimeStr",
                    key: "creationTimeStr"
                }
            ]
        };
    },
    created() {
        this._purchaseServiceProxy = new PurchaseServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this._userServiceProxy = new UserServiceProxy(this.$apiUrl, this.$api);
        this._fileDownloadService = fileDownloadService;
        this.getUser();
    },
    methods: {
        getUser() {
            this.spinning = true;
            this._userServiceProxy
                .getPaged(
                    [],
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    "",
                    "",
                    20,
                    this.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(result => {
                    this.tabledata = result.items;
                    this.tabledata.map(item => {
                        item.creationTimeStr = item.creationTime
                            ? moment(item.creationTime).format(
                                  "YYYY-MM-DD HH:mm:ss"
                              )
                            : "-";
                    });
                    console.log(result);
                });
        },
        moment,
        /**
         * 赏扣饭
         */
        onClickPay() {
            this.spinning = true;
            this._purchaseServiceProxy
                .createPay({
                    orderCode: "123456789AAAA"
                })
                .finally(() => {
                    this.spinning = false;
                })
                .then(result => {
                    window.open(result);
                });
        },
        /**
         * markdown
         * 所有操作都会被解析重新渲染
         */
        Markdownchange(value, render) {
            this.html = render;
        },
        resetMarkdown() {
            this.content = "";
            this.html = "";
        },
        /**
         * 导出
         */
        exportToExcel() {
            this.spinning = true;
            this._userServiceProxy
                .getUsersToExcel()
                .finally(() => {
                    this.spinning = false;
                })
                .then(result => {
                    this._fileDownloadService.downloadTempFile(result);
                });
        }
    }
};
</script>

<style scoped>
</style>

// src/yoyocmstemplate-angular/src/app/demo-management/demo-ui/demoui.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { AppComponentBase } from '@shared/component-base/app-component-base';
import {
    UserServiceProxy,
    PagedResultDtoOfUserListDto,
    PurchaseServiceProxy,
    PurchasePayInput,
} from '@shared/service-proxies/service-proxies';
import { FileDownloadService } from '@shared/utils';

@Component({
    selector: 'app-demoui',
    templateUrl: './demoui.component.html',
    styleUrls: ['./demoui.component.less'],
})
export class DemoUiComponent extends AppComponentBase implements OnInit {
    time: Date | null = null;
    defaultOpenValue = new Date(0, 0, 0, 0, 0, 0);
    validateForm: FormGroup;
    html = ``;
    isVisible = false;
    listOfData = [];
    constructor(
        injector: Injector,
        private fb: FormBuilder,
        private _userService: UserServiceProxy,
        private _purchaseServiceProxy: PurchaseServiceProxy,
        private _fileDownloadService: FileDownloadService,
    ) {
        super(injector);
    }

    ngOnInit() {
        this.validateForm = this.fb.group({
            content: ['1111111111111111', [Validators.required]],
        });
        this._userService
            .getPaged([], undefined, undefined, undefined, undefined, '', '', 20, 0)
            .subscribe((result: PagedResultDtoOfUserListDto) => {
                this.listOfData = result.items;
            });
    }

    /**
     * 演示-markdown 提交表单
     * @param value 表单值
     */
    submitForm(value: any) {
        for (const key in this.validateForm.controls) {
            this.validateForm.controls[key].markAsDirty();
            this.validateForm.controls[key].updateValueAndValidity();
        }
        console.log(value);
    }
    /**
     * 演示-markdown 重置表单
     * @param e
     */
    resetForm(e: MouseEvent): void {
        e.preventDefault();
        // 因为simplemde组件 如果用 FormGroup reset 会赋值null 出现 字符串分割异常
        this.validateForm.setValue({ content: '' });
        // this.validateForm.reset();
        // for (const key in this.validateForm.controls) {
        //   this.validateForm.controls[key].markAsPristine();
        //   this.validateForm.controls[key].updateValueAndValidity();
        // }
    }

    showQuillEditor() {
        this.isVisible = true;
    }
    handleOk(): void {
        this.isVisible = false;
    }

    handleCancel(): void {
        this.isVisible = false;
    }

    /**
     * 演示-导出excel
     */
    exportToExcel(): void {
        this._userService.getUsersToExcel().subscribe(result => {
            console.log(result);
            this._fileDownloadService.downloadTempFile(result);
        });
        // 调用后端的到处方法
    }

    /**
     * 支付演示- 赏口饭
     * 如果需要请到 APi appsettings中进行支付配置
     */
    onClickPay() {
        const input = new PurchasePayInput();
        input.orderCode = '123456789AAAA';
        this._purchaseServiceProxy.createPay(input).subscribe(result => {
            window.open(result);
        });
    }
}

<page-header [title]="l('DemoManagement')"></page-header>

<!-- 演示功能  地址选择 -->
<nz-card [nzTitle]="l('AddressSelection')">
  <div>
    <x-address-linkage [placeHolder]="l('MouseMovementLoading')"></x-address-linkage>
  </div>

  <div>
    <x-address-linkage [placeHolder]="l('MouseClickLoading')" [isClickOnLoad]="true"></x-address-linkage>
  </div>
</nz-card>

<!-- 演示功能  日期时间 -->
<nz-card [nzTitle]="l('DateAndTime')">
  <nz-date-picker></nz-date-picker>
  <br />
  <nz-month-picker></nz-month-picker>
  <br />
  <nz-year-picker></nz-year-picker>
  <br />
  <nz-range-picker nzShowTime></nz-range-picker>
  <br />
  <nz-week-picker></nz-week-picker>
  <br />
</nz-card>

<!-- 演示功能  日期时间  这里的使用方式完全继承自ng-zorro 所以用相同的方式去用就好-->
<nz-card [nzTitle]="l('DateAndTime')">
  <app-year-picker></app-year-picker>
  <app-week-picker></app-week-picker>
  <app-range-picker></app-range-picker>
  <app-month-picker></app-month-picker>
  <app-date-picker></app-date-picker>

  <app-time-picker [(ngModel)]="time" [nzDefaultOpenValue]="defaultOpenValue"> </app-time-picker>
</nz-card>

<!-- 演示功能 支付Demo -->
<nz-card nzTitle="支付Demo">
  <button nz-button nzType="primary" (click)="onClickPay()">赏口饭</button>
</nz-card>

<!-- 演示功能  markdown编辑器 -->
<nz-card [nzTitle]="l('DemoMarkDown')">
  <form nz-form [formGroup]="validateForm" (ngSubmit)="submitForm(validateForm.value)">
    <nz-form-item>
      <nz-form-control [nzErrorTip]="l('FormIsNotValidMessage')">
        <nz-input-group>
          <simplemde formControlName="content"></simplemde>
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item>
      <nz-form-control>
        <button nz-button nzType="primary">{{ l('Save') }}</button>
        <button nz-button nzType="default" (click)="resetForm($event)">
          {{ l('Reset') }}
        </button>
      </nz-form-control>
    </nz-form-item>
  </form>
</nz-card>

<nz-card [nzTitle]="l('DemoMarkDown')">
  <div id="MakrdownEditor"></div>
</nz-card>

<!-- 演示功能  富文本编辑器 -->
<!-- <nz-card [nzTitle]="l('RichTextEditor')">
  <nz-form-item>
    <nz-form-control [nzErrorTip]="l('FormIsNotValidMessage')">
      <nz-input-group nzPrefixIcon="user">
        <div style="height: 26rem;">
          <quill-editor name="content" [(ngModel)]="html"></quill-editor>
        </div>
      </nz-input-group>
    </nz-form-control>
  </nz-form-item>
  <nz-form-item>
    <nz-form-control>
      <button nz-button (click)="showQuillEditor()" nzType="primary">
        {{ l('Preview') }}
      </button>
    </nz-form-control>
  </nz-form-item>
</nz-card> -->

<nz-modal [(nzVisible)]="isVisible" nzTitle="{{ l('预览') }}" (nzOnCancel)="handleCancel()" (nzOnOk)="handleOk()">
  <div [innerHTML]="html" style="height: 26rem;"></div>
</nz-modal>

<!-- 演示功能 导出 -->
<nz-card [nzTitle]="l('ExportToExcel')">
  <nz-row nzGutter="8">
    <nz-col nzMd="20" nzSm="12" class="btn-gutter">
      <button nz-button nzType="default" (click)="exportToExcel()">
        <!-- <i class="iconfont icon-file-excel"></i> -->
        <i class="iconfont icon-file-excel"></i>
        <span>
          {{ l('ExportToExcel') }}
        </span>
      </button>
    </nz-col>
  </nz-row>
  <!-- 表格内容 -->
  <nz-table #basicTable [nzData]="listOfData">
    <thead>
      <tr>
        <th>{{ l('UserName') }}</th>
        <th>{{ l('Roles') }}</th>
        <th>{{ l('CreationTime') }}</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let data of basicTable.data">
        <td>{{ data.userName }}</td>
        <td>
          <ellipsis lines="1" tooltip>
            <span>
              <nz-tag *ngFor="let role of data.roles">
                {{ role.roleName }}
              </nz-tag>
            </span>
          </ellipsis>
        </td>
        <td>{{ data.creationTime | _moment }}</td>
      </tr>
    </tbody>
  </nz-table>
</nz-card>
