// src/yoyocmstemplate-angular/src/app/admin/maintenance/maintenance.component.ts
import { HostCacheDto } from '@shared/service-proxies/service-proxies';
import { Component, OnInit, Injector, AfterViewInit } from '@angular/core';
import { AppComponentBase } from '@shared/component-base/app-component-base';
import {
  WebSiteLogServiceProxy,
  HostCachingServiceProxy,
  EntityDtoOfString,
} from '@shared/service-proxies/service-proxies';
import * as _ from 'lodash';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import { FileDownloadService } from '@shared/utils/file-download.service';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-maintenance',
  templateUrl: './maintenance.component.html',
  styleUrls: ['./maintenance.component.less'],
})
export class MaintenanceComponent extends PagedListingComponentBase<HostCacheDto> implements OnInit {
  logs: any = '';
  constructor(
    injector: Injector,
    private cacheService: HostCachingServiceProxy,
    private webSiteLogService: WebSiteLogServiceProxy,
    private fileDownloadService: FileDownloadService,
  ) {
    super(injector);
  }

  ngOnInit(): void {
    this.refresh();
    this.getWebLogs();
  }
  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    this.cacheService
      .getAllCaches()
      .pipe(finalize(() => finishedCallback()))
      .subscribe(result => {
        this.dataList = result.items;
      });
  }
  protected delete(entity: HostCacheDto): void {}

  clearCache(cacheName): void {
    const input = new EntityDtoOfString();
    input.id = cacheName;

    this.cacheService.clearCache(input).subscribe(() => {
      this.notify.success(this.l('CacheSuccessfullyCleared'));
    });
  }

  clearAllCaches(): void {
    this.cacheService.clearAllCaches().subscribe(() => {
      this.notify.success(this.l('AllCachesSuccessfullyCleared'));
    });
  }

  getWebLogs(): void {
    this.webSiteLogService.getLatestWebLogs().subscribe(result => {
      this.logs = result.latestWebLogLines;
    });
  }

  downloadWebLogs = function() {
    this.webSiteLogService.downloadWebLogs().subscribe(result => {
      this.fileDownloadService.downloadTempFile(result);
    });
  };

  getLogClass(log: string): string {
    if (log.startsWith('DEBUG')) {
      return 'label label-default';
    }

    if (log.startsWith('INFO')) {
      return 'label label-info';
    }

    if (log.startsWith('WARN')) {
      return 'label label-warning';
    }

    if (log.startsWith('ERROR')) {
      return 'label label-danger';
    }

    if (log.startsWith('FATAL')) {
      return 'label label-danger';
    }

    return '';
  }

  getLogType(log: string): string {
    if (log.startsWith('DEBUG')) {
      return 'DEBUG';
    }

    if (log.startsWith('INFO')) {
      return 'INFO';
    }

    if (log.startsWith('WARN')) {
      return 'WARN';
    }

    if (log.startsWith('ERROR')) {
      return 'ERROR';
    }

    if (log.startsWith('FATAL')) {
      return 'FATAL';
    }

    return '';
  }

  getRawLogContent(log: string): string {
    return _.escape(log)
      .replace('DEBUG', '')
      .replace('INFO', '')
      .replace('WARN', '')
      .replace('ERROR', '')
      .replace('FATAL', '');
  }
}

<page-header [title]="l('Maintenance')"></page-header>

<nz-card>
  <nz-tabset>
    <!-- 缓存 -->
    <nz-tab [nzTitle]="l('Caching')">
      <nz-card [nzBordered]="false" [nzExtra]="cachingExtra" [nzTitle]="l('CachesHeaderInfo')">
        <ng-template #cachingExtra>
          <button nz-button [nzType]="'primary'" (click)="clearAllCaches()">
            <i class="iconfont icon-delete "></i>
            <span>{{ l('ClearAll') }}</span>
          </button>
        </ng-template>

        <nz-table #ajaxTable [nzData]="dataList" [nzLoading]="isTableLoading" [nzShowPagination]="false">
          <thead nz-thead>
            <tr>
              <th nz-th></th>
              <th nz-th></th>
            </tr>
          </thead>
          <tbody nz-tbody>
            <tr nz-tbody-tr *ngFor="let item of ajaxTable.data">
              <td>
                {{ item.name }}
              </td>
              <td nz-td>
                <a (click)="clearCache(item.name)">
                  {{ l('Clear') }}
                </a>
              </td>
            </tr>
          </tbody>
        </nz-table>
      </nz-card>
    </nz-tab>

    <!-- 网站日志 -->
    <nz-tab [nzTitle]="l('WebSiteLog')">
      <nz-card [nzBordered]="false" [nzExtra]="webSiteLogExtra" [nzTitle]="l('WebSiteLogsHeaderInfo')">
        <ng-template #webSiteLogExtra>
          <button nz-button [nzType]="'primary'" (click)="downloadWebLogs()">
            <!-- <i class="iconfont icon-download"></i> -->
            <i class="iconfont icon-download "></i>
            <span>{{ l('DownloadAll') }}</span>
          </button>
          <button nz-button [nzType]="'primary'" (click)="getWebLogs()">
            <!-- <i class="iconfont icon-reload"></i> -->
            <i class="iconfont icon-reload "></i>
            <span>{{ l('Refresh') }}</span>
          </button>
        </ng-template>
        <div class="web-log-view full-height">
          <div class="log-line" *ngFor="let log of logs">
            <span [class]="getLogClass(log)">{{ getLogType(log) }}</span>
            {{ getRawLogContent(log) }}
          </div>
        </div>
      </nz-card>
    </nz-tab>
  </nz-tabset>
</nz-card>

// src/yoyocmstemplate-vue/src/app/admin/maintenance/maintenance.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('Maintenance')"></page-header>
        <a-card :bordered="false">
            <a-tabs default-active-key="1">
                <!-- 缓存 -->
                <a-tab-pane key="1" :tab="l('Caching')">
                    <a-card :title="l('CachesHeaderInfo')" :bordered="false">
                        <a-button slot="extra" type="primary" @click="clearAllCaches">
                            <a-icon type="delete" />
                            {{ l('ClearAll') }}
                        </a-button>
                        <a-table :columns="columns" :showHeader="false" :pagination="false" :data-source="cashtabledata">
                            <span slot="action" slot-scope="text, record">
                                <a @click="clearCache(record)">清空</a>
                            </span>
                        </a-table>
                    </a-card>
                </a-tab-pane>
                <!-- 网站日志 -->
                <a-tab-pane key="2" :tab="l('WebSiteLog')">
                    <a-card :title="l('WebSiteLogsHeaderInfo')" :bordered="false">
                        <a-button slot="extra" type="primary" @click="downloadWebLogs">
                            <a-icon type="download" />
                            {{ l('DownloadAll') }}
                        </a-button>
                        <a-button slot="extra" type="primary" @click="getWeblogData">
                            <a-icon type="reload" />
                            {{ l('Refresh') }}
                        </a-button>
                        <div class="web-log-view">
                            <p v-for="(item,index) in weblogList" :key="index">{{ item }}</p>
                        </div>
                    </a-card>
                </a-tab-pane>
            </a-tabs>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import {
    HostCachingServiceProxy,
    WebSiteLogServiceProxy
} from "@/shared/service-proxies";
import { fileDownloadService } from "@/shared/utils";

export default {
    name: "maintenance",
    mixins: [AppComponentBase],
    data() {
        return {
            spinning: false,
            // 缓存
            _hostCachingServiceProxy: "",
            cashtabledata: [],
            columns: [
                {
                    dataIndex: "name",
                    key: "name",
                    slots: { title: "customTitle" },
                    scopedSlots: { customRender: "name" }
                },
                {
                    title: "Action",
                    key: "action",
                    scopedSlots: { customRender: "action" }
                }
            ],
            // web日志
            weblogList: [],
            _webSiteLogServiceProxy: ""
        };
    },
    created() {
        this._hostCachingServiceProxy = new HostCachingServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this._webSiteLogServiceProxy = new WebSiteLogServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.getCashData();
        this.getWeblogData();
    },
    methods: {
        /**
         * 获取混存数据
         */
        getCashData() {
            this.spinning = true;
            this._hostCachingServiceProxy
                .getAllCaches()
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.cashtabledata = res.items;
                });
        },
        /**
         * 获取网站log
         */
        getWeblogData() {
            this.spinning = true;
            this._webSiteLogServiceProxy
                .getLatestWebLogs()
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.weblogList = res.latestWebLogLines;
                });
        },
        /**
         * 单个清空缓存
         */
        clearCache(item) {
            this.spinning = true;
            this._hostCachingServiceProxy
                .clearCache({
                    id: item.name
                })
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.$notification["success"]({
                        message: this.l("CacheSuccessfullyCleared")
                    });
                    this.getCashData();
                });
        },
        /**
         * 清理全部缓存
         */
        clearAllCaches() {
            this.spinning = true;
            this._hostCachingServiceProxy
                .clearAllCaches()
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.$notification["success"]({
                        message: this.l("AllCachesSuccessfullyCleared")
                    });
                    this.getCashData();
                });
        },
        /**
         * 下载日志
         */
        downloadWebLogs() {
            this.spinning = true;
            this._webSiteLogServiceProxy
                .downloadWebLogs()
                .finally(() => {
                    this.spinning = false;
                })
                .then(result => {
                    fileDownloadService.downloadTempFile(result);
                });
        }
    }
};
</script>

<style scoped lang="less">
.web-log-view {
    max-height: 400px;
    overflow-y: scroll;
}
</style>
