// src/yoyocmstemplate-vue/src/layout/default/profile/change-password-modal.vue
<template>
  <div>
    <div class="modal-header">
      <div class="modal-title">{{l('ChangePassword')}}</div>
    </div>

    <a-form :form="form" @submit="save">
      <!-- 当前密码 -->
        
      <a-form-item :label="l('CurrentPassword')" :label-col="{ span: 6 }"  has-feedback :wrapper-col="{ span: 14 }">
        <a-input
          type="password"
          v-decorator="['currentPassword', { rules: [
            { required: true, message: l('ThisFieldIsRequired') },
          ] }]"
        />
      </a-form-item>
      <!-- 新密码 -->
      <a-form-item
        :label="l('NewPassword')"
        :label-col="{ span: 6 }"
         has-feedback
        :wrapper-col="{ span: 14 }"
      >
        <a-input
          type="password"
          v-decorator="['newPassword', { rules: [
            { required: true, message: l('MinLength'),min:6 },
            { required: true, message: l('MaxLength'),max:32 },
          ] }]"
        />
      </a-form-item>
      <!-- 确认新密码 -->
      <a-form-item
         has-feedback
        :label="l('ConfirmPassword')"
        :label-col="{ span: 6 }"
        :wrapper-col="{ span: 14 }"
      >
        <a-input
          type="password"
          v-decorator="['confirmNewPasswordStr', { rules: [{ required: true, validator: confirmNewPassword, }] }]"
        />
      </a-form-item>

      <!-- 功能按钮 -->
      <div class="modal-footer">
        <a-button :disabled="saving" @click="close()" nz-button type="button">{{l("Cancel")}}</a-button>
        <a-button html-type="submit" :loading="saveLoading" type="primary">{{l("Save")}}</a-button>
      </div>
    </a-form>
  </div>
</template>

<script>
import { ModalComponentBase } from "@/shared/component-base";
import {
  ChangePasswordInput,
  ProfileServiceProxy
} from "../../../shared/service-proxies";

export default {
  name: "change-password-modal",
  mixins: [ModalComponentBase],
  data() {
    return {
      form: this.$form.createForm(this),
      profileService: null,
      confirmNewPasswordVal: null,
      inputVal: null,
      saveLoading:false,
    };
  },
  created() {
    this.profileService = new ProfileServiceProxy(this.$apiUrl, this.$api);
    this.inputVal = new ChangePasswordInput();
  },
  computed: {},
  methods: {
    confirmNewPassword(rule, value, callback) {
      const form = this.form;
      if (value && value !== form.getFieldValue("newPassword")) {
        callback(this.l("PasswordsDontMatch"));
      } else {
        callback();
      }
    },
    save(e) {
      e.preventDefault();
      this.form.validateFields((err, values) => {
        if (!err) {
          this.saveLoading = true;
          this.inputVal.currentPassword=values.currentPassword;
          this.inputVal.newPassword=values.newPassword;
          this.profileService
            .changePassword(this.inputVal)
            .finally(() => {
              this.saveLoading = false;
            })
            .then(() => {
              this.saveLoading = false;
              this.notify.success(this.l("YourPasswordHasChangedSuccessfully"));
              this.success();
            });
        }
      });
    }
  }
};
</script>

<style scoped>
</style>

// src/yoyocmstemplate-angular/src/layout/default/profile/change-password-modal.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import {
  ProfileServiceProxy,
  ChangePasswordInput,
} from '@shared/service-proxies/service-proxies';
import { AbstractControl, Validators, FormControl } from '@angular/forms';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';

@Component({
  selector: 'app-change-password-modal',
  templateUrl: './change-password-modal.component.html',
  styles: [],
})
export class ChangePasswordModalComponent extends ModalComponentBase
  implements OnInit {
  input: ChangePasswordInput = new ChangePasswordInput();
  confirmNewPasswordStr = '';

  constructor(injector: Injector, private profileService: ProfileServiceProxy) {
    super(injector);
  }
  ngOnInit() { }

  save(): void {
    this.saving = true;
    this.profileService
      .changePassword(this.input)
      .finally(() => {
        this.saving = false;
      })
      .subscribe(() => {
        this.notify.success(this.l('YourPasswordHasChangedSuccessfully'));
        this.success();
      });
  }
}

<div class="modal-header">
    <div class="modal-title">{{l('ChangePassword')}}</div>
</div>

<form nz-form #validateForm="ngForm" (ngSubmit)="save()" autocomplete="off">
    <!-- 当前密码 -->
    <nz-form-item>
        <nz-form-label [nzSm]="6" [nzXs]="24" nzRequired
                       nzFor="currentPassword">{{l('CurrentPassword')}}</nz-form-label>
        <nz-form-control [nzSm]="14" [nzXs]="24" nzHasFeedback>
            <input nz-input name="currentPassword" #currentPassword="ngModel" [(ngModel)]="input.currentPassword"
                   [placeholder]="l('CurrentPassword')" type="password" required>
            <nz-form-control nzExtra *ngIf="currentPassword.control.dirty&&currentPassword.control.errors">
                <ng-container
                        *ngIf="currentPassword.control.hasError('required')">{{l('ThisFieldIsRequired')}}</ng-container>
            </nz-form-control>
        </nz-form-control>
    </nz-form-item>

    <!-- 新密码 -->
    <nz-form-item>
        <nz-form-label [nzSm]="6" [nzXs]="24" nzRequired nzFor="newPassword">{{l('NewPassword')}}</nz-form-label>
        <nz-form-control [nzSm]="14" [nzXs]="24" nzHasFeedback>
            <input nz-input name="newPassword" #newPassword="ngModel" [(ngModel)]="input.newPassword"
                   [placeholder]="l('NewPassword')" type="password" minlength="6"
                   maxlength="32" required>
            <nz-form-control nzExtra *ngIf="newPassword.control.dirty&&newPassword.control.errors">
                <ng-container
                        *ngIf="newPassword.control.hasError('required')">{{l('ThisFieldIsRequired')}}</ng-container>
                <ng-container *ngIf="newPassword.control.hasError('maxlength')">{{l('MaxLength')}}</ng-container>
                <ng-container *ngIf="newPassword.control.hasError('minlength')">{{l('MinLength')}}</ng-container>
            </nz-form-control>
        </nz-form-control>
    </nz-form-item>

    <!-- 确认新密码 -->
    <nz-form-item>
        <nz-form-label [nzSm]="6" [nzXs]="24" nzRequired
                       nzFor="confirmNewPassword">{{l('ConfirmPassword')}}</nz-form-label>
        <nz-form-control [nzSm]="14" [nzXs]="24" nzHasFeedback>
            <input nz-input name="confirmNewPassword" #confirmNewPassword="ngModel" [(ngModel)]="confirmNewPasswordStr"
                   [placeholder]="l('ConfirmPassword')" type="password" [validateEqual]="input.newPassword" required>
            <nz-form-control nzExtra *ngIf="confirmNewPassword.control.dirty&&confirmNewPassword.control.errors">
                <ng-container *ngIf="confirmNewPassword.control.hasError('validateEqual')">{{l('PasswordsDontMatch')}}
                </ng-container>
            </nz-form-control>
        </nz-form-control>
    </nz-form-item>


    <!-- 功能按钮 -->
    <div class="modal-footer">
        <button nz-button type="button" [disabled]="saving" (click)="close()">
            {{l("Cancel")}}
        </button>
        <button nz-button [nzType]="'primary'" type="submit" [disabled]="!validateForm.valid">
            {{l("Save")}}
        </button>
    </div>


</form>
