// src/yoyocmstemplate-vue/src/layout/default/profile/my-settings-modal.vue
<template>
    <div>
        <div class="modal-header">
            <div class="modal-title">{{l('MySettings')}}</div>
        </div>
        <a-form :form="form" @submit="save">
            <!-- 用户名(登陆使用) -->
            <a-form-item
                :label="l('UserName')"
                :label-col="{ span: 6 }"
                has-feedback
                :wrapper-col="{ span: 14 }">
                <a-input
                    type="text"
                    :disabled="isAdmin"
                    v-decorator="['userName', { rules: [
            { required: true, message: l('ThisFieldIsRequired') },
          ] }]" />
            </a-form-item>

            <!-- 手机号码 -->
            <a-form-item
                :label="l('PhoneNumber')"
                :label-col="{ span: 6 }"
                has-feedback
                :wrapper-col="{ span: 14 }">
                <a-input
                    :placeholder="l('PhoneNumber')"
                    type="text"
                    v-decorator="['phoneNumber', { rules: [{ required: false},] }]" />
            </a-form-item>
            <!-- 邮箱地址 -->
            <a-form-item
                :label="l('EmailAddress')"
                :label-col="{ span: 6 }"
                has-feedback
                :wrapper-col="{ span: 14 }">
                <a-input
                    type="email"
                    :placeholder="l('EmailAddress')"
                    v-decorator="['emailAddress', { rules: [
            { required: true, message: l('ThisFieldIsRequired') },
            { required: true, validator: validationEmail, }
          ] }]" />
            </a-form-item>
            <!-- 功能按钮 -->
            <div class="modal-footer">
                <a-button :disabled="saving" @click="close()" nz-button type="button">{{l("Cancel")}}</a-button>
                <a-button html-type="submit" type="primary" :loading="saveLoading">{{l("Save")}}</a-button>
            </div>
        </a-form>
    </div>
</template>

<script>
import { ModalComponentBase } from "@/shared/component-base";
import { appSessionService } from "@/shared/abp/";
import { AppConsts } from "@/abpPro/AppConsts";
import pick from "lodash.pick";
import {
    CurrentUserProfileEditDto,
    ProfileServiceProxy
} from "../../../shared/service-proxies";
export default {
    name: "my-settings-modal",
    mixins: [ModalComponentBase],
    data() {
        return {
            saveLoading: false,
            form: this.$form.createForm(this),
            isAdmin: true,
            profileService: null,
            appSession: null
        };
    },
    created() {
        this.profileService = new ProfileServiceProxy(this.$apiUrl, this.$api);
        this.profileService.getCurrentUserProfileForEdit().then(result => {
            this.user = result;
            this.isAdmin =
                this.user.userName ===
                AppConsts.userManagement.defaultAdminUserName;
            this.$nextTick(() => {
                this.form.setFieldsValue(
                    pick(result, "userName", "phoneNumber", "emailAddress")
                );
            });
        });
    },
    methods: {
        validationEmail(rule, value, callback) {
            const form = this.form;
            var regEmail = /^[A-Za-z0-9\u4e00-\u9fa5]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/;
            if (value && !regEmail.test(value)) {
                callback(this.l("NotEmail"));
            } else {
                callback();
            }
        },
        save(e) {
            e.preventDefault();
            this.form.validateFields((err, values) => {
                if (!err) {
                    this.saveLoading = true;
                    this.user.userName = values.userName;
                    this.user.phoneNumber = values.phoneNumber;
                    this.user.emailAddress = values.emailAddress;
                    this.profileService
                        .updateCurrentUserProfile(this.user)
                        .finally(() => {
                            this.saving = false;
                        })
                        .then(() => {
                            this.saving = false;
                            appSessionService.user.userName = this.user.userName;
                            appSessionService.user.emailAddress = this.user.emailAddress;
                            this.notify.success(this.l("SavedSuccessfully"));
                            this.success();
                        });
                }
            });
        }
    }
};
</script>

<style scoped>
</style>

// src/yoyocmstemplate-angular/src/layout/default/profile/my-settings-modal.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import {
  CurrentUserProfileEditDto,
  ProfileServiceProxy
} from '@shared/service-proxies/service-proxies';
import { AppSessionService } from '@shared/session/app-session.service';
import { AppConsts } from 'abpPro/AppConsts';
import { Validators } from '@angular/forms';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';

@Component({
  selector: 'app-my-settings-modal',
  templateUrl: './my-settings-modal.component.html',
  styles: []
})
export class MySettingsModalComponent extends ModalComponentBase
  implements OnInit {
  user: CurrentUserProfileEditDto = new CurrentUserProfileEditDto();
  isAdmin = true;

  constructor(injector: Injector, private profileService: ProfileServiceProxy) {
    super(injector);
  }

  ngOnInit() {
    this.profileService.getCurrentUserProfileForEdit().subscribe(result => {
      this.user = result;
      this.isAdmin =
        this.user.userName === AppConsts.userManagement.defaultAdminUserName;
    });
  }

  save(): void {
    this.saving = true;
    this.profileService
      .updateCurrentUserProfile(this.user)
      .finally(() => {
        this.saving = false;
      })
      .subscribe(() => {
        this.appSession.user.userName = this.user.userName;
        this.appSession.user.emailAddress = this.user.emailAddress;
        this.notify.success(this.l('SavedSuccessfully'));
        this.success();
      });
  }
  //#region 头像功能

  upLoadProfilePictureSuccess(event) {
    this.user.profilePictureId = event;
  }
  removeProfilePicture() {
    this.user.profilePictureId = '';
  }

  //#endregion
}

<div class="modal-header">
  <div class="modal-title">{{ l('MySettings') }}</div>
</div>
<form nz-form #validateForm="ngForm" (ngSubmit)="save()" autocomplete="off">
  <nz-form-item>
    <nz-form-label [nzSm]="6" [nzXs]="24">{{ l('ProfilePictureFile') }}</nz-form-label>
    <nz-form-control [nzSm]="14" [nzXs]="24">
      <upload-user-portrait
        [profilePictureId]="user.profilePictureId"
        (onUpLoadProfilePictureSuccess)="upLoadProfilePictureSuccess($event)"
        (onRemoveProfilePicture)="removeProfilePicture()"
      >
      </upload-user-portrait>
    </nz-form-control>
  </nz-form-item>

  <!-- 用户名(登陆使用) -->
  <nz-form-item>
    <nz-form-label [nzSm]="6" [nzXs]="24" nzRequired nzFor="userName">{{ l('UserName') }}</nz-form-label>
    <nz-form-control [nzSm]="14" [nzXs]="24" nzHasFeedback>
      <input
        nz-input
        name="userName"
        #userNameInput="ngModel"
        [(ngModel)]="user.userName"
        [disabled]="isAdmin"
        autocomplete="username"
        required
      />
      <nz-form-control nzExtra *ngIf="userNameInput.control.dirty && userNameInput.control.errors">
        <ng-container *ngIf="userNameInput.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
      </nz-form-control>
      <nz-form-control nzExtra *ngIf="isAdmin">{{ l('ThisAdminUser') }}</nz-form-control>
    </nz-form-control>
  </nz-form-item>
  <!-- 手机号码 -->
  <nz-form-item>
    <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="phoneNumber">{{ l('PhoneNumber') }}</nz-form-label>
    <nz-form-control [nzSm]="14" [nzXs]="24">
      <input
        nz-input
        name="phoneNumber"
        [(ngModel)]="user.phoneNumber"
        [placeholder]="l('PhoneNumber')"
        autocomplete="tel"
      />
    </nz-form-control>
  </nz-form-item>
  <!-- 邮箱地址 -->
  <nz-form-item>
    <nz-form-label [nzSm]="6" [nzXs]="24" nzRequired nzFor="emailAddress">{{ l('EmailAddress') }}</nz-form-label>
    <nz-form-control [nzSm]="14" [nzXs]="24" nzHasFeedback>
      <input
        nz-input
        name="emailAddress"
        #emailAddress="ngModel"
        [(ngModel)]="user.emailAddress"
        [placeholder]="l('EmailAddress')"
        autocomplete="email"
        required
        email
      />
      <nz-form-control nzExtra *ngIf="emailAddress.control.dirty && emailAddress.control.errors">
        <ng-container *ngIf="emailAddress.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
        <ng-container *ngIf="emailAddress.control.hasError('email')">{{ l('NotEmail') }}</ng-container>
      </nz-form-control>
    </nz-form-control>
  </nz-form-item>

  <!-- 功能按钮 -->
  <div class="modal-footer">
    <button nz-button type="button" [disabled]="saving" (click)="close()">
      {{ l('Cancel') }}
    </button>
    <button nz-button [nzType]="'primary'" type="submit" [disabled]="!validateForm.valid || saving">
      {{ l('Save') }}
    </button>
  </div>
</form>
