// src/yoyocmstemplate-angular/src/app/admin/tenants/tenants.component.ts
import { Component, Injector } from '@angular/core';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import {
  TenantServiceProxy,
  TenantListDto,
  SubscribableEditionComboboxItemDto,
  EntityDtoOfInt64,
  NameValueDto,
  CommonLookupServiceProxy,
  CommonLookupFindUsersInput,
} from '@shared/service-proxies/service-proxies';
import { CreateTenantComponent } from '@app/admin/tenants/create-tenant/create-tenant.component';
import { EditTenantComponent } from './edit-tenant/edit-tenant.component';
import { CommonLookupComponent } from '../common/common-lookup/common-lookup.component';
import { EditTenantFeaturesComponent } from './edit-tenant-features/edit-tenant-features.component';
import { ImpersonationService } from '@shared/auth';
import { ActivatedRoute } from '@angular/router';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-tenants',
  templateUrl: './tenants.component.html',
  styles: [],
})
export class TenantsComponent extends PagedListingComponentBase<TenantListDto> {
  advancedFiltersVisible = false; // 是否显示高级过滤
  editionId: any = null; // 版本Id
  subscribableDateRange = [null, null]; // 订阅时间范围
  createDateRange = [null, null]; // 创建时间范围

  constructor(
    injector: Injector,
    private _activatedRoute: ActivatedRoute,
    private _tenantService: TenantServiceProxy,
    private _impersonationService: ImpersonationService,
    private _commonLookupService: CommonLookupServiceProxy,
  ) {
    super(injector);
    this.filterText = this._activatedRoute.snapshot.queryParams.filterText || '';
  }

  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    this._tenantService
      .getPaged(
        this.advancedFiltersVisible ? this.subscribableDateRange[0] || undefined : undefined, // 订阅结束时间开始
        this.advancedFiltersVisible ? this.subscribableDateRange[1] || undefined : undefined, // 订阅结束时间结束
        this.advancedFiltersVisible ? this.createDateRange[0] || undefined : undefined, // 创建时间开始
        this.advancedFiltersVisible ? this.createDateRange[1] || undefined : undefined, // 创建时间结束
        this.editionId || undefined, // 版本id
        this.filterText, // 名称过滤字符串
        this.sorting, // 排序字段
        request.maxResultCount, // 最大数据量
        request.skipCount, // 跳过数据量
      )
      .pipe(finalize(() => finishedCallback()))
      .subscribe(result => {
        this.dataList = result.items;
        this.showPaging(result);
      });
  }

  /**
   * 强制刷新
   */
  forceRefresh() {
    this.filterText = '';
    this.refreshGoFirstPage();
  }

  /**
   * 解锁此租户默认管理员
   * @param entity
   */
  unlockTenantAdminUser(entity: TenantListDto): void {
    this._tenantService.unlockTenantAdmin(new EntityDtoOfInt64({ id: entity.id })).subscribe(() => {
      this.notify.success(this.l('UnlockedTenandAdmin', entity.name));
    });
  }

  /**
   * 修改租户的功能
   * @param entity
   */
  changeTenantFeatures(entity: TenantListDto): void {
    this.modalHelper
      .createStatic(EditTenantFeaturesComponent, {
        tenantId: entity.id,
        tenantName: name,
      })
      .subscribe(res => {});
  }

  /**
   * 使用此租户模拟登陆
   * @param entity
   */
  tenantImpersonateLogin(entity: TenantListDto): void {
    this.modalHelper
      .createStatic(CommonLookupComponent, {
        tenantId: entity.id,
        options: {
          dataSource: (skipCount: number, maxResultCount: number, filter: string, tenantId?: number) => {
            const input = new CommonLookupFindUsersInput();
            input.filterText = filter;
            input.maxResultCount = maxResultCount;
            input.skipCount = skipCount;
            input.tenantId = tenantId;
            return this._commonLookupService.findUsers(input);
          },
          isFilterEnabled: true,
          canSelect: () => true,
        },
      })
      .subscribe(item => {
        if (item) {
          this.impersonateUser(item, entity.id);
        }
      });
  }

  edit(entity: TenantListDto): void {
    this.modalHelper.static(EditTenantComponent, { entityId: entity }).subscribe(res => {
      if (res) {
        this.refresh();
      }
    });
  }

  delete(entity: TenantListDto): void {
    this._tenantService.delete(entity.id).subscribe(() => this.refresh());
  }

  create(): void {
    this.modalHelper.open(CreateTenantComponent, null, 'md').subscribe(res => {
      if (res) {
        this.refresh();
      }
    });
  }

  batchDelete(): void {
    this._tenantService.batchDelete(this.selectedDataItems).subscribe(() => this.refresh());
  }

  selectedEditionChange(edition: SubscribableEditionComboboxItemDto) {
    this.editionId = edition ? edition.value : null;
    this.refresh();
  }

  impersonateUser(item: NameValueDto, id: number): void {
    this._impersonationService.impersonate(parseInt(item.value), id);
  }
}

<page-header [title]="l('Tenants')"> </page-header>

<!-- <full-content (fullscreenChange)="fullChange($event)"> -->
<!-- 表格部分 -->
<nz-card [nzBordered]="false">
  <!-- 检索表单 -->
  <form nz-form [nzLayout]="'vertical'" (ngSubmit)="refresh()">
    <nz-row nzGutter="8">
      <nz-col nzSm="12">
        <nz-form-item>
          <nz-form-label>
            {{ l('TenantNameOrTenancyCode') }}
          </nz-form-label>
          <nz-form-control>
            <nz-input-group nzSearch [nzAddOnAfter]="suffixButton">
              <input type="text" nz-input [(ngModel)]="filterText" (keyup.enter)="refresh()" name="filterText"
                [placeholder]="l('SearchWithThreeDot')" />
              <ng-template #suffixButton>
                <button nz-button nzType="primary" nzSearch type="submit">
                  <!-- <i class="iconfont icon-search"></i> -->
                  <i class="iconfont icon-search"></i>
                  <!-- {{l('Search')}} -->
                </button>
              </ng-template>
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
      </nz-col>
      <nz-col nzSm="12">
        <nz-form-item>
          <nz-form-label>
            {{ l('Edition') }}
          </nz-form-label>
          <nz-form-control>
            <edition-combo [placeholder]="l('PleaseSelect')" (selectedEditionChange)="selectedEditionChange($event)">
            </edition-combo>
            <!-- <edition-select [(selectedEdition)]="filters.selectedEditionId" (selectedEditionChange)="refresh()"></edition-select> -->
          </nz-form-control>
        </nz-form-item>
      </nz-col>
    </nz-row>

    <nz-row nzGutter="8" *ngIf="advancedFiltersVisible">
      <nz-col nzSm="12">
        <nz-form-item>
          <nz-form-label>
            {{ l('SubscriptionEndDateUtc') }}
          </nz-form-label>
          <nz-form-control>
            <nz-range-picker name="SubscriptionEndDateRange" [(ngModel)]="subscribableDateRange"
              [nzPlaceHolder]="[l('StartDateTime'), l('EndDateTime')]" (ngModelChange)="refresh()" style="width:100%;">
            </nz-range-picker>
          </nz-form-control>
        </nz-form-item>
      </nz-col>
      <nz-col nzSm="12">
        <nz-form-item>
          <nz-form-label>
            {{ l('CreationTime') }}
          </nz-form-label>
          <nz-form-control>
            <nz-range-picker name="CreationDateRange" [(ngModel)]="createDateRange"
              [nzPlaceHolder]="[l('StartDateTime'), l('EndDateTime')]" (ngModelChange)="refresh()" style="width:100%;">
            </nz-range-picker>
          </nz-form-control>
        </nz-form-item>
      </nz-col>
    </nz-row>
  </form>
  <!-- 操作部分 -->
  <nz-row nzGutter="8">
    <nz-col nzMd="20" nzSm="12" class="btn-gutter">
      <button nz-button [nzType]="'primary'" *ngIf="isGranted('Pages.Tenants.Create')" (click)="create()">
        <i class="iconfont icon-plus"></i>
        <span>
          {{ l('CreateNewTenant') }}
        </span>
      </button>
      <button nz-button [nzType]="'danger'" *ngIf="isGranted('Pages.Tenants.Delete')" (click)="batchDelete()">
        <i class="iconfont icon-delete"></i>
        <span>
          {{ l('BatchDelete') }}
        </span>
      </button>
    </nz-col>
    <nz-col nzMd="4" nzSm="12" class="text-right">
      <a (click)="advancedFiltersVisible = !advancedFiltersVisible">
        {{ advancedFiltersVisible ? l('HideAdvancedFilters') : l('ShowAdvancedFilters') }}
        <!-- <i class="anticon" [class.anticon-down]="!advancedFiltersVisible"
          [class.anticon-up]="advancedFiltersVisible"></i> -->

        <i class="iconfont" [class.icon-down]="!advancedFiltersVisible" [class.icon-up]="advancedFiltersVisible"></i>
      </a>
    </nz-col>
  </nz-row>
  <!-- 数据部分 -->
  <!-- 复选框提示的内容数据部分 -->
  <table-checkbox-panel [selectLength]="selectedDataItems.length" (onClear)="restCheckStatus(dataList)"
    (onRefresh)="refreshGoFirstPage()"></table-checkbox-panel>

  <nz-table #nzDataTable [nzFrontPagination]="false" [nzShowQuickJumper]="true" [nzShowSizeChanger]="true"
    [nzData]="dataList" [nzTotal]="totalItems" [nzLoading]="isTableLoading" [(nzPageIndex)]="pageNumber"
    [(nzPageSize)]="pageSize" (nzPageIndexChange)="refresh()" (nzPageSizeChange)="refresh()"
    [nzNoResult]="noDataTemplate" [nzShowTotal]="showTotalTemplate">
    <!-- 暂无数据 -->
    <ng-template #noDataTemplate>
      <no-data></no-data>
    </ng-template>
    <!-- 分页信息显示 当前 1 页/共 3 页，共 5 条/显示 1-2 条 -->
    <ng-template #showTotalTemplate let-total let-range="range">
      {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
    </ng-template>
    <!-- 表头 -->
    <thead (nzSortChange)="gridSort($event)">
      <tr>
        <th nzShowCheckbox [(nzChecked)]="allChecked" [nzDisabled]="allCheckboxDisabled"
          [nzIndeterminate]="checkboxIndeterminate" (nzCheckedChange)="checkAll($event)"></th>

        <th nzShowSort nzSortKey="tenancyName">
          <span>{{ l('TenancyCodeName') }}</span>
        </th>
        <th nzShowSort nzSortKey="name">
          <span>{{ l('Name') }}</span>
        </th>
        <th nzShowSort nzSortKey="editionDisplayName">
          <span>{{ l('Edition') }}</span>
        </th>
        <th nzShowSort nzSortKey="subscriptionEndUtc" class="text-center">
          <span>{{ l('SubscriptionEndUtc') }}</span>
        </th>
        <th nzShowSort nzSortKey="isActive" class="text-center">
          <span>{{ l('Active') }}</span>
        </th>
        <th nzShowSort nzSortKey="creationTime" class="text-center">
          <span>{{ l('CreationTime') }}</span>
        </th>
        <th nzWidth="240px" class="text-center">
          <span>{{ l('Actions') }}</span>
        </th>
      </tr>
    </thead>
    <!-- 表格内容 -->
    <tbody>
      <tr *ngFor="let item of nzDataTable.data">
        <td nzShowCheckbox [(nzChecked)]="item.checked" (nzCheckedChange)="refreshCheckStatus(this.dataList)"></td>

        <td>
          <span *ngIf="item.connectionString" nz-tooltip [nzTooltipTitle]="l('HasOwnDatabase')">
            <i class="iconfont icon-database"></i>
            <!-- <i class="iconfont icon-database"></i> -->
          </span>
          {{ item.tenancyName }}
        </td>
        <td>
          {{ item.name }}
        </td>
        <td>
          {{ item.editionDisplayName }}
        </td>
        <td class="text-center">
          {{ item.subscriptionEndUtc ? (item.subscriptionEndUtc | _moment: 'YYYY-MM-DD') : '—' }}
        </td>
        <td class="text-center" [innerHTML]="item.isActive | yn"></td>
        <td class="text-center">
          {{ item.creationTime | _moment: 'YYYY-MM-DD' }}
        </td>
        <td class="text-center">
          <!-- 编辑 -->
          <ng-container *ngIf="isGranted('Pages.Tenants.Edit')">
            <a (click)="edit(item.id)">
              <i class="iconfont icon-edit mr-sm"></i>
              <span>{{ l('Edit') }}</span>
            </a>
            <nz-divider nzType="vertical"></nz-divider>
          </ng-container>
          <!-- 删除 -->
          <ng-container *ngIf="isGranted('Pages.Tenants.Delete')">
            <a nz-popconfirm [nzPopconfirmTitle]="l('ConfirmDeleteWarningMessage')" (nzOnConfirm)="delete(item)"
              [nzOkText]="l('Ok')" [nzCancelText]="l('Cancel')">
              <i class="iconfont icon-delete mr-sm"></i>
              <span>{{ l('Delete') }}</span>
            </a>
            <nz-divider nzType="vertical"></nz-divider>
          </ng-container>

          <!-- 更多 -->
          <ng-container>
            <a nz-dropdown [nzDropdownMenu]="menu">
              {{ l('More') }}
              <!-- <i nz-icon nzType="down"></i> -->
              <i class="iconfont icon-down "></i>
            </a>
            <nz-dropdown-menu #menu="nzDropdownMenu">
              <ul nz-menu>
                <li nz-menu-item *ngIf="isGranted('Pages.Tenants.Impersonation')"
                  (click)="tenantImpersonateLogin(item)">
                  <a>
                    <i class="iconfont icon-login  mr-sm"></i>
                    <!-- <i class="iconfont icon-login mr-sm"></i> -->
                    <span>{{ l('LoginAsThisTenant') }}</span>
                  </a>
                </li>
                <li nz-menu-item *ngIf="item.isActive && isGranted('Pages.Tenants.ChangeFeatures')"
                  (click)="changeTenantFeatures(item)">
                  <a>
                    <i class="iconfont icon-codepen  mr-sm"></i>
                    <!-- <i class="iconfont icon-codepen mr-sm"></i> -->
                    <span>{{ l('Features') }}</span>
                  </a>
                </li>
                <li nz-menu-item (click)="unlockTenantAdminUser(item)">
                  <a>
                    <i class="iconfont icon-unlock  mr-sm"></i>
                    <!-- <i class="iconfont icon-unlock mr-sm"></i> -->
                    <span>{{ l('Unlock') }}</span>
                  </a>
                </li>
              </ul>
            </nz-dropdown-menu>
          </ng-container>
        </td>
      </tr>
    </tbody>
  </nz-table>

</nz-card>
<!-- </full-content> -->

// src/yoyocmstemplate-vue/src/app/admin/tenants/tenants.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('Tenants')"></page-header>
        <a-card :bordered="false">
            <a-form :layout="'vertical'" @submit.prevent="getData">
                <a-row :gutter="8">
                    <!-- 租户名称/租户代码 -->
                    <a-col :sm="12">
                        <a-form-item :label="l('TenantNameOrTenancyCode')">
                            <a-input-search
                                name="filterText"
                                :placeholder="l('SearchWithThreeDot')"
                                @search="getData"
                                enterButton
                                v-model="filterText"
                                v-decorator="['filterText']" />
                        </a-form-item>
                    </a-col>
                    <!-- 版本 -->
                    <a-col :sm="12">
                        <a-form-item :label="l('Edition')">
                            <edition-combo
                                :placeholder="l('PleaseSelect')"
                                :selectedEdition="selectedEdition"
                                @selectedEditionChange="selectedEditionChange($event)"></edition-combo>
                        </a-form-item>
                    </a-col>
                </a-row>
                <a-row :gutter="8" v-if="advancedFiltersVisible">
                    <!-- 订阅结束日期 -->
                    <a-col :sm="12">
                        <a-form-item :label="l('SubscriptionEndDateUtc')">
                            <a-range-picker
                                name="SubscriptionEndDateRange"
                                v-decorator="['subscribableDateRange']"
                                :placeholder="[l('StartDateTime'),l('EndDateTime')]"
                                @change="subscribableDateChange"
                                style="width:100%;" />
                        </a-form-item>
                    </a-col>
                    <!-- 创建时间 -->
                    <a-col :sm="12">
                        <a-form-item :label="l('CreationTime')">
                            <a-range-picker
                                name="CreationDateRange"
                                v-decorator="['createDateRange']"
                                :placeholder="[l('StartDateTime'),l('EndDateTime')]"
                                @change="createDateChange"
                                style="width:100%;" />
                        </a-form-item>
                    </a-col>
                </a-row>
            </a-form>
            <!-- 操作部分 -->
            <a-row :gutter="8">
                <a-col :md="20" :sm="12">
                    <a-button
                        :type="'primary'"
                        v-if="isGranted('Pages.Tenants.Create')"
                        @click="createNewTenant">
                        <a-icon type="plus" />
                        <span>{{l("CreateNewTenant")}}</span>
                    </a-button>
                    <a-button :type="'danger'" v-if="isGranted('Pages.Tenants.Delete')" @click="batchDelete">
                        <a-icon type="delete" />
                        <span>{{l("BatchDelete")}}</span>
                    </a-button>
                </a-col>

                <a-col :md="4" :sm="12" class="text-right">
                    <a @click="advancedFiltersVisible=!advancedFiltersVisible">
                        {{advancedFiltersVisible ? l('HideAdvancedFilters') : l('ShowAdvancedFilters')}}
                        <a-icon :type="advancedFiltersVisible ? 'up' : 'down'" />
                    </a>
                </a-col>
            </a-row>

            <!-- 数据部分 -->
            <div class="my-md">
                <a-alert :type="'info'" :showIcon="true">
                    <template slot="message">
                        <span v-html="l('GridSelectedXItemsTips',selectedRowKeys.length)"></span>
                        <a @click="restCheckStatus()" class="ml-md">{{l('ClearEmpty')}}</a>
                        <a-divider type="vertical"></a-divider>
                        <a @click="getData()">{{l('Refresh')}}</a>
                    </template>
                </a-alert>
            </div>

            <a-row>
                <a-table
                    class="list-table"
                    @change="getData"
                    :pagination="false"
                    :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"
                    :columns="columns"
                    :rowKey="tableDatas => tableDatas.id"
                    :dataSource="tableData">
                    <p class="subscriptionEndUtc" slot="subscriptionEndUtc" slot-scope="record">{{ record }}</p>
                    <a class="isActive" slot="isActive" slot-scope="record">
                        <a-icon v-if="record" type="check" />
                        <a-icon v-if="!record" type="close" />
                    </a>
                    <p
                        class="creationTime"
                        slot="creationTime"
                        slot-scope="record">{{ record | moment('YYYY-MM-DD') }}</p>
                    <template slot-scope="text, record" slot="Actions">
                        <!-- 修改 -->
                        <a @click="edit(record.id)" v-if="isGranted('Pages.Tenants.Edit')">
                            <a-icon type="edit" />
                            <span>{{ l('Edit') }}</span>
                            <a-divider type="vertical" />
                        </a>
                        <!-- 删除 -->
                        <a-popconfirm
                            placement="top"
                            :okText="l('Ok')"
                            :cancelText="l('Cancel')"
                            @confirm="deleteItem(record)"
                            v-if="isGranted('Pages.Tenants.Delete')">
                            <template slot="title">{{ l('ConfirmDeleteWarningMessage') }}</template>
                            <a>
                                <a-icon type="delete" />
                                <span>{{ l('Delete') }}</span>
                                <a-divider type="vertical" />
                            </a>
                        </a-popconfirm>
                        <!-- 更多 -->
                        <a-dropdown>
                            <a class="ant-dropdown-link" @click="e => e.preventDefault()">
                                {{ l('More') }}
                                <a-icon type="down" />
                            </a>
                            <a-menu slot="overlay">
                                <a-menu-item
                                    v-if="isGranted('Pages.Tenants.Impersonation')"
                                    @click="tenantImpersonateLogin(record)">
                                    <a href="javascript:;">
                                        <a-icon type="login" />
                                        <span>{{ l('LoginAsThisTenant') }}</span>
                                    </a>
                                </a-menu-item>
                                <a-menu-item
                                    v-if="record.isActive && isGranted('Pages.Tenants.ChangeFeatures')"
                                    @click="changeTenantFeatures(record)">
                                    <a href="javascript:;">
                                        <a-icon type="codepen" />
                                        <span>{{ l('Features') }}</span>
                                    </a>
                                </a-menu-item>
                                <a-menu-item @click="unlockTenantAdminUser(record)">
                                    <a href="javascript:;">
                                        <a-icon type="unlock" />
                                        <span>{{ l('Unlock') }}</span>
                                    </a>
                                </a-menu-item>
                            </a-menu>
                        </a-dropdown>
                    </template>
                </a-table>
                <a-pagination
                    class="pagination"
                    size="middle"
                    :total="totalItems"
                    showSizeChanger
                    showQuickJumper
                    :showTotal="showTotalFun"
                    @change="onChange"
                    @showSizeChange="showSizeChange" />
            </a-row>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import EditionCombo from "../shared/edition-combo/edition-combo.vue";
import { ModalHelper } from "@/shared/helpers";
// import {
//   PagedListingComponentBase,
//   PagedRequestDto
// } from '../../../shared/component-base/paged-listing-component-base';
import {
    TenantServiceProxy,
    TenantListDto,
    SubscribableEditionComboboxItemDto,
    EntityDtoOfInt64,
    NameValueDto,
    CommonLookupServiceProxy,
    CommonLookupFindUsersInput,
    EntityDto
} from "@/shared/service-proxies";
import { CreateTenantComponent } from "./create-tenant/index";
import { EditTenantComponent } from "./edit-tenant/index";
import { CommonLookupComponent } from "./common-lookup/index";
import { EditTenantFeaturesComponent } from "./edit-tenant-features/index";
import moment from "moment";
import { impersonationService } from "@/shared/auth/index";

export default {
    mixins: [AppComponentBase],
    name: "tenants",
    components: {
        EditionCombo
    },
    data() {
        return {
            _tenantService: null,
            selectedEdition: {
                value: 0
            },
            columns: [
                {
                    title: this.l("TenancyCodeName"),
                    dataIndex: "tenancyName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "tenancyName" }
                },
                {
                    title: this.l("Name"),
                    dataIndex: "name",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "name" }
                },
                {
                    title: this.l("Edition"),
                    dataIndex: "editionDisplayName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "editionDisplayName" }
                },
                {
                    title: this.l("SubscriptionEndUtc"),
                    dataIndex: "subscriptionEndUtc",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "subscriptionEndUtc" }
                },
                {
                    title: this.l("Active"),
                    dataIndex: "isActive",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "isActive" }
                },
                {
                    title: this.l("CreationTime"),
                    dataIndex: "creationTime",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "creationTime" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "Actions",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "Actions" }
                }
            ],
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { maxResultCount: 10, skipCount: 0 },
            // 选择多少项
            selectedRowKeys: [],
            selectedRows: [],
            advancedFiltersVisible: false, // 是否显示高级过滤
            // 请求参数
            filterText: undefined,
            editionId: undefined,
            subscribableDateRange: [null, null], // 订阅时间范围
            createDateRange: [null, null], // 创建时间范围
            tableData: [],
            // loading
            spinning: true
        };
    },
    created() {
        this._tenantService = new TenantServiceProxy(this.$apiUrl, this.$api);
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._tenantService
                .getPaged(
                    this.advancedFiltersVisible
                        ? this.subscribableDateRange[0] || undefined
                        : undefined, // 订阅结束时间开始
                    this.advancedFiltersVisible
                        ? this.subscribableDateRange[1] || undefined
                        : undefined, // 订阅结束时间结束
                    this.advancedFiltersVisible
                        ? this.createDateRange[0] || undefined
                        : undefined, // 创建时间开始
                    this.advancedFiltersVisible
                        ? this.createDateRange[1] || undefined
                        : undefined, // 创建时间结束
                    this.editionId || undefined, // 版本id
                    this.filterText, // 名称过滤字符串
                    this.sorting, // 排序字段
                    this.request.maxResultCount, // 最大数据量
                    this.request.skipCount // 跳过数据量
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    console.log(res);
                    this.tableData = res.items;
                    this.tableData.map(item => {
                        item.subscriptionEndUtc = item.subscriptionEndUtc
                            ? moment(item.subscriptionEndUtc).format(
                                  "YYYY-MM-DD"
                              )
                            : "-";
                    });
                    this.totalItems = res.totalCount;
                    this.totalPages = Math.ceil(
                        res.totalCount / this.request.maxResultCount
                    );
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                })
                .catch(err => {
                    console.log(err);
                });
        },
        /**
         * 版本选择
         */
        selectedEditionChange(e) {
            this.editionId = e ? e.value : null;
            console.log(this.editionId);
            this.getData();
        },
        /**
         * 订阅日期改变
         */
        subscribableDateChange(e) {
            this.subscribableDateRange = e;
            this.getData();
        },
        /**
         * 创建时间改变
         */
        createDateChange(e) {
            this.createDateRange = e;
            this.getData();
        },
        /**
         * 新建租户
         */
        createNewTenant(e) {
            console.log(e);
            ModalHelper.create(CreateTenantComponent, null, {
                width: "400px"
            }).subscribe(res => {
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 批量删除
         */
        batchDelete(e) {
            if (!this.selectedRowKeys || this.selectedRowKeys.length == 0) {
                return;
            }
            this.spinning = true;

            let batchDeleteInput = this.selectedRowKeys.map(o => {
                return new EntityDto({ id: o });
            });

            this._tenantService
                .batchDelete(batchDeleteInput)
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.getData();
                });
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * 单个删除
         */
        deleteItem(item) {
            this.spinning = true;
            this._tenantService
                .delete(item.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.getData();
                });
        },
        /**
         * 编辑
         */
        edit(id) {
            console.log(id);
            ModalHelper.create(
                EditTenantComponent,
                { entityId: id },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 清空选择
         */
        restCheckStatus() {
            this.selectedRowKeys = [];
        },
        /**
         * table选择事件
         */
        onSelectChange(selectedRowKeys, selectedRows) {
            this.selectedRowKeys = selectedRowKeys;
            this.selectedRows = selectedRows;
            console.log(this.selectedRows);
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        },
        /**
         * 使用此租户登录
         */
        tenantImpersonateLogin(item) {
            console.log(item);
            ModalHelper.create(
                CommonLookupComponent,
                { tenantId: item.id },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    this.impersonateUser(res, item.id);
                }
            });
        },
        /**
         * 编辑租户
         */
        changeTenantFeatures(item) {
            ModalHelper.create(
                EditTenantFeaturesComponent,
                { tenantId: item.id },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    // this.getData();
                }
            });
        },
        /**
         * 解锁
         */
        unlockTenantAdminUser(item) {
            console.log(item);
            this.spinning = true;
            this._tenantService
                .unlockTenantAdmin({ id: item.id })
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.$notification["success"]({
                        message: this.l("UnlockedTenandAdmin")
                    });
                })
                .catch(err => {
                    console.log(err);
                });
        },
        impersonateUser(item, id) {
            impersonationService.impersonate(parseInt(item.value), id);
        }
    }
};
</script>

<style scoped>
@import "./tenants.less";
</style>
