// src/yoyocmstemplate-angular/src/app/admin/languages/languages.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import {
  LanguageListDto,
  LanguageServiceProxy,
  SetDefaultLanguageInput,
} from '@shared/service-proxies/service-proxies';
import { Router } from '@angular/router';
import { CreateOrEditLanguageComponent } from '@app/admin/languages/create-or-edit-language/create-or-edit-language.component';
import * as _ from 'lodash';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-languages',
  templateUrl: './languages.component.html',
  styles: [],
})
export class LanguagesComponent extends PagedListingComponentBase<LanguageListDto> {
  defaultLanguageName: string;

  constructor(injector: Injector, private _languageService: LanguageServiceProxy, private router: Router) {
    super(injector);
  }

  changeTexts(language: LanguageListDto): void {
    const self = this;
    setTimeout(() => {
      self.router.navigate(['app/admin/languagetexts', { lang: language.name }]);
    }, 300);
  }

  setAsDefaultLanguage(language: LanguageListDto): void {
    const input = new SetDefaultLanguageInput();
    input.name = language.name;
    this._languageService.setDefaultLanguage(input).subscribe(() => {
      this.refresh();
      this.notify.success(this.l('SuccessfullySaved'));
    });
  }

  // deleteLanguage(language: LanguageListDto): void {
  //   this.message.confirm(
  //     this.l('LanguageDeleteWarningMessage', language.displayName),
  //     isConfirmed => {
  //       if (isConfirmed) {
  //         this.languageService.deleteLanguage(language.id).subscribe(() => {
  //           this.refresh();
  //           this.notify.success(this.l('SuccessfullyDeleted'));
  //         });
  //       }
  //     },
  //   );
  // }

  createOrEditLanguage(languageId?: number): void {
    this.modalHelper.open(CreateOrEditLanguageComponent, { languageId: languageId }).subscribe(res => {
      if (res) {
        this.refresh();
      }
    });
  }

  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: () => void): void {
    this._languageService
      .getLanguages()
      .pipe(finalize(() => finishedCallback()))
      .subscribe(result => {
        this.dataList = result.items;
        this.defaultLanguageName = result.defaultLanguageName;
        this.pageSize = result.items.length;
        //      this.showPaging(result);
      });
  }

  /**
   * 删除
   * @param language 语言实体
   */
  delete(language: LanguageListDto): void {
    this._languageService.deleteLanguage(language.id).subscribe(() => {
      this.refresh();
      this.notify.success(this.l('SuccessfullyDeleted'));
    });
  }

  /**
   * 批量删除
   */
  batchDelete(): void {
    const selectCount = this.selectedDataItems.length;
    if (selectCount <= 0) {
      abp.message.warn(this.l('PleaseSelectAtLeastOneItem'));
      return;
    }

    abp.message.confirm(this.l('ConfirmDeleteXItemsWarningMessage', selectCount), undefined, res => {
      if (res) {
        const ids = _.map(this.selectedDataItems, 'id');
        this._languageService.batchDelete(ids).subscribe(() => {
          this.refresh();
          this.notify.success(this.l('SuccessfullyDeleted'));
        });
      }
    });
  }

  log(data: string): void {
    console.log(data);
  }
}

<page-header [title]="l('Languages')"></page-header>

<nz-card [nzBordered]="false">
  <div class="mb-md">
    <!-- 模糊搜索框 -->
    <nz-row nzGutter="8">
      <nz-col nzSm="24">
        <nz-form-item>
          <nz-form-control>
            <nz-input-group nzSearch [nzAddOnAfter]="suffixSearchButton">
              <input type="text" nz-input [(ngModel)]="filterText" (keyup.enter)="refresh()" name="filterText"
                [placeholder]="l('SearchWithThreeDot')" />
              <ng-template #suffixSearchButton>
                <button nz-button nzType="primary" nzSearch type="submit">
                  <!-- <i class="iconfont icon-search"></i> -->
                  <i class="iconfont icon-search"></i>
                </button>
              </ng-template>
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
      </nz-col>
    </nz-row>
  </div>

  <!-- 操作部分 -->
  <nz-row nzGutter="8">
    <nz-col nzMd="24" nzSm="24" class="btn-gutter">
      <button nz-button [nzType]="'primary'" *ngIf="isGranted('Pages.Administration.Languages.Create')"
        (click)="createOrEditLanguage()">
        <i class="iconfont icon-plus"></i>
        <span>
          {{ l('CreateNewLanguage') }}
        </span>
      </button>
      <button nz-button [nzType]="'danger'" *ngIf="isGranted('Pages.Administration.Languages.Delete')"
        (click)="batchDelete()">
        <i class="iconfont icon-delete"></i>
        <span>
          {{ l('BatchDelete') }}
        </span>
      </button>
    </nz-col>
  </nz-row>

  <!-- 复选框提示的内容数据部分 -->
  <table-checkbox-panel [selectLength]="selectedDataItems.length" (onClear)="restCheckStatus(dataList)"
    (onRefresh)="refreshGoFirstPage()"></table-checkbox-panel>

  <!-- 实体的表格内容 -->


  <nz-table #ajaxTable [nzData]="dataList" [nzTotal]="totalItems" [nzLoading]="isTableLoading"
    (nzPageIndexChange)="pageNumberChange()" (nzPageSizeChange)="refresh()" [nzShowSizeChanger]="true"
    [nzShowQuickJumper]="true" [nzFrontPagination]="false" [nzShowPagination]="false" [nzNoResult]="noDataTemplate">
    <!-- 暂无数据组件 -->
    <ng-template #noDataTemplate>
      <no-data></no-data>
    </ng-template>

    <thead (nzSortChange)="gridSort($event)">
      <tr>
        <th nzShowCheckbox [(nzChecked)]="allChecked" [nzDisabled]="allCheckboxDisabled"
          [nzIndeterminate]="checkboxIndeterminate" (nzCheckedChange)="checkAll($event)"></th>

        <th nz-th>
          <span>{{ l('Name') }}</span>
        </th>
        <th nz-th>
          <span>{{ l('Code') }}</span>
        </th>
        <th nzShowSort nzSortKey="creationTime" class="text-center">
          <span>{{ l('CreationTime') }}</span>
        </th>
        <th nzShowSort nzSortKey="isEmailConfirmed" class="text-center">
          <span>{{ l('Enabled') }}</span>
        </th>

        <th nzWidth="280px" class="text-center">
          <span>{{ l('Actions') }}</span>
        </th>
      </tr>
    </thead>
    <!-- 表格内容 -->
    <tbody nz-tbody>
      <tr *ngFor="let item of ajaxTable.data">
        <!-- 全选框 -->
        <td nzShowCheckbox [(nzChecked)]="item.checked" (nzCheckedChange)="refreshCheckStatus(dataList)"></td>

        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.displayName">
              <!-- <i class="anticon {{item.icon}}"></i> -->
              <i class="iconfont  {{ item.icon }}"></i>
              {{ item.displayName }}
              <span *ngIf="defaultLanguageName === item.name">({{ l('Default') }})</span></span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.name">
              {{ item.name }}
            </span>
          </ellipsis>
        </td>
        <td class="text-center">
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.creationTime | _moment">
              {{ item.creationTime | _moment }}
            </span>
          </ellipsis>
        </td>
        <td class="text-center" [innerHTML]="!item.isDisabled | yn"></td>

        <td>
          <!-- 编辑 -->
          <ng-container
            *ngIf="isGranted('Pages.Administration.Languages.Edit') && item.tenantId === appSession.tenantId">
            <a (click)="createOrEditLanguage(item.id)">
              <i class="iconfont icon-edit mr-sm"></i>
              <span>{{ l('Edit') }}</span>
            </a>
            <nz-divider nzType="vertical"></nz-divider>
          </ng-container>
          <!-- 删除 -->
          <ng-container
            *ngIf="isGranted('Pages.Administration.Languages.Delete') && item.tenantId === appSession.tenantId">
            <a nz-popconfirm [nzPopconfirmTitle]="l('ConfirmDeleteWarningMessage')" (nzOnConfirm)="delete(item)"
              [nzOkText]="l('Ok')" [nzCancelText]="l('Cancel')">
              <i class="iconfont icon-delete mr-sm"></i>
              <span>{{ l('Delete') }}</span>
            </a>
          </ng-container>

          <ng-container
            *ngIf="isGrantedAny('Pages.Administration.Languages.ChangeTexts', 'Pages.Administration.Languages.Edit')">
            <nz-divider nzType="vertical"></nz-divider>

            <a nz-dropdown [nzDropdownMenu]="menu">
              {{ l('Actions') }}
              <!-- <i nz-icon nzType="down"></i> -->
              <i class="iconfont icon-down"></i>
            </a>
            <nz-dropdown-menu #menu="nzDropdownMenu">
              <ul nz-menu>
                <li nz-menu-item *ngIf="isGranted('Pages.Administration.Languages.ChangeTexts')">
                  <a (click)="changeTexts(item)">{{ l('ChangeTexts') }}</a>
                </li>
                <li nz-menu-item *ngIf="isGranted('Pages.Administration.Languages.Edit')">
                  <a (click)="setAsDefaultLanguage(item)">{{ l('SetAsDefaultLanguage') }}</a>
                </li>
              </ul>
            </nz-dropdown-menu>
          </ng-container>
        </td>
      </tr>
    </tbody>
  </nz-table>

</nz-card>

// src/yoyocmstemplate-vue/src/app/admin/languages/languages.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('Languages')"></page-header>
        <a-card :bordered="false">
            <a-form :layout="'vertical'" @submit.prevent="getData">
                <a-row :gutter="8">
                    <!-- 搜索 -->
                    <a-col :sm="24">
                        <a-form-item>
                            <a-input-search
                                name="filterText"
                                :placeholder="l('SearchWithThreeDot')"
                                @search="getData"
                                enterButton
                                v-model="filterText"
                                v-decorator="['filterText']" />
                        </a-form-item>
                    </a-col>
                </a-row>
            </a-form>
            <!-- 操作部分 -->
            <a-row :gutter="8">
                <a-col :md="20" :sm="12">
                    <a-button
                        :type="'primary'"
                        v-if="isGranted('Pages.Administration.Languages.Create')"
                        @click="createOrEditLanguage()">
                        <a-icon type="plus" />
                        <span>{{l("CreateNewLanguage")}}</span>
                    </a-button>
                    <a-button :type="'danger'" v-if="isGranted('Pages.Administration.Languages.Delete')" @click="batchDelete">
                        <a-icon type="delete" />
                        <span>{{l("BatchDelete")}}</span>
                    </a-button>
                </a-col>
            </a-row>

            <!-- 数据部分 -->
            <div class="my-md">
                <a-alert :type="'info'" :showIcon="true">
                    <template slot="message">
                        <span v-html="l('GridSelectedXItemsTips',selectedRowKeys.length)"></span>
                        <a @click="restCheckStatus()" class="ml-md">{{l('ClearEmpty')}}</a>
                        <a-divider type="vertical"></a-divider>
                        <a @click="getData()">{{l('Refresh')}}</a>
                    </template>
                </a-alert>
            </div>

            <a-row>
                <a-table
                    class="list-table"
                    @change="getData"
                    :pagination="false"
                    :rowSelection="{selectedRowKeys: selectedRowKeys,onChange: onSelectChange}"
                    :columns="columns"
                    :rowKey="tableDatas => tableDatas.id"
                    :dataSource="tableData">
                    <p class="isDisabledStr" slot="isDisabledStr" slot-scope="text, record">
                        <a-icon v-if="!record.isDisabled" style="color:#1890ff" type="check" />
                        <a-icon v-if="record.isDisabled" style="color:#1890ff" type="close" />
                    </p>
                    <span slot="actions" slot-scope="text, record">
                        <!-- 修改 -->
                        <a class="table-edit" @click="createOrEditLanguage(record.id)" v-if="isGranted('Pages.Administration.Languages.Edit') && record.tenantId === tenantId">
                            <a-icon type="edit" />{{ l('Edit') }}</a>
                        <!-- 删除 -->
                        <a-popconfirm placement="top" v-if="isGranted('Pages.Administration.Languages.Delete') && record.tenantId === tenantId" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="deleteItem(record)">
                            <template slot="title">
                                {{ l('ConfirmDeleteWarningMessage') }}
                            </template>
                            <a class="table-delete">
                                <a-icon type="delete" />{{ l('Delete') }}</a>
                        </a-popconfirm>
                        <!-- 更多 -->
                        <a-dropdown v-if="isGrantedAny('Pages.Administration.Languages.ChangeTexts', 'Pages.Administration.Languages.Edit')">
                            <a class="ant-dropdown-link" @click="e => e.preventDefault()">
                                {{ l('Actions') }}
                                <a-icon type="down" />
                            </a>
                            <a-menu slot="overlay">
                                <a-menu-item
                                    v-if="isGranted('Pages.Administration.Languages.ChangeTexts')"
                                    @click="changeTexts(record)">
                                    <a href="javascript:;">
                                        <span>{{ l('ChangeTexts') }}</span>
                                    </a>
                                </a-menu-item>
                                <a-menu-item
                                    v-if="isGranted('Pages.Administration.Languages.Edit')"
                                    @click="setAsDefaultLanguage(record)">
                                    <a href="javascript:;">
                                        <span>{{ l('SetAsDefaultLanguage') }}</span>
                                    </a>
                                </a-menu-item>
                            </a-menu>
                        </a-dropdown>
                    </span>
                </a-table>
            </a-row>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { ModalHelper } from "@/shared/helpers";
import { LanguageServiceProxy } from "@/shared/service-proxies";
import CreateOrEditLanguage from "./create-or-edit-language/create-or-edit-language";
import moment from "moment";
import { appSessionService } from "@/shared/abp";

export default {
    mixins: [AppComponentBase],
    name: "languages",
    components: {
        CreateOrEditLanguage
    },
    data() {
        return {
            _languageServiceProxy: null,
            // 选中的权限过滤
            selectedPermission: [],
            // 表格
            columns: [
                {
                    title: this.l("Name"),
                    dataIndex: "displayNameStr",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "displayNameStr" }
                },
                {
                    title: this.l("Code"),
                    dataIndex: "name",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "name" }
                },
                {
                    title: this.l("CreationTime"),
                    dataIndex: "creationTimeStr",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "creationTimeStr" }
                },
                {
                    title: this.l("Enabled"),
                    dataIndex: "isDisabledStr",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "isDisabledStr" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "actions",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "actions" }
                }
            ],
            // 选择多少项
            selectedRowKeys: [],
            selectedRows: [],
            // 请求参数
            filterText: undefined,
            tableData: [],
            // loading
            spinning: false,
            tenantId: ""
        };
    },
    created() {
        this._languageServiceProxy = new LanguageServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.tenantId = appSessionService.tenantId;
        console.log(this.tenantId);
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._languageServiceProxy
                .getLanguages(this.filterText)
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    console.log(res);
                    this.tableData = res.items;
                    this.tableData.map(item => {
                        item.creationTimeStr = item.creationTime
                            ? moment(item.creationTime).format(
                                  "YYYY-MM-DD HH:mm:ss"
                              )
                            : "-";
                        item.displayNameStr =
                            item.name === res.defaultLanguageName
                                ? item.displayName + "(默认)"
                                : item.displayName;
                    });
                });
        },
        /**
         * 创建编辑语言
         */
        createOrEditLanguage(id) {
            ModalHelper.create(
                CreateOrEditLanguage,
                { id: id },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * table选择事件
         */
        onSelectChange(selectedRowKeys, selectedRows) {
            this.selectedRowKeys = selectedRowKeys;
            this.selectedRows = selectedRows;
            console.log(this.selectedRows);
        },
        /**
         * 批量删除
         */
        batchDelete(e) {
            const selectCount = this.selectedRowKeys.length;
            if (selectCount <= 0) {
                abp.message.warn(this.l("PleaseSelectAtLeastOneItem"));
                return;
            }
            this.message.confirm(
                this.l("ConfirmDeleteXItemsWarningMessage", selectCount),
                res => {
                    if (res) {
                        const ids = _.map(this.selectedRowKeys);
                        console.log(ids);
                        this.spinning = true;
                        this._languageServiceProxy
                            .batchDelete(ids)
                            .finally(() => {
                                this.spinning = false;
                            })
                            .then(() => {
                                this.getData();
                                this.$notification["success"]({
                                    message: this.l("SuccessfullyDeleted")
                                });
                            });
                    }
                }
            );
        },
        /**
         * 单个删除
         */
        deleteItem(item) {
            this.spinning = true;
            this._languageServiceProxy
                .deleteLanguage(item.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(() => {
                    this.getData();
                    this.$notification["success"]({
                        message: this.l("SuccessfullyDeleted")
                    });
                });
        },
        /**
         * 清空选择
         */
        restCheckStatus() {
            this.selectedRowKeys = [];
        },
        /**
         * 设为默认语言
         */
        setAsDefaultLanguage(item) {
            this.spinning = true;
            this._languageServiceProxy
                .setDefaultLanguage({
                    name: item.name
                })
                .finally(() => {
                    this.spinning = false;
                })
                .then(() => {
                    this.getData();
                    this.$notification["success"]({
                        message: this.l("SuccessfullySaved")
                    });
                });
        },
        /**
         * 更换文本
         */
        changeTexts(item) {
            setTimeout(() => {
                this.$router.push({
                    path: "/app/admin/languagetexts",
                    query: { lang: item.name }
                });
            }, 300);
        }
    }
};
</script>

<style scoped lang="less">
.subscriptionEndUtc {
    text-align: center;
}
// table
.list-table {
    i {
        margin-right: 10px;
    }
}
.pagination {
    margin: 10px auto;
    text-align: right;
}
.table-edit {
    .anticon {
        margin-right: 10px;
    }
}
.table-delete,
.ant-dropdown-link {
    margin-left: 20px;
}
</style>
