// src/yoyocmstemplate-vue/src/layout/default/header/header.vue
<template>
    <div class="ant-layout-header alain-pro__header">
        <!-- 左边 -->
        <div class="d-flex align-items-center">
            <!-- Menu -->
            <div @click="toggleCollapsedSidebar()" class="alain-pro__header-item alain-pro__header-trigger">
                <a-icon type="menu-fold" v-show="!collapsed"/>
                <a-icon type="menu-unfold" v-show="collapsed"/>
            </div>
            <!-- Github Page -->
            <a class="alain-pro__header-item alain-pro__header-trigger"
               href="https://gitee.com/aiabpedu/LTMCompanyName.YoyoCmsTemplate" target="_blank">
                <a-icon type="github"/>
            </a>
            <!-- 52abp官网 -->
            <a class="alain-pro__header-item alain-pro__header-trigger" href="https://www.52abp.com">
                <a-icon type="link"/>
            </a>

        </div>

        <!-- 右边 -->
        <div class="alain-pro__header-right">
            <header-i18n class="alain-pro__header-item"></header-i18n>
            <header-notifications class="alain-pro__header-item mr-sm"></header-notifications>
            <header-settings class="alain-pro__header-item hidden-xs"></header-settings>
            <header-user class="hidden-xs alain-pro__header-item"></header-user>
        </div>
    </div>


</template>

<script>
    import {HeaderI18n, HeaderNotifications, HeaderSettings, HeaderUser} from './components';
    import {layoutService} from '@/shared/common';


    export default {
        name: "layout-header",
        components: {
            HeaderI18n,
            HeaderNotifications,
            HeaderSettings,
            HeaderUser
        },
        data() {
            return {

            }
        },
        computed: {
            collapsed: {
                get() {
                    return layoutService.data.collapsed;
                },
                set(val) {
                    layoutService.data.collapsed = val;
                }
            }
        },
        methods: {
            toggleCollapsedSidebar() {
                this.collapsed = !this.collapsed;
            }
        }
    }
</script>

<style scoped>

</style>

// src/yoyocmstemplate-angular/src/layout/default/header/header.component.ts
import { Component, Injector } from '@angular/core';
import { SettingsService } from '@delon/theme';
import { SampleComponentBase } from '@shared/component-base';

@Component({
  selector: 'layout-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent extends SampleComponentBase {
  searchToggleStatus: boolean;
  constructor(injector: Injector, public settings: SettingsService) {
    super(injector);
  }

  toggleCollapsedSidebar() {
    this.settings.setLayout('collapsed', !this.settings.layout.collapsed);
  }

  searchToggleChange() {
    this.searchToggleStatus = !this.searchToggleStatus;
  }
}

<div class="d-flex align-items-center">
  <!-- Menu -->
  <div class="alain-pro__header-item alain-pro__header-trigger" (click)="toggleCollapsedSidebar()">
    <i
      class="iconfont"
      [ngClass]="settings.layout.collapsed ? 'icon-indent ' : 'icon-outdent'"
      style="font-size: 18px"
    ></i>
  </div>
  <!-- Github Page -->
  <a class="alain-pro__header-item alain-pro__header-trigger" href="http://code.52abp.com/commercial" target="_blank">
    <i class="iconfont icon-github-fill" style="font-size: 20px"></i>
  </a>
  <!-- 52abp官网 -->
  <a class="alain-pro__header-item alain-pro__header-trigger" href="https://www.52abp.com">
    <i class="iconfont icon-link" style="font-size: 20px"></i>
  </a>
</div>

<!-- 右侧菜单栏 -->
<div class="alain-pro__header-right">
  <header-i18n class="alain-pro__header-item"></header-i18n>
  <header-notifications class="alain-pro__header-item mr-sm"></header-notifications>

  <!-- Settings -->
  <div class="alain-pro__nav-item mr-sm" nz-dropdown nzPlacement="bottomRight" [nzDropdownMenu]="dropdownMenu">
    <i class="iconfont icon-setting"></i>
  </div>

  <nz-dropdown-menu class="hidden-xs alain-pro__header-item" #dropdownMenu="nzDropdownMenu">
    <div nz-menu style="width: 200px">
      <div nz-menu-item>
        <header-fullscreen></header-fullscreen>
      </div>
      <div
        nz-menu-item
        (click)="this.settings.setLayout('theme', this.settings.layout.theme === 'dark' ? 'light' : 'dark')"
      >
        <div>
          <i class="iconfont icon-bg-colors"></i>
          {{ l('SwitchTheme') }}
        </div>
      </div>
      <div nz-menu-item>
        <header-storage></header-storage>
      </div>
    </div>
  </nz-dropdown-menu>
  <header-user class="hidden-xs alain-pro__header-item"></header-user>
</div>
