// src/yoyocmstemplate-angular/src/app/admin/audit-logs/audit-logs-detail/audit-logs-detail.component.ts
import { Component, OnInit, Input, Injector } from '@angular/core';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import { AuditLogListDto } from '@shared/service-proxies/service-proxies';
import * as moment from 'moment';


@Component({
  selector: 'app-audit-logs-detail',
  templateUrl: './audit-logs-detail.component.html',
  styles: []
})
export class AuditLogsDetailComponent extends ModalComponentBase {

  @Input() auditLog: AuditLogListDto;

  constructor(
    injector: Injector
  ) {
    super(injector);
  }

  getExecutionTime(): string {
    const self = this;
    return moment(self.auditLog.executionTime).fromNow() + ' (' + moment(self.auditLog.executionTime).format('YYYY-MM-DD HH:mm:ss') + ')';
  }

  getDurationAsMs(): string {
    const self = this;
    return self.l('Xms', self.auditLog.executionDuration);
  }

  getFormattedParameters(): string {
    const self = this;
    try {
      const json = JSON.parse(self.auditLog.parameters);
      return JSON.stringify(json, null, 4);
    } catch (e) {
      return self.auditLog.parameters;
    }
  }

}

<div class="modal-header">
  <div class="modal-title" *ngIf="auditLog">{{l('AuditLogDetail')}}</div>
</div>

<div>
  <!-- 用户信息 -->
  <div>
    <h3>{{l("UserInformations")}}</h3>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("UserName")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{auditLog.userName}}</span>
      </div>
    </div>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("IpAddress")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{auditLog.clientIpAddress}}</span>
      </div>
    </div>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("Client")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{auditLog.clientName}}</span>
      </div>
    </div>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("Browser")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{auditLog.browserInfo}}</span>
      </div>
    </div>
    <!-- <div nz-row [nzGutter]="8" *ngIf="auditLog.impersonatorUserId">
      <div nz-col [nzSpan]="4">
        <label></label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{AuditLogImpersonatedOperationInfo}}</span>
      </div>
    </div> -->
  </div>

  <!-- 操作信息 -->
  <div>
    <h3>{{l("ActionInformations")}}</h3>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("Service")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{auditLog.serviceName}}</span>
      </div>
    </div>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("Action")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{auditLog.methodName}}</span>
      </div>
    </div>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("Time")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{getExecutionTime()}}</span>
      </div>
    </div>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("Duration")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{getDurationAsMs()}}</span>
      </div>
    </div>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <label>{{l("Parameters")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <pre lang="js">{{getFormattedParameters()}}</pre>
      </div>
    </div>
  </div>

  <!-- 自定义数据 -->
  <div>
    <h3>{{l("CustomData")}}</h3>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="8">
        <label> {{l("None")}}:</label>
      </div>
      <div nz-col [nzSpan]="10">
        <span>{{auditLog.customData}}</span>
      </div>
    </div>
  </div>

  <!-- 错误状态 -->
  <div>
    <h3>{{l("ErrorState")}}</h3>
    <div nz-row [nzGutter]="8">
      <div nz-col [nzSpan]="4">
        <nz-badge *ngIf="auditLog.exception " [nzStatus]="'error'" [nzText]="l('Error')"></nz-badge>
        <nz-badge *ngIf="!auditLog.exception " [nzStatus]="'success'" [nzText]="l('Success')"></nz-badge>
      </div>
    </div>
  </div>

</div>
<!-- 功能按钮 -->
<div class="modal-footer">
  <button nz-button type="button" (click)="close()">
    {{l("Cancel")}}
  </button>
</div>

// src/yoyocmstemplate-vue/src/app/admin/audit-logs/audit-logs-detail/audit-logs-detail.vue
<template>
    <a-spin :spinning="spinning">
        <!-- 标题 -->
        <div class="modal-header">
            <div class="modal-title">
                <span v-if="auditLog">{{ l('AuditLogDetail') }}</span>
            </div>
        </div>
        <!-- 用户信息 -->
        <h3>{{l("UserInformations")}}</h3>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("UserName")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.userName }}</div>
            </a-col>
        </a-row>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("IpAddress")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.clientIpAddress }}</div>
            </a-col>
        </a-row>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("Client")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.clientName }}</div>
            </a-col>
        </a-row>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("Browser")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.browserInfo }}</div>
            </a-col>
        </a-row>

        <!-- 操作信息 -->
        <br>
        <h3>{{l("ActionInformations")}}</h3>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("Service")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.serviceName }}</div>
            </a-col>
        </a-row>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("Action")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.methodName }}</div>
            </a-col>
        </a-row>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("Time")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ getExecutionTime() }}</div>
            </a-col>
        </a-row>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("Duration")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.executionDuration }}ms</div>
            </a-col>
        </a-row>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("Parameters")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.parameters }}</div>
            </a-col>
        </a-row>

        <!-- 数据 -->
        <br>
        <h3>{{l("CustomData")}}</h3>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="4">
                <div class="gutter-box">{{l("None")}}:</div>
            </a-col>
            <a-col class="gutter-row" :span="10">
                <div class="gutter-box">{{ auditLog.customData }}</div>
            </a-col>
        </a-row>

        <!-- 错误状态 -->
        <br>
        <h3>{{l("ErrorState")}}</h3>
        <a-row :gutter="8">
            <a-col class="gutter-row" :span="10">
                <p v-if="!auditLog.exception">
                    <a-badge status="success" />{{ l('Success') }}</p>
                <p v-if="auditLog.exception">
                    <a-badge status="error" />{{ l('Error') }}</p>
            </a-col>
        </a-row>

        <!-- 按钮 -->
        <div class="modal-footer">
            <a-button :disabled="saving" @click="close()" type="button">
                <a-icon type="close-circle" />
                {{ l('Cancel') }}
            </a-button>
        </div>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { ModalComponentBase } from "@/shared/component-base";
import moment from "moment";

export default {
    name: "audit-logs-detail",
    mixins: [AppComponentBase, ModalComponentBase],
    data() {
        return {
            spinning: false
        };
    },
    created() {
        this.fullData(); // 模态框必须,填充数据到data字段
    },
    methods: {
        // 时间
        getExecutionTime() {
            return (
                moment(this.auditLog.executionTime).fromNow() +
                " (" +
                moment(this.auditLog.executionTime).format(
                    "YYYY-MM-DD HH:mm:ss"
                ) +
                ")"
            );
        }
    }
};
</script>

<style scoped>
</style>
