// src/yoyocmstemplate-vue/src/app/admin/audit-logs/audit-logs.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('AuditLogs')"></page-header>
        <a-card :bordered="false">
            <a-form :layout="'vertical'" @submit.prevent="getData">
                <a-row :gutter="8">
                    <!-- 用户名 -->
                    <a-col :sm="24">
                        <a-form-item :label="l('UserName')">
                            <a-input-search
                                name="username"
                                :placeholder="l('UserName')"
                                @search="getData"
                                enterButton
                                v-model="username"
                                v-decorator="['username']" />
                        </a-form-item>
                    </a-col>
                    <!-- 错误状态 -->
                    <a-col :sm="12">
                        <a-form-item :label="l('ErrorState')">
                            <a-select v-model="hasException">
                                <a-select-option value="">{{ l('All') }}</a-select-option>
                                <a-select-option value="false">{{ l('Success') }}</a-select-option>
                                <a-select-option value="true">{{ l('HasError') }}</a-select-option>
                            </a-select>
                        </a-form-item>
                    </a-col>
                    <!--日期范围 -->
                    <a-col :sm="12">
                        <a-form-item :label="l('DateRange')">
                            <a-range-picker :placeholder="[l('StartDateTime'), l('EndDateTime')]" v-model="startToEndDate" />
                        </a-form-item>
                    </a-col>
                    <!-- 服务 -->
                    <a-col :sm="12" v-if="advancedFiltersVisible">
                        <a-form-item :label="l('Service')">
                            <a-input
                                :placeholder="l('Service')"
                                v-model="serviceName"
                                v-decorator="['serviceName']" />
                        </a-form-item>
                    </a-col>
                    <!-- 持续时间 -->
                    <a-col :sm="12" v-if="advancedFiltersVisible">
                        <a-form-item :label="l('Service')">
                            <a-input-number id="MinExecutionDuration" :min="0" :placeholder="l('MinExecutionDuration')" style="text-align: center; width: 152px;" :max="86400000" :step="1" v-model="minExecutionDuration" />
                            ～
                            <a-input-number id="MaxExecutionDuration" :min="0" :placeholder="l('MaxExecutionDuration')" style="text-align: center; width: 152px;" :max="86400000" :step="1" v-model="maxExecutionDuration" />
                        </a-form-item>
                    </a-col>
                    <!-- 方法名 -->
                    <a-col :sm="12" v-if="advancedFiltersVisible">
                        <a-form-item :label="l('MethodName')">
                            <a-input
                                :placeholder="l('MethodName')"
                                v-model="methodName"
                                v-decorator="['methodName']" />
                        </a-form-item>
                    </a-col>
                    <!-- 浏览器 -->
                    <a-col :sm="12" v-if="advancedFiltersVisible">
                        <a-form-item :label="l('Browser')">
                            <a-input
                                :placeholder="l('Browser')"
                                v-model="browserInfo"
                                v-decorator="['browserInfo']" />
                        </a-form-item>
                    </a-col>
                    <!-- -->
                </a-row>
            </a-form>
            <!-- 操作部分 -->
            <a-row :gutter="8">
                <a-col :md="20" :sm="12">
                </a-col>
                <!-- 显示暴击过滤 -->
                <a-col :md="4" :sm="12" :offset="20" class="text-right">
                    <a @click="advancedFiltersVisible=!advancedFiltersVisible">
                        {{advancedFiltersVisible ? l('HideAdvancedFilters') : l('ShowAdvancedFilters')}}
                        <a-icon :type="advancedFiltersVisible ? 'up' : 'down'" />
                    </a>
                </a-col>
            </a-row>
            <!-- table -->
            <a-row class="table--container">
                <a-table
                    class="list-table"
                    @change="getData"
                    :pagination="false"
                    :columns="columns"
                    :rowKey="tableDatas => tableDatas.id"
                    :dataSource="tableData">
                    <!-- 异常 -->
                    <p class="roles" slot="exceptionType" slot-scope="text, record">
                        <a-icon v-if="record.exception" class="text-warning" type="exclamation-circle" />
                        <a-icon v-if="!record.exception" class="text-green" type="check-circle" />
                    </p>
                    <span slot="actions" slot-scope="text, record">
                        <!-- 查看详情 -->
                        <a class="table-edit" @click="getDetails(record)">
                            <a-icon type="search" />{{ l('ViewDetails') }}</a>
                    </span>
                </a-table>
                <a-pagination
                    class="pagination"
                    size="middle"
                    :total="totalItems"
                    showSizeChanger
                    showQuickJumper
                    :showTotal="showTotalFun"
                    @change="onChange"
                    @showSizeChange="showSizeChange" />
            </a-row>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { ModalHelper } from "@/shared/helpers";
import { AuditLogServiceProxy } from "@/shared/service-proxies";
import AuditLogsDetails from "./audit-logs-detail/audit-logs-detail";
import moment from "moment";

export default {
    mixins: [AppComponentBase],
    name: "audit-logs",
    components: {
        AuditLogsDetails
    },
    data() {
        return {
            // 是否显示高级过滤
            advancedFiltersVisible: false,
            // 表格
            columns: [
                {
                    title: this.l("Time"),
                    dataIndex: "executionTimeStr",
                    sorter: true,
                    align: "executionTimeStr",
                    width: 100,
                    scopedSlots: { customRender: "executionTimeStr" }
                },
                {
                    title: this.l("UserName"),
                    dataIndex: "userName",
                    align: "center",
                    scopedSlots: { customRender: "userName" }
                },
                {
                    title: this.l("Service"),
                    dataIndex: "serviceName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "serviceName" }
                },
                {
                    title: this.l("Action"),
                    dataIndex: "methodName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "methodName" }
                },
                {
                    title: this.l("Duration"),
                    dataIndex: "executionDuration",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "executionDuration" }
                },
                {
                    title: this.l("IpAddress"),
                    dataIndex: "clientIpAddress",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "clientIpAddress" }
                },
                {
                    title: this.l("Client"),
                    dataIndex: "clientName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "clientName" }
                },
                {
                    title: this.l("Browser"),
                    dataIndex: "browserInfo",
                    align: "center",
                    width: 100,
                    scopedSlots: { customRender: "browserInfo" }
                },
                {
                    title: this.l("ExceptionType"),
                    dataIndex: "exceptionType",
                    align: "center",
                    scopedSlots: { customRender: "exceptionType" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "actions",
                    align: "center",
                    scopedSlots: { customRender: "actions" }
                }
            ],
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { sorting: "", maxResultCount: 10, skipCount: 0 },
            selectedRows: [],
            tableData: [],
            // loading
            spinning: false,
            // 用户名
            username: "",
            // 错误状态
            hasException: "",
            // 日期范围
            startToEndDate: [],
            // 服务
            serviceName: "",
            // 持续时间
            minExecutionDuration: "",
            maxExecutionDuration: "",
            // 方法名
            methodName: "",
            // 浏览器
            browserInfo: "",
            _auditLogServiceProxy: ""
        };
    },
    created() {
        this._auditLogServiceProxy = new AuditLogServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            console.log(this.startToEndDate);
            this.spinning = true;
            this._auditLogServiceProxy
                .getPagedAuditLogs(
                    this.startToEndDate[0] === null
                        ? undefined
                        : this.startToEndDate[0],
                    this.startToEndDate[1] === null
                        ? undefined
                        : this.startToEndDate[1],
                    this.username,
                    this.serviceName,
                    this.methodName,
                    this.browserInfo,
                    this.hasException,
                    this.minExecutionDuration,
                    this.maxExecutionDuration,
                    this.request.sorting,
                    this.request.maxResultCount,
                    this.request.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.tableData = res.items;
                    this.tableData.map(item => {
                        item.executionTimeStr = item.executionTime
                            ? moment(item.executionTime).format(
                                  "YYYY-MM-DD HH:mm:ss"
                              )
                            : "-";
                    });
                    this.totalItems = res.totalCount;
                    this.totalPages = Math.ceil(
                        res.totalCount / this.request.maxResultCount
                    );
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                    console.log(this.tableData);
                });
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        },
        /**
         * 查看详情
         */
        getDetails(item) {
            ModalHelper.create(
                AuditLogsDetails,
                { auditLog: item },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                console.log(res);
                if (res) {
                    this.getData();
                }
            });
        }
    }
};
</script>

<style scoped lang="less">
.subscriptionEndUtc {
    text-align: center;
}
// table
.list-table {
    i {
        margin-right: 10px;
    }
}
.pagination {
    margin: 10px auto;
    text-align: right;
}
.table-edit {
    .anticon {
        margin-right: 10px;
    }
}
.table-delete,
.ant-dropdown-link {
    margin-left: 20px;
}
.table--container {
    margin-top: 20px;
}
</style>

// src/yoyocmstemplate-angular/src/app/admin/audit-logs/audit-logs.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import { AuditLogListDto, AuditLogServiceProxy } from '@shared/service-proxies/service-proxies';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import { AuditLogsDetailComponent } from '@app/admin/audit-logs/audit-logs-detail/audit-logs-detail.component';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-audit-logs',
  templateUrl: './audit-logs.component.html',
  styles: [],
})
export class AuditLogsComponent extends PagedListingComponentBase<AuditLogListDto> {
  //  <nz-range-picker [(ngModel)]="dateRange" (ngModelChange)="onChange($event)" nzShowTime></nz-range-picker>
  startToEndDate = []; // [ new Date(), addDays(new Date(), 3) ];
  advancedFiltersVisible = false;
  username: string;
  serviceName: string;
  methodName: string;
  browserInfo: string;
  hasException: boolean = undefined;
  minExecutionDuration: number;
  maxExecutionDuration: number;

  errorState = [
    { label: this.l('All'), value: '' },
    { label: this.l('Success'), value: 'false' },
    { label: this.l('HasError'), value: 'true' },
  ];

  constructor(injector: Injector, private auditLogService: AuditLogServiceProxy) {
    super(injector);
  }

  fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    let startData;
    let endData;
    if (this.startToEndDate.length === 2) {
      startData = this.startToEndDate[0] === null ? undefined : this.startToEndDate[0];
      endData = this.startToEndDate[1] === null ? undefined : this.startToEndDate[1];
    }

    this.auditLogService
      .getPagedAuditLogs(
        startData,
        endData,
        this.username,
        this.serviceName,
        this.methodName,
        this.browserInfo,
        this.hasException,
        this.minExecutionDuration,
        this.maxExecutionDuration,
        this.sorting,
        request.maxResultCount,
        request.skipCount,
      )
      .pipe(
        finalize(() => {
          finishedCallback();
        }),
      )
      .subscribe(result => {
        this.dataList = result.items;
        this.showPaging(result);
      });
  }

  protected delete(entity: AuditLogListDto): void {}

  //
  showDetails(item: AuditLogListDto): void {
    this.modalHelper.open(AuditLogsDetailComponent, { auditLog: item }).subscribe(result => {});
  }

  truncateStringWithPostfix(text: string, length: number): string {
    return abp.utils.truncateStringWithPostfix(text, length);
  }
}

<page-header [title]="l('AuditLogs')"></page-header>

<nz-card [nzBordered]="false">
  <!-- 检索表单 -->
  <form nz-form (ngSubmit)="refreshGoFirstPage()" class="mb-md">
    <nz-form-item nz-row nzGutter="8">
      <nz-form-label nz-col [nzSm]="2">
        {{ l('UserName') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="22">
        <nz-input-group nzSearch [nzAddOnAfter]="suffixButton">
          <input type="text" nz-input [(ngModel)]="username" name="UserName" [placeholder]="l('UserName')" />
          <ng-template #suffixButton>
            <button nz-button nzType="primary" nzSearch type="submit">
              <!-- <i class="iconfont icon-search"></i> -->
              <i class="iconfont icon-search "></i>
            </button>
          </ng-template>
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <!-- 错误状态 -->
    <nz-form-item nz-row nzGutter="8">
      <nz-form-label nz-col [nzSm]="2">
        {{ l('ErrorState') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="10">
        <nz-select [(ngModel)]="hasException" name="HasException" [nzPlaceHolder]="l('ErrorState')" nzAllowClear>
          <nz-option [nzLabel]="l('All')" nzValue=""></nz-option>
          <nz-option [nzLabel]="l('Success')" nzValue="false"></nz-option>
          <nz-option [nzLabel]="l('HasError')" nzValue="true"></nz-option>
        </nz-select>
      </nz-form-control>
      <nz-form-label nz-col [nzSm]="2">
        {{ l('DateRange') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="10">
        <nz-range-picker name="DateRange" [(ngModel)]="startToEndDate"
          [nzPlaceHolder]="[l('StartDateTime'), l('EndDateTime')]"></nz-range-picker>
      </nz-form-control>
    </nz-form-item>

    <nz-form-item nz-row nzGutter="8" *ngIf="advancedFiltersVisible">
      <nz-form-label nz-col [nzSm]="2">
        {{ l('Service') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="10">
        <input nz-input name="Service" [(ngModel)]="serviceName" [placeholder]="l('Service')" />
      </nz-form-control>

      <nz-form-label nz-col [nzSm]="2">
        {{ l('Duration') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="10">
        <nz-input-group nzCompact>
          <nz-input-number name="MinExecutionDuration" [(ngModel)]="minExecutionDuration"
            [nzPlaceHolder]="l('MinExecutionDuration')" [nzMin]="0" [nzMax]="86400000" [nzStep]="1"
            style="text-align: center; width: 152px;"></nz-input-number>
          <input type="text" disabled nz-input placeholder="~"
            style="width: 30px; border-left: 0px;pointer-events: none; background-color: rgb(255, 255, 255);" />
          <nz-input-number name="MaxExecutionDuration" [(ngModel)]="maxExecutionDuration"
            [nzPlaceHolder]="l('MaxExecutionDuration')" [nzMin]="0" [nzMax]="86400000" [nzStep]="1"
            style="text-align: center; border-left: 0px; width: 152px;"></nz-input-number>
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item nz-row nzGutter="8" *ngIf="advancedFiltersVisible">
      <nz-form-label nz-col [nzSm]="2">
        {{ l('MethodName') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="10">
        <input nz-input name="MethodName" [(ngModel)]="methodName" [placeholder]="l('MethodName')" />
      </nz-form-control>

      <nz-form-label nz-col [nzSm]="2">
        {{ l('Browser') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="10">
        <input nz-input name="BrowserInfo" [(ngModel)]="browserInfo" [placeholder]="l('Browser')" />
      </nz-form-control>
    </nz-form-item>
  </form>
  <!-- 操作部分 -->
  <nz-row nzGutter="8">
    <nz-col nzMd="20" nzSm="12" class="btn-gutter"> </nz-col>
    <nz-col nzMd="4" nzSm="12" class="text-right">
      <a (click)="advancedFiltersVisible = !advancedFiltersVisible">
        {{ advancedFiltersVisible ? l('HideAdvancedFilters') : l('ShowAdvancedFilters') }}

        <i class="iconfont" [ngClass]="advancedFiltersVisible ? 'icon-down ' : 'icon-up'"></i>
        <!-- <i nz-icon nzType="{{advancedFiltersVisible ? 'down' : 'up'}}" nzTheme="outline"></i> -->
      </a>
    </nz-col>
  </nz-row>
  <!-- 数据部分 -->

  <nz-table #ajaxTable nzShowSizeChanger [nzData]="dataList" [nzTotal]="totalItems" [(nzPageIndex)]="pageNumber"
    [(nzPageSize)]="pageSize" [nzLoading]="isTableLoading" (nzPageIndexChange)="pageNumberChange()"
    [nzPageSizeOptions]="PageSizeOptions" (nzPageSizeChange)="refresh()" [nzNoResult]="noDataTemplate"
    [nzShowTotal]="showTotalTemplate" [nzFrontPagination]="false">
    <!-- 暂无数据 -->
    <ng-template #noDataTemplate>
      <no-data></no-data>
    </ng-template>
    <!-- 分页信息显示 当前 1 页/共 3 页，共 5 条/显示 1-2 条 -->
    <ng-template #showTotalTemplate let-total let-range="range">
      {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
    </ng-template>
    <!-- 表头 -->

    <thead nz-thead (nzSortChange)="gridSort($event)">
      <tr>
        <th nz-th nzShowSort nzSortKey="executionTime">
          <span>{{ l('Time') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="userName">
          <span>{{ l('UserName') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="serviceName">
          <span>{{ l('Service') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="methodName">
          <span>{{ l('Action') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="executionDuration">
          <span>{{ l('Duration') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="ipAddress">
          <span>{{ l('IpAddress') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="clientIpAddress">
          <span>{{ l('Client') }}</span>
        </th>
        <th class="text-center" nzShowSort nzSortKey="browserInfo">
          <span>{{ l('Browser') }}</span>
        </th>
        <th nzWidth="100px" class="text-center">
          <span>{{ l('ExceptionType') }}</span>
        </th>

        <th nzWidth="120px" class="text-center">
          <span>{{ l('Actions') }}</span>
        </th>
      </tr>
    </thead>
    <tbody nz-tbody>
      <tr nz-tbody-tr *ngFor="let item of ajaxTable.data">
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.executionTime | _moment: 'YYYY-MM-DD HH:mm:ss'">
              {{ item.executionTime | _moment: 'YYYY-MM-DD HH:mm:ss' }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.userName">
              {{ item.userName }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.serviceName">
              {{ item.serviceName }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.methodName">
              {{ item.methodName }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="l('Xms', item.executionDuration)">
              {{ l('Xms', item.executionDuration) }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.clientIpAddress">
              {{ item.clientIpAddress }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.clientName">
              {{ item.clientName }}
            </span>
          </ellipsis>
        </td>
        <td class="text-center">
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.browserInfo">
              {{ truncateStringWithPostfix(item.browserInfo, 20) }}
            </span>
          </ellipsis>
        </td>
        <td class="text-center">
          <i class="iconfont icon-warning-circle text-warning" *ngIf="item.exception" nz-tooltip
            [nzTooltipTitle]="l('HasError')"></i>
          <i class="iconfont icon-check-circle  text-green" *ngIf="!item.exception" nz-tooltip
            [nzTooltipTitle]="l('Success')"></i>
        </td>
        <td nzWidth="120px" class="text-center">
          <span>
            <a (click)="showDetails(item)">
              <i class="iconfont icon-search "></i>
              <span>{{ l('ViewDetails') }}</span>
            </a>
          </span>
        </td>
      </tr>
    </tbody>
  </nz-table>

</nz-card>
