// src/yoyocmstemplate-angular/src/layout/components/header-user/header-user.component.ts
import { Component, Injector, OnInit } from '@angular/core';
import { AppComponentBase } from '@shared/component-base';
import { AppAuthService, ImpersonationService } from '@shared/auth';
import { ChangePasswordModalComponent } from '@layout/default/profile/change-password-modal.component';
import { LoginAttemptsModalComponent } from '@layout/default/profile/login-attempts-modal.component';
import { MySettingsModalComponent } from '@layout/default/profile/my-settings-modal.component';

@Component({
  selector: 'header-user',
  templateUrl: './header-user.component.html',
  styles: [],
})
export class HeaderUserComponent extends AppComponentBase implements OnInit {
  loginUserName: string;
  isImpersonatedLogin: boolean;

  constructor(
    injector: Injector,
    private authService: AppAuthService,
    private impersonationService: ImpersonationService,
  ) {
    super(injector);
  }

  ngOnInit(): void {
    this.isImpersonatedLogin = this.abpSession.impersonatorUserId > 0;
    this.loginUserName = this.appSession.getShownLoginName();
  }

  changePassword(): void {
    this.modalHelper.open(ChangePasswordModalComponent).subscribe(result => {
      if (result) {
        this.logout();
      }
    });
  }

  showLoginAttempts(): void {
    this.modalHelper.open(LoginAttemptsModalComponent).subscribe(result => {
    });
  }

  changeMySettings(): void {
    this.modalHelper.open(MySettingsModalComponent).subscribe(result => {
    });
  }

  backToMyAccount(): void {
    this.impersonationService.backToImpersonator();
  }

  logout(): void {
    this.authService.logout();
  }
}

<div
        class="alain-pro__nav-item d-flex align-items-center px-sm"
        nz-dropdown
        nzPlacement="bottomRight"
        [nzDropdownMenu]="dropdownMenu"
>
    <nz-avatar [nzSrc]="'/assets/images/user.png'" nzSize="small" class="mr-sm"></nz-avatar>
    {{ loginUserName }}
</div>

<nz-dropdown-menu #dropdownMenu="nzDropdownMenu">
    <div nz-menu class="width-sm">
        <!-- 返回我的账户 -->
        <div nz-menu-item (click)="backToMyAccount()" *ngIf="isImpersonatedLogin">
            <i class="iconfont icon-rollback  mr-sm"></i>
            <!-- <i class="iconfont icon-rollback mr-sm"></i> -->
            {{ l('BackToMyAccount') }}
        </div>
        <!-- 密码修改 -->
        <div nz-menu-item (click)="changePassword()">
            <i class="iconfont icon-ellipsis  mr-sm"></i>
            <!-- <i class="iconfont icon-ellipsis mr-sm"></i> -->
            {{ l('ChangePassword') }}
        </div>
        <!-- 登陆记录 -->
        <div nz-menu-item (click)="showLoginAttempts()">
            <i class="iconfont icon-unorderedlist  mr-sm"></i>
            <!-- <i class="iconfont icon-bars mr-sm"></i> -->
            {{ l('LoginAttempts') }}
        </div>
        <!-- 设置 -->
        <div nz-menu-item (click)="changeMySettings()">
            <i class="iconfont icon-setting  mr-sm"></i>
            <!-- <i class="iconfont icon-setting mr-sm"></i> -->
            {{ l('MySettings') }}
        </div>
        <li nz-menu-divider></li>
        <!-- 注销 -->
        <div nz-menu-item (click)="logout()">
            <i class="iconfont icon-logout  mr-sm"></i>
            <!-- <i class="iconfont icon-logout mr-sm"></i> -->
            {{ l('Logout') }}
        </div>
    </div>
</nz-dropdown-menu>

// src/yoyocmstemplate-vue/src/layout/default/header/components/header-user.vue
<template>

    <a-dropdown class="alain-pro__nav-item" placement="bottomRight">
        <a-menu slot="overlay" style="width:200px;">
            <a-menu-item @click="backToMyAccount()" v-if="isImpersonatedLogin">
                <i class="anticon anticon-rollback mr-sm"></i>
                {{ l('BackToMyAccount') }}
            </a-menu-item>
            <a-menu-item @click="changePassword()">
                <i class="anticon anticon-ellipsis mr-sm"></i>
                {{ l('ChangePassword') }}
            </a-menu-item>
            <a-menu-item @click="showLoginAttempts()">
                <i class="anticon anticon-bars mr-sm"></i>
                {{ l('LoginAttempts') }}
            </a-menu-item>
            <a-menu-item @click="changeMySettings()">
                <i class="anticon anticon-setting mr-sm"></i>
                {{ l('MySettings') }}
            </a-menu-item>
            <a-divider/>
            <a-menu-item @click="logout()">
                <i class="anticon anticon-logout mr-sm"></i>
                {{ l('Logout') }}
            </a-menu-item>
        </a-menu>


        <div class="alain-pro__nav-item d-flex align-items-center px-sm">
            <a-avatar class="mr-sm" size="small"
                      src="/assets/images/user.png">
            </a-avatar>
            {{ loginUserName }}
        </div>
    </a-dropdown>

</template>

<script>
    import {AppComponentBase} from '@/shared/component-base';
    import {appAuthService, appSessionService} from "@/shared/abp";
    import {ChangePasswordModal, LoginAttemptsModal, MySettingsModal} from '../../profile';
    import {ModalHelper} from '@/shared/helpers';

    export default {
        name: "header-user",
        mixins: [AppComponentBase],
        data() {
            return {
                showNotificationSettings: false
            }
        },
        computed: {
            isImpersonatedLogin() {
                return appSessionService.user.impersonatorUserId > 0;
            },
            loginUserName() {
                return appSessionService.getShownLoginName();
            },
        },
        methods: {
            changePassword() {
                ModalHelper.create(ChangePasswordModal).subscribe((result) => {
                    if (result) {
                            this.logout();
                        }
                });
            },
            showLoginAttempts() {
                ModalHelper.create(LoginAttemptsModal).subscribe(() => {

                });
            },
            changeMySettings() {
                ModalHelper.create(MySettingsModal).subscribe(() => {

                });
            },
            backToMyAccount() {

            },
            logout() {
                appAuthService.logout();
            }
        }
    }
</script>

<style lang="less" scoped>
    .ant-divider-horizontal {
        margin: 4px 0px;
    }
</style>
