// src/yoyocmstemplate-angular/src/layout/components/header-i18n/header-i18n.component.ts
import { Component, Injector, OnInit } from '@angular/core';
import { AppComponentBase } from '@shared/component-base';
import { ChangeUserLanguageDto, ProfileServiceProxy } from '@shared/service-proxies/service-proxies';
import * as _ from 'lodash';

@Component({
  selector: 'header-i18n',
  templateUrl: './header-i18n.component.html',
  styles: [],
})
export class HeaderI18nComponent extends AppComponentBase implements OnInit {
  languages: abp.localization.ILanguageInfo[];
  currentLanguage: abp.localization.ILanguageInfo;

  constructor(injector: Injector, private _profileService: ProfileServiceProxy) {
    super(injector);
  }

  ngOnInit() {
    this.languages = _.filter(this.localization.languages, l => !l.isDisabled);
    this.currentLanguage = this.localization.currentLanguage;
  }

  change(languageName: string): void {
    const input = new ChangeUserLanguageDto();
    input.languageName = languageName;

    this._profileService.changeLanguage(input).subscribe(() => {
      abp.utils.setCookieValue(
        'Abp.Localization.CultureName',
        languageName,
        new Date(new Date().getTime() + 5 * 365 * 86400000), // 5 year
        abp.appPath,
      );

      window.location.reload();
    });
  }
}

<div
        nz-dropdown
        [ngClass]="'btnClass'"
        class="alain-pro__item"
        nzPlacement="bottomRight"
        [nzDropdownMenu]="dropdownMenu"
>
    <span class="iconfont icon-earth" [ngClass]="'btnIconClass'"></span>
    <!-- <i nz-icon nzType="global" [ngClass]="'btnIconClass'"></i> -->
    {{ currentLanguage.displayName }}
    <!-- <i nz-icon type="down"></i> -->
    <span class="iconfont icon-down" style="font-size: 14px;"></span>
</div>

<nz-dropdown-menu #dropdownMenu="nzDropdownMenu">
    <ul nz-menu>
        <li
                nz-menu-item
                *ngFor="let item of languages"
                [nzSelected]="item.name == currentLanguage.name"
                (click)="change(item.name)"
        >
            <!-- <span class="iconfont  {{ item.icon }}"></span> -->
            <i class="anticon {{ item.icon }}"></i>
            <span>{{ item.displayName }}</span>
        </li>
    </ul>
</nz-dropdown-menu>

// src/yoyocmstemplate-vue/src/layout/default/header/components/header-i18n.vue
<template>
    <a-dropdown class="alain-pro__item">
        <a class="ant-dropdown-link" href="#">
            <a-icon type="global"/>
            {{ currentLanguage.displayName }}
            <a-icon type="down"/>
        </a>
        <a-menu slot="overlay">
            <a-menu-item :key="index" v-for="(item,key,index) in languages" @click="change(item.name)">
                <i class="anticon" v-bind:class="[item.icon]"></i>
                <span>{{ item.displayName }}</span>
            </a-menu-item>
        </a-menu>
    </a-dropdown>
</template>

<script>
    import {abpService} from "@/shared/abp";
    import {ChangeUserLanguageDto, ProfileServiceProxy} from "@/shared/service-proxies";
    import {AppComponentBase} from "@/shared/component-base";

    export default {
        name: "header-i18n",
        mixins: [AppComponentBase],
        data() {
            return {
                profileService: null
            }
        },
        created() {
            this.profileService = new ProfileServiceProxy(this.$apiUrl, this.$api);
        },
        computed: {
            languages() {
                return abpService.abp.localization.languages
                    .filter(o => !o.isDisabled && o.name !== this.currentLanguage.name);
            },
            currentLanguage() {
                return abpService.abp.localization.currentLanguage;
            }
        },
        methods: {
            change(languageName) {
                const input = new ChangeUserLanguageDto();
                input.languageName = languageName;

                this.profileService.changeLanguage(input).then(() => {
                    abpService.abp.utils.setCookieValue(
                        'Abp.Localization.CultureName',
                        languageName,
                        new Date(new Date().getTime() + 5 * 365 * 86400000), // 5 year
                        abpService.abp.appPath
                    );

                    window.location.reload();
                });
            }
        }
    }
</script>

<style scoped>

</style>
