// src/yoyocmstemplate-vue/src/app/website/bannerads/create-or-edit-banner-ad.vue
<template>
    <a-spin :spinning="spinning">
        <div class="modal-header">
            <div class="modal-title">
                <span v-if="id">{{ l('Edit') }}</span>
                <span v-if="!id">{{ l('Create') }}</span>
            </div>
        </div>
        <a-form :form="form" @submit="handleSubmit">
            <!-- 标题 -->
            <a-form-item :label="l('Title')">
                <a-input
                    :placeholder="l('Title')"
                    v-decorator="[
                        'title',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]" />
            </a-form-item>

            <!-- 图片地址 -->
            <a-form-item :label="l('ImageUrl')">
                <a-popover :title="l('Preview')">
                    <template slot="content">
                        <img v-if="entity.imageUrl" :src="entity.imageUrl" alt="">
                        <span v-if="!entity.imageUrl">{{ l('NotSelected') }}</span>
                    </template>
                    <a-input
                        :placeholder="l('ImageUrlInputDesc')"
                        v-decorator="[
                        'imageUrl',
                        ]">
                        <p class="pleaseSelect-text" slot="addonAfter" @click="chooseFile('imageUrl')">{{ l('PleaseSelect') }}</p>
                    </a-input>
                </a-popover>
            </a-form-item>

            <!-- 缩略图地址 -->
            <a-form-item :label="l('ThumbImgUrl')">
                <a-popover :title="l('Preview')">
                    <template slot="content">
                        <img v-if="entity.thumbImgUrl" :src="entity.thumbImgUrl" alt="">
                        <span v-if="!entity.thumbImgUrl">{{ l('NotSelected') }}</span>
                    </template>
                    <a-input
                        :placeholder="l('ThumbImgUrlInputDesc')"
                        v-decorator="[
                        'thumbImgUrl',
                        ]">
                        <p class="pleaseSelect-text" slot="addonAfter" @click="chooseFile('thumbImgUrl')">{{ l('PleaseSelect') }}</p>
                    </a-input>
                </a-popover>
            </a-form-item>

            <!-- 描述 -->
            <a-form-item :label="l('Description')">
                <a-textarea
                    :placeholder="l('DescriptionInputDesc')"
                    :auto-size="{ minRows: 3, maxRows: 5 }"
                    maxLength="3000"
                    v-decorator="[
                        'description',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]" />
            </a-form-item>

            <!-- 目标url -->
            <a-form-item :label="l('BannerAdUrl')">
                <a-input
                    :placeholder="l('BannerAdUrlInputDesc')"
                    v-decorator="[
                        'url',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]" />
            </a-form-item>

            <!-- 权重 -->
            <a-form-item :label="l('Weight')">
                <a-input-number v-decorator="[
                        'weight',
                        {
                            rules: [
                            ],
                        },
                        ]" :min="0" :max="1000000" :step="1" />
            </a-form-item>

            <!-- 价格 -->
            <a-form-item :label="l('Price')">
                <a-input
                    :placeholder="l('BannerAdPriceInputDesc')"
                    v-decorator="[
                        'price',
                        {
                            rules: [
                            ],
                        },
                        ]" />
            </a-form-item>

            <!-- 轮播图类型 -->
            <a-form-item :label="l('BannerAdTypes')">
                <a-input
                    :placeholder="l('BannerAdTypesInputDesc')"
                    v-decorator="[
                        'types',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]" />
            </a-form-item>

            <!-- 阅读数 -->
            <a-form-item :label="l('ViewCount')">
                <a-input-number v-decorator="[
                        'viewCount',
                        {
                            rules: [
                            ],
                        },
                        ]" :min="0" :max="1000000" :step="1" />
            </a-form-item>

            <a-form-item class="btn--container">
                <a-button type="button" @click="close()">
                    {{ l("Cancel") }}
                </a-button>
                <a-button type="primary" html-type="submit">
                    {{ l('Save') }}
                </a-button>
            </a-form-item>
        </a-form>
    </a-spin>
</template>

<script>
import { ModalComponentBase } from "@/shared/component-base";
import { ModalHelper } from "@/shared/helpers";
import FileManagerComponent from "../../admin/file-manager/file-manager";
import { BannerImgServiceProxy } from "@/shared/service-proxies";
import pick from "lodash.pick";

export default {
    mixins: [ModalComponentBase],
    name: "create-tenant-component",
    data() {
        return {
            // 获取到的数据
            entity: {},
            spinning: false,
            _bannerImgServiceProxy: ""
        };
    },
    components: {
        FileManagerComponent
    },
    beforeCreate() {
        this.form = this.$form.createForm(this, { name: "register" });
    },
    created() {
        this.fullData(); // 模态框必须,填充数据到data字段
        this._bannerImgServiceProxy = new BannerImgServiceProxy(
            this.$apiUrl,
            this.$api
        );
    },
    mounted() {
        this.form.setFieldsValue({
            weight: 0,
            price: 0,
            viewCount: 0
        });
        console.log(this.id);
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._bannerImgServiceProxy
                .getForEdit(this.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    console.log(res);
                    this.entity = res.bannerAd;
                    this.form.setFieldsValue({
                        title: res.bannerAd.title,
                        imageUrl: res.bannerAd.imageUrl,
                        thumbImgUrl: res.bannerAd.thumbImgUrl,
                        description: res.bannerAd.description,
                        url: res.bannerAd.url,
                        weight: res.bannerAd.weight,
                        price: res.bannerAd.price,
                        types: res.bannerAd.types,
                        viewCount: res.bannerAd.viewCount
                    });
                });
        },
        /**
         * 提交表单
         */
        handleSubmit(e) {
            e.preventDefault();
            this.form.validateFieldsAndScroll((err, values) => {
                if (!err) {
                    this.spinning = true;
                    this._bannerImgServiceProxy
                        .createOrUpdate({
                            bannerAd: Object.assign(values, { id: this.id })
                        })
                        .finally(() => {
                            this.spinning = false;
                        })
                        .then(res => {
                            this.$notification["success"]({
                                message: this.l("SavedSuccessfully")
                            });
                            this.success(true);
                        })
                        .catch(err => {
                            console.log(err);
                        });
                }
            });
        },
        /**
         * 选择文件
         */
        chooseFile(type) {
            ModalHelper.create(
                FileManagerComponent,
                {
                    componentType: "modal"
                },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    if (type === "imageUrl") {
                        this.form.setFieldsValue({
                            imageUrl: res.path
                        });
                        this.entity.imageUrl = res.path;
                    } else if (type === "thumbImgUrl") {
                        this.form.setFieldsValue({
                            thumbImgUrl: res.path
                        });
                        this.entity.thumbImgUrl = res.path;
                    }
                }
            });
        }
    }
};
</script>

<style lang="less" scoped>
/deep/.btn--container .ant-form-item-children {
    display: block;
    margin: 10px auto;
    text-align: center;
}
.pleaseSelect-text {
    font-size: 14px;
    padding: 0 14px;
    text-align: center;
    color: rgba(0, 0, 0, 0.65);
    font-weight: 400;
    line-height: 30px;
    margin-bottom: 0;
}
</style>

// src/yoyocmstemplate-angular/src/app/webSite/banner-ads/create-or-edit-banner-ad/create-or-edit-banner-ad.component.ts
import { Component, OnInit, Injector, Input, ViewChild, AfterViewInit } from '@angular/core';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import {
  CreateOrUpdateBannerAdInput,
  BannerAdEditDto,
  KeyValuePairOfStringString,
} from '@shared/service-proxies/service-proxies';
import { Validators, AbstractControl, FormControl } from '@angular/forms';
import { finalize } from 'rxjs/operators';
import { BannerImgServiceProxy } from '../../../../shared/service-proxies/service-proxies';

@Component({
  selector: 'create-or-edit-banner-ad',
  templateUrl: './create-or-edit-banner-ad.component.html',
  styleUrls: ['create-or-edit-banner-ad.component.less'],
})
export class CreateOrEditBannerAdComponent extends ModalComponentBase implements OnInit {
  /**
   * 编辑时DTO的id
   */
  id: any;

  entity: BannerAdEditDto = new BannerAdEditDto();

  /**
   * 构造函数，在此处配置依赖注入
   */
  constructor(injector: Injector, private _bannerAdService: BannerImgServiceProxy) {
    super(injector);
  }

  ngOnInit(): void {
    this.init();
  }

  /**
   * 初始化方法
   */
  init(): void {
    this._bannerAdService.getForEdit(this.id).subscribe(result => {
      this.entity = result.bannerAd;
    });
  }

  /**
   * 保存方法,提交form表单
   */
  submitForm(): void {
    const input = new CreateOrUpdateBannerAdInput();
    input.bannerAd = this.entity;

    this.saving = true;

    this._bannerAdService
      .createOrUpdate(input)
      .pipe(finalize(() => (this.saving = false)))

      .subscribe(() => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success(true);
      });
  }

  _change(event, type) {
    switch (type) {
      case 'imageUrl':
        this.entity.imageUrl = event.path;
        break;
      case 'thumbImgUrl':
        this.entity.thumbImgUrl = event.path;
        break;
    }
  }
}

<form nz-form #validateForm="ngForm" (ngSubmit)="submitForm()" nzLayout="horizontal" autocomplete="off">
  <!-- 模态框头部 -->
  <div class="modal-header">
    <div class="modal-title">
      <i class="iconfont icon-medicine-box mr-sm"></i>
      <span *ngIf="entity.id">{{ l('Edit') }}</span>
      <span *ngIf="!entity.id">{{ l('Create') }}</span>
    </div>
  </div>
  <!-- 模态框内容 -->
  <fieldset>
    <!-- 提示信息 -->
    <!-- <nz-alert nzType="info" nzCloseable [nzShowIcon]="true" nzMessage="l('我想提示点什么内容给你说')"></nz-alert> -->
    <!-- 标题 : Title 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="title">
        {{ l('Title') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <input nz-input name="title" #title="ngModel" [(ngModel)]="entity.title" [placeholder]="l('TitleInputDesc')"
          required />

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="title.control.dirty && title.control.errors">
          <ng-container *ngIf="title.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <!--标题 : Title 的控件范围结束=END= -->
    <!-- 图片地址 : ImageUrl 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="imageUrl">
        {{ l('ImageUrl') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <nz-input-group [nzAddOnAfter]="imageUrlSelectBtnSelectBtn">
          <input nz-input nz-popover [nzPopoverTitle]="l('Preview')" [nzPopoverContent]="imageUrlSelectContent"
            name="imageUrl" #imageUrl="ngModel" [(ngModel)]="entity.imageUrl" [placeholder]="l('ImageUrlInputDesc')"
            readonly />
          <ng-template #imageUrlSelectBtnSelectBtn>
            <div dialog-img (selected)="_change($event, 'imageUrl')">
              {{ l('PleaseSelect') }}
            </div>
          </ng-template>
          <ng-template #imageUrlSelectContent>
            <img *ngIf="entity.imageUrl" [src]="entity.imageUrl" />
            <span *ngIf="!entity.imageUrl">
              {{ l('NotSelected') }}
            </span>
          </ng-template>
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <!--图片地址 : ImageUrl 的控件范围结束=END= -->
    <!-- 缩略图地址 : ThumbImgUrl 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="thumbImgUrl">
        {{ l('ThumbImgUrl') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24">
        <!--  控件位置 -->
        <nz-input-group [nzAddOnAfter]="thumbImgUrlSelectBtn">
          <input nz-input nz-popover [nzPopoverTitle]="l('Preview')" [nzPopoverContent]="thumbImgUrlSelectContent"
            name="thumbImgUrl" #thumbImgUrl="ngModel" [(ngModel)]="entity.thumbImgUrl"
            [placeholder]="l('ThumbImgUrlInputDesc')" readonly />
          <ng-template #thumbImgUrlSelectBtn>
            <div dialog-img (selected)="_change($event, 'thumbImgUrl')">
              {{ l('PleaseSelect') }}
            </div>
          </ng-template>
          <ng-template #thumbImgUrlSelectContent style="max-width: height 180px;">
            <img *ngIf="entity.thumbImgUrl" [src]="entity.thumbImgUrl" />
            <span *ngIf="!entity.thumbImgUrl">
              {{ l('NotSelected') }}
            </span>
          </ng-template>
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
    <!--缩略图地址 : ThumbImgUrl 的控件范围结束=END= -->
    <!-- 描述 : Description 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="description">
        {{ l('Description') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <textarea rows="4" nz-input name="description" #description="ngModel" [(ngModel)]="entity.description"
          [placeholder]="l('DescriptionInputDesc')" required maxlength="3000"></textarea>
        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="description.control.dirty && description.control.errors">
          <ng-container *ngIf="description.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <!--描述 : Description 的控件范围结束=END= -->
    <!-- Url : Url 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="url">
        {{ l('BannerAdUrl') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <input nz-input name="url" #url="ngModel" [(ngModel)]="entity.url" [placeholder]="l('BannerAdUrlInputDesc')"
          required />

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="url.control.dirty && url.control.errors">
          <ng-container *ngIf="url.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <!--Url : Url 的控件范围结束=END= -->
    <!-- 权重 : Weight 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="weight">
        {{ l('Weight') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <nz-input-number name="weight" #weight="ngModel" [(ngModel)]="entity.weight" [nzMin]="0" [nzMax]="1000000"
          [nzStep]="1"></nz-input-number>
      </nz-form-control>
    </nz-form-item>
    <!--权重 : Weight 的控件范围结束=END= -->
    <!-- Price : Price 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="price">
        {{ l('Price') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <input nz-input name="price" #price="ngModel" [(ngModel)]="entity.price"
          [placeholder]="l('BannerAdPriceInputDesc')" />
      </nz-form-control>
    </nz-form-item>
    <!--Price : Price 的控件范围结束=END= -->
    <!-- Types : Types 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="types">
        {{ l('BannerAdTypes') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <input nz-input name="types" #types="ngModel" [(ngModel)]="entity.types"
          [placeholder]="l('BannerAdTypesInputDesc')" required />

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="types.control.dirty && types.control.errors">
          <ng-container *ngIf="types.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <!--Types : Types 的控件范围结束=END= -->
    <!-- ViewCount : ViewCount 的控件范围=Start= -->
    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="viewCount">
        {{ l('ViewCount') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <!--  控件位置 -->
        <nz-input-number name="viewCount" #viewCount="ngModel" [(ngModel)]="entity.viewCount" [nzMin]="0"
          [nzMax]="1000000" [nzStep]="1"></nz-input-number>
      </nz-form-control>
    </nz-form-item>
    <!--ViewCount : ViewCount 的控件范围结束=END= -->
  </fieldset>
  <!-- 模态框底部 -->
  <div class="modal-footer">
    <button nz-button [nzType]="'default'" type="button" (click)="close()" [disabled]="saving">
      <i class="iconfont icon-close-circle"></i> {{ l('Cancel') }}
    </button>
    <button nz-button [nzType]="'primary'" type="submit" [disabled]="!validateForm.form.valid || saving"
      [nzLoading]="saving">
      <i class="iconfont icon-save" *ngIf="!saving"></i> {{ l('Save') }}
    </button>
  </div>
</form>
