// src/yoyocmstemplate-angular/src/layout/default/sidebar/sidebar.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd/message';
import { SettingsService } from '@delon/theme';
import { AppComponentBase } from '@shared/component-base';
import { AppAuthService } from '@shared/auth/app-auth.service';

@Component({
  selector: 'layout-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.less'],
})
export class SidebarComponent extends AppComponentBase implements OnInit {
  constructor(
    injector: Injector,
    public settings: SettingsService,
  ) {
    super(injector);
  }

  ngOnInit() {

  }

}

<div class="ant-layout-sider-children">
    <div class="alain-pro__sider-logo">
        <a [routerLink]="['/']" class="alain-pro__header-logo-link">
            <img class="alain-pro__header-logo-expanded"
                 src="/assets/images/logos/logo-txt-white-shield.svg"
                 alt="{{ settings.app.name }}"
                 style="max-height:40px;"
            />
            <img class="alain-pro__header-logo-collapsed"
                 src="/assets/images/logos/logo-white-shield.svg"
                 alt="{{ settings.app.name }}"
                 style="max-height:30px;"
            />
        </a>
    </div>
    <yoyo-sidebar-nav></yoyo-sidebar-nav>
</div>

// src/yoyocmstemplate-vue/src/layout/default/sidebar/sidebar.vue
<template>
    <div class="ant-layout-sider-children">
        <!-- logo -->
        <div class="alain-pro__sider-logo">
            <router-link class="alain-pro__header-logo-link" to="/">
                <img class="alain-pro__header-logo-expanded"
                     src="/assets/images/logos/logo-txt-white-shield.svg"

                     style="max-height:40px;"/>
                <img class="alain-pro__header-logo-collapsed"
                     src="/assets/images/logos/logo-white-shield.svg"
                     style="max-height:30px;"/>
            </router-link>
        </div>

        <!-- sidebar -->
        <yoyo-sidebar-nav></yoyo-sidebar-nav>
    </div>
</template>

<script>
    import {YoyoSidebarNav} from './components';

    export default {
        name: "sidebar",
        components: {
            YoyoSidebarNav
        },

    }
</script>

<style lang="less" scoped>
    @import "./sidebar.less";
</style>
