// src/yoyocmstemplate-angular/src/app/wechat-management/wechat-app-configs/wechat-app-config.component.ts
import { Component, Injector, OnInit } from '@angular/core';
import * as _ from 'lodash';
import { appModuleAnimation } from '@shared/animations/routerTransition';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import {
  WechatAppConfigServiceProxy,
  PagedResultDtoOfWechatAppConfigListDto,
  WechatAppConfigListDto,
} from '@shared/service-proxies/service-proxies';
import { CreateOrEditWechatAppConfigComponent } from './create-or-edit-wechat-app-config/create-or-edit-wechat-app-config.component';

import { Router } from '@angular/router';
import { finalize } from 'rxjs/operators';
import { ImgShowComponent } from '@shared/components/img-show/img-show.component';
//  import { FileDownloadService } from '@shared/utils/file-download.service';

@Component({
  templateUrl: './wechat-app-config.component.html',
  styleUrls: ['./wechat-app-config.component.less'],
  animations: [appModuleAnimation()],
})
export class WechatAppConfigComponent extends PagedListingComponentBase<WechatAppConfigListDto> implements OnInit {
  constructor(
    injector: Injector,
    private router: Router,
    private _wechatAppConfigService: WechatAppConfigServiceProxy,
  ) {
    super(injector);
  }

  /**
   * 获取后端数据列表信息
   * @param request 请求的数据的dto 请求必需参数 skipCount: number; maxResultCount: number;
   * @param pageNumber 当前页码
   * @param finishedCallback 完成后回调函数
   */
  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    this._wechatAppConfigService
      .getPaged(this.filterText, request.sorting, request.maxResultCount, request.skipCount)
      .pipe(finalize(() => finishedCallback()))
      .subscribe(result => {
        this.dataList = result.items;
        this.showPaging(result);
      });
  }

  /**
   * 新增或编辑DTO信息
   * @param id 当前DTO的Id
   */
  createOrEdit(id?: number): void {
    this.modalHelper.static(CreateOrEditWechatAppConfigComponent, { id: id }).subscribe(result => {
      if (result) {
        this.refresh();
      }
    });
  }

  /**
   * 删除功能
   * @param entity 角色的实体信息
   */
  delete(entity: WechatAppConfigListDto): void {
    this._wechatAppConfigService.delete(entity.id).subscribe(() => {
      /**
       * 刷新表格数据并跳转到第一页（`pageNumber = 1`）
       */
      this.refreshGoFirstPage();
      this.notify.success(this.l('SuccessfullyDeleted'));
    });
  }

  /**
   * 批量删除
   */
  batchDelete(): void {
    const selectCount = this.selectedDataItems.length;
    if (selectCount <= 0) {
      abp.message.warn(this.l('PleaseSelectAtLeastOneItem'));
      return;
    }

    abp.message.confirm(this.l('ConfirmDeleteXItemsWarningMessage', selectCount), undefined,  res => {
      if (res) {
        const ids = _.map(this.selectedDataItems, 'id');
        this._wechatAppConfigService.batchDelete(ids).subscribe(() => {
          this.refreshGoFirstPage();
          this.notify.success(this.l('SuccessfullyDeleted'));
        });
      }
    });
  }

  /**
   * 导出为Excel表
   */
  exportToExcel(): void {
    abp.message.error('功能开发中！！！！');
    // this._wechatAppConfigService.getWechatAppConfigexportToExcel().subscribe(result => {
    // this._fileDownloadService.downloadTempFile(result);
    // });
  }

  /**
   * 显示二维码图片
   * @param url 二维码链接
   */
  showImg(url: string) {
    this.modalHelper.open(ImgShowComponent, { imgUrl: url }, 'md').subscribe(() => {});
  }

  /**
   * 编辑自定义菜单
   * @param item
   */
  editMenu(item: WechatAppConfigListDto): void {
    const self = this;
    setTimeout(() => {
      self.router.navigate(['app/wechat/create-or-edit-wechat-menu', { appId: item.appId, appName: item.name }]);
    }, 300);
  }

  /**
   * 注册app
   * @param item
   */
  registerApp(item: WechatAppConfigListDto) {
    this._wechatAppConfigService
      .registerWechatApp(item.appId)
      .pipe(finalize(() => {}))
      .subscribe(() => {
        this.notify.success(this.l('RegisterWechatAppSuccessfully'));
        this.refresh();
      });
  }

  editMaterial(item: WechatAppConfigListDto) {
    const self = this;
    setTimeout(() => {
      self.router.navigate(['app/wechat/wechat-materials', { appId: item.appId, appName: item.name }]);
    }, 300);
  }
}

<page-header [title]="l('WechatAppConfig')"></page-header>

<nz-card [nzBordered]="false">
  <div class="mb-md">
    <!-- 模糊搜索框 -->
    <nz-row nzGutter="8">
      <nz-col nzSm="24">
        <nz-form-item>
          <nz-form-control>
            <nz-input-group nzSearch [nzAddOnAfter]="suffixSearchButton">
              <input type="text" nz-input [(ngModel)]="filterText" (keyup.enter)="refresh()" name="filterText"
                [placeholder]="l('SearchWithThreeDot')" />
              <ng-template #suffixSearchButton>
                <button nz-button nzType="primary" nzSearch type="submit" (click)="refresh()">
                  <!-- <i class="iconfont icon-search"></i> -->
                  <i class="iconfont icon-search"></i>
                </button>
              </ng-template>
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
      </nz-col>
    </nz-row>
  </div>

  <div class="mb-md">
    <!-- 操作常规按钮部分 如： 添加、批量删除、导出Excel表 -->
    <nz-row nzGutter="8">
      <nz-col nzMd="20" nzSm="12" class="btn-gutter">
        <button nz-button [nzType]="'primary'" *ngIf="isGranted('Pages.WechatAppConfig.Create')"
          (click)="createOrEdit()">
          <i class="iconfont icon-plus"></i>
          <span>
            {{ l('Create') }}
          </span>
        </button>
        <button nz-button [nzType]="'danger'" *ngIf="isGranted('Pages.WechatAppConfig.BatchDelete')"
          (click)="batchDelete()">
          <i class="iconfont icon-delete"></i>
          <span>
            {{ l('BatchDelete') }}
          </span>
        </button>
        <button nz-button nzType="default" *ngIf="isGranted('Pages.WechatAppConfig.ExportToExcel')"
          (click)="exportToExcel()">
          <!-- <i class="iconfont icon-file-excel"></i> -->
          <i class="iconfont icon-file-excel"></i>
          <span>
            {{ l('ExportToExcel') }}
          </span>
        </button>
      </nz-col>
    </nz-row>
  </div>

  <!-- 复选框提示的内容数据部分 -->
  <!-- 复选框提示的内容数据部分 -->
  <table-checkbox-panel [selectLength]="selectedDataItems.length" (onClear)="restCheckStatus(dataList)"
    (onRefresh)="refreshGoFirstPage()"></table-checkbox-panel>

  <!-- 实体的表格内容 -->

  <nz-table #ajaxTable [nzData]="dataList" [nzTotal]="totalItems" [(nzPageIndex)]="pageNumber" [(nzPageSize)]="pageSize"
    [nzLoading]="isTableLoading" (nzPageIndexChange)="pageNumberChange()" (nzPageSizeChange)="refresh()"
    [nzShowSizeChanger]="true" [nzShowQuickJumper]="true" [nzNoResult]="noDataTemplate"
    [nzShowTotal]="showTotalTemplate" [nzFrontPagination]="false">
    <!-- 暂无数据组件 -->
    <ng-template #noDataTemplate>
      <no-data></no-data>
    </ng-template>
    <!-- 分页信息显示 当前 1 页/共 3 页，共 5 条/显示 1-2 条 -->
    <ng-template #showTotalTemplate let-total let-range="range">
      {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
    </ng-template>
    <!-- 表头 -->
    <thead (nzSortChange)="gridSort($event)">
      <tr>
        <th nzShowCheckbox [(nzChecked)]="allChecked" [nzDisabled]="allCheckboxDisabled"
          [nzIndeterminate]="checkboxIndeterminate" (nzCheckedChange)="checkAll($event)"></th>
        <th nz-th nzShowSort nzSortKey="QRCodeUrl">
          <span>{{ l('QRCodeUrl') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="AppId">
          <span>{{ l('WechatAppId') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="Name">
          <span>{{ l('WechatName') }}</span>
        </th>
        <th nz-th nzShowSort nzSortKey="AppType">
          <span>{{ l('WechatAppType') }}</span>
        </th>
        <th nzWidth="230px" class="text-center">
          <span>{{ l('Actions') }}</span>
        </th>
      </tr>
    </thead>
    <!-- 表格内容 -->
    <tbody>
      <tr *ngFor="let item of ajaxTable.data">
        <!-- 全选框 -->
        <td nzShowCheckbox [(nzChecked)]="item.checked" (nzCheckedChange)="refreshCheckStatus(dataList)"></td>
        <td nz-td>
          <img *ngIf="item.qrCodeUrl" [src]="item.qrCodeUrl" (click)="showImg(item.qrCodeUrl)" style="width:50px;" />
        </td>

        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.appId">
              {{ item.appId }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.name">
              {{ item.name }}
            </span>
          </ellipsis>
        </td>
        <td nz-td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.appTypeStr">
              {{ item.appTypeStr }}
            </span>
          </ellipsis>
        </td>

        <td>
          <!-- 编辑 -->
          <ng-container *ngIf="isGranted('Pages.WechatAppConfig.Edit')">
            <a (click)="createOrEdit(item.id)">
              <i class="iconfont icon-edit mr-sm"></i>
              <span>{{ l('Edit') }}</span>
            </a>
            <nz-divider nzType="vertical"></nz-divider>
          </ng-container>
          <!-- 删除 -->
          <ng-container *ngIf="isGranted('Pages.WechatAppConfig.Delete')">
            <a nz-popconfirm [nzPopconfirmTitle]="l('ConfirmDeleteWarningMessage')" (nzOnConfirm)="delete(item)"
              [nzOkText]="l('Ok')" [nzCancelText]="l('Cancel')">
              <i class="iconfont icon-delete mr-sm"></i>
              <span>{{ l('Delete') }}</span>
            </a>
          </ng-container>
          <!-- 更多 -->
          <ng-container *ngIf="
                isGrantedAny('Pages.WechatAppConfig', 'Pages.WechatAppConfig.Create', 'Pages.WechatAppConfig.Edit')
              ">
            <nz-divider nzType="vertical"></nz-divider>
            <nz-dropdown-menu #menu="nzDropdownMenu">
              <a nz-dropdown>
                <!-- <i class="iconfont icon-down"></i> -->
                <i class="iconfont icon-down"></i>
                <span>{{ l('More') }}</span>
              </a>
              <ul nz-menu>
                <!-- 注册/刷新注册应用 -->
                <li nz-menu-item (click)="registerApp(item)">
                  <!-- <i class="iconfont icon-sync"></i> -->
                  <i class="iconfont icon-sync"></i>
                  <span *ngIf="!item.registered">{{ l('RegisterWechatApp') }}</span>
                  <span *ngIf="item.registered">{{ l('ReRegisterWechatApp') }}</span>
                </li>
                <!-- 编辑菜单 -->
                <li nz-menu-item (click)="editMenu(item)">
                  <i class="iconfont icon-edit mr-sm"></i>
                  <span>{{ l('EditWechatMenu') }}</span>
                </li>
                <!-- 编辑素材 -->
                <li nz-menu-item (click)="editMaterial(item)">
                  <i class="iconfont icon-edit mr-sm"></i>
                  <span>编辑素材</span>
                </li>
              </ul>
            </nz-dropdown-menu>
          </ng-container>
        </td>
      </tr>
    </tbody>
  </nz-table>

</nz-card>

// src/yoyocmstemplate-vue/src/app/wechat/wechat-app-config.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('WechatAppConfig')"></page-header>
        <a-card :bordered="false">
            <a-form :layout="'vertical'" @submit.prevent="getData">
                <a-row :gutter="8">
                    <!-- 搜索 -->
                    <a-col :sm="24">
                        <a-form-item>
                            <a-input-search
                                name="filterText"
                                :placeholder="l('SearchWithThreeDot')"
                                @search="getData"
                                enterButton
                                v-model="filterText"
                                v-decorator="['filterText']" />
                        </a-form-item>
                    </a-col>
                </a-row>
            </a-form>
            <!-- 操作部分 -->
            <a-row :gutter="8">
                <a-col :md="20" :sm="12">
                    <a-button
                        :type="'primary'"
                        v-if="isGranted('Pages.WechatAppConfig.Create')"
                        @click="createOrEdit()">
                        <a-icon type="plus" />
                        <span>{{l("Create")}}</span>
                    </a-button>
                    <a-button :type="'danger'" v-if="isGranted('Pages.WechatAppConfig.BatchDelete')" @click="batchDelete">
                        <a-icon type="delete" />
                        <span>{{l("BatchDelete")}}</span>
                    </a-button>
                    <a-button v-if="isGranted('Pages.WechatAppConfig.ExportToExcel')" @click="exportToExcel">
                        <a-icon type="file-excel" />
                        <span>{{l("ExportToExcel")}}</span>
                    </a-button>
                </a-col>
            </a-row>

            <!-- 数据部分 -->
            <div class="my-md">
                <a-alert :type="'info'" :showIcon="true">
                    <template slot="message">
                        <span v-html="l('GridSelectedXItemsTips',selectedRowKeys.length)"></span>
                        <a @click="restCheckStatus()" class="ml-md">{{l('ClearEmpty')}}</a>
                        <a-divider type="vertical"></a-divider>
                        <a @click="getData()">{{l('Refresh')}}</a>
                    </template>
                </a-alert>
            </div>

            <a-row>
                <a-table
                    class="list-table"
                    @change="getData"
                    :pagination="false"
                    :rowSelection="{selectedRowKeys: selectedRowKeys,onChange: onSelectChange}"
                    :columns="columns"
                    :rowKey="tableDatas => tableDatas.id"
                    :dataSource="tableData">
                    <div slot="QRCodeUrlSlot" slot-scope="text, record">
                        <img v-if="record.qrCodeUrl" :src="record.qrCodeUrl" @click="showImg(record.qrCodeUrl)" style="width:50px;" />
                    </div>
                    <span slot="actions" slot-scope="text, record">
                        <!-- 修改 -->
                        <a class="table-edit" @click="createOrEdit(record)" v-if="isGranted('Pages.WechatAppConfig.Edit')">
                            <a-icon type="edit" />{{ l('Edit') }}</a>
                        <!-- 删除 -->
                        <a-popconfirm placement="top" v-if="isGranted('Pages.WechatAppConfig.Delete')" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="deleteItem(record)">
                            <template slot="title">
                                {{ l('ConfirmDeleteWarningMessage') }}
                            </template>
                            <a class="table-delete">
                                <a-icon type="delete" />{{ l('Delete') }}</a>
                        </a-popconfirm>
                        <!-- 更多 -->
                        <!-- <a-dropdown v-if="isGrantedAny('Pages.Administration.Languages.ChangeTexts', 'Pages.Administration.Languages.Edit')">
                            <a class="ant-dropdown-link" @click="e => e.preventDefault()">
                                {{ l('Actions') }}
                                <a-icon type="down" />
                            </a>
                            <a-menu slot="overlay">
                                <a-menu-item
                                    v-if="isGranted('Pages.Administration.Languages.ChangeTexts')"
                                    @click="changeTexts(record)">
                                    <a href="javascript:;">
                                        <span>{{ l('ChangeTexts') }}</span>
                                    </a>
                                </a-menu-item>
                                <a-menu-item
                                    v-if="isGranted('Pages.Administration.Languages.Edit')"
                                    @click="setAsDefaultLanguage(record)">
                                    <a href="javascript:;">
                                        <span>{{ l('SetAsDefaultLanguage') }}</span>
                                    </a>
                                </a-menu-item>
                            </a-menu>
                        </a-dropdown> -->
                    </span>
                </a-table>
                <a-pagination
                    class="pagination"
                    size="middle"
                    :total="totalItems"
                    showSizeChanger
                    showQuickJumper
                    :showTotal="showTotalFun"
                    @change="onChange"
                    @showSizeChange="showSizeChange" />
            </a-row>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { ModalHelper } from "@/shared/helpers";
import { WechatAppConfigServiceProxy } from "@/shared/service-proxies";
import CreateOrEditWechatAppConfig from "./create-or-edit-wechat-app-config/create-or-edit-wechat-app-config";
import { appSessionService } from "@/shared/abp";
import moment from "moment";

export default {
    mixins: [AppComponentBase],
    name: "languages",
    components: {
        CreateOrEditWechatAppConfig
    },
    data() {
        return {
            _wechatAppConfigServiceProxy: null,
            // 表格
            columns: [
                {
                    title: this.l("QRCodeUrl"),
                    dataIndex: "QRCodeUrlSlot",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "QRCodeUrlSlot" }
                },
                {
                    title: this.l("WechatAppId"),
                    dataIndex: "appId",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "appId" }
                },
                {
                    title: this.l("WechatName"),
                    dataIndex: "name",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "name" }
                },
                {
                    title: this.l("WechatAppType"),
                    dataIndex: "appTypeStr",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "appTypeStr" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "actions",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "actions" }
                }
            ],
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { sorting: "", maxResultCount: 10, skipCount: 0 },
            // 选择多少项
            selectedRowKeys: [],
            selectedRows: [],
            // 请求参数
            filterText: undefined,
            tableData: [],
            // loading
            spinning: false
        };
    },
    created() {
        this._wechatAppConfigServiceProxy = new WechatAppConfigServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._wechatAppConfigServiceProxy
                .getPaged(
                    this.filterText,
                    this.request.sorting,
                    this.request.maxResultCount,
                    this.request.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.tableData = res.items;
                    this.totalItems = res.totalCount;
                    this.totalPages = Math.ceil(
                        res.totalCount / this.request.maxResultCount
                    );
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                });
        },
        /**
         * 创建编辑
         */
        createOrEdit(item) {
            ModalHelper.create(
                CreateOrEditWechatAppConfig,
                { entity: item },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    this.request.skipCount = 0;
                    this.getData();
                }
            });
        },
        /**
         * table选择事件
         */
        onSelectChange(selectedRowKeys, selectedRows) {
            this.selectedRowKeys = selectedRowKeys;
            this.selectedRows = selectedRows;
            console.log(this.selectedRows);
        },
        /**
         * 批量删除
         */
        batchDelete(e) {
            const selectCount = this.selectedRowKeys.length;
            if (selectCount <= 0) {
                abp.message.warn(this.l("PleaseSelectAtLeastOneItem"));
                return;
            }
            this.message.confirm(
                this.l("ConfirmDeleteXItemsWarningMessage", selectCount),
                res => {
                    if (res) {
                        const ids = _.map(this.selectedRowKeys);
                        console.log(ids);
                        this.spinning = true;
                        this._wechatAppConfigServiceProxy
                            .batchDelete(ids)
                            .finally(() => {
                                this.spinning = false;
                            })
                            .then(() => {
                                this.request.skipCount = 0;
                                this.getData();
                                this.$notification["success"]({
                                    message: this.l("SuccessfullyDeleted")
                                });
                            });
                    }
                }
            );
        },
        /**
         * 导出为excel
         * todo
         */
        exportToExcel() {},
        /**
         * 单个删除
         */
        deleteItem(item) {
            this.spinning = true;
            this._wechatAppConfigServiceProxy
                .delete(item.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(() => {
                    this.request.skipCount = 0;
                    this.getData();
                    this.$notification["success"]({
                        message: this.l("SuccessfullyDeleted")
                    });
                });
        },
        /**
         * 清空选择
         */
        restCheckStatus() {
            this.selectedRowKeys = [];
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * table选择事件
         */
        onSelectChange(selectedRowKeys, selectedRows) {
            this.selectedRowKeys = selectedRowKeys;
            this.selectedRows = selectedRows;
            console.log(this.selectedRows);
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        }
    }
};
</script>

<style scoped lang="less">
.subscriptionEndUtc {
    text-align: center;
}
// table
.list-table {
    i {
        margin-right: 10px;
    }
}
.pagination {
    margin: 10px auto;
    text-align: right;
}
.table-edit {
    .anticon {
        margin-right: 10px;
    }
}
.table-delete,
.ant-dropdown-link {
    margin-left: 20px;
}
</style>
