// src/yoyocmstemplate-angular/src/layout/default/profile/login-attempts-modal.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import { UserLoginServiceProxy, ProfileServiceProxy, UserLoginAttemptDto } from '@shared/service-proxies/service-proxies';
import * as moment from 'moment';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';

@Component({
  selector: 'app-login-attempts-modal',
  templateUrl: './login-attempts-modal.component.html',
  styles: []
})
export class LoginAttemptsModalComponent extends ModalComponentBase implements OnInit {

  userLoginAttempts: UserLoginAttemptDto[];

  constructor(
    _injector: Injector,
    private userLoginService: UserLoginServiceProxy
  ) {
    super(_injector);
  }

  ngOnInit() {
    this.userLoginService.getRecentUserLoginAttempts()
      .subscribe(result => {
        this.userLoginAttempts = result.items;
      });
  }

  getLoginAttemptTime(userLoginAttempt: UserLoginAttemptDto): string {
    return moment(userLoginAttempt.creationTime).fromNow() + ' (' + moment(userLoginAttempt.creationTime).format('YYYY-MM-DD hh:mm:ss') + ')';
  }

}

<div class="modal-header">
  <div class="modal-title">{{l('LoginAttempts')}}</div>
</div>

<nz-card *ngFor="let item of userLoginAttempts" style="margin-top: 15px;">
  <div nz-row [nzGutter]="8">
    <div nz-col [nzSpan]="3">
      <label>{{l('LoginState')}}</label>
    </div>

    <div nz-col [nzSpan]="10">
      <nz-badge *ngIf="item.result == 'Success'" [nzStatus]="'success'" [nzText]="l('Success')"></nz-badge>
      <nz-badge *ngIf="item.result != 'Success'" [nzStatus]="'error'" [nzText]="l('Failed')"></nz-badge>
    </div>
  </div>
  <div nz-row [nzGutter]="8">
    <div nz-col [nzSpan]="3">
      <label>{{l('IpAddress')}}:</label>
    </div>

    <div nz-col [nzSpan]="10">
      {{item.clientIpAddress}}
    </div>
  </div>

  <div nz-row [nzGutter]="8">
    <div nz-col [nzSpan]="3">
      <label>{{l('Client')}}:</label>
    </div>

    <div nz-col [nzSpan]="10">
      {{item.clientName}}
    </div>
  </div>

  <div nz-row [nzGutter]="8">
    <div nz-col [nzSpan]="3">
      <label>{{l('Browser')}}:</label>
    </div>

    <div nz-col [nzSpan]="10">
      {{item.browserInfo}}
    </div>
  </div>

  <div nz-row [nzGutter]="8">
    <div nz-col [nzSpan]="3">
      <label>{{l('Time')}}:</label>
    </div>

    <div nz-col [nzSpan]="10">
      {{getLoginAttemptTime(item)}}
    </div>
  </div>
</nz-card>

// src/yoyocmstemplate-vue/src/layout/default/profile/login-attempts-modal.vue
<template>
  <div class="example">
    <!-- 加载中... -->
    <a-spin v-if="isLoading"/>
    <div class="modal-header">
      <div class="modal-title">{{l('LoginAttempts')}}</div>
    </div>
    <a-card v-for="item in userLoginAttempts">
      <a-row :gutter="8">
        <a-col :span="3">
          <label>{{l('LoginState')}}</label>
        </a-col>

        <a-col :span="10">
          <a-badge v-if="item.result == 'Success'" :text="l('Success')" status="success" />
          <a-badge v-if="item.result != 'Success'" :text="l('Failed')" status="error" />
        </a-col>
      </a-row>
        <a-row :gutter="8">
          <a-col :span="3">
            <label>{{l('IpAddress')}}:</label>
          </a-col>
          <a-col :span="10">{{item.clientIpAddress}}</a-col>
        </a-row>

        <a-row :gutter="8">
          <a-col :span="3">
            <label>{{l('Client')}}:</label>
          </a-col>
          <a-col :span="10">{{item.clientName}}</a-col>
        </a-row>
        <a-row :gutter="8">
          <a-col :span="3">
            <label>{{l('Browser')}}:</label>
          </a-col>
          <a-col :span="10">{{item.browserInfo}}</a-col>
        </a-row>
        <a-row :gutter="8">
          <a-col :span="3">
            <label>{{l('Time')}}:</label>
          </a-col>
          <a-col :span="10">{{getLoginAttemptTime(item)}}</a-col>
        </a-row>
    </a-card>
  </div>
</template>

<script>
import { ModalComponentBase } from "@/shared/component-base";
import moment from "moment";

import {
  UserLoginServiceProxy,
  ProfileServiceProxy,
  UserLoginAttemptDto
} from "../../../shared/service-proxies";

export default {
  name: "login-attempts-modal",
  mixins: [ModalComponentBase],
  data() {
    return {
      isLoading:true,
      userLoginAttempts: [],
      userLoginService: null
    };
  },
  created() {
    this.userLoginService = new UserLoginServiceProxy(this.$apiUrl, this.$api);
    this.userLoginService.getRecentUserLoginAttempts().then(result => {
      this.isLoading=false;
      this.userLoginAttempts = result.items;
    });
  },
  methods: {
    getLoginAttemptTime(userLoginAttempt) {
      return (
        moment(userLoginAttempt.creationTime).fromNow() +
        " (" +
        moment(userLoginAttempt.creationTime).format("YYYY-MM-DD hh:mm:ss") +
        ")"
      );
    }
  }
};
</script>

<style scoped>

</style>
