// src/yoyocmstemplate-angular/src/app/admin/tenants/edit-tenant/edit-tenant.component.ts
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import { Component, OnInit, Injector, Input } from '@angular/core';
import { TenantServiceProxy, TenantEditDto, SubscribableEditionComboboxItemDto } from '@shared/service-proxies/service-proxies';
import { finalize } from 'rxjs/operators';


@Component({
  selector: 'app-edit-tenant',
  templateUrl: './edit-tenant.component.html',
  styles: []
})
export class EditTenantComponent extends ModalComponentBase implements OnInit {

  @Input()
  entityId: number;
  entity: TenantEditDto = new TenantEditDto();
  isUnlimited: boolean;
  connectionString: string;
  edition: SubscribableEditionComboboxItemDto;
  subscriptionEndUtc: any;


  constructor(
    injector: Injector,
    private _tenantService: TenantServiceProxy
  ) {
    super(injector);
  }

  ngOnInit() {
    this.saving = true;

    this._tenantService.getForEdit(this.entityId)
      .pipe(finalize(() => {
        this.saving = false;
      })).subscribe((result) => {
        this.entity = result;
        this.subscriptionEndUtc = this.entity.subscriptionEndUtc ? this.entity.subscriptionEndUtc.toDate() : null;
        this.connectionString = this.entity.connectionString;
        this.isUnlimited = !this.entity.subscriptionEndUtc;
      });
  }

  save() {
    this.saving = true;

    // 版本
    this.entity.editionId = this.edition ? parseInt(this.edition.value) : null;
    // 如果没有选择版本或勾选了无限期使用，订阅时间设置为null
    this.entity.subscriptionEndUtc = (!this.entity.editionId || this.isUnlimited) ? null : this.subscriptionEndUtc;

    this._tenantService.update(this.entity)
      .pipe(finalize(() => {
        this.saving = false;
      })).subscribe(() => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success();
      });
  }

  selectedEditionChange(edtion: SubscribableEditionComboboxItemDto) {
    this.edition = edtion;
  }
}

<div class="modal-header">
  <div class="modal-title">
    {{l('EditTenant')}}:
    <span *ngIf="entity">{{entity.tenancyName}}</span>
  </div>
</div>

<nz-spin [nzSpinning]="saving">
  <form nz-form #validateForm="ngForm" (ngSubmit)="save()" nzLayout="vertical">

    <!-- 名称 -->
    <nz-form-item>
      <nz-form-label nzFor="Name" nzRequired>{{l('DisplayTenancyName')}}</nz-form-label>
      <nz-form-control nzHasFeedback>
        <input nz-input name="name" #name="ngModel" [(ngModel)]="entity.name" [placeholder]="l('Name')" required>
        <nz-form-control nzExtra *ngIf="name.control.dirty&&name.control.errors">
          <ng-container *ngIf="name.control.hasError('required')">{{l('ThisFieldIsRequired')}}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>

    <!-- 自定义数据库链接字符串 -->
    <nz-form-item *ngIf="connectionString">
      <nz-form-label nzFor="connectionString" nzRequired>{{l('DatabaseConnectionString')}}</nz-form-label>
      <nz-form-control nzHasFeedback>
        <input nz-input name="connectionString" #connectionString="ngModel" [(ngModel)]="entity.connectionString"
          [placeholder]="l('DatabaseConnectionString')+l('Optional')" required>
        <nz-form-control nzExtra *ngIf="connectionString.control.dirty&&connectionString.control.errors">
          <ng-container *ngIf="connectionString.control.hasError('required')">{{l('ThisFieldIsRequired')}}
          </ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>

    <!-- 版本 -->
    <nz-form-item>
      <nz-form-label>{{l('Edition')}}</nz-form-label>
      <nz-form-control>
        <edition-combo [editionId]="entity.editionId" [placeholder]="l('PleaseSelect')"
          (selectedEditionChange)="selectedEditionChange($event)"></edition-combo>
      </nz-form-control>
    </nz-form-item>

    <!-- 无限时间订阅 -->
    <nz-form-control *ngIf="entity.editionId">
      <label nz-checkbox name="isUnlimited" #isUnlimitedInput="ngModel"
        [(ngModel)]="isUnlimited">{{l("IsUnlimited")}}</label>
    </nz-form-control>

    <!-- 结束时间 -->
    <nz-form-item *ngIf="entity.editionId&&!isUnlimited">
      <nz-form-label nzFor="subscriptionEndUtc" nzRequired>{{l('SubscriptionEndDateUtc')}}</nz-form-label>
      <nz-form-control nzHasFeedback nzRequired>
        <nz-date-picker name="subscriptionEndUtc" #subscriptionEndUtcInput="ngModel" [(ngModel)]="subscriptionEndUtc"
          required></nz-date-picker>
        <nz-form-control nzExtra *ngIf="subscriptionEndUtcInput.control.dirty&&subscriptionEndUtcInput.control.errors">
          <ng-container *ngIf="subscriptionEndUtcInput.control.hasError('required')">{{l('ThisFieldIsRequired')}}
          </ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>

    <!-- 是否试用 -->
    <nz-form-control>
      <label nz-checkbox name="isInTrialPeriod" #isInTrialPeriodInput="ngModel" [(ngModel)]="entity.isInTrialPeriod"
        [nzDisabled]="edition&&edition.isFree">{{l("IsInTrialPeriod")}}</label>
    </nz-form-control>

    <!-- 激活 -->
    <nz-form-control>
      <label nz-checkbox name="isActive" #isActiveInput="ngModel"
        [(ngModel)]="entity.isActive">{{l("IsActive")}}</label>
    </nz-form-control>


    <!-- 功能按钮 -->
    <div class="modal-footer">
      <button nz-button type="button" [disabled]="saving" (click)="close()">
        {{l("Cancel")}}
      </button>
      <button nz-button [nzType]="'primary'" type="submit" [disabled]="!validateForm.valid||saving">
        {{l("Save")}}
      </button>
    </div>


  </form>
</nz-spin>

// src/yoyocmstemplate-vue/src/app/admin/tenants/edit-tenant/edit-tenant.vue
<template>
    <a-spin :spinning="spinning">
        <div class="modal-header">
            <div class="modal-title">{{l('EditTenant')}} <span v-if="entity">:{{entity.tenancyName}}</span></div>
        </div>
        <a-form :form="form" @submit="handleSubmit">
            <!-- 租户显示名称 -->
            <a-form-item :label="l('DisplayTenancyName')">
                <a-input
                    :placeholder="l('Name')"
                    v-decorator="[
                        'name',
                        {
                            rules: [
                                {
                                    required: true,
                                message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]" />
            </a-form-item>

            <!-- UseHostDatabase -->
            <a-form-item :label="l('DatabaseConnectionString')" v-if="entity.connectionString">
                <a-input
                    :placeholder="l('DatabaseConnectionString')+l('Optional')"
                    v-decorator="[
                        'connectionString',
                        {
                            rules: [
                                {
                                    required: true,
                                message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]" />
            </a-form-item>

            <!-- 版本 -->
            <a-form-item :label="l('Edition')" has-feedback v-if="isShowEdition">
                <edition-combo
                    :placeholder="l('PleaseSelect')"
                    :selectedEdition="selectedEdition"
                    @selectedEditionChange="selectedEditionChange($event)"></edition-combo>
            </a-form-item>

            <!-- IsUnlimited -->
            <a-checkbox @change="checkedChange('IsUnlimitedchecked', $event)"
                v-if="isShowIsUnlimited" :checked="IsUnlimitedchecked">{{l("IsUnlimited")}}</a-checkbox>
            <a-form-item :label="l('SubscriptionEndDateUtc')" v-if="!IsUnlimitedchecked && isShowIsUnlimited">
                <a-date-picker
                    @change="subscriptionEndDateUtconChange"
                    placeholder="请选择日期"
                    v-decorator="[
                        'subscriptionEndUtc',
                        {
                            rules: [
                                {
                                    required: true,
                                    message: l('ThisFieldIsRequired'),
                                }
                            ],
                        },
                        ]" />
            </a-form-item>
            <br>

            <!-- 是否试用 -->
            <a-checkbox @change="checkedChange('isInTrialPeriod', $event)"
                :disabled="IsInTrialPerioddisabled"
                :checked="isInTrialPeriod">{{l("IsInTrialPeriod")}}</a-checkbox>
            <br>

            <!-- 是否激活 -->
            <a-checkbox @change="checkedChange('isActive', $event)" :checked="isActive">{{l("IsActive")}}</a-checkbox>

            <a-form-item class="btn--container">
                <a-button type="button" @click="close()">
                    {{ l("Cancel") }}
                </a-button>
                <a-button type="primary" html-type="submit">
                    {{ l('Save') }}
                </a-button>
            </a-form-item>
        </a-form>
    </a-spin>
</template>

<script>
import { ModalComponentBase } from "@/shared/component-base";
import EditionCombo from "../../shared/edition-combo/edition-combo.vue";
import {
    TenantServiceProxy,
    TenantListDto,
    SubscribableEditionComboboxItemDto,
    EntityDtoOfInt64,
    NameValueDto,
    CommonLookupServiceProxy,
    CommonLookupFindUsersInput
} from "@/shared/service-proxies";
import pick from "lodash.pick";

export default {
    mixins: [ModalComponentBase],
    name: "create-tenant-component",
    data() {
        return {
            confirmDirty: false,
            // 版本
            selectedEdition: {},
            // 是否在试用期
            isInTrialPeriod: false,
            IsInTrialPerioddisabled: false,
            // 下次登录需要修改密码
            shouldChangePasswordOnNextLogin: false,
            // 发送激活邮件
            sendActivationEmail: false,
            // 是否激活
            isActive: true,
            IsUnlimitedchecked: false,
            // IsUnlimited
            isShowIsUnlimited: false,
            // 版本号
            editionId: 0,
            spinning: false,
            isShowEdition: false,
            // 获取到的数据
            entity: {},
            entityId: 0
        };
    },
    components: {
        EditionCombo
    },
    // watch: {
    //     entityId(val) {
    //         if (val) {
    //             console.log(val);
    //         }
    //     }
    // },
    beforeCreate() {
        this.form = this.$form.createForm(this, { name: "register" });
    },
    created() {
        this.fullData(); // 模态框必须,填充数据到data字段
    },
    mounted() {
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._tenantService = new TenantServiceProxy(
                this.$apiUrl,
                this.$api
            );
            this._tenantService
                .getForEdit(this.entityId)
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    console.log(res);
                    this.entity = res;
                    this.selectedEdition.value = this.entity.editionId ? this.entity.editionId : 0;
                    setTimeout(() => {
                        this.form.setFieldsValue(
                            pick(
                                this.entity,
                                "name",
                                "connectionString",
                                "subscriptionEndUtc"
                            )
                        );
                        this.IsUnlimitedchecked = !this.entity
                            .subscriptionEndUtc;
                        this.isActive = this.entity.isActive;
                    }, 500);
                    this.isShowEdition = true;
                });
        },
        /**
         * 验证密码
         */
        /**
         * 版本选择
         */
        selectedEditionChange(e) {
            if (e && e.value) {
                this.IsInTrialPerioddisabled = true;
                this.isShowIsUnlimited = true;
                this.editionId = parseInt(e.value);
            } else {
                this.IsInTrialPerioddisabled = false;
                this.isShowIsUnlimited = false;
                this.editionId = null;
            }
        },
        /**
         * 是否试用
         * 下次登录需要修改密码
         * 发送激活邮
         * 是否激活
         */
        checkedChange(type, e) {
            this[`${type}`] = eval(`${e.target.checked}`.toLowerCase());
        },
        /**
         * 订阅结束日期
         */
        subscriptionEndDateUtconChange(date, dateString) {
            console.log(date, dateString);
        },
        /**
         * 提交表单
         */
        handleSubmit(e) {
            e.preventDefault();
            this.form.validateFieldsAndScroll((err, values) => {
                if (!err) {
                    let otherobj = {
                        isInTrialPeriod: this.isInTrialPeriod,
                        isActive: this.isActive,
                        editionId: this.editionId,
                        tenancyName: this.entity.tenancyName,
                        id: this.entityId
                    };
                    values = Object.assign(values, otherobj);
                    values.subscriptionEndUtc =
                        !this.editionId || this.IsUnlimitedchecked
                            ? null
                            : values.subscriptionEndUtc;
                    this.spinning = true;
                    this._tenantService = new TenantServiceProxy(
                        this.$apiUrl,
                        this.$api
                    );
                    this._tenantService
                        .update(values)
                        .finally(() => {
                            this.spinning = false;
                        })
                        .then(res => {
                            // this.notify.success(this.l('SavedSuccessfully'));
                            this.$notification["success"]({
                                message: this.l("SavedSuccessfully")
                            });
                            this.success();
                        })
                        .catch(err => {
                            console.log(err);
                        });
                }
            });
        }
    }
};
</script>

<style lang="less" scoped>
/deep/.btn--container .ant-form-item-children {
    display: block;
    margin: 10px auto;
    text-align: center;
}
</style>
