// src/yoyocmstemplate-angular/src/app/admin/organization-units/organization-unit-members-panel/organization-unit-members-panel.component.ts
import { Component, OnInit, Output, EventEmitter, Injector } from '@angular/core';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import {
  OrganizationUnitUserListDto,
  OrganizationUnitServiceProxy,
  PagedResultDtoOfOrganizationUnitUserListDto,
} from '@shared/service-proxies/service-proxies';
import { NzTreeNode } from 'ng-zorro-antd/tree';
import { finalize } from 'rxjs/operators';
import * as _ from 'lodash';
import { AddMemberComponent } from '@app/admin/organization-units/add-member/add-member.component';

@Component({
  selector: 'app-organization-unit-members-panel',
  templateUrl: './organization-unit-members-panel.component.html',
  styles: [],
})
export class OrganizationUnitMembersPanelComponent extends PagedListingComponentBase<OrganizationUnitUserListDto>
  implements OnInit {
  @Output() memberRemoved = new EventEmitter<number[]>();
  @Output() membersAdded = new EventEmitter<number[]>();

  /**
   * 搜索文本
   */
  filterText = '';

  /**
   * 当前选中机构节点
   */
  private _organizationUnit: NzTreeNode = null;

  /**
   * 当前选中机构
   */
  get organizationUnit(): NzTreeNode {
    return this._organizationUnit;
  }

  set organizationUnit(ou: NzTreeNode) {
    if (this._organizationUnit === ou) {
      return;
    }
    this._organizationUnit = ou;
    if (ou) {
      this.refresh();
    }
  }

  /**
   * 构造函数
   * @param injector 注入器
   * @param _organizationUnitService 组织机构服务
   */
  constructor(injector: Injector, private _organizationUnitService: OrganizationUnitServiceProxy) {
    super(injector);
  }
  ngOnInit() {}

  /**
   * 获取数据列表
   * @param request 分页请求必须参数
   * @param pageNumber 当前页码
   * @param finishedCallback 完成后回调函数
   */
  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    if (!this._organizationUnit) {
      return;
    }

    this._organizationUnitService
      .getPagedOrganizationUnitUsers(
        // tslint:disable-next-line:radix
        parseInt(this._organizationUnit.key),
        this.filterText,
        request.sorting,

        request.maxResultCount,
        request.skipCount,
      )
      .pipe(
        finalize(() => {
          finishedCallback();
        }),
      )
      .subscribe((result: PagedResultDtoOfOrganizationUnitUserListDto) => {
        this.dataList = result.items;

        this.showPaging(result);
      });
  }

  /**
   * 移除用户
   * @param user 当前用户实体
   */
  removeMember(user: OrganizationUnitUserListDto): void {
    // tslint:disable-next-line:radix
    const _ouId = parseInt(this.organizationUnit.key);
    this._organizationUnitService.removeUser(user.id, _ouId).subscribe(() => {
      this.refreshGoFirstPage();
      this.notify.success(this.l('SuccessfullyRemoved'));
      this.memberRemoved.emit([user.id]);
    });
  }
  /**
   * 批量删除
   */
  batchDelete(): void {
    const selectCount = this.selectedDataItems.length;
    debugger;
    console.log(this.selectedDataItems);
    if (selectCount <= 0) {
      abp.message.warn(this.l('PleaseSelectAtLeastOneItem'));
      return;
    }
    this.message.confirm(this.l('ConfirmDeleteXItemsWarningMessage', selectCount), undefined, res => {
      if (res) {
        // tslint:disable-next-line:radix
        const _ouId = parseInt(this.organizationUnit.key);
        const ids = _.map(this.selectedDataItems, 'id');
        this._organizationUnitService.batchRemoveUserFromOrganizationUnit(_ouId, ids).subscribe(() => {
          this.refreshGoFirstPage();
          this.notify.success(this.l('SuccessfullyDeleted'));
          this.memberRemoved.emit(ids);
        });
      }
    });
  }
  /**
   * 增加成员
   */
  addUser(): void {
    this.modalHelper
      .static(AddMemberComponent, {
        // tslint:disable-next-line:radix
        organizationUnitId: parseInt(this.organizationUnit.key),
      })
      .subscribe((res: number[]) => {
        if (res) {
          this.addMembers(res);
        }
      });
  }

  /**
   * 新增后广播事件
   * @param data 新增后回传数据
   */
  addMembers(userIds: number[]): void {
    this.membersAdded.emit(userIds);
    this.refresh();
  }
  /**
   * 清除条件并刷新
   */
  clearFilterAndRefresh(): void {
    this.filterText = '';
    this.refresh();
  }
}

<nz-card>
  <ng-container *ngIf="organizationUnit">
    <!-- 检索表单 -->
    <form nz-form [nzLayout]="'inline'" (ngSubmit)="refresh()" autocomplete="off">
      <nz-form-control>
        <nz-row nzGutter="8">
          <!-- 左边搜索框 -->
          <nz-col nzSpan="16">
            <nz-input-group nzSearch [nzAddOnAfter]="suffixButton">
              <input type="text" nz-input [(ngModel)]="filterText" (keyup.enter)="refresh()" name="filterText"
                [placeholder]="l('SearchWithThreeDot')" />
              <ng-template #suffixButton>
                <button nz-button nzType="primary" nzSearch type="submit">
                  <i class="iconfont icon-search "></i>
                  <!-- <i class="iconfont icon-search"></i> -->
                </button>
              </ng-template>
            </nz-input-group>
          </nz-col>
          <!-- 右边弹框 -->
          <nz-col nzSpan="8" class="text-right">
            <ng-container *ngIf="organizationUnit">
              <ng-container *ngIf="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')">
                <a (click)="addUser()">
                  <!-- <i iconfont icon-plus></i>  -->
                  <i class="iconfont icon-plus "></i>
                  {{ l('AddUser') }}
                </a>
                <nz-divider nzType="vertical"></nz-divider>
              </ng-container>
              <ng-container *ngIf="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')">
                <a (click)="batchDelete()">
                  <!-- <i class="iconfont icon-delete"></i>  -->
                  <i class="iconfont icon-delete "></i>
                  {{ l('BatchDelete') }}
                </a>
                <nz-divider nzType="vertical"></nz-divider>
              </ng-container>
              <a class="ml-sm">
                <!-- <i class="iconfont icon-reload" nz-tooltip [nzTooltipTitle]="l('Refresh')"
                  (click)="clearFilterAndRefresh()"></i> -->

                <i class="iconfont icon-reload " nz-tooltip [nzTooltipTitle]="l('Refresh')"
                  (click)="clearFilterAndRefresh()"></i>
              </a>
            </ng-container>
          </nz-col>
        </nz-row>
      </nz-form-control>
    </form>
    <!-- 复选框提示的内容数据部分 -->
    <table-checkbox-panel [selectLength]="selectedDataItems.length" (onClear)="restCheckStatus(dataList)"
      (onRefresh)="refreshGoFirstPage()"></table-checkbox-panel>

    <nz-table #ajaxTable [nzFrontPagination]="false" [nzShowQuickJumper]="true" [nzShowSizeChanger]="true"
      [nzData]="dataList" [nzTotal]="totalItems" [nzLoading]="isTableLoading" [(nzPageIndex)]="pageNumber"
      [(nzPageSize)]="pageSize" (nzPageIndexChange)="refresh()" (nzPageSizeChange)="refresh()"
      [nzNoResult]="noDataTemplate" [nzShowTotal]="showTotalTemplate">
      <!-- 暂无数据 -->
      <ng-template #noDataTemplate>
        <no-data></no-data>
      </ng-template>
      <!-- 分页信息显示 当前 1 页/共 3 页，共 5 条/显示 1-2 条 -->
      <ng-template #showTotalTemplate let-total let-range="range">
        {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
      </ng-template>
      <!-- 表头 -->
      <thead (nzSortChange)="gridSort($event)">
        <tr>
          <th nzShowCheckbox [(nzChecked)]="allChecked" [nzDisabled]="allCheckboxDisabled"
            [nzIndeterminate]="checkboxIndeterminate" (nzCheckedChange)="checkAll($event)"></th>
          <th nzWidth="150px" class="text-center">
            <span>{{ l('Actions') }}</span>
          </th>
          <th nzShowSort nzSortKey="userName">
            <span>{{ l('UserName') }}</span>
          </th>
          <th nzShowSort nzSortKey="addedTime" class="text-center">
            <span>{{ l('AddedTime') }}</span>
          </th>
        </tr>
      </thead>
      <!-- 表格内容 -->
      <tbody>
        <tr *ngFor="let item of ajaxTable.data">
          <td nzShowCheckbox [(nzChecked)]="item.checked" (nzCheckedChange)="refreshCheckStatus(dataList)"></td>
          <td class="text-center">
            <!-- 删除 -->
            <ng-container *ngIf="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')">
              <a nz-popconfirm
                [nzPopconfirmTitle]="l('RemoveUserFromOuWarningMessage', item.userName, organizationUnit.title)"
                (nzOnConfirm)="removeMember(item)" [nzOkText]="l('Ok')" [nzCancelText]="l('Cancel')">
                <i class="iconfont icon-delete mr-sm"></i>
                <!-- <i class="iconfont icon-delete mr-sm"></i> -->
                <span>{{ l('Delete') }}</span>
              </a>
            </ng-container>
          </td>
          <td>
            {{ item.userName }}
          </td>
          <td class="text-center">
            {{ item.addedTime | _moment }}
          </td>
        </tr>
      </tbody>
    </nz-table>

  </ng-container>

  <div class="text-center" *ngIf="!organizationUnit">
    <no-data [text]="l('SelectAnOrganizationUnitToSeeMembers')"></no-data>
  </div>
</nz-card>

// src/yoyocmstemplate-vue/src/app/admin/organization-units/organization-unit-members-panel/organization-unit-members-panel.vue
<template>
    <a-spin :spinning="spinning">
        <div class="user-container">
            <div class="table--container">
                <!-- 操作 -->
                <a-row :gutter="8" class="opeattion-container">
                    <a-col :span="16">
                        <a-input-search
                            name="filterText"
                            @search="getData"
                            :placeholder="l('SearchWithThreeDot')"
                            enterButton
                            v-model="filterText" />
                    </a-col>
                    <a-col :span="6" :offset="2">
                        <a @click="addUser()" v-if="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')">
                            <a-icon type="plus" /> {{ l('AddUser') }} </a>
                        <a-divider v-if="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')" type="vertical"></a-divider>
                        <a @click="batchDelete()" v-if="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')">
                            <a-icon type="delete" />{{ l('BatchDelete') }} </a>
                        <a-divider type="vertical" v-if="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')"></a-divider>
                        <a :title="l('Refresh')" @click="clearFilterAndRefresh()">
                            <a-icon type="reload" /></a>
                    </a-col>
                </a-row>
                <!-- 数据部分 -->
                <div class="my-md">
                    <a-alert :type="'info'" :showIcon="true">
                        <template slot="message">
                            <span v-html="l('GridSelectedXItemsTips',selectedRowKeys.length)"></span>
                            <a @click="restCheckStatus()" class="ml-md">{{l('ClearEmpty')}}</a>
                            <a-divider type="vertical"></a-divider>
                            <a @click="clearFilterAndRefresh()">{{l('Refresh')}}</a>
                        </template>
                    </a-alert>
                </div>
                <a-table
                    @change="handleChange"
                    :rowSelection="{ selectedRowKeys: selectedRowKeys, onChange: onSelectChange }"
                    :columns="columns"
                    :rowKey="data => data.id"
                    :dataSource="data">
                    <span slot="actions" v-if="isGranted('Pages.Administration.OrganizationUnits.ManageUsers')" slot-scope="text, record">
                        <a-popconfirm placement="top" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="removeMember(record)">
                            <template slot="title">
                                {{ l('RemoveUserFromOuWarningMessage', record.userName, selectTree.displayName) }}
                            </template>
                            <a class="table-delete">
                                <a-icon type="delete" />{{ l('Delete') }}</a>
                        </a-popconfirm>
                    </span>
                </a-table>
            </div>
        </div>
        <a-pagination
            class="pagination"
            size="middle"
            :total="totalItems"
            showSizeChanger
            showQuickJumper
            :showTotal="showTotalFun"
            @change="onChange"
            @showSizeChange="showSizeChange" />
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { OrganizationUnitServiceProxy } from "@/shared/service-proxies";
import { ModalHelper } from "@/shared/helpers";
import Bus from "@/shared/bus/bus";
import AddMemberComponent from "../add-member/add-member";

export default {
    name: "organization-unit-members-panel",
    mixins: [AppComponentBase],
    data() {
        return {
            spinning: false,
            _organizationUnitServiceProxy: null,
            selectedRowKeys: [],
            filteredInfo: null,
            sortedInfo: null,
            filterText: "",
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { maxResultCount: 10, skipCount: 0 },
            // 用户表格
            columns: [
                {
                    title: this.l("UserName"),
                    dataIndex: "userName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "userName" }
                },
                {
                    title: this.l("AddedTime"),
                    dataIndex: "addedTimeStr",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "addedTime" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "actions",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "actions" }
                }
            ],
            // 用户数据
            data: []
        };
    },
    computed: {},
    created() {
        this._organizationUnitServiceProxy = new OrganizationUnitServiceProxy(
            this.$apiUrl,
            this.$api
        );
        // 接受树结构传过来的选中item
        Bus.$on("selectedNode", this.getTree);
        // // 添加用户成功
        // Bus.$on("saveAddMemberSuccess", data => {
        //     if (data) {
        //         this.clearFilterAndRefresh();
        //     }
        // });
    },
    beforeDestroy() {
        Bus.$off("selectedNode");
    },
    methods: {
        /**
         * 选中树结构
         */
        getTree(data) {
            this.selectTree = data;
            this.getData();
        },
        /**
         * 拉取数据
         */
        getData() {
            this.spinning = true;
            this._organizationUnitServiceProxy
                .getPagedOrganizationUnitUsers(
                    this.selectTree.id,
                    this.filterText,
                    "",
                    this.request.maxResultCount,
                    this.request.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(result => {
                    this.data = result.items.map(o => {
                        return {
                            ...o,
                            addedTimeStr: o.addedTime.format(
                                "YYYY-MM-DD HH:mm:ss"
                            )
                        };
                    });
                    this.totalItems = result.totalCount;
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                    this.totalPages = Math.ceil(
                        result.totalCount / this.request.maxResultCount
                    );
                    console.log(result);
                });
        },
        /**
         * 选中table
         */
        onSelectChange(selectedRowKeys) {
            console.log("selectedRowKeys changed: ", selectedRowKeys);
            this.selectedRowKeys = selectedRowKeys;
        },
        handleChange(pagination, filters, sorter) {
            console.log("Various parameters", pagination, filters, sorter);
            this.filteredInfo = filters;
            this.sortedInfo = sorter;
        },
        /**
         * 清除条件并刷新
         */
        clearFilterAndRefresh() {
            this.request = { maxResultCount: 10, skipCount: 0 };
            this.filterText = "";
            this.getData();
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        },
        /**
         * 移除用户
         * @param user 当前用户实体
         */
        removeMember(user) {
            console.log(user);
            const _ouId = parseInt(this.selectTree.id);
            this._organizationUnitServiceProxy
                .removeUser(user.id, _ouId)
                .then(() => {
                    this.$notification["success"]({
                        message: this.l("SuccessfullyRemoved")
                    });
                    this.clearFilterAndRefresh();
                    Bus.$emit("reloadOrganizationUnitTree", true);
                    // this.refreshGoFirstPage();
                    // this.memberRemoved.emit([user.id]);
                });
        },
        /**
         * 清空选择
         */
        restCheckStatus() {
            this.selectedRowKeys = [];
        },
        /**
         * 批量删除
         */
        batchDelete() {
            const selectCount = this.selectedRowKeys.length;
            if (selectCount <= 0) {
                abp.message.warn(this.l("PleaseSelectAtLeastOneItem"));
                return;
            }
            this.message.confirm(
                this.l("ConfirmDeleteXItemsWarningMessage", selectCount),
                res => {
                    if (res) {
                        console.log(res);
                        const _ouId = parseInt(this.selectTree.id);
                        const ids = _.map(this.selectedRowKeys);
                        this._organizationUnitServiceProxy
                            .batchRemoveUserFromOrganizationUnit(_ouId, ids)
                            .then(() => {
                                // this.refreshGoFirstPage();
                                this.notify.success(
                                    this.l("SuccessfullyDeleted")
                                );
                                this.clearFilterAndRefresh();
                                Bus.$emit("reloadOrganizationUnitTree", true);
                                // this.memberRemoved.emit(ids);
                            });
                    }
                }
            );
        },
        /**
         * 增加用户
         */
        addUser() {
            ModalHelper.create(AddMemberComponent, {
                organizationUnitId: parseInt(this.selectTree.id)
            }).subscribe(res => {
                if (res) {
                    this.clearFilterAndRefresh();
                }
            });
        }
    }
};
</script>

<style scoped lang="less">
.user-container {
    border: 1px solid #e8e8e8;
    margin: 20px;
    padding: 20px;
    .table-delete {
        i {
            margin-right: 10px;
        }
    }
}
.opeattion-container {
    margin: 20px 0;
}
.pagination {
    margin: 10px auto;
    text-align: right;
}
</style>
