// src/yoyocmstemplate-angular/src/app/admin/shared/timing/timezone-combo.component.ts
import { Component, EventEmitter, Injector, Input, OnInit, Output } from '@angular/core';
import { SettingScopes, NameValueDto, TimingServiceProxy } from '@shared/service-proxies/service-proxies';
import { AppComponentBase } from '@shared/component-base';

@Component({
    selector: 'timezone-combo',
    template:
    `<nz-select [(ngModel)]="selectedTimeZone" (ngModelChange)="selectedTimeZoneChange.emit($event)">
        <nz-option *ngFor="let timeZone of timeZones" [nzLabel]="timeZone.name" [nzValue]="timeZone.value"></nz-option>
    </nz-select>`
})
export class TimeZoneComboComponent extends AppComponentBase implements OnInit {

    @Output() selectedTimeZoneChange: EventEmitter<string> = new EventEmitter<string>();

    timeZones: NameValueDto[] = [];

    @Input() selectedTimeZone: string = undefined;
  @Input() defaultTimezoneScope: SettingScopes;

    constructor(
        private _timingService: TimingServiceProxy,
        injector: Injector) {
        super(injector);
    }

    ngOnInit(): void {
        const self = this;
        self._timingService.getTimezones(self.defaultTimezoneScope).subscribe(result => {
            self.timeZones = result.items;
        });
    }
}

// src/yoyocmstemplate-vue/src/app/admin/shared/timezone-combo/timezone-combo.vue
<template>
    <a-select :defaultValue="selectedTimeZoneVal" @change="selectChange($event)">
        <a-select-option v-for="item in timeZones" :key="item.value" :value="item.value">{{ item.name }}</a-select-option>
    </a-select>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { TimingServiceProxy } from "@/shared/service-proxies";

export default {
    name: "timezone-combo",
    mixins: [AppComponentBase],
    props: ["selectedTimeZone", "defaultTimezoneScope"],
    data() {
        return {
            timingService: null,
            timeZones: [],
            selectedTimeZoneVal: this.selectedTimeZone
        };
    },
    created() {
        this.timingService = new TimingServiceProxy(this.$apiUrl, this.$api);
    },
    mounted() {
        this.timingService
            .getTimezones(this.defaultTimezoneScope)
            .then(result => {
                this.timeZones = result.items;
            });
    },
    methods: {
        selectChange(val) {
            this.$emit("selectedTimeZoneChange", val);
        }
    },
    watch: {}
};
</script>

<style scoped>
</style>
