// src/yoyocmstemplate-vue/src/account/account-languages/account-languages.vue
<template>
  <ul class="account-language-switch-list">
    <li :key="index" v-for="(language,key,index) of languages">
      <a
        v-if="language.name != currentLanguage.name"
        href="javascript:void();"
        v-bind:title="language.displayName"
        @click="changeLanguage(language.name)"
      >
        <i v-bind:class="language.icon"></i>
      </a>
    </li>
  </ul>
</template>

<script>
import * as _ from "lodash";
import { abpService } from "@/shared/abp";

export default {
  name: "account-languages",
  computed: {
    languages: vm => {
      return _.filter(
        abpService.abp.localization.languages,
        l => !l.isDisabled
      );
    },
    currentLanguage: vm => {
      return abpService.abp.localization.currentLanguage;
    }
  },
  methods: {
    changeLanguage(languageName) {
      abpService.abp.utils.setCookieValue(
        "Abp.Localization.CultureName",
        languageName,
        new Date(new Date().getTime() + 5 * 365 * 86400000), // 5 year
        abp.appPath
      );

      window.location.reload();
    }
  }
};
</script>

<style lang="less" scoped>
@import "./account-languages.less";
</style>

// src/yoyocmstemplate-angular/src/account/account-languages/account-languages.component.ts
import { Component, OnInit, Injector } from '@angular/core';

import * as _ from 'lodash';
import { AppComponentBase } from '@shared/component-base/app-component-base';
import { UtilsService } from 'abp-ng2-module';

@Component({
  // tslint:disable-next-line:component-selector
  selector: 'account-languages',
  templateUrl: './account-languages.component.html',
  styleUrls: ['./account-languages.component.less'],
})
export class AccountLanguagesComponent extends AppComponentBase implements OnInit {
  languages: abp.localization.ILanguageInfo[];
  currentLanguage: abp.localization.ILanguageInfo;

  constructor(injector: Injector, private utilsService: UtilsService) {
    super(injector);
  }

  ngOnInit() {
    this.languages = _.filter(this.localization.languages, l => !l.isDisabled);
    this.currentLanguage = this.localization.currentLanguage;
  }

  changeLanguage(languageName: string): void {
    this.utilsService.setCookieValue(
      'Abp.Localization.CultureName',
      languageName,
      new Date(new Date().getTime() + 5 * 365 * 86400000), // 5 year
      abp.appPath,
    );

    location.reload();
  }
}

<ul class="account-language-switch-list">
  <li *ngFor="let language of languages">
      <a *ngIf="language.name != currentLanguage.name" href="javascript:void();" title="{{language.displayName}}" (click)="changeLanguage(language.name)"><i class="{{language.icon}}"></i></a>
  </li>
</ul>
