// src/yoyocmstemplate-vue/src/app/admin/languages/create-or-edit-language/create-or-edit-language.vue
<template>
    <a-spin :spinning="spinning">
        <div class="modal-header">
            <div class="modal-title" v-if="!language.id">{{l('CreateNewLanguage')}}</div>
            <div class="modal-title" v-if="language.id">
                {{l('EditLanguage')}}:
                <span>{{language.name}}</span>
            </div>
        </div>
        <a-form :form="form" @submit="save()" autocomplete="off">
            <!-- 语言名称 -->
            <a-form-item
                :label="l('LanguageName')">
                <a-select v-decorator="['name', {
                        rules: [
                            { required: true, message: l('ThisFieldIsRequired') },
                        ]
                    }]">
                    <a-select-option v-for="item in languageNames" :key="item.value" :value="item.value">
                        {{ item.displayText }}
                    </a-select-option>
                </a-select>
            </a-form-item>
            <!-- 语言图标 -->
            <a-form-item
                :label="l('LanguageIcon')">
                <a-select v-decorator="['icon', {
                        rules: [
                            { required: true, message: l('ThisFieldIsRequired') },
                        ]
                    }]">
                    <a-select-option v-for="item in flags" :key="item.value" :value="item.value">
                        {{ item.displayText }}
                    </a-select-option>>
                </a-select>
            </a-form-item>
            <!-- 启用 -->
            <a-form-item
                :label="l('Enabled')">
                <a-switch v-decorator="['isEnabled', {valuePropName: 'checked'} ]" :checkedChildren="l('Yes')" :unCheckedChildren="l('No')" />
            </a-form-item>
        </a-form>

        <div class="modal-footer">
            <a-button :disabled="saving" @click="close()" type="button">
                {{l("Cancel")}}
            </a-button>
            <a-button :loading="saving" :type="'primary'" @click="save()">
                <i class="acticon acticon-save"></i>
                <span>{{l("Save")}}</span>
            </a-button>
        </div>
    </a-spin>
</template>
<script>
import { ModalComponentBase } from "@/shared/component-base";
import { LanguageServiceProxy } from "@/shared/service-proxies";

export default {
    name: "create-or-edit-language",
    mixins: [ModalComponentBase],
    components: {},
    data() {
        return {
            form: this.$form.createForm(this),
            languageServiceProxy: "",
            spinning: false,
            // 语言数据
            language: {},
            // 语言名称
            languageNames: [],
            // 图表名称
            flags: []
        };
    },
    created() {
        this.fullData(); // 模态框必须,填充数据到data字段
        this._languageServiceProxy = new LanguageServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.getData();
    },
    methods: {
        getData() {
            this.spinning = true;
            this._languageServiceProxy
                .getLanguageForEdit(this.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.language = res.language;
                    this.flags = res.flags;
                    this.languageNames = res.languageNames;
                    this.form.setFieldsValue({
                        isEnabled: this.id ? this.language.isEnabled : true,
                        icon: this.language.icon,
                        name: this.language.name
                    });
                    this.id = this.language.id;
                    console.log(res);
                });
        },
        /**
         * 提交
         */
        save() {
            this.form.validateFields((err, values) => {
                if (!err) {
                    console.log(values);
                    this.spinning = true;
                    this._languageServiceProxy
                        .createOrUpdateLanguage({
                            language: Object.assign(values, { id: this.id })
                        })
                        .finally(() => {
                            this.spinning = false;
                        })
                        .then(res => {
                            this.notify.success(this.l("SavedSuccessfully"));
                            this.success(true);
                            console.log(res);
                        });
                }
            });
        }
    }
};
</script>

// src/yoyocmstemplate-angular/src/app/admin/languages/create-or-edit-language/create-or-edit-language.component.ts
import { Component, OnInit, Injector, Input } from '@angular/core';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import {
  LanguageServiceProxy,
  LanguageEditDto,
  ComboboxItemDto,
  CreateOrUpdateLanguageInput,
} from '@shared/service-proxies/service-proxies';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-create-or-edit-language',
  templateUrl: './create-or-edit-language.component.html',
  styles: [],
})
export class CreateOrEditLanguageComponent extends ModalComponentBase implements OnInit {
  @Input()
  languageId: number = undefined;
  saving = false;
  language: LanguageEditDto = new LanguageEditDto();
  selectedLanguage: string;
  languageNames: ComboboxItemDto[] = [];
  flags: ComboboxItemDto[] = [];

  constructor(injector: Injector, private languageService: LanguageServiceProxy) {
    super(injector);
  }

  ngOnInit() {
    this.init();
  }

  init(): void {
    this.languageService
      .getLanguageForEdit(this.languageId)
      .pipe()

      .subscribe(result => {
        this.language = result.language;
        this.languageNames = result.languageNames;
        this.flags = result.flags;

        this.selectedLanguage = result.language.name || '';

        if (!this.languageId) {
          this.language.isEnabled = true;
        }
      });
  }

  save(): void {
    this.saving = true;

    if (!this.selectedLanguage || this.selectedLanguage === '' || !this.language.icon || this.language.icon === '') {
      this.saving = false;
      this.message.warn('值不能为空');
      return;
    }

    this.language.name = this.selectedLanguage;
    const input = new CreateOrUpdateLanguageInput();
    input.language = this.language;

    this.languageService
      .createOrUpdateLanguage(input)
      .pipe(finalize(() => (this.saving = false)))
      .subscribe(() => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success();
      });
  }
}

<form nz-form #languageCreateOrEditForm="ngForm" (ngSubmit)="save()" autocomplete="off">
  <div class="modal-header">
    <div class="modal-title">
      <!-- <i class="iconfont icon-global mr-sm"></i> -->
      <i class="iconfont icon-global mr-sm"></i>
      <span *ngIf="language.id">{{ l('EditLanguage') }}: {{ language.name }}</span>
      <span *ngIf="!language.id">{{ l('CreateNewLanguage') }}</span>
    </div>
  </div>

  <fieldset>
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="4" nzFor="languageName" nzRequired>
        {{ l('LanguageName') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="20" nzHasFeedback>
        <nz-select name="languageName" #languageName="ngModel" [(ngModel)]="selectedLanguage"
          [nzPlaceHolder]="l('LanguageName')" [nzShowSearch]="true" required>
          <nz-option *ngFor="let option of languageNames" [nzLabel]="option.displayText" [nzValue]="option.value">
          </nz-option>
        </nz-select>
        <nz-form-control nzExtra *ngIf="languageName.control.dirty && languageName.control.errors">
          <ng-container *ngIf="languageName.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>

    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="4" nzFor="languageIcon" nzRequired>
        {{ l('LanguageIcon') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="20" nzHasFeedback>
        <nz-select name="languageIcon" #languageIcon="ngModel" [(ngModel)]="language.icon"
          [nzPlaceHolder]="l('LanguageIcon')" [nzShowSearch]="true" required>
          <nz-option nzCustomContent *ngFor="let option of flags" [nzValue]="option.value"
            [nzLabel]="option.displayText">
            <!-- <i class="anticon mr-sm" [ngClass]="option.value"></i> -->
            <i class="iconfont mr-sm" [ngClass]="option.value"></i>
            <span>
              {{ option.displayText }}
            </span>
          </nz-option>
        </nz-select>
        <nz-form-control nzExtra *ngIf="languageIcon.control.dirty && languageIcon.control.errors">
          <ng-container *ngIf="languageIcon.control.hasError('required')">{{ l('ThisFieldIsRequired') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <!-- 启用 -->

    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="4" nzFor="IsEnabled">
        {{ l('Enabled') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="20">
        <nz-switch name="IsEnabled" [(ngModel)]="language.isEnabled" [nzCheckedChildren]="l('Yes')"
          [nzUnCheckedChildren]="l('No')"></nz-switch>
      </nz-form-control>
    </nz-form-item>

    <!-- 功能按钮 -->
    <div class="modal-footer">
      <button nz-button [nzType]="'default'" type="button" (click)="close()" [disabled]="saving">
        <!-- <i class="iconfont icon-close-circle-o"></i>  -->
        <i class="iconfont  icon-close-circle"></i>
        {{ l('Cancel') }}
      </button>
      <button nz-button [nzType]="'primary'" type="submit" [disabled]="!languageCreateOrEditForm.form.valid || saving"
        [nzLoading]="saving">
        <!-- <i class="iconfont icon-save" *ngIf="!saving"></i>  -->
        <i class="iconfont  icon-save" *ngIf="!saving"></i>
        {{ l('Save') }}
      </button>
    </div>
  </fieldset>
</form>
