// src/yoyocmstemplate-angular/src/app/admin/users/edit-user-permissions/edit-user-permissions.component.ts
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import { Component, OnInit, ViewChild, Injector, Input } from '@angular/core';
import { PermissionTreeComponent } from '@app/admin/shared/permission-tree/permission-tree.component';
import {
  UserServiceProxy,
  UpdateUserPermissionsInput,
  EntityDtoOfInt64
} from '@shared/service-proxies/service-proxies';

@Component({
  selector: 'app-edit-user-permissions',
  templateUrl: './edit-user-permissions.component.html',
  styles: []
})
export class EditUserPermissionsComponent extends ModalComponentBase
  implements OnInit {
  @ViewChild(PermissionTreeComponent)
  permissionTree: PermissionTreeComponent;

  /**
   * 用户Id
   */
  userId: number;
  /**
   * 用户名
   */
  userName?: string;

  saving = false;
  resettingPermissions = false;

  constructor(injector: Injector, private userService: UserServiceProxy) {
    super(injector);
  }

  ngOnInit() {
    const self = this;

    // self._roleService.getForEdit(self.id).subscribe(result => {
    //   self.role = result.role;

    //   self.permissionTree.editData = result;
    //   self.setFormValues(this.role);
    // });

    self.userService
      .getPermissionsTreeForEdit(self.userId)
      .subscribe(result => {
        this.permissionTree.editData = result;
      });
  }

  /**
   * 保存
   */
  save(): void {
    this.saving = true;
    this.saving = true;
    const input = new UpdateUserPermissionsInput();
    input.id = this.userId;
    input.grantedPermissionNames = this.permissionTree.getGrantedPermissionNames();

    this.userService
      .updatePermissions(input)
      .finally(() => {})
      .subscribe(() => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success();
      });
  }

  /**
   * 重置权限
   */
  resetPermissions(): void {
    const input = new EntityDtoOfInt64();
    input.id = this.userId;

    this.resettingPermissions = true;
    this.userService
      .resetSpecificPermissions(input)
      .finally(() => {
        this.resettingPermissions = false;
      })
      .subscribe(() => {
        this.notify.success(this.l('ResetSuccessfully'));
        this.userService
          .getPermissionsTreeForEdit(this.userId)
          .subscribe(result => {
            this.permissionTree.editData = result;
          });
      });
  }
}

<form nz-form #editUserPermissionsForm="ngForm" (ngSubmit)="save()" nzLayout="horizontal" autocomplete="off">
  <!-- 模态框头部 -->
  <div class="modal-header">
    <div class="modal-title">
      <i class="iconfont icon-safetycertificate  mr-sm"></i>
      <!-- <i class="iconfont icon-safety mr-sm"></i> -->
      <span>
        {{ l('Permissions') }}
        <span *ngIf="userName"> - {{ userName }}</span>
      </span>
    </div>
  </div>

  <!-- 模态框内容 -->

  <fieldset>
    <nz-alert
      nzType="warning"
      nzCloseable
      [nzShowIcon]="true"
      [nzMessage]="l('Note_RefreshPageForPermissionChanges')"
      class="mb-md"
    ></nz-alert>
    <permission-tree #permissionTree></permission-tree>
  </fieldset>

  <!-- 模态框底部内容 -->
  <div class="modal-footer">
    <button
      nz-button
      [nzType]="'default'"
      type="button"
      (click)="resetPermissions()"
      [disabled]="saving"
      [nzLoading]="resettingPermissions"
      nz-tooltip
      [nzTooltipTitle]="l('ResetPermissionsTooltip')"
      class="mr-sm"
    >
      <i class="iconfont icon-reload" *ngIf="!resettingPermissions"></i>
      <!-- <i class="iconfont icon-reload" *ngIf="!resettingPermissions"></i> -->
      {{ l('ResetSpecialPermissions') }}
    </button>

    <button
      nz-button
      [nzType]="'default'"
      type="button"
      (click)="close($event)"
      [disabled]="saving || resettingPermissions"
    >
      <!-- <i class="iconfont icon-close-circle-o"></i>  -->
      <i class="iconfont icon-close-circle"></i>
      {{ l('Cancel') }}
    </button>

    <button
      nz-button
      [nzType]="'primary'"
      type="submit"
      [disabled]="!editUserPermissionsForm.form.valid || saving || resettingPermissions"
      [nzLoading]="saving"
    >
      <!-- <i class="iconfont icon-save" *ngIf="!saving"></i>  -->
      <i class="iconfont icon-save" *ngIf="!saving"></i>
      {{ l('Save') }}
    </button>
  </div>
</form>

// src/yoyocmstemplate-vue/src/app/admin/users/edit-user-permissions/edit-user-permissions.vue
<template>
    <a-spin :spinning="spinning">
        <div class="modal-header">
            <div class="modal-title">
                <a-icon type="safety-certificate" />
                <span>{{ l('Permissions') }}: <span v-if="userName"> - {{ userName }}</span></span>
            </div>
        </div>
        <!-- 提示 -->
        <a-alert :message="l('Note_RefreshPageForPermissionChanges')" type="warning" closable showIcon />
        <search-role-tree
            v-if="isshowPermissionTree"
            :multiple="true"
            :dropDownStyle="{ 'max-height': '500px' }"
            :selectedPermission="selectedPermission"
            @selectedPermissionChange="refreshGoFirstPage">
        </search-role-tree>
        <!-- 按钮 -->
        <div class="modal-footer">
            <a-button :disabled="saving" @click="resetPermissions()" :loading="resettingPermissions" type="button">
                <a-icon type="reload" />
                {{ l('ResetSpecialPermissions') }}
            </a-button>
            <a-button :disabled="saving || resettingPermissions" @click="close()" type="button">
                <a-icon type="close-circle" />
                {{ l('Cancel') }}
            </a-button>
            <a-button :loading="saving || resettingPermissions" :type="'primary'" @click="handleSubmit()">
                <a-icon type="save" />
                {{ l('Save') }}
            </a-button>
        </div>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { ModalComponentBase } from "@/shared/component-base";
import { UserServiceProxy } from "@/shared/service-proxies";
import Bus from "@/shared/bus/bus";
import SearchRoleTree from "../../roles/search-role-tree/index.vue";

export default {
    name: "create-or-edit-role",
    mixins: [AppComponentBase, ModalComponentBase],
    data() {
        return {
            spinning: false,
            // 选中的权限过滤
            selectedPermission: [],
            resettingPermissions: false,
            _userServiceProxy: "",
            isshowPermissionTree: false
        };
    },
    components: {
        SearchRoleTree
    },
    created() {
        this.fullData(); // 模态框必须,填充数据到data字段
        this._userServiceProxy = new UserServiceProxy(this.$apiUrl, this.$api);
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._userServiceProxy
                .getPermissionsTreeForEdit(this.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(result => {
                    console.log(result.grantedPermissionNames);
                    this.selectedPermission = result.grantedPermissionNames;
                    this.isshowPermissionTree = true;
                });
        },
        /**
         * 提交表单
         */
        handleSubmit() {
            this.saving = true;
            this.spinning = true;
            let input = {};
            input.id = this.id;
            input.grantedPermissionNames = this.selectedPermission;
            this._userServiceProxy
                .updatePermissions(input)
                .finally(() => {
                    this.saving = false;
                    this.spinning = false;
                })
                .then(() => {
                    this.notify.success(this.l("SavedSuccessfully"));
                    this.success(true);
                });
        },
        /**
         * 选择完权限过滤
         */
        refreshGoFirstPage(data) {
            this.selectedPermission = data;
        },
        /**
         * 重置权限
         */
        resetPermissions() {
            let input = {};
            input.id = this.id;
            this.resettingPermissions = true;
            this._userServiceProxy
                .resetSpecificPermissions(input)
                .finally(() => {
                    this.resettingPermissions = false;
                })
                .then(() => {
                    this.notify.success(this.l("ResetSuccessfully"));
                    this._userServiceProxy
                        .getPermissionsTreeForEdit(this.id)
                        .then(result => {
                            this.selectedPermission = result;
                        });
                });
        }
    }
};
</script>

<style scoped lang="less">
.modal-header {
    .anticon {
        margin-right: 10px;
    }
}
.pagination {
    margin: 10px auto;
    text-align: right;
}
.ant-alert {
    margin-bottom: 10px;
}
</style>
