// src/yoyocmstemplate-angular/src/app/wechat-management/wechat-app-configs/create-or-edit-wechat-app-config/create-or-edit-wechat-app-config.component.ts
import { Component, OnInit, Injector, Input, ViewChild, AfterViewInit } from '@angular/core';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';
import {
  CreateOrUpdateWechatAppConfigInput,
  WechatAppConfigEditDto,
  WechatAppConfigServiceProxy,
} from '@shared/service-proxies/service-proxies';
import { Validators, AbstractControl, FormControl } from '@angular/forms';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'create-or-edit-wechat-app-config',
  templateUrl: './create-or-edit-wechat-app-config.component.html',
  styleUrls: ['create-or-edit-wechat-app-config.component.less'],
})
export class CreateOrEditWechatAppConfigComponent extends ModalComponentBase implements OnInit {
  /**
   * 编辑时DTO的id
   */
  id: any;

  entity: WechatAppConfigEditDto = new WechatAppConfigEditDto();

  wechatAppTypeList: any[] = [];

  /**
   * 初始化的构造函数
   */
  constructor(injector: Injector, private _wechatAppConfigService: WechatAppConfigServiceProxy) {
    super(injector);
  }

  ngOnInit(): void {
    this.init();
  }

  /**
   * 初始化方法
   */
  init(): void {
    this._wechatAppConfigService.getForEdit(this.id).subscribe(result => {
      this.entity = result.wechatAppConfig;
      this.wechatAppTypeList = result.wechatAppTypeList;
      if (!this.id) {
        this.entity.appType = this.wechatAppTypeList[0].value;
      }
    });
  }

  /**
   * 保存方法,提交form表单
   */
  submitForm(): void {
    const input = new CreateOrUpdateWechatAppConfigInput();
    input.wechatAppConfig = this.entity;

    this.saving = true;

    this._wechatAppConfigService
      .createOrUpdate(input)
      .pipe(finalize(() => (this.saving = false)))
      .subscribe(() => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success(true);
      });
  }
}

<form nz-form #validateForm="ngForm" (ngSubmit)="submitForm()" nzLayout="horizontal" autocomplete="off">
  <!-- 模态框头部 -->
  <div class="modal-header">
    <div class="modal-title">
      <i class="iconfont icon-medicine-box mr-sm"></i>
      <span *ngIf="entity.id">{{ l('Edit') }}</span>
      <span *ngIf="!entity.id">{{ l('Create') }}</span>
    </div>
  </div>
  <!-- 模态框内容 -->
  <fieldset>
    <!-- 提示信息 -->
    <!-- <nz-alert nzType="info" nzCloseable [nzShowIcon]="true" nzMessage="l('我想提示点什么内容给你说')"></nz-alert> -->
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="name">{{ l('WechatName') }}</nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <input nz-input name="name" #name="ngModel" [(ngModel)]="entity.name" [placeholder]="l('WechatName')"
          required />

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="name.control.dirty && name.control.errors">
          <ng-container *ngIf="name.control.hasError('required')">{{ l('CanNotNull') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="appId">{{ l('WechatAppId') }}</nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <input nz-input name="appId" #appId="ngModel" [(ngModel)]="entity.appId" [placeholder]="l('WechatAppId')"
          required />

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="appId.control.dirty && appId.control.errors">
          <ng-container *ngIf="appId.control.hasError('required')">{{ l('CanNotNull') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="appSecret">{{ l('WechatAppSecret') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <input nz-input name="appSecret" #appSecret="ngModel" [(ngModel)]="entity.appSecret"
          [placeholder]="l('WechatAppSecret')" required />

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="appSecret.control.dirty && appSecret.control.errors">
          <ng-container *ngIf="appSecret.control.hasError('required')">{{ l('CanNotNull') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="6" [nzXs]="24" nzRequired nzFor="token">{{ l('WechatToken') }}</nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <input nz-input name="token" #token="ngModel" [(ngModel)]="entity.token" [placeholder]="l('WechatToken')"
          required />

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="token.control.dirty && token.control.errors">
          <ng-container *ngIf="token.control.hasError('required')">{{ l('CanNotNull') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="encodingAESKey">{{ l('WechatEncodingAESKey') }}</nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24" nzHasFeedback>
        <input nz-input name="encodingAESKey" #encodingAESKey="ngModel" [(ngModel)]="entity.encodingAESKey"
          [placeholder]="l('WechatEncodingAESKey')" />
      </nz-form-control>
    </nz-form-item>

    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="appOrgId">{{ l('WechatAppOrgId') }}</nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24">
        <input nz-input name="appOrgId" #appOrgId="ngModel" [(ngModel)]="entity.appOrgId"
          [placeholder]="l('WechatAppOrgId')" />
      </nz-form-control>
    </nz-form-item>

    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="appType">{{ l('WechatAppType') }}</nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24">
        <nz-select name="appType" #appType="ngModel" [(ngModel)]="entity.appType" [nzPlaceHolder]="l('WechatAppType')"
          style="width: 100%;">
          <nz-option *ngFor="let option of wechatAppTypeList" [nzLabel]="option.key" [nzValue]="option.value">
          </nz-option>
        </nz-select>

        <!-- 校验 -->
        <nz-form-control nzExtra *ngIf="appType.control.dirty && appType.control.errors">
          <ng-container *ngIf="appType.control.hasError('required')">{{ l('CanNotNull') }}</ng-container>
        </nz-form-control>
      </nz-form-control>
    </nz-form-item>

    <nz-form-item nz-row>
      <nz-form-label [nzSm]="6" [nzXs]="24" nzFor="qrCodeUrl">{{ l('QRCodeUrl') }}</nz-form-label>
      <nz-form-control nz-col [nzSm]="14" [nzXs]="24">
        <input nz-input name="qrCodeUrl" #qrCodeUrl="ngModel" [(ngModel)]="entity.qrCodeUrl"
          [placeholder]="l('QRCodeUrl')" />
      </nz-form-control>
    </nz-form-item>
  </fieldset>
  <!-- 模态框底部 -->
  <div class="modal-footer">
    <button nz-button [nzType]="'default'" type="button" (click)="close()" [disabled]="saving">
      <!-- <i class="iconfont icon-close-circle-o"></i>  -->
      <i class="iconfont icon-close-circle"></i>
      {{ l('Cancel') }}
    </button>
    <button nz-button [nzType]="'primary'" type="submit" [disabled]="!validateForm.form.valid || saving"
      [nzLoading]="saving">
      <!-- <i class="iconfont icon-save" *ngIf="!saving"></i> -->
      <i class="iconfont icon-save" *ngIf="!saving"></i>
      {{ l('Save') }}
    </button>
  </div>
</form>

// src/yoyocmstemplate-vue/src/app/wechat/create-or-edit-wechat-app-config/create-or-edit-wechat-app-config.vue
<template>
    <a-spin :spinning="spinning">
        <!-- 标题 -->
        <div class="modal-header">
            <div class="modal-title">
                <span v-if="entity && entity.id">{{ l('Edit') }}</span>
                <span v-if="!entity">{{ l('Create') }}</span>
            </div>
        </div>
        <a-form :form="form" :label-col="{ span: 5 }" :wrapper-col="{ span: 12 }">
            <a-form-item :label="l('WechatName')">
                <a-input :placeholder="l('WechatName')"
                    v-decorator="['name', { rules: [{ required: true, message: l('CanNotNull') }] }]" />
            </a-form-item>
            <a-form-item :label="l('WechatAppId')">
                <a-input :placeholder="l('WechatAppId')"
                    v-decorator="['appId', { rules: [{ required: true, message: l('CanNotNull') }] }]" />
            </a-form-item>
            <a-form-item :label="l('WechatAppSecret')">
                <a-input :placeholder="l('WechatAppSecret')"
                    v-decorator="['appSecret', { rules: [{ required: true, message: l('CanNotNull') }] }]" />
            </a-form-item>
            <a-form-item :label="l('WechatToken')">
                <a-input :placeholder="l('WechatToken')"
                    v-decorator="['token', { rules: [{ required: true, message: l('CanNotNull') }] }]" />
            </a-form-item>
            <a-form-item :label="l('WechatEncodingAESKey')">
                <a-input :placeholder="l('WechatEncodingAESKey')"
                    v-decorator="['encodingAESKey', { rules: [] }]" />
            </a-form-item>
            <a-form-item :label="l('WechatAppOrgId')">
                <a-input :placeholder="l('WechatAppOrgId')"
                    v-decorator="['appOrgId', { rules: [] }]" />
            </a-form-item>
            <a-form-item :label="l('WechatAppType')">
                <a-select :placeholder="l('WechatAppType')" v-decorator="['appType', { rules: [] }]">
                    <a-select-option v-for="item in wechatAppTypeList" :key="item.value" :value="item.value">
                        {{ item.key }}
                    </a-select-option>
                </a-select>
            </a-form-item>
            <a-form-item :label="l('QRCodeUrl')">
                <a-input :placeholder="l('QRCodeUrl')"
                    v-decorator="['qrCodeUrl', { rules: [] }]" />
            </a-form-item>
        </a-form>
        <!-- 按钮 -->
        <div class="modal-footer">
            <a-button :disabled="saving" @click="close()" type="button">
                <a-icon type="close-circle" />
                {{ l('Cancel') }}
            </a-button>
            <a-button :loading="saving" :type="'primary'" @click="handleSubmit">
                <a-icon type="save" />
                {{ l('Save') }}
            </a-button>
        </div>
    </a-spin>
</template>

<script>
import { ModalComponentBase } from "@/shared/component-base";
import { WechatAppConfigServiceProxy } from "@/shared/service-proxies";

export default {
    name: "create-or-edit-wechat-app-config",
    mixins: [ModalComponentBase],
    data() {
        return {
            spinning: false,
            name: "",
            _wechatAppConfigServiceProxy: "",
            formLayout: "horizontal",
            form: this.$form.createForm(this, { name: "coordinated" }),
            wechatAppTypeList: []
        };
    },
    created() {
        this._wechatAppConfigServiceProxy = new WechatAppConfigServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.fullData(); // 模态框必须,填充数据到data字段
    },
    mounted() {
        console.log(this.entity);
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._wechatAppConfigServiceProxy
                .getForEdit(this.entity ? this.entity.id : "")
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.wechatAppTypeList = res.wechatAppTypeList;
                    this.form.setFieldsValue({
                        name: res.wechatAppConfig.name,
                        appId: res.wechatAppConfig.appId,
                        appSecret: res.wechatAppConfig.appSecret,
                        token: res.wechatAppConfig.token,
                        encodingAESKey: res.wechatAppConfig.encodingAESKey,
                        appOrgId: res.wechatAppConfig.appOrgId,
                        qrCodeUrl: res.wechatAppConfig.qrCodeUrl,
                        appType: res.wechatAppTypeList.find(
                            item => item.key === res.wechatAppConfig.appType
                        )
                            ? res.wechatAppTypeList.find(
                                  item =>
                                      item.key === res.wechatAppConfig.appType
                              ).value
                            : res.wechatAppTypeList[0].value
                    });
                    console.log(res);
                });
        },
        /**
         * 提交数据
         */
        handleSubmit(e) {
            e.preventDefault();
            this.form.validateFields((err, values) => {
                if (!err) {
                    console.log("Received values of form: ", values);
                    let parmas = Object.assign(values, {
                        id: this.entity ? this.entity.id : ""
                    });
                    this.spinning = true;
                    this._wechatAppConfigServiceProxy
                        .createOrUpdate({ wechatAppConfig: parmas })
                        .finally(() => {
                            this.spinning = false;
                        })
                        .then(res => {
                            this.notify.success(this.l("SavedSuccessfully"));
                            this.success(true);
                        });
                }
            });
        }
    }
};
</script>

<style lang="less" scoped>
</style>
