// src/yoyocmstemplate-angular/src/app/admin/language-texts/language-texts.component.ts
import { Component, OnInit, AfterViewInit, Injector } from '@angular/core';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import {
  LanguageTextListDto,
  UpdateLanguageTextInput,
  LanguageServiceProxy,
} from '@shared/service-proxies/service-proxies';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { AppConsts } from 'abpPro/AppConsts';
import { EditLanguageTextComponent } from '@app/admin/language-texts/edit-language-text/edit-language-text.component';
import { ReuseTabService } from '@delon/abc';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-language-texts',
  templateUrl: './language-texts.component.html',
  styles: [],
})
export class LanguageTextsComponent extends PagedListingComponentBase<LanguageTextListDto> implements AfterViewInit {
  languages: abp.localization.ILanguageInfo[] = [];
  baseLanguageName: string;
  targetLanguageName: string;
  sourceNames: string[] = [];
  sourceName: string;

  targetValueFilters: any[] = [
    {
      label: this.l('All'),
      value: 'ALL',
    },
    {
      label: this.l('EmptyOnes'),
      value: 'EMPTY',
    },
  ];
  targetValueFilter = 'ALL';

  filterText: string;

  constructor(
    injector: Injector,
    private _languageService: LanguageServiceProxy,
    private _router: Router,
    private _activatedRoute: ActivatedRoute,
    private _reuseTabService: ReuseTabService,
  ) {
    super(injector);

    abp.localization.sources.forEach((item, index, array) => {
      if (item.type === 'MultiTenantLocalizationSource') {
        this.sourceNames.push(item.name);
      }
    });
    this.languages = abp.localization.languages;
    this.init();
  }

  ngAfterViewInit(): void {}

  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    this._languageService
      .getLanguageTexts(
        this.sourceName,
        this.baseLanguageName,
        this.targetLanguageName,
        this.targetValueFilter,
        this.filterText,
        undefined,
        request.maxResultCount,
        request.skipCount,
      )
      .pipe(finalize(() => finishedCallback()))
      .subscribe(result => {
        this.dataList = result.items;
        this.totalItems = result.totalCount;
      });
  }

  init(): void {
    this.sourceName = AppConsts.localization.defaultLocalizationSourceName;
    this.baseLanguageName = abp.localization.currentLanguage.name;
    this._reuseTabService.title = this.l('LanguageTexts');

    this._activatedRoute.params.subscribe((params: Params) => {
      this.targetLanguageName = params.lang;
    });
  }

  onSearch(e?: any): void {
    this.pageNumber = 1;
    this.refresh();
  }

  truncateString(text): string {
    return abp.utils.truncateStringWithPostfix(text, 32, '...');
  }

  findIcon(name: string): string {
    let icon = '';
    for (let index = 0; index < this.languages.length; index++) {
      if (this.languages[index].name === name) {
        icon = this.languages[index].icon;
        break;
      }
    }
    return icon;
  }

  backLanguageList(): void {
    this._router.navigate(['app/admin/languages']);
  }

  edit(data: LanguageTextListDto): void {
    const pars = new UpdateLanguageTextInput();
    pars.sourceName = this.sourceName;
    pars.key = data.key;
    pars.languageName = this.targetLanguageName;
    pars.value = data.targetValue;

    this.modalHelper
      .open(EditLanguageTextComponent, {
        data: pars,
        baseText: data.baseValue,
        baseLanguageName: this.baseLanguageName,
        targetLanguageName: this.targetLanguageName,
      })
      .subscribe(res => {
        if (res) {
          this.refresh();
        }
      });
  }
}

<page-header [title]="l('LanguageTexts')"></page-header>

<!-- 表格部分 -->
<nz-card [nzBordered]="false" [nzExtra]="extra" [nzTitle]="l('LanguagesHeaderInfo')">
  <ng-template #extra>
    <button nz-button (click)="refresh()">
      <!-- <i class="iconfont icon-reload"></i> -->
      <i class="iconfont icon-reload"></i>
      <span>{{ l('Refresh') }}</span>
    </button>
    <button nz-button (click)="backLanguageList()" [nzType]="'primary'">
      <!-- <i class="iconfont icon-rollback"></i> -->
      <i class="iconfont icon-rollback"></i>
      <span>{{ l('BackLanguageList') }}</span>
    </button>
  </ng-template>
  <!-- 检索表单 -->
  <form nz-form (ngSubmit)="onSearch()" class="mb-md">
    <!-- 搜索框 -->
    <nz-form-item nz-row>
      <nz-form-control>
        <nz-input-group nzSearch [nzAddOnAfter]="suffixSearchButton">
          <input type="text" nz-input (keyup.enter)="onSearch()" [(ngModel)]="filterText" name="filterText"
            [placeholder]="l('SearchWithThreeDot')" />
          <ng-template #suffixSearchButton>
            <button nz-button nzType="primary" nzSearch type="submit">
              <!-- <i class="iconfont icon-search"></i> -->
              <i class="iconfont icon-search"></i>
            </button>
          </ng-template>
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>

    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="2" nzFor="BaseLanguage">
        {{ l('BaseLanguage') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="4">
        <nz-select name="BaseLanguage" [(ngModel)]="baseLanguageName" [nzPlaceHolder]="l('BaseLanguage')"
          (ngModelChange)="onSearch()" [nzShowSearch]="true">
          <nz-option nzCustomContent *ngFor="let language of languages" [nzValue]="language.name"
            [nzLabel]="language.displayName">
            <!-- <i class="anticon mr-sm" [ngClass]="language.icon"></i> -->
            <i class="iconfont mr-sm" [ngClass]="language.icon"></i>
            <span>
              {{ language.displayName }}
            </span>
          </nz-option>
        </nz-select>
      </nz-form-control>

      <nz-form-label nz-col [nzSm]="2" nzFor="TargetLanguage">
        {{ l('TargetLanguage') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="4">
        <nz-select name="TargetLanguage" [(ngModel)]="targetLanguageName" [nzPlaceHolder]="l('TargetLanguage')"
          (ngModelChange)="onSearch()" [nzShowSearch]="true">
          <nz-option nzCustomContent *ngFor="let language of languages" [nzValue]="language.name"
            [nzLabel]="language.displayName">
            <!-- <i class="anticon mr-sm" [ngClass]="language.icon"></i> -->
            <i class="iconfont mr-sm" [ngClass]="language.icon"></i>
            <span>
              {{ language.displayName }}
            </span>
          </nz-option>
        </nz-select>
      </nz-form-control>

      <nz-form-label nz-col [nzSm]="2" nzFor="sourceName">
        {{ l('Source') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="4">
        <nz-select name="sourceName" [(ngModel)]="sourceName" [nzPlaceHolder]="l('Source')" (ngModelChange)="onSearch()"
          [nzShowSearch]="true">
          <nz-option *ngFor="let sourceName of sourceNames" [nzValue]="sourceName" [nzLabel]="sourceName"></nz-option>
        </nz-select>
      </nz-form-control>

      <nz-form-label nz-col [nzSm]="2" nzFor="TargetValue">
        {{ l('TargetValue') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="4">
        <nz-select name="TargetValue" [(ngModel)]="targetValueFilter" [nzPlaceHolder]="l('TargetValue')"
          (ngModelChange)="onSearch()" [nzShowSearch]="true">
          <nz-option nzValue="ALL" [nzLabel]="l('All')"></nz-option>
          <nz-option nzValue="EMPTY" [nzLabel]="l('EmptyOnes')"></nz-option>
        </nz-select>
      </nz-form-control>
    </nz-form-item>
  </form>

  <!-- 数据部分 -->

  <nz-table #ajaxTable nzShowSizeChanger [nzData]="dataList" [nzTotal]="totalItems" [(nzPageIndex)]="pageNumber"
    [(nzPageSize)]="pageSize" [nzLoading]="isTableLoading" (nzPageIndexChange)="pageNumberChange()"
    (nzPageSizeChange)="refresh()" [nzFrontPagination]="false">
    <!-- 暂无数据 -->
    <ng-template #noDataTemplate>
      <no-data></no-data>
    </ng-template>
    <!-- 分页信息显示 当前 1 页/共 3 页，共 5 条/显示 1-2 条 -->
    <ng-template #showTotalTemplate let-total let-range="range">
      {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
    </ng-template>
    <!-- 表头 -->
    <thead (nzSortChange)="gridSort($event)">
      <tr>
        <th nzShowSort nzSortKey="key">
          <span>{{ l('Key') }}</span>
        </th>
        <th nzShowSort nzSortKey="baseValue">
          <span>{{ l('BaseValue') }}</span>
        </th>
        <th nzShowSort nzSortKey="targetValue">
          <span> {{ l('TargetValue') }}</span>
        </th>

        <th nzWidth="150px" class="text-center">
          <span>{{ l('Actions') }}</span>
        </th>
      </tr>
    </thead>

    <tbody nz-tbody>
      <tr nz-tbody-tr *ngFor="let item of ajaxTable.data">
        <td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.key">
              {{ item.key }}
            </span>
          </ellipsis>
        </td>
        <td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.baseValue">
              {{ item.baseValue }}
            </span>
          </ellipsis>
        </td>
        <td>
          <ellipsis lines="1">
            <span nz-tooltip [nzTooltipTitle]="item.targetValue">
              {{ item.targetValue }}
            </span>
          </ellipsis>
        </td>
        <td class="text-center">
          <!-- 编辑 -->
          <a (click)="edit(item)">
            class="iconfont icon-edit
            <i class="iconfont icon-edit mr-sm"></i>
            <span>{{ l('Edit') }}</span>
          </a>
        </td>
      </tr>
    </tbody>
  </nz-table>

</nz-card>

// src/yoyocmstemplate-vue/src/app/admin/language-texts/language-texts.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('LanguageTexts')"></page-header>
        <a-card :title="l('LanguagesHeaderInfo')" :bordered="false">
            <a-button slot="extra" @click="getData">
                <a-icon type="reload" />
                {{ l('Refresh') }}
            </a-button>
            <a-button slot="extra" type="primary" @click="backLanguageList">
                <a-icon type="rollback" />
                {{ l('BackLanguageList') }}
            </a-button>
            <a-form :form="form" :layout="'vertical'" @submit.prevent="getData">
                <a-row :gutter="8">
                    <!-- 搜索 -->
                    <a-col :sm="24">
                        <a-form-item>
                            <a-input-search
                                name="filterText"
                                :placeholder="l('SearchWithThreeDot')"
                                @search="getData"
                                enterButton
                                v-model="filterText"
                                v-decorator="['filterText']" />
                        </a-form-item>
                    </a-col>
                    <!-- 源语言 -->
                    <a-col :sm="6">
                        <a-form-item :label="l('BaseLanguage')">
                            <a-select :placeholder="l('BaseLanguage')" @change="getData" v-decorator="['baseLanguageName', {
                                    rules: [
                                        { required: true, message: l('ThisFieldIsRequired') },
                                    ]
                                }]">
                                <a-select-option v-for="item in ILanguageInfo" :key="item.name" :value="item.name">
                                    {{ item.displayName }}
                                </a-select-option>
                            </a-select>
                        </a-form-item>
                    </a-col>
                    <!-- 目标语言 -->
                    <a-col :sm="6">
                        <a-form-item :label="l('TargetLanguage')">
                            <a-select :placeholder="l('TargetLanguage')" @change="getData" v-decorator="['targetLanguageName', {
                                    rules: [
                                        { required: true, message: l('ThisFieldIsRequired') },
                                    ]
                                }]">
                                <a-select-option v-for="item in ILanguageInfo" :key="item.name" :value="item.name">
                                    {{ item.displayName }}
                                </a-select-option>
                            </a-select>
                        </a-form-item>
                    </a-col>
                    <!-- 源 -->
                    <a-col :sm="6">
                        <a-form-item :label="l('Source')">
                            <a-select :placeholder="l('Source')" @change="getData" v-decorator="['sourceName', {
                                    rules: [
                                        { required: true, message: l('ThisFieldIsRequired') },
                                    ]
                                }]">
                                <a-select-option v-for="item in sources" :key="item.name" :value="item.name">
                                    {{ item.name }}
                                </a-select-option>
                            </a-select>
                        </a-form-item>
                    </a-col>
                    <!-- 目标值 -->
                    <a-col :sm="6">
                        <a-form-item :label="l('TargetValue')">
                            <a-select :placeholder="l('TargetValue')" @change="getData" v-decorator="['targetValueFilter', {
                                    rules: [
                                        { required: true, message: l('ThisFieldIsRequired') },
                                    ]
                                }]">
                                <a-select-option value="ALL">
                                    {{ l('All') }}
                                </a-select-option>
                                <a-select-option value="EMPTY">
                                    {{ l('EmptyOnes') }}
                                </a-select-option>
                            </a-select>
                        </a-form-item>
                    </a-col>
                </a-row>
            </a-form>
            <!-- table -->
            <a-row>
                <a-table
                    class="list-table"
                    @change="getData"
                    :pagination="false"
                    :columns="columns"
                    :rowKey="tableDatas => tableDatas.id"
                    :dataSource="tableData">
                    <span slot="actions" slot-scope="text, record">
                        <!-- 修改 -->
                        <a class="table-edit" @click="edit(record)">
                            <a-icon type="edit" />{{ l('Edit') }}</a>
                    </span>
                </a-table>
                <a-pagination
                    class="pagination"
                    size="middle"
                    :total="totalItems"
                    showSizeChanger
                    showQuickJumper
                    :showTotal="showTotalFun"
                    @change="onChange"
                    @showSizeChange="showSizeChange" />
            </a-row>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { ModalHelper } from "@/shared/helpers";
import { LanguageServiceProxy } from "@/shared/service-proxies";
import moment from "moment";
import { AppConsts } from "@/abpPro/AppConsts";
import { appSessionService } from "@/shared/abp";
import EditLanguageText from "./edit-language-text/edit-language-text";

export default {
    mixins: [AppComponentBase],
    name: "language-texts",
    components: {},
    data() {
        return {
            form: this.$form.createForm(this),
            // 表格
            columns: [
                {
                    title: this.l("Key"),
                    dataIndex: "key",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "key" }
                },
                {
                    title: this.l("BaseValue"),
                    dataIndex: "baseValue",
                    align: "center",
                    scopedSlots: { customRender: "baseValue" }
                },
                {
                    title: this.l("TargetValue"),
                    dataIndex: "targetValue",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "targetValue" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "actions",
                    align: "center",
                    scopedSlots: { customRender: "actions" }
                }
            ],
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { sorting: "", maxResultCount: 10, skipCount: 0 },
            // 请求参数
            filterText: "",
            tableData: [],
            // loading
            spinning: false,
            // 语言下拉
            ILanguageInfo: [],
            // 源
            sources: [],
            _languageServiceProxy: "",
            // 请求参数
            sourceName: "",
            baseLanguageName: "",
            targetLanguageName: "",
            targetValueFilter: ""
        };
    },
    created() {
        this.ILanguageInfo = abp.localization.languages;
        this.sources = abp.localization.sources;
        this._languageServiceProxy = new LanguageServiceProxy(
            this.$apiUrl,
            this.$api
        );
        this.$nextTick(() => {
            console.log(this.$route.query.lang);
            this.form.setFieldsValue({
                baseLanguageName: this.ILanguageInfo.find(
                    item => item.isDefault
                ).name,
                targetLanguageName: this.ILanguageInfo.find(
                    item => item.name === this.$route.query.lang
                ).name,
                sourceName: this.sources[0].name,
                targetValueFilter: "ALL"
            });
            this.getData();
        });
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            console.log(this.form.getFieldsValue());
            this.sourceName = this.form.getFieldsValue().sourceName;
            this.baseLanguageName = this.form.getFieldsValue().baseLanguageName;
            this.targetLanguageName = this.form.getFieldsValue().targetLanguageName;
            this.targetValueFilter = this.form.getFieldsValue().targetValueFilter;
            this.spinning = true;
            this._languageServiceProxy
                .getLanguageTexts(
                    this.sourceName,
                    this.baseLanguageName,
                    this.targetLanguageName,
                    this.targetValueFilter,
                    this.filterText,
                    undefined,
                    this.request.maxResultCount,
                    this.request.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    console.log(res);
                    this.tableData = res.items;
                    // this.tableData.map(item => {
                    //     item.creationTimeStr = item.creationTime
                    //         ? moment(item.creationTime).format(
                    //               "YYYY-MM-DD HH:mm:ss"
                    //           )
                    //         : "-";
                    // });
                    this.totalItems = res.totalCount;
                    this.totalPages = Math.ceil(
                        res.totalCount / this.request.maxResultCount
                    );
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                });
        },
        /**
         * 编辑语言
         */
        edit(item) {
            console.log(item);
            let senItem = Object.assign(item, {
                baseLanguageName: this.form.getFieldsValue().baseLanguageName,
                baseLanguageNameText: this.ILanguageInfo.find(
                    item =>
                        item.name ===
                        this.form.getFieldsValue().baseLanguageName
                ).displayName,
                targetLanguageNameText: this.ILanguageInfo.find(
                    item =>
                        item.name ===
                        this.form.getFieldsValue().targetLanguageName
                ).displayName,
                targetLanguageName: this.form.getFieldsValue()
                    .targetLanguageName,
                sourceName: this.form.getFieldsValue().sourceName,
                value: item.targetValue
                // sourceName:
            });
            ModalHelper.create(
                EditLanguageText,
                {
                    editItem: senItem
                },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        },
        /**
         * 返回语言列表
         */
        backLanguageList() {
            this.$router.push({
                path: "/app/admin/languages"
            });
        }
    }
};
</script>

<style scoped lang="less">
.subscriptionEndUtc {
    text-align: center;
}
// table
.list-table {
    i {
        margin-right: 10px;
    }
}
.pagination {
    margin: 10px auto;
    text-align: right;
}
.table-edit {
    .anticon {
        margin-right: 10px;
    }
}
.table-delete,
.ant-dropdown-link {
    margin-left: 20px;
}
</style>
