// src/yoyocmstemplate-angular/src/account/login/login.component.ts
import { Component, Injector, ViewChild, OnInit } from '@angular/core';

import { LoginService } from './login.service';
import { appModuleAnimation } from '@shared/animations/routerTransition';
import { AppComponentBase } from '@shared/component-base/app-component-base';
import { AbpSessionService } from 'abp-ng2-module';
import { SessionServiceProxy, UpdateUserSignInTokenOutput } from '@shared/service-proxies';
import { UrlHelper } from '@shared/helpers/UrlHelper';
import { AppCaptchaType } from 'abpPro/AppEnums';
import { AppConsts } from 'abpPro/AppConsts';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.less'],
  animations: [appModuleAnimation()],
})
export class LoginComponent extends AppComponentBase implements OnInit {

  submitting = false;

  verificationImgUrl = '';

  /** 是否启用多租户 */
  get isMultiTenancyEnabled(): boolean {
    return abp.multiTenancy.isEnabled;
  }

  /** 是否已选中租户 */
  get multiTenancySideIsTeanant(): boolean {
    return this.appSession.tenantId > 0;
  }

  /** 允许注册租户 */
  get isTenantSelfRegistrationAllowed(): boolean {
    if (this.appSession.tenantId) {
      return false;
    }
    return this.setting.getBoolean('App.Host.AllowSelfRegistration');
  }


  /** 允许注册用户 */
  get isSelfRegistrationAllowed(): boolean {
    if (!this.appSession.tenantId) {
      return false;
    }
    return this.setting.getBoolean('App.AllowSelfRegistrationUser');
  }

  /** 是否使用登陆验证码 */
  get useCaptcha(): boolean {
    return this.setting.getBoolean('App.UserManagement.EnableCapthaOnLogin');
  }

  /** 验证码时间戳 */
  captchaTimestamp: any;


  /** 激活的三方登陆类型 */
  get enabledExternalLoginTypes(): string[] {
    return JSON.parse(this.setting.get('App.UserManagement.ExternalLoginProviders'));
  }

  constructor(
    injector: Injector,
    public loginService: LoginService,
    private _abpSessionService: AbpSessionService,
    private _sessionAppService: SessionServiceProxy,
  ) {
    super(injector);
  }

  getCaptchaType(): number {
    if (this.appSession.tenantId) {
      return AppCaptchaType.TenantUserLogin;
    } else {
      return AppCaptchaType.HostUserLogin;
    }
  }



  async ngOnInit() {
    this.titleSrvice.setTitle(this.l('LogIn'));

    if (this._abpSessionService.userId > 0 && UrlHelper.getReturnUrl()) {
      this._sessionAppService.updateUserSignInToken().subscribe((result: UpdateUserSignInTokenOutput) => {
        const initialReturnUrl = UrlHelper.getReturnUrl();
        const returnUrl =
          initialReturnUrl +
          (initialReturnUrl.indexOf('?') >= 0 ? '&' : '?') +
          'accessToken=' +
          result.signInToken +
          '&userId=' +
          result.encodedUserId +
          '&tenantId=' +
          result.encodedTenantId;

        location.href = returnUrl;
      });
    }
  }

  /** 登录按钮 */
  login(): void {
    this.submitting = true;
    this.loginService.authenticate((success: boolean) => {
      if (!success) {
        // 登陆失败,刷新验证码
        this.updateCaptchaTimestamp();
      }

      this.submitting = false;
    });
  }

  //#region 验证码功能
  onKey(e: KeyboardEvent): any {
    if (e.key === 'Tab') {
      this.initImg();
    }
  }
  initImg(): void {
    const userName = this.loginService.authenticateModel.userNameOrEmailAddress;
    if (!userName || userName === '' || this.verificationImgUrl !== '') {
      return;
    }
    this.clearimg();
  }

  clearimg(): void {
    const userName = this.loginService.authenticateModel.userNameOrEmailAddress;
    if (!userName || userName === '') {
      // 未输入账号
      return;
    }

    let tid: any = this.appSession.tenantId;
    if (!tid) {
      tid = '';
    }
    const timestamp = new Date().getTime();

    this.verificationImgUrl =
      AppConsts.remoteServiceBaseUrl +
      '/api/TokenAuth/GenerateVerification' +
      '?name=' +
      userName +
      '&tid=' +
      tid +
      '&t=' +
      timestamp;
  }

  /** 更新验证码时间戳 */
  private updateCaptchaTimestamp() {
    this.captchaTimestamp = new Date().getTime();
  }
}

<!-- 表单输入错误模板 -->
<ng-template #errorTpl let-control>
  <validation-messages [formCtrl]="control"></validation-messages>
</ng-template>

<nz-spin [nzTip]="l('LogIningWithThreeDot')" [nzSpinning]="saving">
  <!-- 租户切换 -->
  <div *ngIf="isMultiTenancyEnabled">
    <tenant-change></tenant-change>
  </div>

  <!-- <ng-container *ngIf="loginService.authentSuccessModel">
    <a routerLink="/account/register">注册账号,绑定登录</a>
  </ng-container> -->
  <!--  输入框  -->
  <form nz-form #loginForm="ngForm" (ngSubmit)="login()" autocomplete="off">
    <br />
    <!-- 账号 -->
    <nz-form-item>
      <nz-form-control [nzErrorTip]="errorTpl">
        <nz-input-group [nzPrefix]="nzPrefixIconUser">
          <input
            nz-input
            name="userNameOrEmailAddress"
            #userNameOrEmailAddressInput="ngModel"
            [(ngModel)]="loginService.authenticateModel.userNameOrEmailAddress"
            [placeholder]="l('UserNameOrEmail')"
            required
            maxlength="255"
          />
        </nz-input-group>
        <ng-template #nzPrefixIconUser>
          <span class="iconfont icon-user" style="color: rgba(0, 0, 0, 0.25)"></span>
        </ng-template>
      </nz-form-control>
    </nz-form-item>

    <!-- 密码 -->
    <nz-form-item>
      <nz-form-control [nzErrorTip]="errorTpl">
        <nz-input-group [nzPrefix]="nzPrefixIconLock">
          <input
            nz-input
            name="password"
            #passwordInput="ngModel"
            [(ngModel)]="loginService.authenticateModel.password"
            [placeholder]="l('Password')"
            type="password"
            required
            maxlength="32"
          />
        </nz-input-group>
        <ng-template #nzPrefixIconLock>
          <span class="iconfont icon-lock" style="color: rgba(0, 0, 0, 0.25)"></span>
        </ng-template>
      </nz-form-control>
    </nz-form-item>

    <!-- 验证码-->
    <nz-form-item *ngIf="useCaptcha">
      <nz-form-control [nzErrorTip]="errorTpl">
        <!-- <yoyo-captcha
          name="verificationCode"
          #verificationCodeInput="ngModel"
          [(ngModel)]="loginService.authenticateModel.verificationCode"
          [key]="loginService.authenticateModel.userNameOrEmailAddress"
          [timestamp]="captchaTimestamp"
          required
        >
        </yoyo-captcha> -->
        <nz-col [nzSpan]="12">
          <nz-input-group [nzPrefix]="nzPrefixIconPicture">
            <input
              nz-input
              name="verificationCode"
              #verificationCodeInput="ngModel"
              [(ngModel)]="loginService.authenticateModel.verificationCode"
              [placeholder]="l('CAPTCHA')"
              type="text"
              (click)="initImg()"
              (keyup)="onKey($event)"
              required
              maxlength="32"
            />
          </nz-input-group>
          <ng-template #nzPrefixIconPicture>
            <span class="iconfont icon-image" style="color: rgba(0, 0, 0, 0.25)"></span>
          </ng-template>
          <!-- </nz-col>
        <nz-col [nzSpan]="12" class="text-right"> -->
          <img (click)="clearimg()" [src]="verificationImgUrl" />
        </nz-col>
      </nz-form-control>
    </nz-form-item>

    <!-- 登陆按钮 -->
    <button nz-button [nzType]="'primary'" class="yoyo__block" [disabled]="!loginForm.form.valid || submitting">
      <i class="iconfont icon-login"></i>
      <span>{{ l('LogIn') }}</span>
    </button>
  </form>
</nz-spin>

// src/yoyocmstemplate-vue/src/account/login/login.vue
<template>
    <div id="login">
        <a-spin :spinning="submitting" :tip="l('LogIningWithThreeDot')">
            <a-card>
                <div slot="title">
                    <div class="text-center yoyo__block">
                        <i class="anticon anticon-login"></i>
                        <span>{{l("LogIn")}}</span>
                    </div>
                </div>

                <a-form :form="form" @submit="login($event)">
                    <a-form-item :help="userNameError() || ''" :validate-status="userNameError() ? 'error' : ''">

                        <a-input :placeholder="l('UserNameOrEmail')"
                                 @blur="userNameOrEmailAddressOnBlur()"
                                 v-decorator="['userNameOrEmailAddress',{
                                 rules: [
                                    { required: true, message: l('ThisFieldIsRequired')}
                                    ]
                                 }]"
                        >
                            <i class="anticon anticon-user" slot="prefix"></i>
                        </a-input>
                    </a-form-item>
                    <a-form-item :help="passwordError() || ''" :validate-status="passwordError() ? 'error' : ''">
                        <a-input
                                :placeholder="l('Password')"
                                type="password"
                                v-decorator="['password',{
                                rules: [
                                    { required: true, message: l('ThisFieldIsRequired') }
                                    ]
                                }]"
                        >
                            <i class="anticon anticon-lock" slot="prefix"></i>
                        </a-input>
                    </a-form-item>
                    <a-form-item v-if="useCaptcha">
                        <captcha ref="captcha"
                                 :placeholder="l('CAPTCHA')"
                                 :primaryKey="primaryKey"
                                 :type="captchaType"
                                 v-decorator="['verificationCode',{
                                    rules: [
                                        { required: true, message: l('ThisFieldIsRequired') }
                                    ]
                                    }]"></captcha>
                    </a-form-item>
                    <a-form-item>
                        <a-button :disabled="hasErrors(form.getFieldsError())"
                                  class="yoyo__block"
                                  html-type="submit"
                                  type="primary">
                            {{l("LogIn")}}
                        </a-button>
                    </a-form-item>
                </a-form>


            </a-card>
        </a-spin>
    </div>
</template>

<script>
    import {TokenAuthServiceProxy} from "@/shared/service-proxies";
    import {AppComponentBase} from "@/shared/component-base";
    import {Captcha} from '../components';
    import AFormItem from "ant-design-vue/es/form/FormItem";
    import {abpService, appSessionService} from '@/shared/abp';
    import {AppCaptchaType} from '@/abpPro/AppEnums';
    import {loginService} from './login.service';


    function hasErrors(fieldsError) {
        return Object.keys(fieldsError).some(field => fieldsError[field]);
    }

    export default {
        components: {
            AFormItem,
            Captcha
        },
        mixins: [AppComponentBase],
        data() {
            return {
                hasErrors,
                isSubmitting: false, // 提交中
                tmpPrimaryKey: undefined,
                verificationImgUrl: undefined, // 验证码地址
                form: this.$form.createForm(this),
                tokenAuthService: TokenAuthServiceProxy,
            };
        },
        computed: {
            primaryKey() { // 验证码主键
                return this.tmpPrimaryKey;
            },
            submitting() { // 提交中
                return this.isSubmitting;
            },
            externalLoginProviders() { // 第三方登陆提供者
                return loginService.externalLoginProviders;
            },
            multiTenancySideIsTeanant() { // 是否已选中租户
                return abpService.tenantId > 0;
            },
            isTenantSelfRegistrationAllowed() { // 是否允许注册租户
                if (abpService.tenantId) {
                    return false;
                }
                return abpService.abp.setting.getBoolean('App.Host.AllowSelfRegistration');
            },
            isMultiTenancyEnabled() { // 是否启用多租户
                return abpService.abp.multiTenancy.isEnabled;
            },
            isSelfRegistrationAllowed() { // 是否允许注册
                if (!this.appSessionService.tenantId) {
                    return false;
                }
                return abpService.abp.setting.getBoolean('App.AllowSelfRegistrationUser');
            },
            useCaptcha() { // 是否使用登陆验证码
                return abpService.abp.setting.getBoolean('App.UseCaptchaOnUserLogin');
            },
            captchaType() { // 验证码类型
                if (appSessionService.tenantId) {
                    return AppCaptchaType.TenantUserLogin;
                } else {
                    return AppCaptchaType.HostUserLogin;
                }
            },
            captchaLength() { // 验证码长度
                return abpService.abp.setting.getInt('App.CaptchaOnUserLoginLength');
            },
            enabledExternalLoginTypes() { // 第三方登陆的类型
                return JSON.parse(
                    abpService.abp.setting.get('App.UserManagement.ExternalLoginProviders')
                );
            }
        },
        created() {
            this.tokenAuthService = new TokenAuthServiceProxy(this.$apiUrl, this.$api);
            loginService.initExternalLoginProviders()
                .then(() => {

                });

            if (appSessionService.userId > 0 && loginService.getReturnUrl()) {
                appSessionService.session
                    .updateUserSignInToken()
                    .subscribe((result) => {
                        const initialReturnUrl = loginService.getReturnUrl();
                        const returnUrl =
                            initialReturnUrl +
                            (initialReturnUrl.indexOf('?') >= 0 ? '&' : '?') +
                            'accessToken=' +
                            result.signInToken +
                            '&userId=' +
                            result.encodedUserId +
                            '&tenantId=' +
                            result.encodedTenantId;

                        location.href = returnUrl;
                    });
            }
        },
        mounted() {

        },
        watch: {},
        methods: {
            // handler
            handleUsernameOrEmail(rule, value, callback) {
                const {state} = this;
                const regex = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/;
                if (regex.test(value)) {
                    state.loginType = 0;
                } else {
                    state.loginType = 1;
                }
                callback();
            },
            // Only show error after a field is touched.
            userNameError() {
                const {getFieldError, isFieldTouched} = this.form;
                return isFieldTouched('userNameOrEmailAddress') && getFieldError('userNameOrEmailAddress');
            },
            // Only show error after a field is touched.
            passwordError() {
                const {getFieldError, isFieldTouched} = this.form;
                return isFieldTouched('password') && getFieldError('password');
            },
            userNameOrEmailAddressOnBlur() {
                this.tmpPrimaryKey = this.form.getFieldValue('userNameOrEmailAddress');
            },
            login(e) {
                e.preventDefault();

                loginService.authenticateModel.userNameOrEmailAddress = this.form.getFieldValue('userNameOrEmailAddress');
                loginService.authenticateModel.password = this.form.getFieldValue('password');
                loginService.authenticateModel.verificationCode = this.form.getFieldValue('verificationCode');
                loginService.authenticateModel.rememberClient = this.form.getFieldValue('rememberClient');

                loginService.authenticate(undefined, () => {
                    if (this.$refs.captcha) {
                        this.$refs.captcha.clearImg();
                    }
                }, () => {
                    this.isSubmitting = false;
                });

            },
            loginSuccess(res) {
                /**
                 * TODO: 这里跳转会进入err函数,因为初始化 $router 时没有加入 path 为 / 的路由,跳转无法匹配到
                 * 但是会在 permission.js 中根据url redirect 信息重定向到正常页面,所以这里认为是正常的跳转
                 */
                // this.$router.goto(
                //     {path: "/"},
                //     () => {
                //     },
                //     err => {
                //         this.$notification.success({
                //             message: "欢迎",
                //             description: `${timeFix()}，欢迎回来`
                //         });
                //     }
                // );
                // this.isLoginError = false;
            }
        }
    };
</script>

<style lang="less" scoped>
    @import "./login.less";
</style>
