// src/yoyocmstemplate-angular/src/app/admin/organization-units/create-or-edit-organiaztion-unit/create-or-edit-organiaztion-unit.component.ts
import { Component, OnInit, Injector, Input } from '@angular/core';
// tslint:disable-next-line:max-line-length
import {
  OrganizationUnitServiceProxy,
  CreateOrganizationUnitInput,
  UpdateOrganizationUnitInput,
  OrganizationUnitListDto,
} from '@shared/service-proxies/service-proxies';
import { Validators } from '@angular/forms';
import { finalize } from 'rxjs/operators';
import { ModalComponentBase } from '@shared/component-base/modal-component-base';

export interface IOrganizationUnitOnEdit {
  id?: number;
  parentId?: number;
  displayName?: string;
  parentDisplayName?: string;
}

@Component({
  selector: 'app-create-or-edit-organiaztion-unit',
  templateUrl: './create-or-edit-organiaztion-unit.component.html',
  styles: [],
})
export class CreateOrEditOrganiaztionUnitComponent extends ModalComponentBase
  implements OnInit {
  @Input()
  organizationUnit: IOrganizationUnitOnEdit = {};

  constructor(
    injector: Injector,
    private organizationUnitService: OrganizationUnitServiceProxy,
  ) {
    super(injector);
  }

  ngOnInit() {}

  save(): void {
    if (this.organizationUnit.id) {
      this.updateUnit();
    } else {
      // 创建
      this.createUnit();
    }
  }

  updateUnit(): any {
    // 编辑
    const updateInput = new UpdateOrganizationUnitInput();
    updateInput.id = this.organizationUnit.id;
    updateInput.displayName = this.organizationUnit.displayName;
    this.saving = true;
    this.organizationUnitService
      .update(updateInput)
      .pipe(finalize(() => (this.saving = false)))
      .subscribe(result => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success(result);
      });
  }
  createUnit(): any {
    // 创建
    const input = new CreateOrganizationUnitInput();
    input.parentId = this.organizationUnit.parentId;
    input.displayName = this.organizationUnit.displayName;
    this.saving = true;

    this.organizationUnitService
      .create(input)
      .pipe(finalize(() => (this.saving = false)))
      .subscribe((result: OrganizationUnitListDto) => {
        this.notify.success(this.l('SavedSuccessfully'));
        this.success(result);
      });
  }
}

<form nz-form #organizationCreateOrEditForm="ngForm" (ngSubmit)="save()" autocomplete="off">
  <div class="modal-header">
    <div class="modal-title">
      <!-- <i class="iconfont icon-share-alt mr-sm"></i> -->
      <i class="iconfont icon-share  mr-sm"></i>
      <span *ngIf="organizationUnit.id">{{ l('Edit') }}: {{ organizationUnit.displayName }}</span>
      <span *ngIf="!organizationUnit.id && !organizationUnit.parentId">{{ l('NewOrganizationUnit') }}</span>
      <span *ngIf="organizationUnit.parentId && organizationUnit.parentDisplayName">{{
        l('AddSubNodeForXParentNode', organizationUnit.parentDisplayName)
      }}</span>
    </div>
  </div>

  <fieldset>
    <nz-form-item nz-row>
      <nz-form-label nz-col [nzSm]="3" nzFor="DisplayName" nzRequired>
        {{ l('NameOfThings') }}
      </nz-form-label>
      <nz-form-control nz-col [nzSm]="21" nzHasFeedback>
        <nz-input-group [nzPrefix]="nzPrefixIconBook">
          <input nz-input #organizationUnitDisplayName="ngModel" name="DisplayName"
            [(ngModel)]="organizationUnit.displayName" [placeholder]="l('NameOfThings')" required maxlength="128" />
        </nz-input-group>

        <nz-form-control nzExtra
          *ngIf="organizationUnitDisplayName.control.dirty && organizationUnitDisplayName.control.errors">
          <ng-container *ngIf="organizationUnitDisplayName.control.hasError('required')">{{ l('ThisFieldIsRequired') }}
          </ng-container>
          <ng-container *ngIf="organizationUnitDisplayName.control.hasError('minlength')">{{ l('MinLength') }}
          </ng-container>
          <ng-container *ngIf="organizationUnitDisplayName.control.hasError('maxlength')">{{ l('MaxLength') }}
          </ng-container>
        </nz-form-control>

        <ng-template #nzPrefixIconBook><span class="iconfont icon-book" style="color: rgba(0, 0, 0, 0.25);"></span>
        </ng-template>
      </nz-form-control>
    </nz-form-item>
  </fieldset>

  <div class="modal-footer">
    <button nz-button [nzType]="'default'" type="button" (click)="close($event)" [disabled]="saving">
      <!-- <i class="iconfont icon-close-circle-o"></i>  -->
      <i class="iconfont icon-close-circle "></i>
      {{ l('Cancel') }}
    </button>
    <button nz-button [nzType]="'primary'" type="submit" [disabled]="!organizationCreateOrEditForm.form.valid || saving"
      [nzLoading]="saving">
      <!-- <i class="iconfont icon-save" *ngIf="!saving"></i>  -->
      <i class="iconfont icon-save " *ngIf="!saving"></i>
      {{ l('Save') }}
    </button>
  </div>
</form>

// src/yoyocmstemplate-vue/src/app/admin/organization-units/create-or-edit-organiaztion-unit/create-or-edit-organiaztion-unit.vue
<template>
    <section>
        <div class="modal-header">
            <div class="modal-title" v-if="organizationUnit.id">
                <a-icon type="share-alt" />{{ l('Edit') }}: {{ organizationUnit.displayName }}</div>
            <div class="modal-title" v-if="!organizationUnit.id && !organizationUnit.parentId">
                <a-icon type="share-alt" />{{ l('NewOrganizationUnit') }}</div>
            <div class="modal-title" v-if="organizationUnit.parentId && organizationUnit.parentDisplayName">
                <a-icon type="share-alt" />{{l('AddSubNodeForXParentNode', organizationUnit.parentDisplayName)}}</div>
        </div>
        <a-form :form="form" :label-col="{ span: 5 }" :wrapper-col="{ span: 12 }">
            <a-form-item :label="l('NameOfThings')">
                <a-input :placeholder="l('NameOfThings')"
                    v-decorator="['displayName', { rules: [
                            { required: true, message: l('ThisFieldIsRequired') },
                            { max:128, message: l('MaxLength')  }
                        ] }]" />
            </a-form-item>
        </a-form>

        <div class="modal-footer">
            <a-button :disabled="saving" @click="close()" type="button">
                <a-icon type="close-circle" />
                {{ l('Cancel') }}
            </a-button>
            <a-button :loading="saving" :type="'primary'" @click="handleSubmit()">
                <a-icon type="save" />
                {{ l('Save') }}
            </a-button>
        </div>
    </section>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { ModalComponentBase } from "@/shared/component-base";
import { OrganizationUnitServiceProxy } from "@/shared/service-proxies";

export default {
    name: "create-or-edit-organiaztion-unit",
    mixins: [AppComponentBase, ModalComponentBase],
    data() {
        return {
            // 表单
            formLayout: "horizontal",
            form: this.$form.createForm(this, { name: "coordinated" }),
            _organizationUnitServiceProxy: null
        };
    },
    created() {
        this.fullData(); // 模态框必须,填充数据到data字段
        this._organizationUnitServiceProxy = new OrganizationUnitServiceProxy(
            this.$apiUrl,
            this.$api
        );
        console.log(this.organizationUnit);
        // 修改
        if (this.organizationUnit) {
            this.$nextTick(() => {
                this.form.setFieldsValue({
                    displayName: this.organizationUnit.displayName
                });
            });
        }
    },
    methods: {
        /**
         * 提交表单
         */
        handleSubmit() {
            this.form.validateFields((err, values) => {
                if (!err) {
                    console.log("Received values of form: ", values);
                    if (this.organizationUnit.id) {
                        this.updateUnit(values);
                    } else {
                        // 创建
                        this.createUnit(values);
                    }
                }
            });
        },
        /**
         * 创建
         */
        createUnit(parmas) {
            Object.assign(parmas, {
                parentId: this.organizationUnit.parentId
            });
            this.saving = true;
            this._organizationUnitServiceProxy
                .create(parmas)
                .finally(() => {
                    this.saving = false;
                })
                .then(result => {
                    this.$notification["success"]({
                        message: this.l("SavedSuccessfully")
                    });
                    this.success(result);
                });
        },
        /**
         * 编辑
         */
        updateUnit(value) {
            this.organizationUnit.displayName = value.displayName;
            this.saving = true;
            this._organizationUnitServiceProxy
                .update(this.organizationUnit)
                .finally(() => {
                    this.saving = false;
                })
                .then(result => {
                    this.notify.success(this.l("SavedSuccessfully"));
                    this.success(result);
                });
        }
    }
};
</script>

<style scoped lang="less">
.modal-header {
    .anticon-share-alt {
        margin-right: 10px;
    }
}
</style>
