// src/yoyocmstemplate-angular/src/app/admin/editions/editions.component.ts
import { Component, OnInit, Injector } from '@angular/core';
import { EditionServiceProxy, EditionListDto } from '@shared/service-proxies/service-proxies';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base';
import { finalize } from 'rxjs/operators';
import { CreateOrEditEditionComponent } from './create-or-edit-edition/create-or-edit-edition.component';

@Component({
  selector: 'app-editions',
  templateUrl: './editions.component.html',
  styles: [],
})
export class EditionsComponent extends PagedListingComponentBase<EditionListDto> implements OnInit {


  constructor(
    injector: Injector,
    private _editionService: EditionServiceProxy,
  ) {
    super(injector);
  }

  ngOnInit(): void {
    super.ngOnInit();
  }


  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: () => void): void {

    this._editionService.getEditions()
      .pipe(finalize(() => {
        finishedCallback();
      })).subscribe((result) => {
      this.dataList = result.items;
    });
  }

  batchDelete() {

  }

  create() {
    this.modalHelper.static(CreateOrEditEditionComponent)
      .subscribe((res) => {
        if (res) {
          this.refresh();
        }
      });
  }

  edit(entityId: number) {
    this.modalHelper.static(CreateOrEditEditionComponent, { editionId: entityId })
      .subscribe((res) => {
        if (res) {
          this.refresh();
        }
      });
  }


  delete(entity: EditionListDto) {
    this.message.confirm(
      this.l('EditionDeleteWarningMessage', entity.displayName),
      undefined,
      isConfirmed => {
        if (isConfirmed) {
          this._editionService.deleteEdition(entity.id).subscribe(() => {
            this.refresh();
            this.notify.success(this.l('SuccessfullyDeleted'));
          });
        }
      },
    );
  }

  /**
   * 强制刷新
   */
  forceRefresh() {
    this.refreshGoFirstPage();
  }

}

<page-header [title]="l('Editions')"> </page-header>

<!-- <full-content (fullscreenChange)="fullChange($event)"> -->
<!-- 表格部分 -->
<nz-card [nzBordered]="false">
  <!-- 操作部分 -->
  <nz-row nzGutter="8">
    <nz-col nzMd="20" nzSm="12" class="btn-gutter">
      <button nz-button [nzType]="'primary'" *ngIf="isGranted('Pages.Editions.Create')" (click)="create()">
        <i class="iconfont icon-plus"></i>
        <span>
          {{ l('CreateNewEdition') }}
        </span>
      </button>
      <button nz-button [nzType]="'danger'" *ngIf="isGranted('Pages.Editions.Delete')" (click)="batchDelete()">
        <i class="iconfont icon-delete"></i>
        <span>
          {{ l('BatchDelete') }}
        </span>
      </button>
    </nz-col>
  </nz-row>
  <!-- 复选框提示的内容数据部分 -->
  <table-checkbox-panel [selectLength]="selectedDataItems.length" (onClear)="restCheckStatus(dataList)"
    (onRefresh)="refreshGoFirstPage()"></table-checkbox-panel>

  <nz-table #nzDataTable [nzFrontPagination]="false" [nzShowPagination]="false" [nzData]="dataList"
    [nzLoading]="isTableLoading" [nzNoResult]="noDataTemplate">
    <!-- 暂无数据 -->
    <ng-template #noDataTemplate>
      <no-data></no-data>
    </ng-template>
    <!-- 表头 -->
    <thead (nzSortChange)="gridSort($event)">
      <tr>
        <th nzShowCheckbox [(nzChecked)]="allChecked" [nzDisabled]="allCheckboxDisabled"
          [nzIndeterminate]="checkboxIndeterminate" (nzCheckedChange)="checkAll($event)"></th>
        <th nzShowSort nzSortKey="name">
          <span>{{ l('Edition') }}</span>
        </th>
        <th nzShowSort nzSortKey="editionName">
          <span>{{ l('EditionName') }}</span>
        </th>
        <th nzShowSort nzSortKey="creationTime" class="text-center">
          <span>{{ l('CreationTime') }}</span>
        </th>
        <th nzWidth="240px" class="text-center">
          <span>{{ l('Actions') }}</span>
        </th>
      </tr>
    </thead>
    <!-- 表格内容 -->
    <tbody>
      <tr *ngFor="let item of nzDataTable.data">
        <td nzShowCheckbox [(nzChecked)]="item.checked" (nzCheckedChange)="refreshCheckStatus(dataList)"></td>
        <td>
          {{ item.name }}
        </td>
        <td>
          {{ item.displayName }}
        </td>
        <td class="text-center">
          {{ item.creationTime | _moment: 'YYYY-MM-DD' }}
        </td>
        <td class="text-center">
          <!-- 编辑 -->
          <ng-container *ngIf="isGranted('Pages.Editions.Edit')">
            <a (click)="edit(item.id)">
              <i class="iconfont icon-edit mr-sm"></i>
              <span>{{ l('Edit') }}</span>
            </a>
            <nz-divider nzType="vertical"></nz-divider>
          </ng-container>
          <!-- 删除 -->
          <ng-container *ngIf="isGranted('Pages.Editions.Delete')">
            <a nz-popconfirm [nzPopconfirmTitle]="l('ConfirmDeleteWarningMessage')" (nzOnConfirm)="delete(item)"
              [nzOkText]="l('Ok')" [nzCancelText]="l('Cancel')">
              <i class="iconfont icon-delete mr-sm"></i>
              <span>{{ l('Delete') }}</span>
            </a>
          </ng-container>
        </td>
      </tr>
    </tbody>
  </nz-table>

</nz-card>

// src/yoyocmstemplate-vue/src/app/admin/editions/editions.vue
<template>
    <div>
        <page-header :title="l('Editions')"></page-header>
        <!-- 表格部分 -->
        <a-card :bordered="false">
            <!-- 操作部分 -->
            <a-row :gutter="8">
                <a-col :md="20" :sm="12" class="btn-gutter">
                    <a-button @click="create()" type="primary" v-if="isGranted('Pages.Editions.Create')">
                        <i class="anticon anticon-plus"></i>
                        <span>{{l("CreateNewEdition")}}</span>
                    </a-button>
                    <a-button
                        @click="batchDelete()"
                        type="danger"
                        v-if="isGranted('Pages.Editions.Delete')">
                        <i class="anticon anticon-delete"></i>
                        <span>{{l("BatchDelete")}}</span>
                    </a-button>
                </a-col>
            </a-row>
            <!-- 数据部分 -->
            <div class="my-md">
                <a-alert :showIcon="true" type="info">
                    <template slot="message">
                        <span v-html="l('GridSelectedXItemsTips',selectedRowKeys.length)"></span>
                        <a @click="restCheckStatus(dataList)" class="ml-md">
                            {{l('ClearEmpty')}}
                        </a>
                        <a-divider type="vertical"></a-divider>
                        <a @click="refresh()">
                            {{l('Refresh')}}
                        </a>
                    </template>
                </a-alert>
            </div>
            <a-row class="my-md">
                <a-table :dataSource="dataList" :loading="isTableLoading"
                    :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}"
                    @change="tableChange">
                    <a-table-column :title="l('Edition')" dataIndex="name" key="name" sorter="true">

                    </a-table-column>
                    <a-table-column :title="l('EditionName')" dataIndex="displayName"
                        key="displayName" sorter="true"></a-table-column>
                    <a-table-column :title="l('CreationTime')" dataIndex="creationTimeStr"
                        key="creationTime" sorter="true"></a-table-column>
                    <a-table-column :title="l('Actions')" key="action">
                        <template slot-scope="text, record">
                            <span>
                                <a @click="edit(record.id)">
                                    <a-icon type="edit" />
                                    <span>{{l('Edit')}}</span>
                                </a>
                                <a-divider type="vertical" />
                                <a-popconfirm

                                    :cancelText="l('Cancel')"
                                    :okText="l('Ok')"
                                    :title="l('ConfirmDeleteWarningMessage')"
                                    @confirm="onDelete(record)">
                                    <a href="#">
                                        <a-icon type="delete" />
                                        <span>{{l('Delete')}}</span>
                                    </a>
                                </a-popconfirm>
                            </span>
                        </template>
                    </a-table-column>

                </a-table>
            </a-row>
        </a-card>
    </div>
</template>

<script>
import { PagedListingComponentBase } from "@/shared/component-base";
import { ModalHelper } from "@/shared/helpers";
import { EditionServiceProxy } from "@/shared/service-proxies";
import CreateOrEditEdition from "./create-or-edit-edition/create-or-edit-edition";

export default {
    name: "editions",
    mixins: [PagedListingComponentBase],
    components: {},
    data() {
        return {
            editionService: null
        };
    },
    created() {
        this.editionService = new EditionServiceProxy(this.$apiUrl, this.$api);
    },
    methods: {
        create() {
            ModalHelper.create(CreateOrEditEdition, {
                editionId: undefined
            }).subscribe(res => {
                if (res) {
                    this.refresh();
                }
            });
        },
        edit(entityId) {
            ModalHelper.create(CreateOrEditEdition, {
                editionId: entityId
            }).subscribe(res => {
                if (res) {
                    this.refresh();
                }
            });
        },
        onDelete(entity) {
            abp.message.confirm(
                this.l("EditionDeleteWarningMessage", entity.displayName),
                isConfirmed => {
                    if (isConfirmed) {
                        this.editionService
                            .deleteEdition(entity.id)
                            .then(() => {
                                this.refresh();
                                this.notify.success(
                                    this.l("SuccessfullyDeleted")
                                );
                            });
                    }
                }
            );
        },
        forceRefresh() {
            this.refreshGoFirstPage();
        },
        fetchDataList(request, pageNumber, finishedCallback) {
            // 获取数据抽象接口，必须实现
            this.editionService
                .getEditions()
                .finally(() => {
                    finishedCallback();
                })
                .then(result => {
                    this.dataList = result.items.map(o => {
                        return {
                            key: o.id,
                            ...o,
                            creationTimeStr: o.creationTime.format(
                                "YYYY-MM-DD HH:mm:ss"
                            )
                        };
                    });
                });
        },
        /**
         * table选择事件
         */
        onSelectChange(selectedRowKeys, selectedRows) {
            this.selectedRowKeys = selectedRowKeys;
            console.log(selectedRowKeys);
        },
        /**
         * 批量删除
         * todo
         * 接口暂缺
         */
        batchDelete() {}
    }
};
</script>

<style scoped lang="less">
.ant-table-body i {
    margin-right: 10px;
}
</style>
