// src/yoyocmstemplate-angular/src/app/admin/roles/roles.component.ts
import { Component, OnInit, Injector, ViewChild, NgZone } from '@angular/core';
import { PagedListingComponentBase, PagedRequestDto } from '@shared/component-base/paged-listing-component-base';
import { RoleListDto, RoleServiceProxy } from '@shared/service-proxies/service-proxies';
import { CreateOrEditRoleComponent } from '@app/admin/roles/create-or-edit-role/create-or-edit-role.component';
import { PermissionComboxComponent } from '@app/admin/shared/permission-combox/permission-combox.component';
import * as _ from 'lodash';
import { AppConsts } from 'abpPro/AppConsts';
import { finalize } from 'rxjs/operators';

@Component({
  selector: 'app-roles',
  templateUrl: './roles.component.html',
  styles: [],
})
export class RolesComponent extends PagedListingComponentBase<RoleListDto> {
  advancedFiltersVisible = false; // 是否显示高级过滤

  /**
   * 选中的权限过滤
   */
  selectedPermission: string[] = [];

  constructor(injector: Injector, private _roleService: RoleServiceProxy, public _zone: NgZone) {
    super(injector);
  }

  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    this._roleService
      .getPaged(
        this.selectedPermission,

        this.filterText,
        request.sorting,
        request.maxResultCount,
        request.skipCount,
      )
      .pipe(finalize(() => finishedCallback()))
      .subscribe(result => {
        this.dataList = result.items;
        this.showPaging(result);
      });
  }

  /**
   * 强制刷新
   */
  forceRefresh() {
    this.filterText = '';
    this.refreshGoFirstPage();
  }

  ngOnInit(): void {
    // 初始化加载表格数据
    this.refresh();
  }

  /**
   * 删除功能
   * @param entity 角色的实体信息
   */
  delete(entity: RoleListDto): void {
    if (entity.isStatic) {
      abp.message.warn(this.l('XUserCannotBeDeleted', AppConsts.userManagement.defaultAdminUserName));
      return;
    }
    this._roleService.delete(entity.id).subscribe(() => {
      this.refreshGoFirstPage();
      this.notify.success(this.l('SuccessfullyDeleted'));
    });
  }

  /**
   * 新增或编辑角色
   * @param id 当前角色Id
   */
  createOrEdit(id?: number): void {
    this.modalHelper.static(CreateOrEditRoleComponent, { id: id }).subscribe(res => {
      if (res) {
        this.refresh();
      }
    });
  }

  /**
   * 批量删除
   */
  batchDelete(): void {
    const selectCount = this.selectedDataItems.length;
    if (selectCount <= 0) {
      abp.message.warn(this.l('PleaseSelectAtLeastOneItem'));

      return;
    }
    this.message.confirm(this.l('ConfirmDeleteXItemsWarningMessage', selectCount), undefined, res => {
      if (res) {
        const ids = _.map(this.selectedDataItems, 'id');
        this._roleService.batchDelete(ids).subscribe(() => {
          this.refresh();
          this.notify.success(this.l('SuccessfullyDeleted'));
        });
      }
    });
  }

  refreshTheWindwosPageEvents() {
    window.location.reload();
  }

  refreshCheckStatus(entityList: any[]): void {
    // 是否全部选中
    const allChecked = entityList.every(value => value.checked === true);
    // 是否全部未选中
    const allUnChecked = entityList.every(value => !value.checked);
    // 是否全选
    this.allChecked = allChecked;
    // 全选框样式控制
    this.checkboxIndeterminate = !allChecked && !allUnChecked;
    // 已选中数据
    this.selectedDataItems = entityList.filter(value => value.checked && !value.isStatic);
  }
}

<page-header [title]="l('Roles')"></page-header>

<!-- 表格部分 -->
<nz-card [nzBordered]="false">
  <!-- 检索的表单内容 -->
  <form nz-form [nzLayout]="'vertical'" (ngSubmit)="refreshGoFirstPage()" class="mb-md">
    <!-- 模糊搜索框 -->
    <nz-row nzGutter="8">
      <nz-col nzSm="12">
        <nz-form-item>
          <nz-form-control>
            <nz-input-group nzSearch [nzAddOnAfter]="suffixSearchButton">
              <input
                type="text"
                nz-input
                [(ngModel)]="filterText"
                (keyup.enter)="refresh()"
                name="filterText"
                [placeholder]="l('SearchWithThreeDot')"
              />
              <ng-template #suffixSearchButton>
                <button nz-button nzType="primary" nzSearch type="submit">
                  <i class="iconfont icon-search"></i>
                  <!-- <i class="iconfont icon-search"></i> -->
                </button>
              </ng-template>
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
      </nz-col>
      <nz-col nzSm="12">
        <app-permission-combox
          [multiple]="true"
          [dropDownStyle]="{ 'max-height': '500px' }"
          [(selectedPermission)]="selectedPermission"
          (selectedPermissionChange)="refreshGoFirstPage()"
        >
        </app-permission-combox>
      </nz-col>
    </nz-row>
  </form>

  <div class="mb-md">
    <!-- 操作按钮 -->
    <nz-row nzGutter="8">
      <!-- 添加、批量删除、导出Excel表等按钮 -->
      <nz-col nzMd="20" nzSm="12" class="btn-gutter">
        <button
          nz-button
          [nzType]="'primary'"
          *ngIf="isGranted('Pages.Administration.Roles.Create')"
          (click)="createOrEdit()"
        >
          <i class="iconfont icon-plus"></i>

          <span>
            {{ l('CreateNewRole') }}
          </span>
        </button>
        <button
          nz-button
          [nzType]="'danger'"
          *ngIf="isGranted('Pages.Administration.Roles.Delete')"
          (click)="batchDelete()"
        >
          <i class="iconfont icon-delete"></i>

          <span>
            {{ l('BatchDelete') }}
          </span>
        </button>
        <button nz-button (click)="refreshTheWindwosPageEvents()">
          <i class="iconfont icon-refresh"></i>

          <span>
            {{ l('Refresh') }}
          </span>
        </button>
      </nz-col>
    </nz-row>
  </div>

  <!-- 数据部分 -->
  <!-- 复选框提示的内容数据部分 -->
  <table-checkbox-panel
    [selectLength]="selectedDataItems.length"
    (onClear)="restCheckStatus(dataList)"
    (onRefresh)="refreshGoFirstPage()"
  ></table-checkbox-panel>
  <!-- 表格 -->
  <div class="mb-md">
    <nz-table
      #ajaxTable
      nzShowSizeChanger
      [nzData]="dataList"
      [nzTotal]="totalItems"
      [(nzPageIndex)]="pageNumber"
      [(nzPageSize)]="pageSize"
      [nzLoading]="isTableLoading"
      (nzPageIndexChange)="pageNumberChange()"
      (nzPageSizeChange)="refresh()"
      [nzFrontPagination]="false"
      [nzNoResult]="noDataTemplate"
      [nzShowTotal]="showTotalTemplate"
    >
      <!-- 暂无数据 -->
      <ng-template #noDataTemplate>
        <no-data></no-data>
      </ng-template>
      <!-- 分页信息显示 当前 1 页/共 3 页，共 5 条/显示 1-2 条 -->
      <ng-template #showTotalTemplate let-total let-range="range">
        {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
      </ng-template>
      <!-- 表头 -->
      <thead>
        <tr>
          <th
            nzShowCheckbox
            [(nzChecked)]="allChecked"
            [nzDisabled]="allCheckboxDisabled"
            [nzIndeterminate]="checkboxIndeterminate"
            (nzCheckedChange)="checkAll($event)"
          ></th>

          <th>
            <span>{{ l('RoleName') }}</span>
          </th>
          <th class="text-center">
            <span>{{ l('CreationTime') }}</span>
          </th>

          <th nzWidth="230px" class="text-center">
            <span>{{ l('Actions') }}</span>
          </th>
        </tr>
      </thead>
      <!-- 表格内容 -->

      <tbody>
        <tr *ngFor="let item of ajaxTable.data">
          <td
            nzShowCheckbox
            [(nzChecked)]="item.checked && !item.isStatic"
            [nzDisabled]="item.isStatic"
            (nzCheckedChange)="refreshCheckStatus(dataList)"
          ></td>

          <td>
            <ellipsis lines="1">
              <span nz-tooltip [nzTooltipTitle]="item.displayName"> {{ item.displayName }}</span>

              <nz-tag *ngIf="item.isStatic" [nzColor]="'#108ee9'" nz-tooltip [nzTooltipTitle]="l('StaticRole_Tooltip')">
                {{ l('Static') }}</nz-tag
              >
              <nz-tag
                *ngIf="item.isDefault"
                [nzColor]="'#2db7f5'"
                nz-tooltip
                [nzTooltipTitle]="l('DefaultRole_Description')"
              >
                {{ l('Default') }}</nz-tag
              >
            </ellipsis>
          </td>
          <td class="text-center">
            <span nz-tooltip [nzTooltipTitle]="item.creationTime"> {{ item.creationTime | _moment }}</span>
          </td>
          <td class="text-center">
            <!-- 编辑 -->
            <ng-container *ngIf="isGranted('Pages.Administration.Roles.Edit')">
              <a (click)="createOrEdit(item.id)">
                <i class="iconfont icon-edit mr-sm"></i>

                <span>{{ l('Edit') }}</span>
              </a>
              <nz-divider nzType="vertical"></nz-divider>
            </ng-container>
            <!-- 删除 -->
            <ng-container *ngIf="!item.isStatic && isGranted('Pages.Administration.Roles.Delete')">
              <a
                nz-popconfirm
                [nzPopconfirmTitle]="l('ConfirmDeleteWarningMessage')"
                (nzOnConfirm)="delete(item)"
                [nzOkText]="l('Ok')"
                [nzCancelText]="l('Cancel')"
              >
                <i class="iconfont icon-delete mr-sm"></i>
                <span>{{ l('Delete') }}</span>
              </a>
            </ng-container>
          </td>
        </tr>
      </tbody>
    </nz-table>
  </div>
</nz-card>

// src/yoyocmstemplate-vue/src/app/admin/roles/roles.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('Roles')"></page-header>
        <a-card :bordered="false">
            <a-form :layout="'vertical'" @submit.prevent="getData">
                <a-row :gutter="8">
                    <!-- 搜索 -->
                    <a-col :sm="12">
                        <a-form-item>
                            <a-input-search
                                name="filterText"
                                :placeholder="l('SearchWithThreeDot')"
                                @search="getData"
                                enterButton
                                v-model="filterText"
                                v-decorator="['filterText']" />
                        </a-form-item>
                    </a-col>
                    <!-- 权限过滤 -->
                    <a-col :sm="12">
                        <a-form-item>
                            <permission-combox
                                :multiple="true"
                                :dropDownStyle="{ 'max-height': '500px' }"
                                :selectedPermission="selectedPermission"
                                @selectedPermissionChange="refreshGoFirstPage">
                            </permission-combox>
                        </a-form-item>
                    </a-col>
                </a-row>
            </a-form>
            <!-- 操作部分 -->
            <a-row :gutter="8">
                <a-col :md="20" :sm="12">
                    <a-button
                        :type="'primary'"
                        v-if="isGranted('Pages.Administration.Roles.Create')"
                        @click="createOrEdit()">
                        <a-icon type="plus" />
                        <span>{{l("CreateNewRole")}}</span>
                    </a-button>
                    <a-button :type="'danger'" v-if="isGranted('Pages.Administration.Roles.Delete')" @click="batchDelete">
                        <a-icon type="delete" />
                        <span>{{l("BatchDelete")}}</span>
                    </a-button>
                </a-col>
            </a-row>

            <!-- 数据部分 -->
            <div class="my-md">
                <a-alert :type="'info'" :showIcon="true">
                    <template slot="message">
                        <span v-html="l('GridSelectedXItemsTips',selectedRowKeys.length)"></span>
                        <a @click="restCheckStatus()" class="ml-md">{{l('ClearEmpty')}}</a>
                        <a-divider type="vertical"></a-divider>
                        <a @click="getData()">{{l('Refresh')}}</a>
                    </template>
                </a-alert>
            </div>

            <a-row>
                <a-table
                    class="list-table"
                    @change="getData"
                    :pagination="false"
                    :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange, getCheckboxProps:getCheckboxProps}"
                    :columns="columns"
                    :rowKey="tableDatas => tableDatas.id"
                    :dataSource="tableData">
                    <p class="displayName" slot="displayName" slot-scope="text, record">{{ record.displayName }}
                        <a-tag v-if="record.isStatic" color="#108ee9"> {{ l('Static') }}</a-tag>
                        <a-tag v-if="record.isDefault" color="#2db7f5"> {{ l('Default') }}</a-tag>
                    </p>
                    <span slot="actions" slot-scope="text, record">
                        <!-- 修改 -->
                        <a class="table-edit" @click="createOrEdit(record.id)" v-if="isGranted('Pages.Administration.Roles.Edit')">
                            <a-icon type="edit" />{{ l('Edit') }}</a>
                        <!-- 删除 -->
                        <a-popconfirm placement="top" v-if="!record.isStatic && isGranted('Pages.Administration.Roles.Delete')" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="deleteItem(record)">
                            <template slot="title">
                                {{ l('ConfirmDeleteWarningMessage') }}
                            </template>
                            <a class="table-delete">
                                <a-icon type="delete" />{{ l('Delete') }}</a>
                        </a-popconfirm>
                    </span>
                </a-table>
                <a-pagination
                    class="pagination"
                    size="middle"
                    :total="totalItems"
                    showSizeChanger
                    showQuickJumper
                    :showTotal="showTotalFun"
                    @change="onChange"
                    @showSizeChange="showSizeChange" />
            </a-row>
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import PermissionCombox from "../shared/permission-combox/permission-combox.vue";
import { ModalHelper } from "@/shared/helpers";
import { RoleServiceProxy } from "@/shared/service-proxies";
import CreateEditRoleCompent from "./create-or-edit-role/create-or-edit-role";
import moment from "moment";

export default {
    mixins: [AppComponentBase],
    name: "tenants",
    components: {
        PermissionCombox,
        CreateEditRoleCompent
    },
    data() {
        return {
            _roleServiceProxy: null,
            // 选中的权限过滤
            selectedPermission: [],
            // 表格
            columns: [
                {
                    title: this.l("RoleName"),
                    dataIndex: "displayName",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "displayName" }
                },
                {
                    title: this.l("CreationTime"),
                    dataIndex: "creationTimeStr",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "creationTimeStr" }
                },
                {
                    title: this.l("Actions"),
                    dataIndex: "actions",
                    sorter: true,
                    align: "center",
                    scopedSlots: { customRender: "actions" }
                }
            ],
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { sorting: "", maxResultCount: 10, skipCount: 0 },
            // 选择多少项
            selectedRowKeys: [],
            selectedRows: [],
            // 请求参数
            filterText: undefined,
            tableData: [],
            // loading
            spinning: false
        };
    },
    created() {
        this._roleServiceProxy = new RoleServiceProxy(this.$apiUrl, this.$api);
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._roleServiceProxy
                .getPaged(
                    this.selectedPermission,
                    this.filterText,
                    this.request.sorting,
                    this.request.maxResultCount,
                    this.request.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.tableData = res.items;
                    this.tableData.map(item => {
                        item.creationTimeStr = item.creationTime
                            ? moment(item.creationTime).format(
                                  "YYYY-MM-DD HH:mm:ss"
                              )
                            : "-";
                    });
                    this.totalItems = res.totalCount;
                    this.totalPages = Math.ceil(
                        res.totalCount / this.request.maxResultCount
                    );
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                });
        },
        /**
         * table默认配置 （是否禁用）
         */
        getCheckboxProps: record => ({
            props: {
                disabled: record.isStatic
            }
        }),
        /**
         * 添加角色  修改角色
         */
        createOrEdit(id) {
            ModalHelper.create(
                CreateEditRoleCompent,
                { id: id },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                console.log(res);
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 批量删除
         */
        batchDelete(e) {
            const selectCount = this.selectedRowKeys.length;
            if (selectCount <= 0) {
                abp.message.warn(this.l("PleaseSelectAtLeastOneItem"));
                return;
            }
            this.message.confirm(
                this.l("ConfirmDeleteXItemsWarningMessage", selectCount),
                res => {
                    if (res) {
                        const ids = _.map(this.selectedRowKeys);
                        console.log(ids);
                        this.spinning = true;
                        this._roleServiceProxy
                            .batchDelete(ids)
                            .finally(() => {
                                this.spinning = false;
                            })
                            .then(() => {
                                this.selectedRowKeys = [];
                                this.refreshGoFirstPage(
                                    this.selectedPermission
                                );
                                this.$notification["success"]({
                                    message: this.l("SuccessfullyDeleted")
                                });
                            });
                    }
                }
            );
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * 单个删除
         */
        deleteItem(item) {
            console.log(item);
            if (item.isStatic) {
                abp.message.warn(
                    this.l(
                        "XUserCannotBeDeleted",
                        AppConsts.userManagement.defaultAdminUserName
                    )
                );
                return;
            }
            this.spinning = true;
            this._roleServiceProxy
                .delete(item.id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(() => {
                    this.refreshGoFirstPage(this.selectedPermission);
                    this.$notification["success"]({
                        message: this.l("SuccessfullyDeleted")
                    });
                });
        },
        /**
         * 清空选择
         */
        restCheckStatus() {
            this.selectedRowKeys = [];
        },
        /**
         * table选择事件
         */
        onSelectChange(selectedRowKeys, selectedRows) {
            this.selectedRowKeys = selectedRowKeys;
            this.selectedRows = selectedRows;
            console.log(this.selectedRows);
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        },
        /**
         * 选择完权限过滤
         */
        refreshGoFirstPage(data) {
            this.selectedPermission = data;
            this.request = { maxResultCount: 10, skipCount: 0 };
            this.getData();
        }
    }
};
</script>

<style scoped lang="less">
@import "./roles.less";
</style>
