// src/yoyocmstemplate-angular/src/shared/components/file-manager/file-manager.component.ts
import {
  Component,
  OnInit,
  Input,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Output,
  EventEmitter,
  TemplateRef,
  Injector,
} from '@angular/core';
import { _HttpClient } from '@delon/theme';
import { UploadFile } from 'ng-zorro-antd/upload';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzFormatEmitEvent } from 'ng-zorro-antd/tree';
import { ArrayService, copy } from '@delon/util';
import { AppComponentBase, PagedListingComponentBase, PagedRequestDto } from '@shared/component-base';
import { HttpClient } from '@angular/common/http';
import { AppConsts } from 'abpPro/AppConsts';
import { TokenService } from 'abp-ng2-module';
import {
  SysFileServiceProxy,
  SysFileListDto,
  PagedResultDtoOfSysFileListDto,
  SysFileEditDto,
} from '../../service-proxies/service-proxies';
import { finalize, filter } from 'rxjs/operators';
import { EntityDtoOfGuid, MoveSysFilesInput } from '../../service-proxies/service-proxies';
import { element } from 'protractor';

@Component({
  selector: 'file-manager',
  templateUrl: './file-manager.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileManagerComponent extends PagedListingComponentBase<SysFileListDto> implements OnInit {
  constructor(
    injector: Injector,
    private _sysfileService: SysFileServiceProxy,
    public http: _HttpClient,
    private cdr: ChangeDetectorRef,
    private arrSrv: ArrayService,
    private msg: NzMessageService,
    private _tokenService: TokenService,
  ) {
    super(injector);
    // 设置头部信息
    this.uploadHeaders = {
      Authorization: 'Bearer ' + this._tokenService.getToken(),
    };
  }

  uploadHeaders: any;
  parentId = '';
  uploadFileUrl: string;

  filepath = AppConsts.remoteServiceBaseUrl + '/sysfiles/';

  showType: 'big' | 'small' = 'big';
  s: any = { orderby: 0, ps: 20, pi: 1, q: '' };
  loading = false;

  directoryLists: any[] = [];

  list: any[] = [];
  item: any;
  /** 路径的深度 */
  path: number[] = [0];
  total = 0;

  @Input()
  params: any;

  @Input()
  actions: TemplateRef<any>;

  @Input()
  multiple: boolean | number = false;

  @Output()
  selected = new EventEmitter<any>();

  // #endregion

  // #region rename

  /**文件夹模型 */
  directoryModel = false;
  /**文件夹名称 */
  directoryName = '';
  renameModel = false;
  renameTitle = '';

  // #endregion

  // #region move
  moveModel = false;
  moveId = '';
  folderNodes: any[] = [];

  // 模糊搜索
  filterText = '';

  protected fetchDataList(request: PagedRequestDto, pageNumber: number, finishedCallback: Function): void {
    this._sysfileService
      .getPaged(this.parentId, this.filterText, request.sorting, request.maxResultCount, request.skipCount)
      .pipe(
        finalize(() => {
          finishedCallback();
        }),
      )
      .subscribe((result: any) => {
        this.list = result.items.map(res => {
          res.fileExt = res.fileExt.replace('.', '');
          res.selected = false;
          res.path = this.filepath + res.path;
          return res;
        });

        // console.log(this.list);
        this.showPaging(result);
        this.cdr.detectChanges();
      });
  }

  ngOnInit(): void {
    // 初始化加载表格数据
    this.refresh();
    this.getFileUploadUrl('');
  }

  getCode(mp: string, type: 'link' | 'code') {
    return type === 'link' ? mp : `<img src="${mp}">`;
  }

  getFileUploadUrl(parendId: string) {
    this.uploadFileUrl = AppConsts.remoteServiceBaseUrl + '/api/services/app/SysFile/Create?parentId=' + parendId;
  }

  // #region op

  back() {
    this.path.pop(); // 移除最后一个元素
    //  console.log(this.path);
    const length = this.path.length;
    const tempParentId = this.path[length - 1];
    if (tempParentId === 0) {
      this.parentId = '';
    } else {
      this.parentId = tempParentId.toString();
    }
    this.getFileUploadUrl(this.parentId);

    this.refresh();

    //   this.refreshGoFirstPage();
  }

  /** 进入文件夹 */
  next(i: any) {
    this.path.push(i.id);
    // console.log(i);
    // console.log(this.path);

    this.parentId = i.id;
    this.getFileUploadUrl(i.id);
    this.refresh();
  }

  /**
   * 如果是文件夹则显示文件夹中的内容
   * @param i 选中的项
   */
  cho(i: any) {
    if (i.dir) {
      this.next(i);
      return;
    }
    i.selected = !i.selected;
    this.selected.emit(i);
    this.cdr.detectChanges();
  }

  // #endregion

  // #region uplad

  uploadChange({ file }: { file: UploadFile }) {
    if (file.status === 'done') {
      this.refresh();
    }
  }

  openDirectory() {
    this.directoryModel = true;
  }

  createDirecotry() {
    const input = new SysFileEditDto();
    input.name = this.directoryName;
    input.parentId = this.parentId;
    this._sysfileService
      .createDirectory(input)
      .pipe()
      .subscribe((res: any) => {
        //  console.log(res);
        res.fileExt = res.fileExt.replace('.', '');
        res.selected = false;
        this.list.push(res);
        this.notify.success(this.l('SavedSuccessfully'));
        this.directoryName = null;
        //    this.refresh();
        this.directoryModel = false;

        this.cdr.detectChanges();
      });
  }

  /**
   * 获取待移动的文件夹列表
   * @param data 待移动的文件夹列表
   */
  getMoveDirectoryList(parentId: string): any[] {
    let directories: any[] = [];
    if (parentId == null) {
      directories = this.directoryLists.filter(item => {
        return item.parentId == null;
      });
    } else {
      directories = this.directoryLists.filter(item => {
        if (item.parentId == parentId) {
          item.disabled = true;
        }

        return item.parentId == parentId;
      });
    }

    console.log(this.directoryLists);
    return directories;
  }

  /**
   * 懒加载当前文件夹下的目录
   * @param e 选择的文件夹
   */
  onDirectoryExpandChange(e: NzFormatEmitEvent): void {
    // console.log(e.node);
    const node = e.node;
    if (node && node.getChildren().length === 0 && node.isExpanded) {
      const data = this.getMoveDirectoryList(e.node.key);
      // console.log(data);

      node.addChildren(data);

      // this.loadNode().then(data => {
      //   node.addChildren(data);
      // });
    }
  }

  /** 打开模态框，获取文件夹列表 */
  openMoveModal(i: any) {
    this.directoryLists = [];
    this.moveModel = true;
    this.item = i; // 当前文件夹
    console.log(i); // 003
    this.moveId = i.parentId;

    this._sysfileService
      .getDirectories()
      .pipe()
      .subscribe((res: any) => {
        res.splice(0, 0, { id: '', parentId: null, name: '根目录' }); // 往数组中添加一个对象

        res.forEach((element: { id: any; parentId: any; code: any; name: any }) => {
          this.directoryLists.push({
            key: element.id,
            parentId: element.parentId,
            code: element.code,
            title: element.name,
          });
        });

        const directories = this.getMoveDirectoryList(null);

        this.folderNodes = this.arrSrv.arrToTree(directories, {
          cb: e => {
            if (e.parentId === this.moveId) {
              e.disabled = true;
            }
          },
        });

        //  console.log(this.folderNodes);
        this.cdr.detectChanges();
      });
  }
  moveOk() {
    console.log(this.item);
    console.log(this.moveId);
    const input = new MoveSysFilesInput();
    input.id = this.item.id;
    input.newParentId = this.moveId;
    this._sysfileService
      .move(input)
      .pipe()
      .subscribe((res: any) => {
        this.refresh(); // 刷新表格数据并跳转到第一页（`pageNumber = 1`）
        this.notify.success(this.l('SavedSuccessfully'));
        this.moveModel = false;
        //     this.list.splice(
        //       this.list.findIndex(w => w.id === this.item.id),
        //       1,
        //     );

        this.cdr.detectChanges();
      });
  }
  // #endregion

  /** 打开重命名模态框 */
  rename(i: any) {
    this.renameModel = true;
    this.item = i;
    this.renameTitle = i.name;
  }
  /** 重命名方法 */
  renameOk() {
    const input = new SysFileEditDto();
    input.id = this.item.id;
    input.name = this.renameTitle;
    this._sysfileService.reFileName(input).subscribe(() => {
      this.refresh(); // 刷新表格数据并跳转到第一页（`pageNumber = 1`）
      this.notify.success(this.l('SuccessfullyDeleted'));
      this.renameModel = false;
      this.cdr.detectChanges();
    });
  }
  /**
   * 复制代码或者链接
   * @param mp url
   * @param type 代码或者链接
   */
  copyData(mp: string, type: 'link' | 'code') {
    copy(this.getCode(mp, type)).then(() => this.msg.success('Copy Success'));
  }

  // #endregion
  // #region copy
  /**
   * 复制文件
   * @param id 待copy文件id
   */
  copyImg(id: any) {
    const input = new SysFileEditDto();
    input.id = id;
    this._sysfileService
      .copyFile(input)
      .pipe()
      .subscribe((res: any) => {
        //    console.log(res);
        res.selected = false;
        res.path = this.filepath + res.path;

        this.list.push(res);
        this.notify.success(this.l('SavedSuccessfully'));

        //    this.refresh();

        this.cdr.detectChanges();
      });
  }

  // #region remove

  /**
   * 删除文件
   * @param id 文件id
   */
  remove(id: any) {
    this._sysfileService
      .delete(id)
      .pipe()
      .subscribe(() => {
        this.refresh();
        this.notify.success(this.l('SuccessfullyDeleted'));
      });
  }

  // #endregion
}

<div class="d-flex justify-content-between">
  <div class="d-flex align-items-center flex-1">
    <nz-upload
      [nzAction]="uploadFileUrl"
      [nzShowUploadList]="false"
      [nzHeaders]="uploadHeaders"
      nzMultiple
      (nzChange)="uploadChange($event)"
    >
      <button nz-button nzType="primary">
        <i nz-icon nzType="upload"></i>
        <span>{{ l('FileUpload') }}</span>
      </button>
    </nz-upload>
    <ng-template [ngTemplateOutlet]="actions"></ng-template>
    <button class="ml-sm" nz-button (click)="openDirectory()">
      <i class="iconfont icon-plus"></i>
      <span>
        {{ l('CreateDirectory') }}
      </span>
    </button>
    <button class="ml-sm" nz-button (click)="refreshGoFirstPage()">
      <i class="iconfont icon-reload"></i>
      <span>
        {{ l('Refresh') }}
      </span>
    </button>
  </div>

  <nz-button-group>
    <button nz-button (click)="showType = 'big'" [disabled]="showType == 'big'">
      <i nz-icon nzType="appstore"></i>
    </button>
    <button nz-button (click)="showType = 'small'" [disabled]="showType == 'small'">
      <i nz-icon nzType="bars"></i>
    </button>
  </nz-button-group>
</div>
<nz-spin [nzSpinning]="loading">
  <div *ngIf="showType == 'small'" class="file-manager__header">
    <div class="file-manager__header-name">{{ l('FileName') }}</div>
    <div class="file-manager__header-pixel">{{ l('Pixel') }}</div>
    <div class="file-manager__header-time">{{ l('LastModificationTime') }}</div>
  </div>
  <div class="file-manager" [ngClass]="{ 'file-manager__small': showType == 'small' }">
    <div *ngIf="path.length > 1" (click)="back()" class="file-item">
      <i class="file-item__icon iconfont icon-rollback"></i>
      <div class="file-item__name">...</div>
      <!-- 路径比较深的显示back按钮 -->
    </div>
    <div
      *ngFor="let i of list; let idx = index"
      class="file-item"
      [ngClass]="{ 'file-item__selected': i.selected }"
      (click)="cho(i)"
    >
      <i
        *ngIf="i.dir === true"
        class="file-item__icon iconfont   "
        [ngClass]="'icon-' + i.fileExt"
        style="font-size: 29px;"
      ></i>
      <ng-container *ngIf="i.dir === false">
        <i
          *ngIf="!i.isImg"
          class="file-item__icon iconfont   "
          [ngClass]="'icon-' + i.fileExt"
          style="font-size: 29px;"
        ></i>
        <div class="file-item__img" *ngIf="i.isImg" [ngStyle]="{ 'background-image': 'url(' + i.path + ')' }"></div>
      </ng-container>
      <div class="file-item__name">{{ i.name }}</div>
      <div class="file-item__pixel">
        <span *ngIf="i.isImg">{{ i.width }}x{{ i.height }}</span>
      </div>
      <div class="file-item__time">{{ i.creationTime | _moment }}</div>
      <span nz-dropdown [nzDropdownMenu]="actionMenu" class="dd-btn file-item__actions">
        <i nz-icon nzType="ellipsis"></i>
      </span>
      <nz-dropdown-menu #actionMenu="nzDropdownMenu">
        <ul nz-menu>
          <li nz-menu-item nz-popconfirm nzPopconfirmTitle="l('AreYouSure')" (nzOnConfirm)="copyImg(i.id)">
            Copy
          </li>
          <li nz-menu-item (click)="copyData(i.path, 'link')">{{ l('CopyUrl') }}</li>
          <li nz-menu-item (click)="copyData(i.path, 'code')">{{ l('CopyCode') }}</li>
          <li nz-menu-item (click)="rename(i)">{{ l('ReName') }}</li>
          <li nz-menu-item (click)="openMoveModal(i)">{{ l('Move') }}</li>
          <li nz-menu-item nz-popconfirm nzPopconfirmTitle="l('AreYouSure')" (nzOnConfirm)="remove(i.id)">
            {{ l('DeleteSysFile') }}
          </li>
        </ul>
      </nz-dropdown-menu>
    </div>
  </div>
  <div class="text-center mt-md">
    <ng-template #showTotalTemplate let-total let-range="range">
      {{ l('GridFooterDisplayText', pageNumber, totalPages, total, range[0], range[1]) }}
    </ng-template>
    <nz-pagination
      [(nzPageIndex)]="pageNumber"
      [nzTotal]="totalItems"
      [nzShowTotal]="showTotalTemplate"
      [nzPageSizeOptions]="[10, 20, 30, 40, 50]"
      [(nzPageSize)]="pageSize"
      nzShowQuickJumper
      nzShowSizeChanger
      (nzPageIndexChange)="pageNumberChange()"
      (nzPageSizeChange)="refresh()"
    ></nz-pagination>
  </div>

  <div class="no-data" *ngIf="totalItems === 0">
    {{ l('NoData') }}
  </div>
</nz-spin>


<nz-modal [(nzVisible)]="renameModel" [nzTitle]="l('ReName')" (nzOnOk)="renameOk()" (nzOnCancel)="renameModel = false">
  <input nz-input [(ngModel)]="renameTitle" name="renameTitle" />
</nz-modal>


<nz-modal [(nzVisible)]="moveModel" [nzTitle]="l('Move')" (nzOnOk)="moveOk()" (nzOnCancel)="moveModel = false">
  <nz-tree-select
    class="d-block"
    [nzNodes]="folderNodes"
    nzShowSearch
    nzExpandAll
    [(ngModel)]="moveId"
    [nzAsyncData]="true"
    (nzExpandChange)="onDirectoryExpandChange($event)"
  >
  </nz-tree-select>
</nz-modal>

<nz-modal
  [(nzVisible)]="directoryModel"
  nzTitle="创建文件夹"
  (nzOnOk)="createDirecotry()"
  (nzOnCancel)="directoryModel = false"
>
  <input nz-input [(ngModel)]="directoryName" name="directoryName"
/></nz-modal>

// src/yoyocmstemplate-vue/src/app/admin/file-manager/file-manager.vue
<template>
    <a-spin :spinning="spinning">
        <page-header :title="l('FileManager')"></page-header>
        <a-card :bordered="false">
            <!-- 按钮 -->
            <a-row :gutter="8">
                <a-col :sm="22" :md="20">
                    <!-- <a-button type="primary">
                        <a-icon type="upload" />
                        {{ l('FileUpload') }}
                    </a-button> -->
                    <a-upload
                        class="fileUpload"
                        :action="uploadFileUrl"
                        :multiple="false"
                        :fileList="uploadfileList"
                        :headers="uploadHeaders"
                        @change="uploadChange">
                        <a-button type="primary">
                            <a-icon type="upload" />
                            <span>{{l("FileUpload")}}</span>
                        </a-button>
                    </a-upload>
                    <a-button @click="openDirectory">
                        <a-icon type="plus" />
                        {{ l('CreateDirectory') }}
                    </a-button>
                    <a-button @click="getData">
                        <a-icon type="reload" />
                        {{ l('Refresh') }}
                    </a-button>
                </a-col>
                <a-col :sm="2" :md="4">
                    <a-button @click="showType = 'big'" :disabled="showType === 'big'">
                        <a-icon type="appstore" />
                    </a-button>
                    <a-button class="bars-btn" @click="showType = 'small'" :disabled="showType === 'small'">
                        <a-icon type="bars" />
                    </a-button>
                </a-col>
            </a-row>
            <!-- big横向展示 -->
            <section class="big-list-item" v-show="showType==='big'">
                <a-row :gutter="10">
                    <a-col :sm="3" v-if="path.length > 1" @click="back()" class="file-item">
                        <i class="file-item__icon iconfont icon-rollback"></i>
                        <div class="file-item__name" style="text-align:center">...</div>
                        <!-- 路径比较深的显示back按钮 -->
                    </a-col>
                    <a-col :sm="3" v-for="item in fileList" :key="item.id" :class="{ 'file_item__selected': item.selected }" @click="cho(item)">
                        <div class="dd-btn">
                            <a-dropdown>
                                <a class="ant-dropdown-link" @click="e => e.preventDefault()">
                                    <a-icon type="ellipsis" />
                                </a>
                                <a-menu slot="overlay">
                                    <a-menu-item>
                                        <a-popconfirm placement="top" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="copyImg(item.id)">
                                            <template slot="title">
                                                {{ l('AreYouSure') }}
                                            </template>
                                            <a href="javascript:;">Copy</a>
                                        </a-popconfirm>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="copyData(item.path, 'link')">{{ l('CopyUrl') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="copyData(item.path, 'code')">{{ l('CopyCode') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="rename(item)">{{ l('ReName') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="movefile(item)">{{ l('Move') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <!-- <a href="javascript:;">{{ l('DeleteSysFile') }}</a> -->
                                        <a-popconfirm placement="top" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="remove(item.id)">
                                            <template slot="title">
                                                {{ l('AreYouSure') }}
                                            </template>
                                            <a href="javascript:;">{{ l('DeleteSysFile') }}</a>
                                        </a-popconfirm>
                                    </a-menu-item>
                                </a-menu>
                            </a-dropdown>
                        </div>
                        <i
                            v-if="item.dir === true"
                            class="file-item__icon iconfont   "
                            :class="'icon-' + item.fileExt"
                            style="font-size: 29px;"></i>
                        <div v-if="item.dir === false">
                            <i
                                v-if="!item.isImg"
                                class="file-item__icon iconfont   "
                                :class="'icon-' + item.fileExt"
                                style="font-size: 29px;"></i>
                            <div class="file-item__img" v-if="item.isImg" :style="{ 'background-image': 'url(' + item.path + ')' }"></div>
                        </div>
                        <div class="file_item__name">{{ item.name }}</div>
                        <div class="file_item__pixel">
                            <span v-if="item.isImg">{{ item.width }}x{{ item.height }}</span>
                        </div>
                    </a-col>
                </a-row>
            </section>
            <!-- smalltable展示 -->
            <section class="small-list-item" v-show="showType==='small'">
                <div v-if="path.length > 1" @click="back()" class="back-item">
                    <i class="file-item__icon iconfont icon-rollback"></i>&nbsp;&nbsp;...
                </div>
                <a-table :columns="columns" :pagination="false" :data-source="fileList" :customRow="tableclick">
                    <span slot="name" slot-scope="text, record">
                        <div class="icon-container">
                            <i
                                v-if="record.dir === true"
                                class="file-item__icon iconfont   "
                                :class="'icon-' + record.fileExt"
                                style="font-size: 29px;"></i>
                            <i
                                v-if="record.dir === false && !record.isImg"
                                class="file-item__icon iconfont   "
                                :class="'icon-' + record.fileExt"
                                style="font-size: 29px;"></i>
                            <div class="file-item__img" v-if="record.dir === false && record.isImg" :style="{ 'background-image': 'url(' + record.path + ')' }"></div>
                        </div>
                        {{ record.name }}
                    </span>
                    <span slot="pixel" v-if="record.isImg" slot-scope="text, record">
                        {{ record.width }}x{{ record.height }}
                    </span>
                    <span slot="lastModificationTimeStr" class="lastModificationTimeStr" slot-scope="text, record">
                        {{ record.lastModificationTimeStr }}
                        <div class="dd-btn">
                            <a-dropdown>
                                <a class="ant-dropdown-link" @click="e => e.preventDefault()">
                                    <a-icon type="ellipsis" />
                                </a>
                                <a-menu slot="overlay" class="ant-dropdown-link">
                                    <a-menu-item>
                                        <a-popconfirm placement="top" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="copyImg(record.id)">
                                            <template slot="title">
                                                {{ l('AreYouSure') }}
                                            </template>
                                            <a href="javascript:;">Copy</a>
                                        </a-popconfirm>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="copyData(record.path, 'link')">{{ l('CopyUrl') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="copyData(record.path, 'code')">{{ l('CopyCode') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="rename(record)">{{ l('ReName') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <a href="javascript:;" @click="movefile(record)">{{ l('Move') }}</a>
                                    </a-menu-item>
                                    <a-menu-item>
                                        <!-- <a href="javascript:;">{{ l('DeleteSysFile') }}</a> -->
                                        <a-popconfirm placement="top" :okText="l('Ok')" :cancelText="l('Cancel')" @confirm="remove(record.id)">
                                            <template slot="title">
                                                {{ l('AreYouSure') }}
                                            </template>
                                            <a href="javascript:;">{{ l('DeleteSysFile') }}</a>
                                        </a-popconfirm>
                                    </a-menu-item>
                                </a-menu>
                            </a-dropdown>
                        </div>
                    </span>
                </a-table>
            </section>
            <!-- 分页 -->
            <a-pagination
                class="pagination"
                size="middle"
                :total="totalItems"
                showSizeChanger
                showQuickJumper
                :showTotal="showTotalFun"
                @change="onChange"
                @showSizeChange="showSizeChange" />
        </a-card>
    </a-spin>
</template>

<script>
import { AppComponentBase } from "@/shared/component-base";
import { SysFileServiceProxy } from "@/shared/service-proxies";
import { AppConsts } from "@/abpPro/AppConsts";
import CreateDirectory from "./create-directory";
import Rename from "./rename";
import { ModalHelper } from "@/shared/helpers";
import MoveFile from "./move-file";
import { ModalComponentBase } from "@/shared/component-base";
import moment from "moment";
// import { fileDownloadService } from "@/shared/utils";

export default {
    name: "file-manager",
    mixins: [AppComponentBase, ModalComponentBase],
    components: {
        CreateDirectory,
        Rename,
        MoveFile
    },
    data() {
        return {
            spinning: false,
            // 显示类型
            showType: "big",
            _sysFileServiceProxy: "",
            parentId: "",
            // 总数
            totalItems: 0,
            // 当前页码
            pageNumber: 1,
            // 共多少页
            totalPages: 1,
            // 条数显示范围
            pagerange: [1, 1],
            // 显示条数
            pageSizeOptions: ["10", "20", "30", "40"],
            request: { maxResultCount: 10, skipCount: 0 },
            //  文件列表
            fileList: [],
            filepath: AppConsts.remoteServiceBaseUrl + "/sysfiles/",
            // small table
            columns: [
                {
                    title: this.l("FileName"),
                    dataIndex: "name",
                    align: "left",
                    scopedSlots: { customRender: "name" }
                },
                {
                    title: this.l("Pixel"),
                    dataIndex: "pixel",
                    align: "center",
                    scopedSlots: { customRender: "pixel" }
                },
                {
                    title: this.l("LastModificationTime"),
                    dataIndex: "lastModificationTimeStr",
                    align: "center",
                    scopedSlots: { customRender: "lastModificationTimeStr" }
                }
            ],
            // 上传文件
            uploadfileList: [],
            uploadFileUrl: "",
            uploadHeaders: {},
            // 路劲深度
            path: [0]
        };
    },
    created() {
        this.fullData();
        this._sysFileServiceProxy = new SysFileServiceProxy(
            this.$apiUrl,
            this.$api
        );
        Object.assign(this.uploadHeaders, {
            Authorization: "Bearer " + abp.auth.getToken()
        });
        this.getFileUploadUrl("");
        this.getData();
    },
    methods: {
        /**
         * 获取数据
         */
        getData() {
            this.spinning = true;
            this._sysFileServiceProxy
                .getPaged(
                    this.parentId,
                    "",
                    "",
                    this.request.maxResultCount,
                    this.request.skipCount
                )
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    this.fileList = res.items;
                    this.fileList = res.items.map(item => {
                        item.fileExt = item.fileExt.replace(".", "");
                        item.selected = false;
                        item.path = this.filepath + item.path;
                        item.lastModificationTimeStr = moment(
                            item.lastModificationTime
                        ).format("YYYY-MM-DD hh:mm:ss");
                        return item;
                    });
                    //  this.fileList .map(item=>item.)
                    this.totalItems = res.totalCount;
                    this.totalPages = Math.ceil(
                        res.totalCount / this.request.maxResultCount
                    );
                    this.pagerange = [
                        (this.pageNumber - 1) * this.request.maxResultCount + 1,
                        this.pageNumber * this.request.maxResultCount
                    ];
                });
        },
        /**
         * 获取上传文件地址
         */
        getFileUploadUrl(parendId) {
            this.uploadFileUrl =
                AppConsts.remoteServiceBaseUrl +
                "/api/services/app/SysFile/Create?parentId=" +
                parendId;
        },
        /**
         * 分页事件
         */
        showTotalFun() {
            return this.l(
                "GridFooterDisplayText",
                this.pageNumber,
                this.totalPages,
                this.totalItems,
                this.pagerange[0],
                this.pagerange[1]
            );
        },
        /**
         * 分页
         */
        onChange(page, pageSize) {
            this.pageNumber = page;
            this.request.skipCount = (page - 1) * this.request.maxResultCount;
            this.getData();
        },
        showSizeChange(current, size) {
            this.pageNumber = 1;
            this.request.maxResultCount = size;
            this.getData();
        },
        /**
         * big
         * 点击item
         */
        cho(item) {
            if (item.dir) {
                this.next(item);
                return;
            }
            // this.$set(this.fileList, item.selected, !item.selected);
            console.log(item);
            if (this.componentType === "modal") {
                this.success(item);
                this.close();
            }
            // this.selected.emit(i);
            // this.cdr.detectChanges();
        },
        /**
         * 进入文件夹
         */
        next(i) {
            this.path.push(i.id);
            this.parentId = i.id;
            this.getFileUploadUrl(i.id);
            this.getData();
        },
        /**
         *上传文件
         */
        uploadChange(info) {
            this.spinning = true;
            let fileList = [...info.fileList];
            fileList = fileList.slice(-2);
            fileList = fileList.map(file => {
                if (file.response) {
                    file.url = file.response.url;
                }
                return file;
            });
            this.uploadfileList = fileList;
            if (info.file.status === "done") {
                this.spinning = false;
                this.$notification["success"]({
                    message: "文件上传成功"
                });
                this.getData();
            }
        },
        /**
         * 新建文件夹
         */
        openDirectory() {
            ModalHelper.create(
                CreateDirectory,
                {
                    parentId: this.parentId
                },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 返回上一级
         */
        back() {
            this.path.pop(); // 移除最后一个元素
            const length = this.path.length;
            const tempParentId = this.path[length - 1];
            if (tempParentId === 0) {
                this.parentId = "";
            } else {
                this.parentId = tempParentId.toString();
            }
            this.getFileUploadUrl(this.parentId);
            this.getData();
        },
        /**
         * 单机table
         */
        tableclick(record, index) {
            return {
                on: {
                    click: () => {
                        this.cho(record);
                    }
                }
            };
        },
        /**
         * 复制文件
         * @param id 待copy文件id
         */
        copyImg(id) {
            this.spinning = true;
            this._sysFileServiceProxy
                .copyFile({
                    id: id
                })
                .finally(() => {
                    this.spinning = false;
                })
                .then(res => {
                    res.selected = false;
                    res.path = this.filepath + res.path;
                    // this.fileList.push(res);
                    this.getData();
                    this.$notification["success"]({
                        message: this.l("SavedSuccessfully")
                    });
                });
        },
        /**
         * 复制代码或者链接
         * @param mp url
         * @param type 代码或者链接
         */
        copyData(mp, type) {
            console.log(this.getCode(mp, type));
            this.$copyText(this.getCode(mp, type)).then(() =>
                this.$notification["success"]({
                    message: "Copy Success"
                })
            );
        },
        getCode(mp, type) {
            return type === "link" ? mp : `<img src="${mp}">`;
        },
        /**
         * 重命名
         */
        rename(item) {
            ModalHelper.create(
                Rename,
                {
                    renameItem: item
                },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                console.log(res);
                if (res) {
                    this.getData();
                }
            });
        },
        /**
         * 移动文件
         */
        movefile(item) {
            ModalHelper.create(
                MoveFile,
                {
                    item: item
                },
                {
                    width: "400px"
                }
            ).subscribe(res => {
                console.log(res);
                if (res) {
                    this.path = [0];
                    this.parentId = "";
                    this.getFileUploadUrl("");
                    this.getData();
                }
            });
        },
        /**
         * 删除文件
         */
        remove(id) {
            this.spinning = true;
            this._sysFileServiceProxy
                .delete(id)
                .finally(() => {
                    this.spinning = false;
                })
                .then(() => {
                    this.getData();
                    this.$notification["success"]({
                        message: this.l("SuccessfullyDeleted")
                    });
                });
        }
    }
};
</script>

<style scoped lang="less">
/deep/.ant-upload-list-text {
    display: none;
}
.bars-btn {
    margin-left: 0;
}
// 横向展示
.big-list-item {
    margin-top: 20px;
    .iconfont {
        display: block;
        font-size: 40px;
        margin: 16px 0;
        text-align: center;
    }
    /deep/.ant-row {
        width: 100%;
        margin-left: 0 !important;
        margin-right: 0 !important;
    }
    .ant-col-sm-3 {
        box-sizing: border-box;
        padding-top: 15px;
        height: 150px;
        border: 1px solid transparent;
        position: relative;
        cursor: pointer;
        &:hover {
            border: 1px solid rgba(0, 0, 0, 0.05);
            .dd-btn {
                display: block;
            }
        }
        .dd-btn {
            height: 24px;
            width: 24px;
            line-height: 24px;
            border-radius: 50%;
            color: #bfbfbf;
            background-color: #f5f5f5;
            text-align: center;
            cursor: pointer;
            position: absolute;
            margin: auto;
            right: 10px;
            top: 10px;
            display: none;
        }
        // .anticon-ellipsis {
        //     &:hover {
        //         cursor: pointer;
        //     }
        // }
    }
    .file_item__name {
        color: #4e5155;
        height: 28px;
        text-align: center;
        line-height: 28px;
        padding: 0 8px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
    .file_item__pixel {
        text-align: center;
    }
    .file-item__img {
        background-color: transparent;
        background-position: center center;
        background-size: cover;
        display: block;
        margin: 0 auto 0.75rem;
        width: 4rem;
        height: 4rem;
        font-size: 2.5rem;
        line-height: 4rem;
    }
    .file_item__selected {
        border-color: #1890ff !important;
        background-color: #e6f7ff !important;
    }
}
// smalltable展示
.small-list-item {
    margin: 20px 0;
    .file-item__img {
        display: block;
        margin: 0 8px;
        width: 32px;
        height: 32px;
        text-align: center;
        font-size: 20px;
        line-height: 32px;
        background-color: transparent;
        background-position: center center;
        background-size: cover;
        float: left;
    }
    .dd-btn {
        height: 24px;
        width: 24px;
        line-height: 24px;
        border-radius: 50%;
        color: #bfbfbf;
        background-color: transparent;
        text-align: center;
        cursor: pointer;
        float: right;
        // position: absolute;
        // margin: auto;
        // right: 10px;
        // top: 10px;
        // display: none;
        .ant-dropdown-link {
            color: transparent;
        }
    }
    /deep/.ant-table-tbody td {
        .icon-container {
            min-height: 10px;
            width: 50px;
            float: left;
            &::before {
                content: "";
            }
        }
        &:last-child:hover {
            .dd-btn {
                background-color: #f5f5f5;
                display: block;
                .ant-dropdown-link {
                    color: #bfbfbf;
                }
            }
        }
    }
    .back-item {
        cursor: pointer;
        height: 50px;
    }
}
.fileUpload {
    float: left;
    margin-right: 10px;
}
// 分页
.pagination {
    text-align: center;
}
</style>
